import { prisma, runTranslations } from "./translate-lib.mjs";

// 10 recipes from East and Central Asia: China (Sichuan, Cantonese,
// Beijing), Singapore, Japan, Korea, Taiwan, and the Uyghur/Uzbek
// tradition of Central Asia. Each web-researched for authentic
// technique before writing, per standing instructions. Nutrition
// estimates are set directly here (caloriesPerServing/proteinG/carbsG/
// fatG), per standing instruction to never leave new recipes without
// nutrition.
const newRecipes = [
  {
    slug: "dan-dan-noodles",
    title: "Dan Dan Noodles",
    description:
      "Sichuan's famous noodle dish - served dry, not as a soup, tossed in a numbing, spicy sauce of sesame paste, chili oil, and Sichuan peppercorns, topped with crispy fried pork. It's plated unmixed and tossed tableside just before eating.",
    imageEmoji: "🍜",
    cookTimeMinutes: 35,
    servings: 4,
    caloriesPerServing: 520,
    proteinG: 22,
    carbsG: 58,
    fatG: 22,
    ingredients: [
      { text: "1 lb fresh wheat noodles (or thin dried round noodles)", ingredient: "wheat noodles", quantity: 1 },
      { text: "8 oz ground pork", ingredient: "ground pork", quantity: 8 },
      { text: "2 tbsp preserved mustard greens (sui mi ya cai)", ingredient: "preserved mustard greens", quantity: 2 },
      { text: "3 tbsp light soy sauce, divided", ingredient: "light soy sauce", quantity: 3 },
      { text: "2 tbsp Chinese sesame paste (or tahini)", ingredient: "sesame paste", quantity: 2 },
      { text: "2 tbsp chili oil, plus the sediment", ingredient: "chili oil", quantity: 2 },
      { text: "1 tbsp black vinegar", ingredient: "black vinegar", quantity: 1 },
      { text: "1 tsp Sichuan peppercorns, toasted and ground", ingredient: "sichuan peppercorns", quantity: 1 },
      { text: "4 cloves garlic, minced", ingredient: "garlic", quantity: 4 },
      { text: "2 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 2 },
      { text: "4 scallions, chopped", ingredient: "scallion", quantity: 4 },
      { text: "Chopped peanuts, for garnish", ingredient: "peanuts", quantity: null },
    ],
    steps: [
      "Heat vegetable oil in a wok over medium-high heat, add ground pork, and stir-fry, breaking it into small crispy bits, until deeply browned, about 5-6 minutes.",
      "Add the preserved mustard greens and half the garlic to the pork and stir-fry another minute, then set aside.",
      "Toast the Sichuan peppercorns in a dry pan for 30 seconds until fragrant, then grind - freshly ground peppercorns lose their numbing punch within days, so grind just before using.",
      "For the sauce, whisk the sesame paste with a splash of warm water to loosen it, then combine with the remaining soy sauce, chili oil and its sediment, black vinegar, remaining garlic, and ground peppercorns in the bottom of each serving bowl.",
      "Cook the noodles in boiling water until just tender, then use a ladle of the starchy noodle water to loosen the sauce in each bowl before draining the noodles.",
      "Divide the noodles among the bowls on top of the sauce - do not mix yet, since dan dan noodles are traditionally served this way and tossed tableside.",
      "Top each bowl with the crispy pork mixture, chopped scallions, and peanuts, then toss everything together just before eating so the sauce coats every strand.",
    ],
    tags: ["dinner", "lunch"],
    bg: {
      title: "Дан Дан Нудълс",
      description: "Сичуанско ястие с юфка, поднесено сухо, не като супа - остър и изтръпващ сос от сусамова паста, чили олио и сичуански пипер, покрит с хрупкаво запържено свинско. Поднася се без разбъркване и се смесва точно преди хапване.",
      steps: [
        "Загрейте олиото в уок на средно-силен огън, добавете смляното свинско и запържете, разчупвайки го на малки хрупкави парченца, докато стане дълбоко кафяво, около 5-6 минути.",
        "Добавете туршийните зеленчуци и половината чесън към свинското и запържете още минута, после оставете настрана.",
        "Препечете сичуанския пипер в сух тиган за 30 секунди, докато замирише, после го смелете - прясно смляният пипер губи изтръпващата си сила за дни, затова го смелете точно преди употреба.",
        "За соса разбъркайте сусамовата паста с малко топла вода, за да я разредите, после я смесете с останалия соев сос, чили олиото с утайката му, черния оцет, останалия чесън и смления пипер на дъното на всяка купа за сервиране.",
        "Сварете юфката във вряла вода до готовност, после използвайте черпак от нишестената вода на юфката, за да разредите соса във всяка купа, преди да отцедите юфката.",
        "Разпределете юфката в купите върху соса - не разбърквайте още - Дан Дан юфка традиционно се поднася така и се разбърква на масата.",
        "Отгоре поставете хрупкавата свинска смес, нарязания пролетен лук и фъстъците, после разбъркайте всичко точно преди хапване, за да покрие сосът всяка нишка.",
      ],
      ingredients: [
        "450г прясна пшенична юфка (или суха, тънка кръгла)",
        "225г смляно свинско",
        "2 с.л. консервирани туршийни горчични зеленчуци (суи ми я цай)",
        "3 с.л. светъл соев сос, разделен",
        "2 с.л. китайска сусамова паста (или тахан)",
        "2 с.л. чили олио, плюс утайката",
        "1 с.л. черен оцет",
        "1 ч.л. сичуански пипер, препечен и смлян",
        "4 скилидки чесън, ситно нарязани",
        "2 с.л. олио",
        "4 стръка пролетен лук, нарязани",
        "Натрошени фъстъци, за украса",
      ],
    },
  },
  {
    slug: "hainanese-chicken-rice",
    title: "Hainanese Chicken Rice",
    description:
      "Singapore's beloved dish of silky poached chicken over fragrant rice cooked in the chicken's own broth. The secret is a steady, gentle simmer that never fully boils, which keeps the meat tender instead of tough.",
    imageEmoji: "🍗",
    cookTimeMinutes: 75,
    servings: 4,
    caloriesPerServing: 620,
    proteinG: 38,
    carbsG: 62,
    fatG: 22,
    ingredients: [
      { text: "1 whole chicken (about 3-3.5 lbs)", ingredient: "whole chicken", quantity: 1 },
      { text: "4-inch piece ginger, sliced", ingredient: "ginger", quantity: 1 },
      { text: "1 tbsp ginger, grated", ingredient: "ginger", quantity: 1 },
      { text: "4 scallions, whole", ingredient: "scallion", quantity: 4 },
      { text: "2 tsp salt", ingredient: "salt", quantity: 2 },
      { text: "2 cups jasmine rice", ingredient: "jasmine rice", quantity: 2 },
      { text: "2 tbsp rendered chicken fat or oil", ingredient: "chicken fat", quantity: 2 },
      { text: "4 cloves garlic, minced", ingredient: "garlic", quantity: 4 },
      { text: "2 pandan leaves, tied in a knot (optional)", ingredient: "pandan leaves", quantity: 2 },
      { text: "4 red chilies (for chili sauce)", ingredient: "red chili", quantity: 4 },
      { text: "2 cloves garlic (for chili sauce)", ingredient: "garlic", quantity: 2 },
      { text: "1 tbsp lime juice (for chili sauce)", ingredient: "lime juice", quantity: 1 },
      { text: "1 tsp sugar (for chili sauce)", ingredient: "sugar", quantity: 1 },
    ],
    steps: [
      "Pound the ginger slices lightly to release their oils, then place in a large pot with about 4 quarts water, the whole scallions, and salt; bring to a full boil.",
      "Lower the chicken carefully into the boiling water breast-side down; when the water returns to a boil, immediately reduce to the lowest simmer.",
      "Poach gently, never boiling, for 40-45 minutes, until the chicken is just cooked through - maintaining a steady, gentle heat rather than a boil is what keeps the meat silky instead of tough.",
      "Remove the chicken and plunge immediately into an ice water bath for 10-15 minutes - this tightens the skin to give it the dish's signature smooth, bouncy texture.",
      "Skim the fat from the poaching broth; heat 2 tbsp of it in a pot, add the grated ginger and garlic, and toast lightly until fragrant.",
      "Add the rinsed rice and stir to coat every grain in the fragrant fat, then add the poaching broth (using the same ratio as for plain rice) and the pandan leaves if using; cover and cook until the rice is tender and fragrant.",
      "For the chili sauce, blend the chilies, garlic, lime juice, sugar, and a few tablespoons of the hot poaching broth until smooth.",
      "Chop the chicken into pieces and serve over the rice with the chili sauce and a bowl of the poaching broth as a light soup on the side.",
    ],
    tags: ["dinner", "lunch"],
    bg: {
      title: "Хайнанска Пилешка Оризова Купа",
      description: "Сингапурско ястие от нежно поширано пиле върху ароматен ориз, сварен в бульона от самото пиле - готвенето на съвсем слаб огън, никога до кипене, е тайната за копринено меко месо.",
      steps: [
        "Леко разчукайте резените джинджифил, за да освободят маслата си, после ги сложете в голяма тенджера с около 4 литра вода, целия пролетен лук и солта; кипнете напълно.",
        "Внимателно спуснете пилето във врящата вода с гърдите надолу; когато водата отново заври, веднага намалете на най-слабо къкрене.",
        "Поширайте леко, никога до кипене, 40-45 минути, докато пилето точно се сготви - поддържането на постоянна, слаба топлина, вместо кипене, е това, което пази месото копринено меко, вместо жилаво.",
        "Извадете пилето и веднага го потопете в ледена вода за 10-15 минути - това стяга кожата и придава характерната гладка, еластична текстура на ястието.",
        "Обезмаслете бульона от поширането; загрейте 2 с.л. от него в тенджера, добавете настъргания джинджифил и чесъна и леко ги запържете, докато замиришат.",
        "Добавете изплакнатия ориз и разбъркайте, за да покриете всяко зърно с ароматната мазнина, после добавете бульона от поширането (в същото съотношение като за обикновен ориз) и панданените листа, ако ги ползвате; покрийте и гответе, докато оризът омекне и ароматизира.",
        "За чили соса пасирайте лютите чушки, чесъна, лимоновия сок, захарта и няколко супени лъжици от горещия бульон от поширането до гладкост.",
        "Нарежете пилето на парчета и сервирайте върху ориза с чили соса и купичка от бульона от поширането като лека супа отстрани.",
      ],
      ingredients: [
        "1 цяло пиле (около 1.4-1.6кг)",
        "Парче джинджифил 10 см, нарязано на резени",
        "1 с.л. настърган джинджифил",
        "4 стръка пролетен лук, цели",
        "2 ч.л. сол",
        "2 чаши жасминов ориз",
        "2 с.л. пилешка мазнина или олио",
        "4 скилидки чесън, ситно нарязани",
        "2 листа пандан, вързани на възел (по желание)",
        "4 червени люти чушки (за чили соса)",
        "2 скилидки чесън (за чили соса)",
        "1 с.л. лимонов сок (за чили соса)",
        "1 ч.л. захар (за чили соса)",
      ],
    },
  },
  {
    slug: "tonkatsu",
    title: "Tonkatsu",
    description:
      "Japan's crispy fried pork cutlet, breaded in airy panko for an audibly crunchy crust. Pressing the crumbs firmly into the meat on both sides, including the edges, is what keeps the coating from falling off during frying.",
    imageEmoji: "🍱",
    cookTimeMinutes: 30,
    servings: 4,
    caloriesPerServing: 520,
    proteinG: 32,
    carbsG: 34,
    fatG: 28,
    ingredients: [
      { text: "4 pork loin cutlets (about 6 oz each)", ingredient: "pork loin", quantity: 4 },
      { text: "Salt and pepper, to taste", ingredient: "salt and pepper", quantity: null },
      { text: "1/2 cup all-purpose flour", ingredient: "flour", quantity: 0.5 },
      { text: "2 eggs, beaten", ingredient: "egg", quantity: 2 },
      { text: "2 cups panko breadcrumbs", ingredient: "panko breadcrumbs", quantity: 2 },
      { text: "Vegetable oil, for deep frying", ingredient: "vegetable oil", quantity: null },
      { text: "4 cups shredded cabbage, for serving", ingredient: "cabbage", quantity: 4 },
      { text: "3 tbsp ketchup (for sauce)", ingredient: "ketchup", quantity: 3 },
      { text: "2 tbsp Worcestershire sauce (for sauce)", ingredient: "worcestershire sauce", quantity: 2 },
      { text: "1 tbsp oyster sauce (for sauce)", ingredient: "oyster sauce", quantity: 1 },
      { text: "1 tsp sugar (for sauce)", ingredient: "sugar", quantity: 1 },
    ],
    steps: [
      "Season the pork cutlets with salt and pepper, then use the back of a knife or a meat mallet to lightly pound them to an even thickness; let rest at room temperature for 5-10 minutes before breading, which helps the coating adhere and fry more evenly.",
      "Set up three shallow dishes: flour in the first, beaten eggs in the second, and panko in the third; lightly crush the panko with your hands to create a mix of fine and coarse crumbs for extra crunch.",
      "Dredge each cutlet in flour, shaking off the excess - too much flour makes the coating gummy - then dip fully in the egg, and finally press firmly into the panko on both sides so it adheres well, including the edges.",
      "Heat oil to 340F (170C) in a deep pot or pan.",
      "Fry the cutlets for 3-4 minutes per side, until deep golden brown and cooked through, then drain on a wire rack rather than paper towels, which trap steam and soften the crust.",
      "Whisk together the ketchup, Worcestershire sauce, oyster sauce, and sugar for the tonkatsu sauce.",
      "Slice the cutlets into strips and serve over shredded raw cabbage with the tonkatsu sauce, steamed rice, and miso soup.",
    ],
    tags: ["dinner", "lunch"],
    bg: {
      title: "Тонкацу",
      description: "Японски пържен свински шницел, панициран в панко трохи за въздушна, хрупкава коричка. Плътно притискане на трохите в месото от двете страни е тайната панировката да не падне при пържене.",
      steps: [
        "Подправете свинските пържоли със сол и пипер, после леко ги начукайте с гърба на нож или чук за месо до равномерна дебелина; оставете да престоят на стайна температура 5-10 минути преди паниране, което помага панировката да залепне и да се изпържи по-равномерно.",
        "Подгответе три плитки съда: брашно в първия, разбити яйца във втория и панко трохи в третия; леко натрошете панкото с ръце, за да получите смес от фини и едри трохи за допълнителна хрупкавост.",
        "Овалайте всяка пържола в брашно, изтръсквайки излишъка - твърде много брашно прави панировката лепкава - после потопете напълно в яйцето и накрая притиснете плътно в панкото от двете страни, включително по краищата.",
        "Загрейте олио до 170°C в дълбока тенджера или тиган.",
        "Пържете пържолите 3-4 минути от всяка страна, докато станат дълбоко златисти и се изпекат напълно, после отцедете върху решетка, а не хартиена кърпа, която задържа парата и омекотява коричката.",
        "Разбийте кетчупа, устърширския сос, соя със стриди и захарта за соса тонкацу.",
        "Нарежете пържолите на ивици и сервирайте върху сурово настъргано зеле със соса тонкацу, ориз на пара и мисо супа.",
      ],
      ingredients: [
        "4 свински пържоли (около 170г всяка)",
        "Сол и черен пипер на вкус",
        "1/2 чаша брашно",
        "2 яйца, разбити",
        "2 чаши панко трохи",
        "Олио за дълбоко пържене",
        "4 чаши настъргано зеле, за сервиране",
        "3 с.л. кетчуп (за соса)",
        "2 с.л. устърширски сос (за соса)",
        "1 с.л. соев сос стриди (за соса)",
        "1 ч.л. захар (за соса)",
      ],
    },
  },
  {
    slug: "taiyaki",
    title: "Taiyaki",
    description:
      "Japan's fish-shaped street snack - a thin, crisp waffle shell filled with warm sweet red bean paste. The batter should be mixed just until smooth, since overmixing makes the shell tough instead of light.",
    imageEmoji: "🐟",
    cookTimeMinutes: 45,
    servings: 6,
    caloriesPerServing: 210,
    proteinG: 5,
    carbsG: 40,
    fatG: 3,
    ingredients: [
      { text: "1 cup all-purpose flour", ingredient: "flour", quantity: 1 },
      { text: "1 tsp baking powder", ingredient: "baking powder", quantity: 1 },
      { text: "1 egg", ingredient: "egg", quantity: 1 },
      { text: "3/4 cup milk", ingredient: "milk", quantity: 0.75 },
      { text: "2 tbsp water", ingredient: "water", quantity: 2 },
      { text: "2 tbsp sugar", ingredient: "sugar", quantity: 2 },
      { text: "Pinch of salt", ingredient: "salt", quantity: null },
      { text: "1 cup sweet red bean paste (anko)", ingredient: "red bean paste", quantity: 1 },
      { text: "Butter or oil, for greasing the mold", ingredient: "butter", quantity: null },
    ],
    steps: [
      "Sift the flour and baking powder into a bowl and make a well in the center.",
      "In a separate bowl, beat the egg lightly, then whisk in the milk, water, sugar, and salt.",
      "Pour the wet ingredients into the well of flour and mix just until smooth, being careful not to overmix, which would make the taiyaki tough instead of light.",
      "Cover and refrigerate the batter for at least 30 minutes to rest.",
      "Divide the red bean paste into portions and shape each into a small log to fit inside the mold.",
      "Heat a taiyaki pan over low heat and grease both sides of the mold, then fill one side halfway with batter.",
      "Place a portion of red bean paste on top of the batter, then cover with a bit more batter, close the pan, and cook, flipping periodically, for 10-15 minutes until both sides are deep golden brown.",
      "Serve warm, when the shell is crispiest and the filling is still molten.",
    ],
    tags: ["dessert", "snack"],
    bg: {
      title: "Таяки",
      description: "Японска улична сладост във формата на риба - тънко хрупкаво тесто, пълнено с топла сладка паста от червен боб. Тестото не бива да се разбърква прекалено, иначе таякито излиза твърдо вместо леко.",
      steps: [
        "Пресейте брашното и бакпулвера в купа и направете кладенче в центъра.",
        "В отделна купа леко разбийте яйцето, после разбъркайте с млякото, водата, захарта и солта.",
        "Изсипете течната смес в кладенчето с брашното и разбъркайте само докато се получи гладко тесто, внимавайки да не разбърквате прекалено, което би направило таякито твърдо вместо леко.",
        "Покрийте и оставете тестото в хладилник поне 30 минути да почине.",
        "Разделете пастата от червен боб на порции и оформете всяка на малко руло, за да пасне във формата.",
        "Загрейте тиган за таяки на слаб огън и намажете двете страни на формата, после напълнете едната страна наполовина с тесто.",
        "Сложете порция паста от червен боб върху тестото, после покрийте с още малко тесто, затворете тигана и гответе, обръщайки периодично, 10-15 минути, докато и двете страни станат дълбоко златисти.",
        "Сервирайте топло, докато коричката е най-хрупкава, а пълнежът все още течен.",
      ],
      ingredients: [
        "1 чаша брашно",
        "1 ч.л. бакпулвер",
        "1 яйце",
        "3/4 чаша мляко",
        "2 с.л. вода",
        "2 с.л. захар",
        "Щипка сол",
        "1 чаша сладка паста от червен боб (анко)",
        "Масло или олио, за намазване на формата",
      ],
    },
  },
  {
    slug: "sundubu-jjigae",
    title: "Sundubu Jjigae",
    description:
      "Korea's spicy soft tofu stew - the silken tofu goes into the pot in large chunks straight from the tube, unpressed and undrained, and is barely stirred afterward so it stays velvety instead of breaking into mush.",
    imageEmoji: "🍲",
    cookTimeMinutes: 30,
    servings: 4,
    caloriesPerServing: 320,
    proteinG: 24,
    carbsG: 12,
    fatG: 20,
    ingredients: [
      { text: "2 tubes (12 oz each) soft silken tofu (sundubu)", ingredient: "silken tofu", quantity: 2 },
      { text: "8 oz thinly sliced pork or beef", ingredient: "pork", quantity: 8 },
      { text: "1/2 cup kimchi, chopped", ingredient: "kimchi", quantity: 0.5 },
      { text: "1 tbsp gochugaru (Korean chili flakes)", ingredient: "gochugaru", quantity: 1 },
      { text: "1/2 tbsp gochujang", ingredient: "gochujang", quantity: 0.5 },
      { text: "1 tbsp sesame oil", ingredient: "sesame oil", quantity: 1 },
      { text: "3 cloves garlic, minced", ingredient: "garlic", quantity: 3 },
      { text: "1/2 onion, sliced", ingredient: "onion", quantity: 0.5 },
      { text: "3 cups anchovy or beef broth", ingredient: "broth", quantity: 3 },
      { text: "1 tbsp soy sauce", ingredient: "soy sauce", quantity: 1 },
      { text: "2 scallions, sliced", ingredient: "scallion", quantity: 2 },
      { text: "4 eggs", ingredient: "egg", quantity: 4 },
    ],
    steps: [
      "Heat the sesame oil in a Korean earthenware pot (ttukbaegi) or heavy pot over medium heat, add the garlic and onion, and saute until fragrant.",
      "Add the sliced meat and cook until no longer pink, then add the kimchi, gochugaru, and gochujang and stir-fry for 1-2 minutes to bloom the chili flavors.",
      "Pour in the broth and soy sauce, bring to a simmer, and cook for 5-8 minutes until the flavors meld.",
      "Gently spoon the soft tofu into the pot in large chunks straight from the tube, without pressing or draining it - avoid stirring too much afterward, since sundubu is delicate and breaks down into mush if handled roughly.",
      "Simmer for another 3-4 minutes, just until the tofu is heated through.",
      "Crack an egg into each bowl right before serving, or into the pot itself while it's still bubbling hot, so the residual heat gently cooks it.",
      "Garnish with scallions and serve immediately with steamed rice, while it's still boiling in the pot.",
    ],
    tags: ["dinner", "lunch"],
    bg: {
      title: "Сундубу Джигае",
      description: "Корейска пикантна яхния с копринено меко тофу - тофуто се слага на едри късове направо от опаковката, без да се притиска, и не се разбърква много, за да остане нежно, а не да се разпадне на каша.",
      steps: [
        "Загрейте сусамовото олио в корейски глинен съд (тукбеги) или тежка тенджера на средна температура, добавете чесъна и лука и запържете, докато замиришат.",
        "Добавете нарязаното месо и гответе, докато престане да е розово, после добавете кимчито, кочугару и кочуджанга и запържете 1-2 минути, за да се разгърне ароматът на чушките.",
        "Налейте бульона и соевия сос, кипнете и гответе 5-8 минути, докато вкусовете се съчетаят.",
        "Внимателно сложете мекото тофу в тенджерата на едри късове направо от опаковката, без да го притискате или отцеждате - избягвайте да разбърквате много след това, тъй като сундубу е нежно и се разпада на каша при грубо боравене.",
        "Къкрете още 3-4 минути, само докато тофуто се затопли напълно.",
        "Счупете по едно яйце във всяка купа точно преди сервиране, или направо в тенджерата, докато още кипи, за да се сготви леко от остатъчната топлина.",
        "Украсете с пролетен лук и сервирайте веднага с ориз на пара, докато яхнията още къкри в съда.",
      ],
      ingredients: [
        "2 опаковки (по 340г) меко копринено тофу (сундубу)",
        "225г тънко нарязано свинско или телешко месо",
        "1/2 чаша кимчи, нарязано",
        "1 с.л. кочугару (корейски люти чушки на люспи)",
        "1/2 с.л. кочуджанг",
        "1 с.л. сусамово олио",
        "3 скилидки чесън, ситно нарязани",
        "1/2 лук, нарязан на резени",
        "3 чаши бульон от аншоа или телешки бульон",
        "1 с.л. соев сос",
        "2 стръка пролетен лук, нарязани",
        "4 яйца",
      ],
    },
  },
  {
    slug: "hotteok",
    title: "Hotteok",
    description:
      "Korea's sweet yeasted street pancake, stuffed with molten cinnamon sugar. Pressing the filled dough flat in the pan for 8-10 seconds is what spreads the filling evenly and gives hotteok its signature round shape.",
    imageEmoji: "🥞",
    cookTimeMinutes: 120,
    servings: 6,
    caloriesPerServing: 280,
    proteinG: 5,
    carbsG: 48,
    fatG: 8,
    ingredients: [
      { text: "2 cups all-purpose flour", ingredient: "flour", quantity: 2 },
      { text: "2 tbsp glutinous rice flour", ingredient: "glutinous rice flour", quantity: 2 },
      { text: "2 tbsp sugar", ingredient: "sugar", quantity: 2 },
      { text: "1 tsp instant yeast", ingredient: "yeast", quantity: 1 },
      { text: "1/2 tsp salt", ingredient: "salt", quantity: 0.5 },
      { text: "3/4 cup warm milk", ingredient: "milk", quantity: 0.75 },
      { text: "2 tbsp vegetable oil, plus more for frying", ingredient: "vegetable oil", quantity: 2 },
      { text: "1/2 cup brown sugar (for filling)", ingredient: "brown sugar", quantity: 0.5 },
      { text: "1 tbsp ground cinnamon (for filling)", ingredient: "cinnamon", quantity: 1 },
      { text: "2 tbsp chopped peanuts (for filling)", ingredient: "peanuts", quantity: 2 },
      { text: "1 tbsp all-purpose flour (for filling)", ingredient: "flour", quantity: 1 },
    ],
    steps: [
      "In a large bowl, whisk together the flour, glutinous rice flour, sugar, yeast, and salt, then stir in the warm milk and oil to form a soft, sticky dough.",
      "Cover and let rise in a warm place until doubled in size, about 1-2 hours.",
      "For the filling, mix the brown sugar, cinnamon, chopped peanuts, and flour together in a small bowl - the flour keeps the sugar from turning into a runny syrup that leaks out too fast.",
      "Lightly oil your hands, take a portion of dough, and flatten it into a small disc, then place a spoonful of filling in the center.",
      "Gather the edges of the dough up and around the filling, pinching to seal it completely so no filling escapes.",
      "Heat a lightly oiled griddle or pan over medium-low heat, place the filled dough ball seam-side down, and press down firmly with a flat spatula for 8-10 seconds to flatten it into a round pancake - this pressing step is what spreads the filling evenly and gives hotteok its shape.",
      "Cook for 2-3 minutes per side until golden brown, pressing occasionally, until the sugar filling has melted inside.",
      "Serve hot in a small cup or on a napkin, since the molten filling can drip.",
    ],
    tags: ["dessert", "snack"],
    bg: {
      title: "Хотток",
      description: "Корейски сладки палачинки с квасено тесто, пълнени с разтопена канелена захар - притискането на тестото в тигана за 8-10 секунди е това, което разпределя пълнежа равномерно и придава характерната плоска кръгла форма.",
      steps: [
        "В голяма купа разбъркайте брашното, оризовото брашно, захарта, маята и солта, после разбъркайте с топлото мляко и олиото, за да се получи меко, лепкаво тесто.",
        "Покрийте и оставете да втаса на топло място, докато удвои обема си, около 1-2 часа.",
        "За пълнежа смесете кафявата захар, канелата, натрошените фъстъци и брашното в малка купа - брашното пази захарта да не се превърне в течен сироп, който изтича твърде бързо.",
        "Намажете леко ръцете си с олио, вземете парче тесто и го сплескайте в малък диск, после сложете лъжица пълнеж в центъра.",
        "Съберете краищата на тестото нагоре и около пълнежа, стискайки, за да го затворите напълно, така че пълнежът да не изтича.",
        "Загрейте леко намазан тиган на средно-слаб огън, сложете топчето тесто с шева надолу и притиснете силно с плоска шпатула за 8-10 секунди, за да го сплескате в кръгла палачинка - това притискане разпределя пълнежа равномерно и придава на хоттока характерната форма.",
        "Печете 2-3 минути от всяка страна до златисто, притискайки от време на време, докато захарният пълнеж се разтопи вътре.",
        "Сервирайте горещо в малка чашка или салфетка, тъй като разтопеният пълнеж може да капе.",
      ],
      ingredients: [
        "2 чаши брашно",
        "2 с.л. оризово брашно от лепкав ориз",
        "2 с.л. захар",
        "1 ч.л. инстантна мая",
        "1/2 ч.л. сол",
        "3/4 чаша топло мляко",
        "2 с.л. олио, плюс още за пържене",
        "1/2 чаша кафява захар (за пълнежа)",
        "1 с.л. смляна канела (за пълнежа)",
        "2 с.л. натрошени фъстъци (за пълнежа)",
        "1 с.л. брашно (за пълнежа)",
      ],
    },
  },
  {
    slug: "taiwanese-beef-noodle-soup",
    title: "Taiwanese Beef Noodle Soup",
    description:
      "Taiwan's national dish - beef shank braised low and slow with doubanjiang, star anise, and cinnamon until it falls apart, served over noodles in the rich, spiced broth it cooked in.",
    imageEmoji: "🍲",
    cookTimeMinutes: 210,
    servings: 6,
    caloriesPerServing: 580,
    proteinG: 38,
    carbsG: 62,
    fatG: 18,
    ingredients: [
      { text: "2.5 lbs boneless beef shank, cut into 2-inch chunks", ingredient: "beef shank", quantity: 2.5 },
      { text: "2 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 2 },
      { text: "3 tbsp doubanjiang (spicy fermented bean paste)", ingredient: "doubanjiang", quantity: 3 },
      { text: "1 onion, sliced", ingredient: "onion", quantity: 1 },
      { text: "6 cloves garlic", ingredient: "garlic", quantity: 6 },
      { text: "3-inch piece ginger, sliced", ingredient: "ginger", quantity: 1 },
      { text: "4 star anise", ingredient: "star anise", quantity: 4 },
      { text: "1 cinnamon stick", ingredient: "cinnamon stick", quantity: 1 },
      { text: "2 tbsp Sichuan peppercorns", ingredient: "sichuan peppercorns", quantity: 2 },
      { text: "1/2 cup soy sauce", ingredient: "soy sauce", quantity: 0.5 },
      { text: "2 tbsp dark soy sauce", ingredient: "dark soy sauce", quantity: 2 },
      { text: "2 tbsp rock sugar or sugar", ingredient: "rock sugar", quantity: 2 },
      { text: "3 tomatoes, quartered", ingredient: "tomato", quantity: 3 },
      { text: "8 cups water or beef broth", ingredient: "beef broth", quantity: 8 },
      { text: "1.5 lbs fresh wheat noodles", ingredient: "wheat noodles", quantity: 1.5 },
      { text: "Baby bok choy, blanched, for serving", ingredient: "bok choy", quantity: null },
      { text: "Pickled mustard greens and scallions, for garnish", ingredient: "pickled mustard greens", quantity: null },
    ],
    steps: [
      "Bring a large pot of water to a boil and blanch the beef shank chunks for 1 minute to remove excess blood and impurities, then drain and rinse.",
      "Heat the oil in a large pot, add the doubanjiang, onion, garlic, and ginger, and stir-fry for 2-3 minutes until fragrant and the oil turns red.",
      "Add the star anise, cinnamon stick, and Sichuan peppercorns and toast for 30 seconds.",
      "Add the blanched beef, soy sauce, dark soy sauce, sugar, and tomatoes, and stir to coat the beef in the aromatics.",
      "Pour in the water or broth, bring to a boil, then reduce to a gentle simmer, cover, and cook for 2.5 to 3 hours, until the beef is fall-apart tender.",
      "Cook the noodles separately in boiling water until just tender, then divide among bowls.",
      "Ladle the beef, broth, and tomatoes over the noodles, top with blanched bok choy, pickled mustard greens, and scallions, and serve hot.",
    ],
    tags: ["dinner", "lunch"],
    bg: {
      title: "Тайванска Телешка Супа с Юфка",
      description: "Националното ястие на Тайван - телешки джолан, бавно къкрян с доубанджианг, звезден анасон и канела, докато не се разпадне от мекота, поднесен върху юфка в наситения си пикантен бульон.",
      steps: [
        "Кипнете голяма тенджера вода и бланширайте телешките парчета за 1 минута, за да отстраните излишната кръв и примеси, после отцедете и изплакнете.",
        "Загрейте олиото в голяма тенджера, добавете доубанджианга, лука, чесъна и джинджифила и запържете 2-3 минути, докато замиришат и олиото почервенее.",
        "Добавете звездния анасон, канелата и сичуанския пипер и препечете 30 секунди.",
        "Добавете бланшираното телешко, соевия сос, тъмния соев сос, захарта и доматите и разбъркайте, за да покриете телешкото с подправките.",
        "Налейте водата или бульона, кипнете, после намалете на леко къкрене, покрийте и гответе 2.5 до 3 часа, докато телешкото се разпадне от мекота.",
        "Сварете юфката отделно във вряла вода до готовност, после разпределете в купи.",
        "Залейте телешкото, бульона и доматите върху юфката, украсете с бланшираното бок чой, кисели горчични зеленчуци и пролетен лук и сервирайте горещо.",
      ],
      ingredients: [
        "1.1кг телешки джолан без кост, нарязан на парчета по 5 см",
        "2 с.л. олио",
        "3 с.л. доубанджианг (лют ферментирал бобов сос)",
        "1 лук, нарязан на резени",
        "6 скилидки чесън",
        "Парче джинджифил 7-8 см, нарязано на резени",
        "4 звезди анасон",
        "1 пръчка канела",
        "2 с.л. сичуански пипер",
        "1/2 чаша соев сос",
        "2 с.л. тъмен соев сос",
        "2 с.л. кристална захар или обикновена захар",
        "3 домата, нарязани на четвъртинки",
        "8 чаши вода или телешки бульон",
        "675г прясна пшенична юфка",
        "Бок чой, бланширано, за сервиране",
        "Кисели горчични зеленчуци и пролетен лук, за украса",
      ],
    },
  },
  {
    slug: "lagman",
    title: "Lagman",
    description:
      "A noodle dish loved across Central Asia by Uyghurs and Uzbeks alike - a hearty meat-and-vegetable stew ladled over long, elastic noodles traditionally stretched and pulled entirely by hand, using oil rather than flour to keep the strands from sticking.",
    imageEmoji: "🍜",
    cookTimeMinutes: 90,
    servings: 6,
    caloriesPerServing: 480,
    proteinG: 28,
    carbsG: 52,
    fatG: 18,
    ingredients: [
      { text: "2 lbs lamb or beef, cut into small chunks", ingredient: "lamb", quantity: 2 },
      { text: "3 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 3 },
      { text: "1 onion, sliced", ingredient: "onion", quantity: 1 },
      { text: "2 bell peppers, sliced", ingredient: "bell pepper", quantity: 2 },
      { text: "2 carrots, sliced", ingredient: "carrot", quantity: 2 },
      { text: "3 tomatoes, chopped (or 2 tbsp tomato paste)", ingredient: "tomato", quantity: 3 },
      { text: "4 cloves garlic, minced", ingredient: "garlic", quantity: 4 },
      { text: "1 tsp cumin", ingredient: "cumin", quantity: 1 },
      { text: "1 tsp paprika", ingredient: "paprika", quantity: 1 },
      { text: "1/2 tsp chili flakes", ingredient: "chili flakes", quantity: 0.5 },
      { text: "4 cups beef broth", ingredient: "beef broth", quantity: 4 },
      { text: "1 lb fresh or dried wheat noodles", ingredient: "wheat noodles", quantity: 1 },
      { text: "2 potatoes, cubed (optional)", ingredient: "potato", quantity: 2 },
      { text: "Fresh cilantro, for garnish", ingredient: "cilantro", quantity: null },
    ],
    steps: [
      "If making hand-pulled noodles, work the dough with plenty of vegetable oil rather than flour to keep it from sticking, then stretch and pull it repeatedly, doubling it over each time, until it forms long, elastic strands - this takes patience and practice, so store-bought thick wheat noodles work well as a substitute.",
      "Heat the oil in a large pot or wok, brown the meat in batches over high heat, then remove and set aside.",
      "In the same pot, saute the onion, bell peppers, and carrots until softened, then add the garlic, cumin, paprika, and chili flakes and cook for 1 minute until fragrant.",
      "Return the meat to the pot, add the tomatoes (or tomato paste) and potatoes if using, and stir to combine.",
      "Pour in the broth, bring to a boil, then reduce to a simmer and cook covered for 45-60 minutes, until the meat is tender and the sauce has thickened into a hearty stew.",
      "Cook the noodles separately in boiling water until tender, then drain.",
      "Divide the noodles among bowls and ladle the meat and vegetable stew generously over the top, garnishing with fresh cilantro.",
    ],
    tags: ["dinner", "lunch"],
    bg: {
      title: "Лагман",
      description: "Ястие с юфка от Централна Азия, обичано от уйгури и узбеки - плътна месно-зеленчукова яхния, залята върху дълга еластична юфка, традиционно опъвана и разтегляна на ръка с олио вместо брашно.",
      steps: [
        "Ако правите юфка на ръка, работете тестото с много олио вместо брашно, за да не залепва, после го разтягайте и опъвайте многократно, сгъвайки го наполовина всеки път, докато се получат дълги еластични нишки - това изисква търпение и практика, така че готова дебела пшенична юфка също върши работа.",
        "Загрейте олиото в голяма тенджера или уок, запържете месото на партиди на силен огън до кафяво, после извадете и оставете настрана.",
        "В същата тенджера запържете лука, чушките и морковите, докато омекнат, после добавете чесъна, кимиона, червения пипер и лютите люспи и гответе 1 минута, докато замиришат.",
        "Върнете месото в тенджерата, добавете доматите (или доматеното пюре) и картофите, ако ги ползвате, и разбъркайте.",
        "Налейте бульона, кипнете, после намалете на къкрене и гответе покрито 45-60 минути, докато месото омекне, а сосът се сгъсти в наситена яхния.",
        "Сварете юфката отделно във вряла вода до готовност, после отцедете.",
        "Разпределете юфката в купи и залейте щедро с месно-зеленчуковата яхния отгоре, украсявайки с пресен кориандър.",
      ],
      ingredients: [
        "900г агнешко или телешко месо, нарязано на малки късове",
        "3 с.л. олио",
        "1 лук, нарязан на резени",
        "2 чушки, нарязани на резени",
        "2 моркова, нарязани на резени",
        "3 домата, нарязани (или 2 с.л. доматено пюре)",
        "4 скилидки чесън, ситно нарязани",
        "1 ч.л. кимион",
        "1 ч.л. червен пипер",
        "1/2 ч.л. люти чушки на люспи",
        "4 чаши телешки бульон",
        "450г прясна или суха пшенична юфка",
        "2 картофа, нарязани на кубчета (по желание)",
        "Пресен кориандър, за украса",
      ],
    },
  },
  {
    slug: "char-siu",
    title: "Char Siu",
    description:
      "Cantonese barbecued pork - long strips marinated in fermented red bean curd, honey, and five-spice, then roasted until the edges char and caramelize. The fermented bean curd is what gives authentic char siu its signature red color.",
    imageEmoji: "🍖",
    cookTimeMinutes: 300,
    servings: 6,
    caloriesPerServing: 420,
    proteinG: 30,
    carbsG: 18,
    fatG: 26,
    ingredients: [
      { text: "2.5 lbs pork shoulder, cut into long strips 2-3 inches thick", ingredient: "pork shoulder", quantity: 2.5 },
      { text: "2 tbsp fermented red bean curd (nam yu), mashed", ingredient: "fermented red bean curd", quantity: 2 },
      { text: "3 tbsp honey, divided", ingredient: "honey", quantity: 3 },
      { text: "2 tbsp maltose (or additional honey)", ingredient: "maltose", quantity: 2 },
      { text: "3 tbsp hoisin sauce", ingredient: "hoisin sauce", quantity: 3 },
      { text: "2 tbsp soy sauce", ingredient: "soy sauce", quantity: 2 },
      { text: "1 tbsp Shaoxing wine", ingredient: "shaoxing wine", quantity: 1 },
      { text: "1 tsp five-spice powder", ingredient: "five-spice powder", quantity: 1 },
      { text: "3 cloves garlic, minced", ingredient: "garlic", quantity: 3 },
      { text: "Red food coloring (optional, for color)", ingredient: "red food coloring", quantity: null },
    ],
    steps: [
      "In a bowl, combine the mashed fermented red bean curd, 2 tbsp honey, maltose, hoisin sauce, soy sauce, Shaoxing wine, five-spice powder, and garlic to make the marinade - the fermented bean curd is what gives authentic char siu its characteristic red color and deep savory-sweet flavor.",
      "Add the pork strips to the marinade, turning to coat thoroughly; don't trim the fat, since it renders down and bastes the meat as it cooks. Cover and marinate in the fridge for at least 4 hours, ideally overnight.",
      "Preheat the oven to 375F (190C) and set a wire rack over a foil-lined baking sheet with water in the bottom to catch drips and prevent smoking.",
      "Arrange the pork strips on the rack and roast for 25 minutes, then flip and roast another 15 minutes.",
      "Brush the remaining honey over the pork and roast for a final 5-10 minutes, until the edges are charred and caramelized and the internal temperature reaches 145F (63C).",
      "Let the pork rest for 10 minutes before slicing - this lets the juices redistribute so the meat stays tender rather than drying out.",
      "Slice and serve over steamed rice, or toss into fried rice or noodle dishes.",
    ],
    tags: ["dinner", "lunch"],
    bg: {
      title: "Ча Сиу",
      description: "Кантонско барбекю свинско - дълги ивици месо, мариновани в ферментирала червена соева извара, мед и петте подправки, после печени, докато краищата не се овъглят и карамелизират. Ферментиралата извара е тайната за характерния червен цвят и дълбок вкус.",
      steps: [
        "В купа смесете намачканата ферментирала соева извара, 2 с.л. мед, малтозата, хойсин соса, соевия сос, виното шаосин, сместа от пет подправки и чесъна, за да направите марината - ферментиралата соева извара е това, което придава на автентичното ча сиу характерния му червен цвят и дълбок сладко-солен вкус.",
        "Сложете свинските ивици в марината, обръщайки ги, за да се покрият напълно; не отрязвайте мазнината, тъй като се стопява и полива месото, докато се пече. Покрийте и мариновайте в хладилник поне 4 часа, най-добре цяла нощ.",
        "Загрейте фурната на 190°C и сложете решетка върху тава, застлана с фолио, с вода на дъното, за да улавя капките и да предотврати задимяване.",
        "Наредете свинските ивици върху решетката и печете 25 минути, после обърнете и печете още 15 минути.",
        "Намажете останалия мед върху свинското и печете последните 5-10 минути, докато краищата се овъглят и карамелизират, а вътрешната температура достигне 63°C.",
        "Оставете свинското да почине 10 минути преди нарязване - това позволява на соковете да се преразпределят, за да остане месото крехко, вместо да изсъхне.",
        "Нарежете и сервирайте върху ориз на пара, или добавете към пържен ориз или юфка.",
      ],
      ingredients: [
        "1.1кг свинско рамо, нарязано на дълги ивици с дебелина 5-7 см",
        "2 с.л. ферментирала червена соева извара (нам ю), намачкана",
        "3 с.л. мед, разделен",
        "2 с.л. малтоза (или още мед)",
        "3 с.л. хойсин сос",
        "2 с.л. соев сос",
        "1 с.л. вино шаосин",
        "1 ч.л. смес от пет подправки",
        "3 скилидки чесън, ситно нарязани",
        "Червена хранителна боя (по желание, за цвят)",
      ],
    },
  },
  {
    slug: "congee",
    title: "Congee",
    description:
      "China's silky rice porridge - unlike Western rice soups that keep the grains intact, congee relies on long, gentle simmering to break the rice down completely into a smooth, creamy porridge, not a soup with whole grains floating in it.",
    imageEmoji: "🥣",
    cookTimeMinutes: 65,
    servings: 4,
    caloriesPerServing: 220,
    proteinG: 6,
    carbsG: 44,
    fatG: 3,
    ingredients: [
      { text: "1 cup white rice (jasmine or long-grain)", ingredient: "white rice", quantity: 1 },
      { text: "8 cups water or chicken broth", ingredient: "chicken broth", quantity: 8 },
      { text: "1-inch piece ginger, sliced", ingredient: "ginger", quantity: 1 },
      { text: "2 cloves garlic, smashed", ingredient: "garlic", quantity: 2 },
      { text: "2 scallions, whites and greens separated, sliced", ingredient: "scallion", quantity: 2 },
      { text: "1 tbsp soy sauce", ingredient: "soy sauce", quantity: 1 },
      { text: "1.5 tsp salt", ingredient: "salt", quantity: 1.5 },
      { text: "1 tsp sesame oil", ingredient: "sesame oil", quantity: 1 },
      { text: "1/2 tsp white pepper", ingredient: "white pepper", quantity: 0.5 },
      { text: "Shredded cooked chicken, thousand-year egg, or fried shallots, for topping (optional)", ingredient: "shredded chicken", quantity: null },
    ],
    steps: [
      "Rinse the rice in a fine-mesh strainer under cold water until the water runs mostly clear.",
      "Place the rice in a large pot with the water or broth, ginger, garlic, and scallion whites, and bring to a boil over medium-high heat.",
      "Once boiling, reduce the heat to maintain a brisk simmer, uncovered, and cook for 45-60 minutes, stirring occasionally and scraping the bottom of the pot to prevent sticking - unlike Western rice soups that keep the grains intact, congee relies on long, gentle cooking to break the rice down completely into a smooth, creamy porridge.",
      "If the congee gets too thick, add more water or broth as needed to keep it loose enough to stir easily.",
      "Once the rice has broken down into a soft, velvety porridge, remove the ginger and garlic pieces.",
      "Stir in the soy sauce, salt, sesame oil, and white pepper, tasting and adjusting as needed.",
      "Ladle into bowls and top with scallion greens and your choice of shredded chicken, thousand-year egg, or fried shallots before serving hot.",
    ],
    tags: ["breakfast", "lunch"],
    bg: {
      title: "Конджи",
      description: "Китайска оризова каша - за разлика от западните оризови супи, зърната тук напълно се разпадат чрез дълго, леко готвене, докато не се получи гладка, кремообразна каша, а не супа с цели зърна.",
      steps: [
        "Изплакнете ориза в цедка с фини дупки под студена вода, докато водата стане почти бистра.",
        "Сложете ориза в голяма тенджера с водата или бульона, джинджифила, чесъна и бялото на пролетния лук и кипнете на средно-силен огън.",
        "След като заври, намалете огъня, за да поддържате бързо къкрене без капак, и гответе 45-60 минути, разбърквайки от време на време и изстъргвайки дъното на тенджерата, за да не залепва - за разлика от западните оризови супи, при които зърната остават цели, конджи разчита на дълго, леко готвене, за да се разпадне оризът напълно в гладка, кремообразна каша.",
        "Ако конджито стане твърде гъсто, добавете още вода или бульон при нужда, за да остане достатъчно рехаво за лесно разбъркване.",
        "След като оризът се разпадне в мека, кадифена каша, извадете парчетата джинджифил и чесън.",
        "Разбъркайте соевия сос, солта, сусамовото олио и белия пипер, опитвайки и коригирайки при нужда.",
        "Сипете в купи и украсете със зеленото на пролетния лук и накъсано пиле, стогодишно яйце или пържен лук шалот по избор, преди да сервирате горещо.",
      ],
      ingredients: [
        "1 чаша бял ориз (жасминов или дълго зърнест)",
        "8 чаши вода или пилешки бульон",
        "Парче джинджифил 2.5 см, нарязано на резени",
        "2 скилидки чесън, натрошени",
        "2 стръка пролетен лук, бялото и зеленото разделени, нарязани",
        "1 с.л. соев сос",
        "1.5 ч.л. сол",
        "1 ч.л. сусамово олио",
        "1/2 ч.л. бял пипер",
        "Накъсано варено пиле, стогодишно яйце или пържен лук шалот, за гарниране (по желание)",
      ],
    },
  },
];

async function main() {
  for (const recipe of newRecipes) {
    const created = await prisma.recipe.create({
      data: {
        slug: recipe.slug,
        title: recipe.title,
        description: recipe.description,
        imageEmoji: recipe.imageEmoji,
        cookTimeMinutes: recipe.cookTimeMinutes,
        servings: recipe.servings,
        steps: JSON.stringify(recipe.steps),
        tags: JSON.stringify(recipe.tags),
        caloriesPerServing: recipe.caloriesPerServing,
        proteinG: recipe.proteinG,
        carbsG: recipe.carbsG,
        fatG: recipe.fatG,
      },
    });

    for (let i = 0; i < recipe.ingredients.length; i++) {
      const ing = recipe.ingredients[i];
      const ingredient = await prisma.ingredient.upsert({
        where: { name: ing.ingredient },
        update: {},
        create: { name: ing.ingredient },
      });
      await prisma.recipeIngredient.create({
        data: {
          recipeId: created.id,
          ingredientId: ingredient.id,
          displayText: ing.text,
          quantity: ing.quantity,
          position: i,
        },
      });
    }

    console.log(`Created ${recipe.slug}`);
  }
  console.log(`Created ${newRecipes.length} recipes total.`);

  await runTranslations(
    newRecipes.map((r) => ({
      slug: r.slug,
      title: r.bg.title,
      description: r.bg.description,
      steps: r.bg.steps,
      ingredients: r.bg.ingredients,
    })),
  );
}

main();
