import { prisma, runTranslations } from "./translate-lib.mjs";

// 10 new international recipes, each web-researched for authentic technique
// before writing, per standing instructions. Chicken Vindaloo substitutes
// dried red chili + paprika for traditional Kashmiri chilies (rarely
// available outside India) - substitution stated explicitly in its own
// description.
const newRecipes = [
  {
    slug: "beef-wellington",
    title: "Beef Wellington",
    description:
      "A beef tenderloin coated in mustard, wrapped in a savory mushroom duxelles and a layer of prosciutto, then encased in puff pastry and baked until the pastry is golden and the beef is rosy pink inside - searing the beef first and cooking the duxelles until completely dry are what keep the pastry from turning soggy underneath.",
    imageEmoji: "🥩",
    cookTimeMinutes: 90,
    servings: 6,
    ingredients: [
      { text: "2 lb beef tenderloin, trimmed", ingredient: "beef tenderloin", quantity: 2 },
      { text: "2 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 2 },
      { text: "2 tbsp dijon mustard", ingredient: "dijon mustard", quantity: 2 },
      { text: "1 lb mushrooms, finely chopped", ingredient: "mushroom", quantity: 1 },
      { text: "2 shallots, finely chopped", ingredient: "shallot", quantity: 2 },
      { text: "2 cloves garlic, minced", ingredient: "garlic", quantity: 2 },
      { text: "1 tbsp thyme leaves", ingredient: "thyme", quantity: 1 },
      { text: "8 slices prosciutto", ingredient: "prosciutto", quantity: 8 },
      { text: "1 lb puff pastry", ingredient: "puff pastry", quantity: 1 },
      { text: "1 egg, beaten (for egg wash)", ingredient: "eggs", quantity: 1 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "Pepper to taste", ingredient: "pepper", quantity: null },
    ],
    steps: [
      "Season the beef tenderloin generously with salt and pepper, then sear in the vegetable oil in a very hot pan for 1-2 minutes per side until browned all over but still raw inside. Let cool, then brush all over with the dijon mustard.",
      "Pulse the mushrooms, shallots, garlic, and thyme in a food processor until finely minced. Cook this mixture in the same pan over medium heat, stirring often, for 10-15 minutes until all the liquid has evaporated and it forms a dry, dense paste (the duxelles) - any remaining moisture here is what makes the pastry soggy later, so cook it until it's genuinely dry, not just soft.",
      "Lay a large sheet of plastic wrap on the counter and arrange the prosciutto slices in a slightly overlapping layer. Spread the cooled duxelles evenly over the prosciutto.",
      "Place the mustard-coated beef in the center and use the plastic wrap to roll the prosciutto and duxelles tightly around it, twisting the ends to seal. Chill in the refrigerator for 30 minutes to set the shape.",
      "Preheat the oven to 425°F. Roll out the puff pastry on a floured surface, unwrap the beef, and place it in the center. Wrap the pastry around the beef, sealing the seams with a little egg wash, and trim any excess.",
      "Place seam-side down on a baking sheet, brush all over with the remaining egg wash, and score a light pattern on top with a knife.",
      "Bake for 35-40 minutes, until the pastry is deep golden brown and a meat thermometer inserted into the center reads 125°F for medium-rare.",
      "Rest for 10 minutes before slicing into thick rounds and serving.",
    ],
    tags: ["dinner"],
    bg: {
      title: "Говеждо Уелингтън",
      description:
        "Телешко филе, намазано с горчица, увито в пикантен дюксел от гъби и слой прошуто, после облечено в бутер тесто и изпечено до златисто, докато месото остане розово отвътре - запържването на месото първо и готвенето на дюкселя до пълна сухота са това, което пази тестото от разкисване отдолу.",
      steps: [
        "Подправете щедро телешкото филе със сол и пипер, после запържете в олиото в много горещ тиган за 1-2 минути от всяка страна, докато се зачерви отвсякъде, но остане сурово отвътре. Оставете да изстине, после намажете отвсякъде с дижонската горчица.",
        "Пуснете гъбите, шалота, чесъна и мащерката в кухненски робот, докато се получи ситно смляна смес. Гответе тази смес в същия тиган на среден огън, като бъркате често, 10-15 минути, докато цялата течност се изпари и се получи суха, плътна паста (дюкселят) - останалата влага тук е това, което прави тестото разкиснато по-късно, затова гответе го, докато стане наистина сухо, не само меко.",
        "Разстелете голям лист фолио на плота и наредете резените прошуто в леко застъпващ се слой. Разпределете охладения дюксел равномерно върху прошутото.",
        "Поставете намазаното с горчица говеждо в центъра и използвайте фолиото, за да навиете прошутото и дюкселя плътно около него, като усуквате краищата, за да запечатате. Охладете в хладилника 30 минути, за да се стегне формата.",
        "Загрейте фурната на 220°C. Разточете бутер тестото върху набрашнена повърхност, разопаковайте говеждото и го поставете в центъра. Увийте тестото около говеждото, запечатвайки шевовете с малко разбито яйце, и отрежете излишъка.",
        "Поставете с шева надолу върху тава за печене, намажете отвсякъде с останалото разбито яйце и надраскайте лек десен отгоре с нож.",
        "Печете 35-40 минути, докато тестото стане дълбоко златисто кафяво, а термометър за месо, забит в центъра, покаже 52°C за средно препечено.",
        "Оставете да почине 10 минути преди да нарежете на дебели резени и сервирате.",
      ],
      ingredients: [
        "900 г телешко филе, почистено",
        "2 с.л. олио",
        "2 с.л. дижонска горчица",
        "450 г гъби, ситно нарязани",
        "2 шалота, ситно нарязани",
        "2 скилидки чесън, ситно нарязани",
        "1 с.л. листа мащерка",
        "8 резена прошуто",
        "450 г бутер тесто",
        "1 яйце, разбито (за намазване)",
        "Сол на вкус",
        "Черен пипер на вкус",
      ],
    },
  },
  {
    slug: "coq-au-vin",
    title: "Coq au Vin",
    description:
      "Chicken braised low and slow in red wine with bacon lardons, pearl onions, and mushrooms until the sauce turns deep and glossy - browning the bacon and chicken well before the wine goes in, and finishing the sauce with a butter-flour paste rather than cornstarch, are what give real coq au vin its rich, French-bistro depth.",
    imageEmoji: "🍷",
    cookTimeMinutes: 120,
    servings: 4,
    ingredients: [
      { text: "6 oz bacon, cut into lardons", ingredient: "bacon", quantity: 6 },
      { text: "3 lb chicken thighs and drumsticks", ingredient: "chicken thighs", quantity: 3 },
      { text: "1 cup pearl onions, peeled", ingredient: "pearl onions", quantity: 1 },
      { text: "8 oz mushrooms, quartered", ingredient: "mushroom", quantity: 8 },
      { text: "2 cloves garlic, minced", ingredient: "garlic", quantity: 2 },
      { text: "1/4 cup brandy", ingredient: "brandy", quantity: 0.25 },
      { text: "3 cups red wine", ingredient: "red wine", quantity: 3 },
      { text: "1 cup chicken broth", ingredient: "chicken broth", quantity: 1 },
      { text: "1 bay leaf", ingredient: "bay leaf", quantity: 1 },
      { text: "1 tsp thyme", ingredient: "thyme", quantity: 1 },
      { text: "2 tbsp butter", ingredient: "butter", quantity: 2 },
      { text: "2 tbsp flour", ingredient: "flour", quantity: 2 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "Pepper to taste", ingredient: "pepper", quantity: null },
    ],
    steps: [
      "Cook the bacon lardons in a large Dutch oven over medium heat until crisp and the fat has rendered, then remove with a slotted spoon and set aside, leaving the fat in the pot.",
      "Pat the chicken pieces completely dry, season with salt and pepper, and brown them in the bacon fat in batches until deeply golden on all sides - dry chicken and a hot pan are what actually give a good sear, since wet chicken just steams. Remove and set aside.",
      "Add the pearl onions and mushrooms to the pot and sauté until golden, then stir in the garlic.",
      "Return the chicken and bacon to the pot, pour in the brandy, and carefully ignite it with a long lighter to burn off the alcohol - this flambé step is what concentrates the brandy's flavor without leaving it raw and harsh.",
      "Once the flames die down, pour in the red wine and chicken broth, add the bay leaf and thyme, and bring to a simmer. Cover and cook on low heat for 1 to 1.5 hours, until the chicken is falling-off-the-bone tender.",
      "Mash the butter and flour together into a smooth paste (a beurre manié), then whisk it into the simmering sauce a little at a time until the sauce thickens and turns glossy - this classic French thickening method, not cornstarch, is what gives the sauce its silky body without dulling the wine flavor.",
      "Discard the bay leaf, season to taste, and serve hot with crusty bread or over egg noodles.",
    ],
    tags: ["dinner", "french"],
    bg: {
      title: "Кок о вен",
      description:
        "Пиле, задушено бавно в червено вино с бекон, малки лукчета и гъби, докато сосът стане дълбок и лъскав - доброто запържване на бекона и пилето, преди да се добави виното, и довършването на соса с паста от масло и брашно, вместо царевично нишесте, е това, което дава на истинското Кок о Вен неговата богата, френска бистро дълбочина.",
      steps: [
        "Гответе бекона на тиган в голяма тенджера на среден огън, докато стане хрупкав и мазнината се разтопи, после извадете с решетъчна лъжица и оставете настрана, като запазите мазнината в тенджерата.",
        "Подсушете напълно парчетата пиле, подправете със сол и пипер, и запържете в бекановата мазнина на порции до дълбоко златисто от всички страни - сухото пиле и горещият тиган са това, което наистина дава добро зачервяване, тъй като мокрото пиле просто се задушава на пара. Извадете и оставете настрана.",
        "Добавете малките лукчета и гъбите в тенджерата и запържете до златисто, после разбъркайте чесъна.",
        "Върнете пилето и бекона в тенджерата, залейте с бренди и внимателно го запалете с дълга запалка, за да изгори алкохолът - тази стъпка на пламване е това, което концентрира вкуса на брендито, без да остане суров и остър.",
        "След като пламъците утихнат, залейте с червеното вино и пилешкия бульон, добавете дафиновия лист и мащерката, и оставете да заври леко. Покрийте и гответе на слаб огън 1 до 1.5 часа, докато пилето стане толкова крехко, че се отделя от костта.",
        "Разбъркайте маслото и брашното заедно в гладка паста (бьор маниé), после я разбъркайте в къкрещия сос малко по малко, докато сосът се сгъсти и стане лъскав - този класически френски метод за сгъстяване, а не царевично нишесте, е това, което дава на соса неговото копринено тяло, без да заглушава вкуса на виното.",
        "Изхвърлете дафиновия лист, подправете на вкус, и сервирайте горещо с хрупкав хляб или върху яйчна юфка.",
      ],
      ingredients: [
        "170 г бекон, нарязан на люспи",
        "1.3 кг пилешки бутчета и кълки",
        "1 чаша малки лукчета, обелени",
        "225 г гъби, нарязани на четвъртинки",
        "2 скилидки чесън, ситно нарязани",
        "1/4 чаша бренди",
        "3 чаши червено вино",
        "1 чаша пилешки бульон",
        "1 дафинов лист",
        "1 ч.л. мащерка",
        "2 с.л. масло",
        "2 с.л. брашно",
        "Сол на вкус",
        "Черен пипер на вкус",
      ],
    },
  },
  {
    slug: "ratatouille",
    title: "Ratatouille",
    description:
      "The traditional rustic Provençal vegetable stew - eggplant, zucchini, bell peppers, onion, and tomato, each sautéed separately before being combined and simmered together - cooking each vegetable on its own first, rather than dumping everything into one pot at once, is what keeps every vegetable holding its own texture instead of collapsing into a single mush.",
    imageEmoji: "🍆",
    cookTimeMinutes: 60,
    servings: 6,
    ingredients: [
      { text: "1 large eggplant, cut into cubes", ingredient: "eggplant", quantity: 1 },
      { text: "2 zucchini, cut into cubes", ingredient: "zucchini", quantity: 2 },
      { text: "2 bell peppers, cut into cubes", ingredient: "bell peppers", quantity: 2 },
      { text: "1 onion, sliced", ingredient: "onion", quantity: 1 },
      { text: "4 cloves garlic, minced", ingredient: "garlic", quantity: 4 },
      { text: "4 tomatoes, diced", ingredient: "tomato", quantity: 4 },
      { text: "1/4 cup olive oil", ingredient: "olive oil", quantity: 0.25 },
      { text: "1 tsp herbes de Provence", ingredient: "herbes de Provence", quantity: 1 },
      { text: "1 bay leaf", ingredient: "bay leaf", quantity: 1 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "Pepper to taste", ingredient: "pepper", quantity: null },
    ],
    steps: [
      "Heat a few tablespoons of olive oil in a large pan and sauté the eggplant on its own until golden and softened, then remove and set aside.",
      "In the same pan, sauté the zucchini on its own until lightly golden, then remove and set aside - cooking each vegetable separately like this, rather than all at once, is what keeps their individual textures intact instead of everything turning to mush.",
      "Sauté the bell peppers on their own until softened, then remove and set aside.",
      "Add a little more oil and sauté the onion until translucent, then add the garlic and cook for 1 minute more.",
      "Add the diced tomatoes, herbes de Provence, and bay leaf to the pan with the onion and garlic, and simmer for 10 minutes until the tomatoes break down into a sauce.",
      "Return all the sautéed vegetables to the pan, season with salt and pepper, and simmer gently, uncovered, for 15-20 minutes, stirring occasionally, until everything is tender but the vegetables still hold their shape.",
      "Discard the bay leaf and serve warm or at room temperature, as a side dish or on its own with crusty bread.",
    ],
    tags: ["dinner", "vegetarian", "vegan"],
    bg: {
      title: "Ратату",
      description:
        "Традиционната груба провансалска зеленчукова яхния - патладжан, тиквички, чушки, лук и домат, всеки запържен отделно, преди да се съберат и задушат заедно - готвенето на всеки зеленчук поотделно първо, вместо да се хвърли всичко в един тиган наведнъж, е това, което пази всеки зеленчук да запази собствената си текстура, вместо да се превърне в обща каша.",
      steps: [
        "Загрейте няколко супени лъжици зехтин в голям тиган и запържете патладжана самостоятелно, докато стане златист и омекне, после извадете и оставете настрана.",
        "В същия тиган запържете тиквичките самостоятелно, докато леко позлатеят, после извадете и оставете настрана - готвенето на всеки зеленчук поотделно по този начин, вместо всички наведнъж, е това, което пази отделните им текстури непокътнати, вместо всичко да се превърне в каша.",
        "Запържете чушките самостоятелно, докато омекнат, после извадете и оставете настрана.",
        "Добавете малко повече олио и запържете лука, докато стане прозрачен, после добавете чесъна и гответе още 1 минута.",
        "Добавете нарязаните домати, провансалските билки и дафиновия лист в тигана с лука и чесъна, и гответе на слаб огън 10 минути, докато доматите се разпаднат в сос.",
        "Върнете всички запържени зеленчуци в тигана, подправете със сол и пипер, и гответе леко, без капак, 15-20 минути, като разбърквате от време на време, докато всичко омекне, но зеленчуците все още запазват формата си.",
        "Изхвърлете дафиновия лист и сервирайте топло или на стайна температура, като гарнитура или самостоятелно с хрупкав хляб.",
      ],
      ingredients: [
        "1 голям патладжан, нарязан на кубчета",
        "2 тиквички, нарязани на кубчета",
        "2 чушки, нарязани на кубчета",
        "1 лук, нарязан",
        "4 скилидки чесън, ситно нарязани",
        "4 домата, нарязани на кубчета",
        "1/4 чаша зехтин",
        "1 ч.л. провансалски билки",
        "1 дафинов лист",
        "Сол на вкус",
        "Черен пипер на вкус",
      ],
    },
  },
  {
    slug: "peking-duck",
    title: "Peking Duck",
    description:
      "Whole duck air-dried uncovered in the refrigerator for a full day before roasting, its skin brushed first with a maltose-and-water glaze - the long, uncovered air-drying is what pulls moisture out of the skin so it turns paper-thin and shatteringly crisp in the oven instead of soft and rubbery, and maltose (not honey) is what gives it the deep mahogany color. Sliced skin and meat are served with mandarin pancakes, hoisin sauce, and scallion, in the classic Beijing style.",
    imageEmoji: "🦆",
    cookTimeMinutes: 180,
    servings: 4,
    ingredients: [
      { text: "1 whole duck (4-5 lb)", ingredient: "duck", quantity: 1 },
      { text: "3 tbsp maltose", ingredient: "maltose", quantity: 3 },
      { text: "1/4 cup water (for the glaze)", ingredient: "water", quantity: 0.25 },
      { text: "1 tbsp rice vinegar", ingredient: "rice vinegar", quantity: 1 },
      { text: "1 tsp salt", ingredient: "salt", quantity: 1 },
      { text: "12 mandarin pancakes", ingredient: "mandarin pancakes", quantity: 12 },
      { text: "1/2 cup hoisin sauce", ingredient: "hoisin sauce", quantity: 0.5 },
      { text: "1 cucumber, cut into thin strips", ingredient: "cucumber", quantity: 1 },
      { text: "4 scallions, cut into thin strips", ingredient: "scallion", quantity: 4 },
    ],
    steps: [
      "Bring a large pot of water to a boil. Holding the duck with tongs, ladle the boiling water evenly over the skin all over the duck for a minute or two, until the skin tightens and turns pale - this blanching step separates the skin from the fat layer beneath, which is what lets it puff up and crisp in the oven.",
      "Pat the duck completely dry, then rub the salt inside the cavity.",
      "Whisk together the maltose, water, and rice vinegar until smooth, then brush this glaze evenly over the entire skin of the duck. Hang or rest the duck uncovered on a rack in the refrigerator for 24 hours - this long, uncovered air-drying is what dries out the skin so it crisps properly instead of steaming soft in the oven.",
      "Preheat the oven to 375°F. Place the duck breast-side up on a rack set over a roasting pan and roast for 45 minutes, then flip and roast breast-side down for another 20 minutes, then flip back and roast breast-side up for a final 15-20 minutes, until the skin is a deep mahogany and glass-crisp.",
      "Let the duck rest for 10 minutes, then carve the skin and meat into thin slices.",
      "Serve with warmed mandarin pancakes, hoisin sauce, cucumber, and scallion - each diner spreads hoisin on a pancake, then adds duck, cucumber, and scallion before rolling it up.",
    ],
    tags: ["dinner", "asian"],
    bg: {
      title: "Пекинска патица",
      description:
        "Цяла патица, суша непокрита в хладилника цял ден преди печене, кожата ѝ намазана първо с глазура от малтоза и вода - дългото, непокрито сушене е това, което изтегля влагата от кожата, за да стане тя тънка като хартия и хрупкава като стъкло във фурната, вместо мека и гумена, а малтозата (не медът) е това, което ѝ дава дълбокия махагонов цвят. Нарязаните кожа и месо се сервират с мандаринови палачинки, хойсин сос и пресен лук, по класическия пекински начин.",
      steps: [
        "Оставете голяма тенджера с вода да заври. Държейки патицата с щипки, залейте кожата ѝ равномерно с врящата вода навсякъде за минута-две, докато кожата се стегне и побледнее - тази стъпка на попарване отделя кожата от мастния слой отдолу, което е това, което ѝ позволява да се издуе и стегне във фурната.",
        "Подсушете патицата напълно, после натрийте солта вътре в кухината.",
        "Разбийте заедно малтозата, водата и оризовия оцет до гладкост, после намажете тази глазура равномерно върху цялата кожа на патицата. Окачете или оставете патицата непокрита на решетка в хладилника за 24 часа - това дълго, непокрито сушене е това, което изсушава кожата, за да стане хрупкава правилно, вместо да се задуши мека във фурната.",
        "Загрейте фурната на 190°C. Поставете патицата с гърдите нагоре на решетка над тава за печене и печете 45 минути, после обърнете и печете с гърдите надолу още 20 минути, после обърнете отново с гърдите нагоре за последните 15-20 минути, докато кожата стане дълбоко махагонова и хрупкава като стъкло.",
        "Оставете патицата да почине 10 минути, после нарежете кожата и месото на тънки резени.",
        "Сервирайте с претоплени мандаринови палачинки, хойсин сос, краставица и пресен лук - всеки сътрапезник намазва палачинка с хойсин, после добавя патица, краставица и лук, преди да я навие.",
      ],
      ingredients: [
        "1 цяла патица (1.8-2.3 кг)",
        "3 с.л. малтоза",
        "1/4 чаша вода (за глазурата)",
        "1 с.л. оризов оцет",
        "1 ч.л. сол",
        "12 мандаринови палачинки",
        "1/2 чаша хойсин сос",
        "1 краставица, нарязана на тънки ивици",
        "4 стръка пресен лук, нарязани на тънки ивици",
      ],
    },
  },
  {
    slug: "xiao-long-bao",
    title: "Xiao Long Bao",
    description:
      "Shanghai soup dumplings whose 'soup' is actually a savory pork gelatin, solidified from a pork-skin stock and chilled until firm, then diced and folded into the filling so it melts back into broth as the dumplings steam - folding in solid gelatin instead of trying to spoon in liquid broth is the real trick that keeps the soup sealed inside during pleating.",
    imageEmoji: "🥟",
    cookTimeMinutes: 150,
    servings: 6,
    ingredients: [
      { text: "1 lb pork skin", ingredient: "pork skin", quantity: 1 },
      { text: "4 cups water (for the stock)", ingredient: "water", quantity: 4 },
      { text: "3 slices ginger", ingredient: "ginger", quantity: 3 },
      { text: "2 scallions", ingredient: "scallion", quantity: 2 },
      { text: "1 lb ground pork", ingredient: "ground pork", quantity: 1 },
      { text: "2 tbsp soy sauce", ingredient: "soy sauce", quantity: 2 },
      { text: "1 tbsp shaoxing wine", ingredient: "shaoxing wine", quantity: 1 },
      { text: "1 tsp sesame oil", ingredient: "sesame oil", quantity: 1 },
      { text: "1 tsp sugar", ingredient: "sugar", quantity: 1 },
      { text: "1 tsp minced ginger (for the filling)", ingredient: "ginger", quantity: 1 },
      { text: "1 tsp minced scallion (for the filling)", ingredient: "scallion", quantity: 1 },
      { text: "30 dumpling wrappers", ingredient: "dumpling wrappers", quantity: 30 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
    ],
    steps: [
      "Blanch the pork skin in boiling water for 5 minutes, then scrape off any remaining fat and hair and rinse well.",
      "Simmer the cleaned pork skin with the water, ginger slices, and scallions for 2-3 hours, until the liquid has reduced by about half and turned slightly syrupy - this long simmer is what breaks the skin's collagen down into natural gelatin.",
      "Strain the stock, discarding the solids, season lightly with salt, then pour into a shallow dish and refrigerate for at least 3 hours, until firmly set into a jelly.",
      "Once set, dice the pork jelly into small cubes. Mix the ground pork with the soy sauce, shaoxing wine, sesame oil, sugar, minced ginger, and minced scallion until well combined, then fold in the diced pork jelly - folding in solid, chilled jelly rather than trying to add liquid broth is what keeps the soup sealed inside the dumpling until it steams.",
      "Place a spoonful of filling in the center of each dumpling wrapper. Pleat the edges around the filling, working in one direction and overlapping each pleat slightly, aiming for 12-18 pleats, then twist and pinch the top to seal completely.",
      "Line a steamer basket with parchment paper or cabbage leaves, arrange the dumplings with space between them, and steam over boiling water for 8-10 minutes, until the wrappers are translucent.",
      "Serve immediately, very carefully - bite a small opening in the wrapper first to let the hot soup cool slightly, then eat with black vinegar and julienned ginger.",
    ],
    tags: ["dinner", "asian", "snack"],
    bg: {
      title: "Сяо лун бао",
      description:
        "Шанхайски кнедли със супа, чиято 'супа' всъщност е солен свински желатин, втвърден от бульон от свинска кожа и охладен до стегнатост, после нарязан на кубчета и сгънат във пълнежа, за да се разтопи обратно в бульон, докато кнедлите се готвят на пара - сгъването на твърд желатин, вместо да се опитвате да сложите течен бульон с лъжица, е истинският трик, който пази супата запечатана вътре по време на набирането.",
      steps: [
        "Попарете свинската кожа във вряща вода за 5 минути, после изстържете остатъчната мазнина и косми и изплакнете добре.",
        "Гответе на слаб огън почистената свинска кожа с водата, резените джинджифил и пресния лук за 2-3 часа, докато течността намалее наполовина и стане леко сиропена - това дълго варене е това, което разгражда колагена от кожата в естествен желатин.",
        "Прецедете бульона, изхвърлете твърдите частици, подправете леко със сол, после изсипете в плитко блюдо и охладете в хладилника поне 3 часа, докато се стегне добре в желе.",
        "След като се стегне, нарежете свинското желе на малки кубчета. Смесете свинската кайма със соевия сос, шаосинското вино, сусамовото масло, захарта, ситно нарязания джинджифил и ситно нарязания пресен лук, докато се смеси добре, после сгънете нарязаното на кубчета желе - сгъването на твърдо, охладено желе, вместо да се опитвате да добавите течен бульон, е това, което пази супата запечатана вътре в кнедлата, докато се сготви на пара.",
        "Поставете лъжичка пълнеж в центъра на всяка кора за кнедли. Наберете краищата около пълнежа, работейки в една посока и леко застъпвайки всяко набиране, стремейки се към 12-18 набирания, после усукайте и притиснете отгоре, за да запечатате напълно.",
        "Постелете кошница за готвене на пара с хартия за печене или зелеви листа, наредете кнедлите с разстояние помежду им, и гответе на пара над вряща вода 8-10 минути, докато корите станат прозрачни.",
        "Сервирайте веднага, много внимателно - отхапете малък отвор в корите първо, за да оставите горещата супа да поизстине леко, после яжте с черен оцет и нарязан на тънки ивици джинджифил.",
      ],
      ingredients: [
        "450 г свинска кожа",
        "4 чаши вода (за бульона)",
        "3 резена джинджифил",
        "2 стръка пресен лук",
        "450 г свинска кайма",
        "2 с.л. соев сос",
        "1 с.л. шаосинско вино",
        "1 ч.л. сусамово масло",
        "1 ч.л. захар",
        "1 ч.л. ситно нарязан джинджифил (за пълнежа)",
        "1 ч.л. ситно нарязан пресен лук (за пълнежа)",
        "30 кори за кнедли",
        "Сол на вкус",
      ],
    },
  },
  {
    slug: "naan",
    title: "Naan",
    description:
      "Soft, pillowy Indian flatbread leavened with both yeast and yogurt, slapped onto a screaming-hot surface so it puffs and chars in spots within minutes - the yogurt is what gives naan its tender, slightly tangy crumb, and a covered, water-misted hot pan or stone is the closest a home oven gets to a real tandoor's blistering char.",
    imageEmoji: "🫓",
    cookTimeMinutes: 40,
    servings: 6,
    ingredients: [
      { text: "3 cups flour", ingredient: "flour", quantity: 3 },
      { text: "1 tsp yeast", ingredient: "yeast", quantity: 1 },
      { text: "1 tsp sugar", ingredient: "sugar", quantity: 1 },
      { text: "3/4 cup warm water", ingredient: "water", quantity: 0.75 },
      { text: "1/2 cup plain yogurt", ingredient: "yogurt", quantity: 0.5 },
      { text: "2 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 2 },
      { text: "1 tsp salt", ingredient: "salt", quantity: 1 },
      { text: "3 tbsp melted butter, for brushing", ingredient: "butter", quantity: 3 },
      { text: "2 cloves garlic, minced (optional)", ingredient: "garlic", quantity: 2 },
    ],
    steps: [
      "Dissolve the yeast and sugar in the warm water and let sit for 5-10 minutes until foamy.",
      "Mix the flour and salt in a large bowl, then add the yeast mixture, yogurt, and oil. Knead for 8-10 minutes until you have a smooth, slightly tacky dough - the yogurt is what gives real naan its soft, faintly tangy crumb, not just plain water dough.",
      "Cover and let rise in a warm place for 1-1.5 hours, until roughly doubled in size.",
      "Divide the dough into 6 pieces and roll each into a teardrop or oval shape, about 1/4 inch thick.",
      "Heat a cast-iron skillet or griddle over high heat until very hot, almost smoking. Place a naan in the dry pan, cover with a lid, and cook for 1-2 minutes, until large bubbles form and the bottom is spotted with brown char.",
      "Flip and cook the other side uncovered for 1 minute more, until it's also charred in spots and cooked through - the intense, direct heat is what mimics a tandoor's blistering char in a way a moderate oven never can.",
      "Brush immediately with melted butter (mixed with the minced garlic, if using) and keep warm under a towel while you cook the remaining naan. Serve warm.",
    ],
    tags: ["baking", "vegetarian"],
    bg: {
      title: "Наан",
      description:
        "Меко, пухкаво индийско плоско хлебче, втасано и с мая, и с кисело мляко, залепено на пищящо гореща повърхност, за да се издуе и почерни на петна за минути - киселото мляко е това, което дава на наан неговата нежна, леко кисела средина, а покрит, напръскан с вода горещ тиган или камък е най-близкото, до което една домашна фурна може да достигне до истинско запечатване в тандур.",
      steps: [
        "Разтворете маята и захарта в топлата вода и оставете за 5-10 минути, докато се разпени.",
        "Смесете брашното и солта в голяма купа, после добавете маената смес, киселото мляко и олиото. Месете 8-10 минути, докато се получи гладко, леко лепкаво тесто - киселото мляко е това, което дава на истинския наан неговата мека, леко кисела средина, не просто тесто с обикновена вода.",
        "Покрийте и оставете да втаса на топло място 1-1.5 часа, докато приблизително удвои обема си.",
        "Разделете тестото на 6 части и разточете всяка във форма на капка или овал, около 0.5 см дебелина.",
        "Загрейте чугунен тиган или скара на силен огън, докато стане много горещ, почти да пуши. Поставете едно наан в сухия тиган, покрийте с капак и гответе 1-2 минути, докато се образуват големи мехури, а дъното се напъстри с кафяви изгорели петна.",
        "Обърнете и гответе другата страна без капак още 1 минута, докато и тя се напъстри на петна и се сготви напълно - интензивната, директна топлина е това, което имитира хрупкавото запечатване на тандур по начин, който умерена фурна никога не може.",
        "Намажете веднага с разтопено масло (смесено със ситно нарязания чесън, ако използвате), и запазете топло под кърпа, докато сготвите останалите наан. Сервирайте топло.",
      ],
      ingredients: [
        "3 чаши брашно",
        "1 ч.л. мая",
        "1 ч.л. захар",
        "3/4 чаша топла вода",
        "1/2 чаша кисело мляко",
        "2 с.л. олио",
        "1 ч.л. сол",
        "3 с.л. разтопено масло, за намазване",
        "2 скилидки чесън, ситно нарязани (по избор)",
      ],
    },
  },
  {
    slug: "samosa",
    title: "Samosa",
    description:
      "Crisp, flaky pastry triangles filled with spiced potato and peas, folded from semicircles into cones before frying - rubbing oil into the flour until sandy before adding any water is what gives samosa dough its shatteringly flaky layers, and letting the filling cool completely is what keeps the dough from turning soggy as you fold it.",
    imageEmoji: "🧆",
    cookTimeMinutes: 60,
    servings: 6,
    ingredients: [
      { text: "2 cups flour", ingredient: "flour", quantity: 2 },
      { text: "1/4 cup vegetable oil (for the dough)", ingredient: "vegetable oil", quantity: 0.25 },
      { text: "1/2 tsp salt (for the dough)", ingredient: "salt", quantity: 0.5 },
      { text: "1/2 cup water", ingredient: "water", quantity: 0.5 },
      { text: "3 potatoes, boiled and cubed", ingredient: "potato", quantity: 3 },
      { text: "1/2 cup peas", ingredient: "peas", quantity: 0.5 },
      { text: "1 tsp cumin seeds", ingredient: "cumin seeds", quantity: 1 },
      { text: "1 tsp coriander powder", ingredient: "coriander powder", quantity: 1 },
      { text: "1 tsp garam masala", ingredient: "garam masala", quantity: 1 },
      { text: "1 tsp ginger, minced", ingredient: "ginger", quantity: 1 },
      { text: "1 green chili, minced", ingredient: "green chili", quantity: 1 },
      { text: "2 tbsp cilantro, chopped", ingredient: "cilantro", quantity: 2 },
      { text: "1 tbsp lemon juice", ingredient: "lemon juice", quantity: 1 },
      { text: "4 cups vegetable oil, for frying", ingredient: "vegetable oil", quantity: 4 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
    ],
    steps: [
      "Mix the flour and 1/2 tsp salt in a bowl, then rub in the 1/4 cup oil with your fingertips until the mixture looks sandy and holds together when pressed - this oil-rubbing step is what creates the flaky layers in the fried pastry.",
      "Gradually add the water and knead into a firm, smooth dough. Cover and let rest for 20-30 minutes.",
      "Heat a little oil in a pan and add the cumin seeds. Once they sizzle, add the ginger and green chili, then the boiled potatoes, peas, coriander powder, and garam masala. Cook for 5 minutes, mashing the potatoes slightly, then stir in the cilantro, lemon juice, and salt. Let the filling cool completely before using - warm filling makes the dough soggy and hard to seal.",
      "Divide the dough into 6 balls, roll each into a thin oval, and cut in half to make two semicircles.",
      "Take one semicircle, wet the straight edge with water, and fold it into a cone, pressing the seam to seal.",
      "Fill the cone with 2 tablespoons of the cooled potato filling, then wet the top edge and pinch it closed, pressing firmly to seal completely - don't overstuff, or the seam will burst open while frying.",
      "Heat the 4 cups of oil to 325°F and fry the samosas in batches for 8-10 minutes, until light golden, then increase the heat to 375°F and fry for another 2-3 minutes until deep golden and crisp - this two-stage frying is what cooks the pastry through without burning the outside.",
      "Drain on paper towels and serve hot with chutney.",
    ],
    tags: ["snack", "vegetarian"],
    bg: {
      title: "Самоса",
      description:
        "Хрупкави, ронливи триъгълници тесто, пълнени с подправен картоф и грах, сгънати от полукръгове в конуси преди пържене - втриването на олио в брашното до пясъчна текстура, преди да се добави вода, е това, което дава на тестото за самоса неговите хрупкаво ронливи слоеве, а оставянето на пълнежа да изстине напълно е това, което пази тестото от разкисване, докато го сгъвате.",
      steps: [
        "Смесете брашното и 1/2 ч.л. сол в купа, после втрийте 1/4 чаша олио с върховете на пръстите, докато сместа заприлича на пясък и се държи заедно, когато се притисне - тази стъпка на втриване на олиото е това, което създава ронливите слоеве в изпържения тесто.",
        "Постепенно добавяйте водата и омесете в стегнато, гладко тесто. Покрийте и оставете да почине 20-30 минути.",
        "Загрейте малко олио в тиган и добавете кимиона на семена. След като засъскат, добавете джинджифила и лютата чушка, после сварените картофи, граха, смления кориандър и гарам масала. Гответе 5 минути, като леко смачквате картофите, после разбъркайте кориандъра, лимоновия сок и солта. Оставете пълнежа да изстине напълно, преди да го използвате - топлият пълнеж прави тестото разкиснато и трудно за запечатване.",
        "Разделете тестото на 6 топки, разточете всяка в тънък овал, и срежете наполовина, за да направите два полукръга.",
        "Вземете един полукръг, намокрете правия ръб с вода, и го сгънете в конус, притискайки шева, за да запечатате.",
        "Напълнете конуса с 2 супени лъжици от охладения картофен пълнеж, после намокрете горния ръб и го притиснете затворен, притискайки силно, за да запечатате напълно - не препълвайте, иначе шевът ще се пукне при пържене.",
        "Загрейте 4-те чаши олио до 165°C и пържете самосите на порции 8-10 минути, докато станат светло златисти, после увеличете температурата на 190°C и пържете още 2-3 минути, докато станат дълбоко златисти и хрупкави - това двустепенно пържене е това, което сготвя тестото напълно, без да изгори отвън.",
        "Отцедете върху хартиени кърпи и сервирайте горещи с чътни.",
      ],
      ingredients: [
        "2 чаши брашно",
        "1/4 чаша олио (за тестото)",
        "1/2 ч.л. сол (за тестото)",
        "1/2 чаша вода",
        "3 картофа, сварени и нарязани на кубчета",
        "1/2 чаша грах",
        "1 ч.л. кимион на семена",
        "1 ч.л. смлян кориандър",
        "1 ч.л. гарам масала",
        "1 ч.л. джинджифил, ситно нарязан",
        "1 люта чушка, ситно нарязана",
        "2 с.л. кориандър (зелен), нарязан",
        "1 с.л. лимонов сок",
        "4 чаши олио за пържене",
        "Сол на вкус",
      ],
    },
  },
  {
    slug: "chicken-vindaloo",
    title: "Chicken Vindaloo",
    description:
      "A fiery Goan curry built on vinegar, garlic, and dried red chilies - the Portuguese-derived dish that Goans reworked with Indian spices and vinegar in place of the original wine. This version uses dried red chilies and paprika in place of the traditional Kashmiri chilies, which give the sauce its color without adding much heat and can be hard to find outside India; marinating the chicken in the spice paste for at least an hour, not just simmering it in at the end, is what lets the vinegar and spices actually penetrate the meat.",
    imageEmoji: "🌶️",
    cookTimeMinutes: 60,
    servings: 4,
    ingredients: [
      { text: "2 lb chicken thighs, cut into pieces", ingredient: "chicken thighs", quantity: 2 },
      { text: "6 dried red chilies", ingredient: "dried red chili", quantity: 6 },
      { text: "1 tbsp paprika", ingredient: "paprika", quantity: 1 },
      { text: "1 tbsp coriander seeds", ingredient: "coriander seeds", quantity: 1 },
      { text: "1 tsp cumin seeds", ingredient: "cumin seeds", quantity: 1 },
      { text: "1 tsp mustard seeds", ingredient: "mustard seeds", quantity: 1 },
      { text: "1 inch cinnamon stick", ingredient: "cinnamon stick", quantity: 1 },
      { text: "4 cloves", ingredient: "cloves", quantity: 4 },
      { text: "1 tsp black peppercorns", ingredient: "black peppercorns", quantity: 1 },
      { text: "6 cloves garlic", ingredient: "garlic", quantity: 6 },
      { text: "1 inch ginger", ingredient: "ginger", quantity: 1 },
      { text: "1/3 cup malt vinegar", ingredient: "malt vinegar", quantity: 0.33 },
      { text: "1 tsp turmeric", ingredient: "turmeric", quantity: 1 },
      { text: "1 onion, sliced", ingredient: "onion", quantity: 1 },
      { text: "2 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 2 },
      { text: "1 tsp tamarind paste", ingredient: "tamarind paste", quantity: 1 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
    ],
    steps: [
      "Toast the dried red chilies, coriander seeds, cumin seeds, mustard seeds, cinnamon stick, cloves, and peppercorns in a dry pan over medium heat for 2-3 minutes until fragrant. Let cool, then grind to a powder.",
      "Blend the ground spices with the paprika, garlic, ginger, malt vinegar, turmeric, and a splash of water into a smooth, thick paste.",
      "Coat the chicken pieces in the spice paste and marinate for at least 1 hour, ideally overnight in the refrigerator - marinating, not just simmering the paste in at the end, is what lets the vinegar and spices actually penetrate the meat instead of just coating the outside.",
      "Heat the oil in a large pot and sauté the onion until deep golden brown, about 10-12 minutes.",
      "Add the marinated chicken along with all its marinade and cook for 5 minutes, stirring, until the spices are fragrant and slightly darker.",
      "Add the tamarind paste and enough water to just cover the chicken. Bring to a simmer, then cover and cook on low heat for 30-35 minutes, until the chicken is tender and the sauce has thickened to a thick curry consistency.",
      "Season with salt to taste and serve hot with rice.",
    ],
    tags: ["dinner", "asian"],
    bg: {
      title: "Пилешко виндалу",
      description:
        "Огнено гоанско къри, изградено върху оцет, чесън и сушени червени люти чушки - ястие с португалски произход, което гоанците преработили с индийски подправки и оцет вместо оригиналното вино. Тази версия използва сушени червени чушки и червен пипер вместо традиционните кашмирски чушки, които дават цвят на соса, без да добавят много лютивина, и трудно се намират извън Индия; мариноването на пилето в подправената паста поне час, не просто добавянето ѝ накрая при задушаването, е това, което позволява на оцета и подправките наистина да проникнат в месото.",
      steps: [
        "Препечете сушените червени чушки, семената кориандър, кимиона на семена, семената горчица, канелената пръчка, карамфила и черния пипер в сух тиган на среден огън 2-3 минути, докато замиришат. Оставете да изстинат, после смелете на прах.",
        "Разбийте смлените подправки с червения пипер, чесъна, джинджифила, малцовия оцет, куркумата и малко вода в гладка, гъста паста.",
        "Покрийте парчетата пиле с подправената паста и маринирайте поне 1 час, най-добре през нощта в хладилника - мариноването, а не просто добавянето на пастата накрая при задушаването, е това, което позволява на оцета и подправките наистина да проникнат в месото, вместо просто да покрият повърхността.",
        "Загрейте олиото в голяма тенджера и запържете лука до дълбоко златисто кафяво, около 10-12 минути.",
        "Добавете маринованото пиле заедно с цялата марината и гответе 5 минути, разбърквайки, докато подправките замиришат и потъмнеят леко.",
        "Добавете тамариндовата паста и достатъчно вода, за да покрие пилето точно. Оставете да заври леко, после покрийте и гответе на слаб огън 30-35 минути, докато пилето омекне, а сосът се сгъсти до гъста консистенция на къри.",
        "Подправете със сол на вкус и сервирайте горещо с ориз.",
      ],
      ingredients: [
        "900 г пилешки бутчета, нарязани на парчета",
        "6 сушени червени люти чушки",
        "1 с.л. червен пипер",
        "1 с.л. семена кориандър",
        "1 ч.л. кимион на семена",
        "1 ч.л. семена горчица",
        "1 парче (2.5 см) канелена пръчка",
        "4 карамфилчета",
        "1 ч.л. черен пипер на зърна",
        "6 скилидки чесън",
        "1 парче (2.5 см) джинджифил",
        "1/3 чаша малцов оцет",
        "1 ч.л. куркума",
        "1 лук, нарязан",
        "2 с.л. олио",
        "1 ч.л. тамариндова паста",
        "Сол на вкус",
      ],
    },
  },
  {
    slug: "tres-leches-cake",
    title: "Tres Leches Cake",
    description:
      "A light, butter-free sponge cake soaked overnight in a mixture of evaporated milk, condensed milk, and whole milk, then topped with whipped cream - the sponge's airy, egg-based structure (built like an angel food cake rather than a rich butter cake) is exactly what lets it soak up so much of the three-milk mixture without turning to mush.",
    imageEmoji: "🍰",
    cookTimeMinutes: 60,
    servings: 12,
    ingredients: [
      { text: "1 1/2 cups flour", ingredient: "flour", quantity: 1.5 },
      { text: "1 tsp baking powder", ingredient: "baking powder", quantity: 1 },
      { text: "1/4 tsp salt", ingredient: "salt", quantity: 0.25 },
      { text: "5 eggs, separated", ingredient: "eggs", quantity: 5 },
      { text: "1 cup sugar", ingredient: "sugar", quantity: 1 },
      { text: "1/3 cup milk", ingredient: "milk", quantity: 0.33 },
      { text: "1 tsp vanilla extract", ingredient: "vanilla extract", quantity: 1 },
      { text: "1 can (12 oz) evaporated milk", ingredient: "evaporated milk", quantity: 12 },
      { text: "1 can (14 oz) condensed milk", ingredient: "condensed milk", quantity: 14 },
      { text: "1 cup whole milk (for soaking)", ingredient: "milk", quantity: 1 },
      { text: "1 1/2 cups heavy cream", ingredient: "heavy cream", quantity: 1.5 },
      { text: "3 tbsp powdered sugar", ingredient: "powdered sugar", quantity: 3 },
    ],
    steps: [
      "Preheat the oven to 350°F and grease a 9x13-inch baking dish. Whisk together the flour, baking powder, and salt in a bowl.",
      "Beat the egg whites to soft peaks, then gradually add half the sugar, beating until stiff and glossy.",
      "In a separate bowl, beat the egg yolks with the remaining sugar until pale and thick, then mix in the 1/3 cup milk and vanilla.",
      "Fold the flour mixture into the yolk mixture, then gently fold in the beaten egg whites in two batches, being careful not to deflate the batter - this airy, whipped-egg structure, built without any butter or oil, is what lets the finished cake soak up so much liquid later without collapsing.",
      "Pour the batter into the prepared dish and bake for 25-30 minutes, until a toothpick comes out clean. Let cool completely.",
      "Whisk together the evaporated milk, condensed milk, and the 1 cup of whole milk. Poke holes all over the cooled cake with a fork or skewer, then slowly pour the milk mixture evenly over the top, letting it soak in as you go.",
      "Cover and refrigerate for at least 8 hours, ideally overnight - this long soak is what lets the milk mixture penetrate all the way through the cake instead of just sitting on top.",
      "Whip the heavy cream with the powdered sugar to soft peaks and spread over the top of the soaked cake before serving, chilled.",
    ],
    tags: ["dessert", "vegetarian", "baking"],
    bg: {
      title: "Трес лечес",
      description:
        "Лек бисквитен блат без масло, накиснат през нощта в смес от евапорирано мляко, кондензирано мляко и пълномаслено мляко, после покрит с бита сметана - въздушната, изградена на яйца структура на блата (направен като блат за агнешка торта, а не като плътна маслена бисквита) е точно това, което му позволява да попие толкова много от смесата от три млека, без да се превърне в каша.",
      steps: [
        "Загрейте фурната на 175°C и намажете тава за печене 23х33 см. Разбъркайте брашното, бакпулвера и солта в купа.",
        "Разбийте белтъците до меки върхове, после постепенно добавете половината от захарта, разбивайки до стегнатост и лъскавост.",
        "В отделна купа разбийте жълтъците с останалата захар, докато побледнеят и сгъстеят, после разбъркайте 1/3 чаша мляко и ванилията.",
        "Прибавете брашнената смес към жълтъчната смес, после леко прибавете разбитите белтъци на две части, внимавайки да не спаднете тестото - тази въздушна, изградена на разбити яйца структура, направена без никакво масло или олио, е това, което позволява на готовия блат да попие толкова много течност по-късно, без да хлътне.",
        "Изсипете тестото в подготвената тава и печете 25-30 минути, докато клечка за зъби излезе чиста. Оставете да изстине напълно.",
        "Разбъркайте заедно евапорираното мляко, кондензираното мляко и 1-та чаша пълномаслено мляко. Пробийте дупки навсякъде по изстиналия блат с вилица или шиш, после бавно излейте млечната смес равномерно отгоре, оставяйки я да попие, докато напредвате.",
        "Покрийте и охладете в хладилника поне 8 часа, най-добре през нощта - това дълго накисване е това, което позволява на млечната смес да проникне чак до дъното на блата, вместо просто да седи отгоре.",
        "Разбийте течната сметана с пудрата захар до меки върхове и разстелете върху накиснатия блат преди сервиране, охладен.",
      ],
      ingredients: [
        "1 1/2 чаши брашно",
        "1 ч.л. бакпулвер",
        "1/4 ч.л. сол",
        "5 яйца, разделени",
        "1 чаша захар",
        "1/3 чаша мляко",
        "1 ч.л. екстракт от ванилия",
        "1 кутия (340 г) евапорирано мляко",
        "1 кутия (400 г) кондензирано мляко",
        "1 чаша пълномаслено мляко (за накисване)",
        "1 1/2 чаши течна сметана",
        "3 с.л. пудра захар",
      ],
    },
  },
  {
    slug: "poutine",
    title: "Poutine",
    description:
      "Quebec's double-fried potatoes topped with squeaky fresh cheese curds and a light poultry gravy poured on hot enough to just melt the curds without fully dissolving them - double-frying (once low to cook through, once hot to crisp) and using real curds instead of shredded cheese are the two things that separate real poutine from fries with cheese sauce.",
    imageEmoji: "🍟",
    cookTimeMinutes: 45,
    servings: 4,
    ingredients: [
      { text: "4 large russet potatoes, cut into 1/2-inch fries", ingredient: "potato", quantity: 4 },
      { text: "4 cups vegetable oil, for frying", ingredient: "vegetable oil", quantity: 4 },
      { text: "2 tbsp butter", ingredient: "butter", quantity: 2 },
      { text: "2 tbsp flour", ingredient: "flour", quantity: 2 },
      { text: "2 cups chicken broth", ingredient: "chicken broth", quantity: 2 },
      { text: "1 tbsp worcestershire sauce", ingredient: "worcestershire sauce", quantity: 1 },
      { text: "8 oz cheese curds", ingredient: "cheese curds", quantity: 8 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "Pepper to taste", ingredient: "pepper", quantity: null },
    ],
    steps: [
      "Soak the cut potatoes in cold water for 30 minutes to remove excess starch, then drain and pat completely dry.",
      "Heat the oil to 325°F and fry the potatoes in batches for 5 minutes, until softened but pale - this first, lower-temperature fry cooks the inside through without browning the outside.",
      "Remove the potatoes and let them rest for at least 10 minutes while you make the gravy.",
      "Melt the butter in a saucepan, whisk in the flour, and cook for 1-2 minutes to make a light roux. Gradually whisk in the chicken broth and worcestershire sauce, then simmer for 8-10 minutes, until slightly thickened. Season with salt and pepper.",
      "Increase the oil temperature to 375°F and fry the potatoes a second time for 2-3 minutes, until deep golden and crisp - this second, hotter fry is what gives real poutine fries their crunch.",
      "Let the cheese curds sit at room temperature for 20-30 minutes before serving so they're not fridge-cold.",
      "Pile the double-fried potatoes onto a plate, scatter the cheese curds generously over the top, and immediately pour the hot gravy over everything - the gravy's heat should soften and melt the curds just slightly while leaving most of them intact, not fully dissolved. Serve right away.",
    ],
    tags: ["lunch", "dinner", "snack"],
    bg: {
      title: "Путин",
      description:
        "Двойно изпържени картофи от Квебек, покрити със скърцащо прясно извара на бучки и лек сос от птиче месо, изсипан достатъчно горещ, за да разтопи бучките леко, без да ги разтвори напълно - двойното пържене (веднъж на слаба температура, за да се сготви отвътре, веднъж на силна, за да стане хрупкаво) и използването на истински извара на бучки, вместо настъргано сирене, са двете неща, които отличават истинския путин от пържени картофи със сирен сос.",
      steps: [
        "Накиснете нарязаните картофи в студена вода за 30 минути, за да премахнете излишното нишесте, после отцедете и подсушете напълно.",
        "Загрейте олиото до 165°C и пържете картофите на порции 5 минути, докато омекнат, но останат бледи - това първо пържене на по-ниска температура сготвя отвътре, без да зачерви отвън.",
        "Извадете картофите и ги оставете да починат поне 10 минути, докато приготвяте соса.",
        "Разтопете маслото в тенджера, разбъркайте брашното, и гответе 1-2 минути, за да направите лек ру. Постепенно разбъркайте пилешкия бульон и устърширския сос, после гответе на слаб огън 8-10 минути, докато леко се сгъсти. Подправете със сол и пипер.",
        "Увеличете температурата на олиото на 190°C и изпържете картофите втори път за 2-3 минути, докато станат дълбоко златисти и хрупкави - това второ, по-горещо пържене е това, което дава на истинския путин неговата хрупкавост.",
        "Оставете изварата на бучки на стайна температура 20-30 минути преди сервиране, за да не е студена от хладилника.",
        "Натрупайте двойно изпържените картофи в чиния, поръсете щедро с извара на бучки отгоре, и веднага залейте всичко с горещия сос - топлината на соса трябва да омекоти и разтопи бучките само леко, оставяйки повечето от тях цели, не напълно разтворени. Сервирайте веднага.",
      ],
      ingredients: [
        "4 големи картофа, нарязани на пръчки 1.25 см",
        "4 чаши олио за пържене",
        "2 с.л. масло",
        "2 с.л. брашно",
        "2 чаши пилешки бульон",
        "1 с.л. устърширски сос",
        "225 г извара на бучки",
        "Сол на вкус",
        "Черен пипер на вкус",
      ],
    },
  },
];

async function main() {
  for (const recipe of newRecipes) {
    const created = await prisma.recipe.create({
      data: {
        slug: recipe.slug,
        title: recipe.title,
        description: recipe.description,
        imageEmoji: recipe.imageEmoji,
        cookTimeMinutes: recipe.cookTimeMinutes,
        servings: recipe.servings,
        steps: JSON.stringify(recipe.steps),
        tags: JSON.stringify(recipe.tags),
      },
    });

    for (let i = 0; i < recipe.ingredients.length; i++) {
      const { text, ingredient, quantity } = recipe.ingredients[i];
      const ingredientRow = await prisma.ingredient.upsert({
        where: { name: ingredient },
        update: {},
        create: { name: ingredient },
      });
      await prisma.recipeIngredient.create({
        data: {
          recipeId: created.id,
          ingredientId: ingredientRow.id,
          displayText: text,
          quantity,
          position: i,
        },
      });
    }
    console.log(`Created ${recipe.slug}`);
  }
  console.log(`Created ${newRecipes.length} recipes total.`);

  // runTranslations disconnects prisma when done, so it must run last.
  await runTranslations(newRecipes.map((r) => ({ slug: r.slug, ...r.bg })));
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
