import { prisma, runTranslations } from "./translate-lib.mjs";

// 10 recipes from East Asia (China, Japan, Korea, Taiwan), drawn from
// the larger "recipes from the East" research project. Each
// web-researched for authentic technique before writing, per standing
// instructions. Nutrition estimates are set directly here
// (caloriesPerServing/proteinG/carbsG/fatG), per standing instruction
// to never leave new recipes without nutrition.
const newRecipes = [
  {
    slug: "zongzi",
    title: "Zongzi",
    description:
      "Sticky rice dumplings wrapped in bamboo leaves and boiled for hours, filled with savory pork and mung bean or other regional fillings. Wrapping the leaves rough-side out and weighting the dumplings while they boil are what keep them tightly packed.",
    imageEmoji: "🎋",
    cookTimeMinutes: 180,
    servings: 8,
    caloriesPerServing: 340,
    proteinG: 12,
    carbsG: 48,
    fatG: 11,
    ingredients: [
      { text: "20 dried bamboo leaves, soaked and rinsed", ingredient: "bamboo leaves", quantity: 20 },
      { text: "3 cups glutinous rice, soaked 4 hours", ingredient: "glutinous rice", quantity: 3 },
      { text: "1 lb pork belly, cut into chunks", ingredient: "pork belly", quantity: 1 },
      { text: "1 cup dried mung beans, soaked and split", ingredient: "mung beans", quantity: 1 },
      { text: "6 dried shiitake mushrooms, soaked and diced", ingredient: "dried shiitake mushrooms", quantity: 6 },
      { text: "4 tbsp light soy sauce", ingredient: "light soy sauce", quantity: 4 },
      { text: "2 tbsp dark soy sauce", ingredient: "dark soy sauce", quantity: 2 },
      { text: "2 tbsp Shaoxing wine", ingredient: "shaoxing wine", quantity: 2 },
      { text: "1 tbsp five-spice powder", ingredient: "five spice powder", quantity: 1 },
      { text: "2 tsp salt, divided", ingredient: "salt", quantity: 2 },
      { text: "Kitchen twine, for tying", ingredient: "kitchen twine", quantity: null },
    ],
    steps: [
      "Marinate the pork belly chunks in soy sauce, dark soy sauce, Shaoxing wine, five-spice powder, and 1 tsp salt for at least 1 hour.",
      "Drain the soaked rice and toss it with a little soy sauce and oil so the grains are lightly seasoned before wrapping.",
      "Take two bamboo leaves overlapping with the rough, shiny side facing out, and fold into a cone shape near the wide end.",
      "Layer a spoonful of rice, mung beans, mushroom, and a chunk of marinated pork, then top with more rice, pressing down to pack it tightly and remove air pockets.",
      "Fold the leaves over the filling to fully enclose it into a tight pyramid or bundle shape, then wrap tightly with kitchen twine.",
      "Place the tied zongzi in a large pot, weigh them down with a heavy plate so they stay fully submerged, and cover completely with water.",
      "Boil for 2.5 to 3 hours, topping up with hot water as needed to keep them submerged, until the rice is fully tender and translucent.",
      "Let cool slightly before unwrapping - the leaves peel away cleanly once the rice has set.",
    ],
    tags: ["dinner", "lunch"],
    bg: {
      title: "Дзонгзъ",
      description: "Лепкав ориз, увит в бамбукови листа и варен часове наред, пълнен със свинско и боб мунг или други регионални плънки. Увиването на листата с грапавата страна навън и притискането на пакетчетата по време на варене ги пазят плътно стегнати.",
      steps: [
        "Мариновайте парчетата свинска гърда в соевия сос, тъмния соев сос, шаосинско вино, подправка петте аромата и 1 ч.л. сол за поне 1 час.",
        "Отцедете накиснатия ориз и го разбъркайте с малко соев сос и олио, за да се овкуси леко зърната преди увиване.",
        "Вземете два бамбукови листа, застъпени, с грапавата, лъскава страна навън, и ги нагънете във форма на конус близо до широкия край.",
        "Наредете лъжица ориз, боб мунг, гъба и парче маринован свинско, после отгоре още ориз, притискайки плътно, за да премахнете въздушните джобове.",
        "Прегънете листата върху плънката, за да я затворите напълно в стегната пирамидална форма, после увийте плътно с кухненски канап.",
        "Наредете вързаните дзонгзъ в голяма тенджера, притиснете ги с тежка чиния, за да останат напълно потопени, и покрийте изцяло с вода.",
        "Варете 2.5 до 3 часа, доливайки гореща вода при нужда, за да останат потопени, докато оризът стане напълно мек и прозрачен.",
        "Оставете да изстинат леко преди развиване - листата се обелват чисто, след като оризът се е стегнал.",
      ],
      ingredients: [
        "20 сушени бамбукови листа, накиснати и изплакнати",
        "3 чаши лепкав ориз, накиснат 4 часа",
        "450г свинска гърда, нарязана на парчета",
        "1 чаша сушен боб мунг, накиснат и разцепен",
        "6 сушени шийтаке гъби, накиснати и нарязани на кубчета",
        "4 с.л. светъл соев сос",
        "2 с.л. тъмен соев сос",
        "2 с.л. шаосинско вино",
        "1 с.л. подправка петте аромата",
        "2 ч.л. сол, разделена",
        "Кухненски канап, за връзване",
      ],
    },
  },
  {
    slug: "twice-cooked-pork",
    title: "Twice-Cooked Pork",
    description:
      "A classic Sichuan stir-fry where pork belly is first simmered whole, then thinly sliced and stir-fried until the edges curl and crisp, tossed with fermented broad bean paste and leeks. The two-stage cooking is what gives the pork its signature chewy-crisp texture.",
    imageEmoji: "🥓",
    cookTimeMinutes: 50,
    servings: 4,
    caloriesPerServing: 420,
    proteinG: 20,
    carbsG: 10,
    fatG: 32,
    ingredients: [
      { text: "1.5 lb pork belly, in one piece", ingredient: "pork belly", quantity: 1 },
      { text: "2-inch piece ginger, sliced (for boiling)", ingredient: "ginger", quantity: 1 },
      { text: "2 scallions, whole (for boiling)", ingredient: "scallion", quantity: 2 },
      { text: "3 tbsp doubanjiang (fermented broad bean chili paste)", ingredient: "doubanjiang", quantity: 3 },
      { text: "1 tbsp fermented black beans, rinsed", ingredient: "fermented black beans", quantity: 1 },
      { text: "1 tbsp sweet bean sauce (or hoisin)", ingredient: "sweet bean sauce", quantity: 1 },
      { text: "1 leek, sliced diagonally", ingredient: "leek", quantity: 1 },
      { text: "1 green bell pepper, sliced", ingredient: "green bell pepper", quantity: 1 },
      { text: "3 cloves garlic, sliced", ingredient: "garlic", quantity: 3 },
      { text: "1 tbsp Shaoxing wine", ingredient: "shaoxing wine", quantity: 1 },
      { text: "1 tsp sugar", ingredient: "sugar", quantity: 1 },
      { text: "2 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 2 },
    ],
    steps: [
      "Place the whole pork belly in a pot with the ginger slices and scallions, cover with water, and simmer for 25-30 minutes until just cooked through but still firm.",
      "Remove the pork and let it cool completely (chilling it in the fridge for an hour makes it easier to slice thinly).",
      "Slice the cooled pork belly as thinly as possible against the grain.",
      "Heat the oil in a wok over medium heat and stir-fry the pork slices until the fat renders and the edges begin to curl and crisp, about 4-5 minutes.",
      "Push the pork to one side, add the doubanjiang, fermented black beans, and garlic to the empty space, and fry until fragrant and the oil turns red.",
      "Stir everything together, add the sweet bean sauce, Shaoxing wine, and sugar, and toss to coat the pork evenly.",
      "Add the leek and bell pepper and stir-fry over high heat for 2-3 minutes, just until the leek turns bright green and slightly softened but still has bite.",
      "Serve immediately with steamed rice.",
    ],
    tags: ["dinner"],
    bg: {
      title: "Двойно Сготвено Свинско",
      description: "Класическо сичуанско ястие от уок, в което свинска гърда първо се вари цяла, после се нарязва на тънки резени и се запържва, докато краищата се навият и хрупнат, разбъркана с ферментирала бобена паста и праз. Двуетапното готвене придава на свинското характерната дъвчащо-хрупкава текстура.",
      steps: [
        "Сложете цялата свинска гърда в тенджера с резените джинджифил и пролетния лук, покрийте с вода и къкрете 25-30 минути, докато точно се сготви, но остане стегната.",
        "Извадете свинското и оставете да изстине напълно (изстудяването в хладилник за час улеснява тънкото нарязване).",
        "Нарежете изстиналата свинска гърда възможно най-тънко, срещу влакната.",
        "Загрейте олиото в уок на средна температура и запържете резените свинско, докато мазнината се разтопи и краищата започнат да се навиват и хрупват, около 4-5 минути.",
        "Избутайте свинското настрани, добавете доубанджианг, ферментиралия черен боб и чесъна в празното място и запържете, докато замиришат и олиото почервенее.",
        "Разбъркайте всичко заедно, добавете сладкия бобен сос, шаосинското вино и захарта и разбъркайте, за да покриете свинското равномерно.",
        "Добавете праза и чушката и запържете на силен огън 2-3 минути, точно докато празът стане ярко зелен и леко омекне, но остане хрупкав.",
        "Сервирайте веднага с варен ориз.",
      ],
      ingredients: [
        "680г свинска гърда, на цяло парче",
        "Парче джинджифил 5 см, нарязано на резени (за варене)",
        "2 стръка пролетен лук, цели (за варене)",
        "3 с.л. доубанджианг (ферментирала бобена чили паста)",
        "1 с.л. ферментирал черен боб, изплакнат",
        "1 с.л. сладък бобен сос (или хоисин)",
        "1 праз, нарязан диагонално",
        "1 зелена чушка, нарязана",
        "3 скилидки чесън, нарязани",
        "1 с.л. шаосинско вино",
        "1 ч.л. захар",
        "2 с.л. олио",
      ],
    },
  },
  {
    slug: "hong-kong-egg-tart",
    title: "Hong Kong Egg Tart",
    description:
      "A beloved Hong Kong bakery classic - a flaky or shortcrust pastry shell filled with a silky, barely-sweet egg custard, baked just until set. Straining the custard and baking at a gentle temperature are what keep the top smooth instead of bubbled and cratered.",
    imageEmoji: "🥧",
    cookTimeMinutes: 50,
    servings: 12,
    caloriesPerServing: 210,
    proteinG: 4,
    carbsG: 22,
    fatG: 12,
    ingredients: [
      { text: "2 1/4 cups all-purpose flour", ingredient: "all-purpose flour", quantity: 2 },
      { text: "1 cup cold unsalted butter, cubed", ingredient: "unsalted butter", quantity: 1 },
      { text: "1/3 cup powdered sugar", ingredient: "powdered sugar", quantity: 1 },
      { text: "1 egg (for pastry)", ingredient: "egg", quantity: 1 },
      { text: "5 eggs (for custard)", ingredient: "egg", quantity: 5 },
      { text: "3/4 cup sugar", ingredient: "sugar", quantity: 1 },
      { text: "1 cup hot water", ingredient: "water", quantity: 1 },
      { text: "1/2 cup evaporated milk", ingredient: "evaporated milk", quantity: 1 },
      { text: "1 tsp vanilla extract", ingredient: "vanilla extract", quantity: 1 },
    ],
    steps: [
      "Rub the cold butter into the flour and powdered sugar until crumbly, then bind with the egg into a smooth dough; wrap and chill for 30 minutes.",
      "Roll out the dough and press it into tart molds, trimming the edges; chill the shells while making the custard.",
      "Dissolve the sugar in the hot water and let cool to room temperature.",
      "Whisk the eggs gently (avoiding too much air, which causes bubbles) and combine with the sugar water, evaporated milk, and vanilla.",
      "Strain the custard through a fine sieve at least once, ideally twice, to remove any egg strands and air bubbles - this is essential for a smooth, glassy top.",
      "Pour the strained custard into the chilled tart shells, filling almost to the top.",
      "Bake at 375°F (190°C) for 8 minutes, then lower the temperature to 300°F (150°C) and continue baking for 12-15 minutes, until the custard is just set with a slight wobble in the center.",
      "Let cool slightly before serving - the custard continues to set as it cools, and is best enjoyed warm.",
    ],
    tags: ["dessert"],
    bg: {
      title: "Хонконгска Тарталета с Крем",
      description: "Обичана хонконгска класика от сладкарница - пластовидна или пясъчна коричка, пълнена с копринен, едва подсладен яйчен крем, изпечена точно докато се стегне. Прецеждането на крема и печенето на нежна температура пазят повърхността гладка, вместо напукана и с мехурчета.",
      steps: [
        "Разтрийте студеното масло с брашното и пудрата захар до ронливо, после свържете с яйцето в гладко тесто; увийте и охладете 30 минути.",
        "Разточете тестото и го притиснете в калъпчета за тарталети, изрязвайки краищата; охладете коричките, докато правите крема.",
        "Разтворете захарта в горещата вода и оставете да изстине до стайна температура.",
        "Разбийте яйцата леко (избягвайки прекалено много въздух, който причинява мехурчета) и смесете с подсладената вода, кондензираното мляко и ванилията.",
        "Прецедете крема през фина цедка поне веднъж, идеално два пъти, за да премахнете нишките яйце и въздушните мехурчета - това е задължително за гладка, стъклена повърхност.",
        "Изсипете прецедения крем в охладените коричките, пълнейки почти до горе.",
        "Печете на 190°C за 8 минути, после намалете температурата на 150°C и продължете да печете 12-15 минути, докато кремът точно се стегне с леко разклащане в центъра.",
        "Оставете да изстине леко преди сервиране - кремът продължава да се стяга, докато изстива, и е най-вкусен топъл.",
      ],
      ingredients: [
        "2.25 чаши универсално брашно",
        "225г студено несолено масло, на кубчета",
        "1/3 чаша пудра захар",
        "1 яйце (за коричката)",
        "5 яйца (за крема)",
        "3/4 чаша захар",
        "1 чаша гореща вода",
        "1/2 чаша кондензирано мляко",
        "1 ч.л. ванилов екстракт",
      ],
    },
  },
  {
    slug: "tonkotsu-ramen",
    title: "Tonkotsu Ramen",
    description:
      "Fukuoka's rich, cloudy pork bone ramen, where the broth's creamy body comes from hours of a hard, violent boil that emulsifies the marrow and collagen into the water, not a gentle simmer. Topped with chashu pork, a soft-boiled egg, and black garlic oil.",
    imageEmoji: "🍜",
    cookTimeMinutes: 480,
    servings: 4,
    caloriesPerServing: 640,
    proteinG: 32,
    carbsG: 58,
    fatG: 30,
    ingredients: [
      { text: "3 lb pork trotters and neck bones", ingredient: "pork bones", quantity: 1 },
      { text: "1 lb pork belly, rolled and tied (for chashu)", ingredient: "pork belly", quantity: 1 },
      { text: "1/2 cup soy sauce (for chashu braise)", ingredient: "soy sauce", quantity: 1 },
      { text: "1/4 cup mirin", ingredient: "mirin", quantity: 1 },
      { text: "4 cloves garlic", ingredient: "garlic", quantity: 4 },
      { text: "1 tbsp sesame oil", ingredient: "sesame oil", quantity: 1 },
      { text: "4 cloves garlic, thinly sliced (for black garlic oil)", ingredient: "garlic", quantity: 4 },
      { text: "4 portions fresh thin ramen noodles", ingredient: "ramen noodles", quantity: 4 },
      { text: "4 soft-boiled eggs, marinated in soy sauce", ingredient: "egg", quantity: 4 },
      { text: "4 tbsp tare (concentrated soy seasoning base)", ingredient: "tare", quantity: 4 },
      { text: "Sliced scallions and nori, for garnish", ingredient: "scallion", quantity: null },
    ],
    steps: [
      "Blanch the pork bones in boiling water for 10 minutes, then scrub off any scum and residue thoroughly under running water.",
      "Return the cleaned bones to a large pot, cover generously with fresh water, and bring to a full, hard, rolling boil - not a gentle simmer - and maintain that violent boil for 8-10 hours, topping up water as needed, until the broth turns milky white and thick.",
      "Meanwhile, braise the rolled pork belly in a mixture of soy sauce, mirin, garlic, and enough water to cover, simmering gently for 2-2.5 hours until tender, then slice into rounds for chashu.",
      "Fry the thinly sliced garlic in oil over low heat, stirring constantly, until deeply browned and fragrant, to make black garlic oil (mayu); set aside.",
      "Strain the finished tonkotsu broth through a fine sieve, discarding the bones.",
      "Cook the ramen noodles in boiling water for 60-90 seconds until just tender (they should stay firm since they'll continue softening in the hot broth).",
      "Spoon the tare into the bottom of each bowl, ladle in the hot tonkotsu broth and whisk briefly to combine, then add the drained noodles.",
      "Top with slices of chashu, a halved soft-boiled egg, a drizzle of black garlic oil, scallions, and nori before serving immediately.",
    ],
    tags: ["dinner"],
    bg: {
      title: "Тонкоцу Рамен",
      description: "Богатият, мътен рамен от свински кокали от Фукуока, чието кремообразно тяло идва от часове силно, бурно кипене, което емулгира костния мозък и колагена във водата, а не леко къкрене. Отгоре с чашу свинско, меко сварено яйце и черно чеснов олио.",
      steps: [
        "Бланширайте свинските кокали във вряла вода 10 минути, после изтъркайте старателно всякаква пяна и остатъци под течаща вода.",
        "Върнете почистените кокали в голяма тенджера, покрийте обилно с прясна вода и кипнете напълно, бурно и продължително - не леко къкрене - и поддържайте това бурно кипене 8-10 часа, доливайки вода при нужда, докато бульонът стане млечнобял и гъст.",
        "Междувременно задушете навитата свинска гърда в смес от соев сос, мирин, чесън и достатъчно вода да покрие, къкрейки леко 2-2.5 часа, докато омекне, после нарежете на кръгчета за чашу.",
        "Запържете тънко нарязания чесън в олио на слаб огън, разбърквайки постоянно, докато дълбоко покафенее и замирише, за да направите черно чеснов олио (маю); оставете настрана.",
        "Прецедете готовия тонкоцу бульон през фина цедка, изхвърляйки кокалите.",
        "Сварете рамен юфката във вряла вода 60-90 секунди до готовност (трябва да остане стегната, тъй като ще продължи да омеква в горещия бульон).",
        "Сложете таре на дъното на всяка купа, налейте горещия тонкоцу бульон и разбъркайте кратко, за да се смесят, после добавете отцедената юфка.",
        "Отгоре наредете резени чашу, разполовено меко сварено яйце, малко черно чеснов олио, пролетен лук и нори преди сервиране веднага.",
      ],
      ingredients: [
        "1.4кг свински крачета и вратни кости",
        "450г свинска гърда, навита и вързана (за чашу)",
        "1/2 чаша соев сос (за задушаването на чашу)",
        "1/4 чаша мирин",
        "4 скилидки чесън",
        "1 с.л. сусамово олио",
        "4 скилидки чесън, тънко нарязани (за черно чеснов олио)",
        "4 порции прясна тънка рамен юфка",
        "4 меко сварени яйца, маринована в соев сос",
        "4 с.л. таре (концентрирана соева основа)",
        "Нарязан пролетен лук и нори, за украса",
      ],
    },
  },
  {
    slug: "dorayaki",
    title: "Dorayaki",
    description:
      "Japan's beloved pancake sandwich, two fluffy honey-sweetened castella-style pancakes filled with sweet red bean paste. A rest period lets the batter's baking powder relax and the honey deepen, which gives the pancakes their signature soft, spongy crumb.",
    imageEmoji: "🥞",
    cookTimeMinutes: 40,
    servings: 6,
    caloriesPerServing: 260,
    proteinG: 6,
    carbsG: 52,
    fatG: 3,
    ingredients: [
      { text: "4 eggs", ingredient: "egg", quantity: 4 },
      { text: "1/2 cup sugar", ingredient: "sugar", quantity: 1 },
      { text: "3 tbsp honey", ingredient: "honey", quantity: 3 },
      { text: "1 1/2 cups all-purpose flour", ingredient: "all-purpose flour", quantity: 2 },
      { text: "1 tsp baking powder", ingredient: "baking powder", quantity: 1 },
      { text: "3 tbsp water", ingredient: "water", quantity: 1 },
      { text: "1 tsp vegetable oil, for the pan", ingredient: "vegetable oil", quantity: 1 },
      { text: "1 1/2 cups sweet red bean paste (anko)", ingredient: "red bean paste", quantity: 2 },
    ],
    steps: [
      "Whisk the eggs and sugar together until pale and slightly thickened, then whisk in the honey and water.",
      "Sift the flour and baking powder together and gently fold into the egg mixture until just smooth, taking care not to overmix.",
      "Cover the batter and let it rest for 15-30 minutes - this relaxes the gluten and lets the flavors settle, giving a more tender, evenly domed pancake.",
      "Heat a non-stick pan or griddle over low-medium heat and lightly wipe with oil.",
      "Pour small ladles of batter to form 3-4 inch rounds, cooking until bubbles form on the surface and the edges look set, about 1-2 minutes.",
      "Flip and cook the other side for another minute, until lightly golden on both sides but still soft.",
      "Stack the cooked pancakes under a clean towel to keep them soft and steamy while you cook the rest.",
      "Spread a generous layer of sweet red bean paste on the flat side of one pancake and sandwich with a second pancake, flat sides together.",
    ],
    tags: ["dessert", "breakfast"],
    bg: {
      title: "Дораяки",
      description: "Обичаният японски сандвич от палачинки - две пухкави, подсладени с мед палачинки от вида кастела, пълнени със сладка паста от червен боб. Периодът на почивка отпуска бакпулвера в тестото и задълбочава меда, което придава на палачинките характерната мека, гъбеста трохичка.",
      steps: [
        "Разбийте яйцата и захарта заедно, докато побледнеят и леко се сгъстят, после разбъркайте меда и водата.",
        "Пресейте брашното и бакпулвера заедно и внимателно ги вгънете в яйчената смес, докато стане гладко, внимавайки да не разбърквате прекалено много.",
        "Покрийте тестото и оставете да почине 15-30 минути - това отпуска глутена и позволява на ароматите да се сплотят, давайки по-нежна, равномерно изпъкнала палачинка.",
        "Загрейте незалепващ тиган или скара на слаб до среден огън и леко избършете с олио.",
        "Изсипете малки черпаци тесто, за да оформите кръгчета 8-10 см, като готвите, докато мехурчета се появят на повърхността и краищата изглеждат стегнати, около 1-2 минути.",
        "Обърнете и гответе другата страна още минута, докато леко позлатее от двете страни, но остане мека.",
        "Наредете сготвените палачинки под чиста кърпа, за да останат меки и топли, докато гответе останалите.",
        "Намажете обилен слой сладка паста от червен боб от плоската страна на една палачинка и направете сандвич с втора палачинка, плоски страни заедно.",
      ],
      ingredients: [
        "4 яйца",
        "1/2 чаша захар",
        "3 с.л. мед",
        "1.5 чаши универсално брашно",
        "1 ч.л. бакпулвер",
        "3 с.л. вода",
        "1 ч.л. олио, за тигана",
        "1.5 чаши сладка паста от червен боб (анко)",
      ],
    },
  },
  {
    slug: "shabu-shabu",
    title: "Shabu-Shabu",
    description:
      "A Japanese hot pot where paper-thin slices of beef are swished briefly through simmering kombu broth right at the table - just a few seconds until the color changes - then dipped in ponzu or sesame sauce. The gentle, never-boiling broth keeps every ingredient tender.",
    imageEmoji: "🍲",
    cookTimeMinutes: 40,
    servings: 4,
    caloriesPerServing: 420,
    proteinG: 32,
    carbsG: 24,
    fatG: 20,
    ingredients: [
      { text: "1 large piece kombu (dried kelp)", ingredient: "kombu", quantity: 1 },
      { text: "1.5 lb beef ribeye or sirloin, sliced paper-thin", ingredient: "beef ribeye", quantity: 1 },
      { text: "1/2 napa cabbage, cut into pieces", ingredient: "napa cabbage", quantity: 1 },
      { text: "8 oz enoki mushrooms, trimmed", ingredient: "enoki mushrooms", quantity: 1 },
      { text: "4 shiitake mushrooms, sliced", ingredient: "shiitake mushrooms", quantity: 4 },
      { text: "1 block firm tofu, cubed", ingredient: "firm tofu", quantity: 1 },
      { text: "1 carrot, thinly sliced", ingredient: "carrot", quantity: 1 },
      { text: "1 bunch shungiku (chrysanthemum greens) or spinach", ingredient: "shungiku greens", quantity: 1 },
      { text: "8 oz shirataki or udon noodles", ingredient: "udon noodles", quantity: 1 },
      { text: "1/2 cup ponzu sauce, for dipping", ingredient: "ponzu sauce", quantity: 1 },
      { text: "1/2 cup sesame dipping sauce (goma dare)", ingredient: "sesame dipping sauce", quantity: 1 },
      { text: "2 scallions, sliced, for garnish", ingredient: "scallion", quantity: 2 },
    ],
    steps: [
      "Soak the kombu in a large pot of water for 30 minutes, then heat gently until small bubbles form at the edges - never let it come to a full boil, which makes the kombu bitter.",
      "Remove the kombu just before boiling and keep the broth at a gentle simmer at the table, over a portable burner.",
      "Arrange the thinly sliced beef, vegetables, mushrooms, tofu, and noodles attractively on platters around the pot.",
      "Set out small bowls of ponzu and sesame dipping sauce for each diner.",
      "Using chopsticks, swish a slice of beef back and forth in the simmering broth for just a few seconds, until the color changes from red to pale pink - this quick motion is where the dish gets its name, meaning \"swish swish.\"",
      "Dip the just-cooked beef into ponzu or sesame sauce and eat immediately.",
      "Add the vegetables, mushrooms, and tofu to the pot in batches, letting them simmer for a few minutes until tender, and eat them with the dipping sauces as well.",
      "Once the meat and vegetables are finished, add the noodles to the remaining flavorful broth and simmer briefly as a final course.",
    ],
    tags: ["dinner"],
    bg: {
      title: "Шабу-Шабу",
      description: "Японско горещо гърне, в което тънки като хартия резени говеждо се разклащат за кратко в леко къкрещ бульон от комбу направо на масата - само няколко секунди, докато цветът се промени - после се потапят в понзу или сусамов сос. Нежният, никога не завиращ бульон пази всяка съставка нежна.",
      steps: [
        "Накиснете комбуто в голяма тенджера с вода за 30 минути, после загрейте леко, докато малки мехурчета се появят по краищата - никога не оставяйте да заври напълно, което прави комбуто горчиво.",
        "Извадете комбуто точно преди завиране и поддържайте бульона на леко къкрене на масата, върху преносим котлон.",
        "Наредете тънко нарязаното говеждо, зеленчуците, гъбите, тофуто и юфката привлекателно върху плата около гърнето.",
        "Сложете малки купички с понзу и сусамов сос за потапяне за всеки сътрапезник.",
        "С пръчици разклатете резен говеждо напред-назад в къкрещия бульон само за няколко секунди, докато цветът се промени от червено на бледорозово - това бързо движение дава името на ястието, означаващо \"шляп-шляп\".",
        "Потопете току-що сготвеното говеждо в понзу или сусамов сос и изяжте веднага.",
        "Добавете зеленчуците, гъбите и тофуто в гърнето на порции, оставяйки ги да къкрят няколко минути до омекване, и ги яжте също със соса за потапяне.",
        "След като месото и зеленчуците свършат, добавете юфката в останалия ароматен бульон и къкрете кратко като последно блюдо.",
      ],
      ingredients: [
        "1 голямо парче комбу (сушени водорасли)",
        "680г говежди рибай или бут, нарязан на тънки като хартия резени",
        "1/2 китайско зеле, нарязано на парчета",
        "225г еноки гъби, почистени",
        "4 шийтаке гъби, нарязани",
        "1 блокче твърдо тофу, нарязано на кубчета",
        "1 морков, нарязан на тънки резени",
        "1 връзка шунгику (хризантемови листа) или спанак",
        "225г ширатаки или удон юфка",
        "1/2 чаша понзу сос, за потапяне",
        "1/2 чаша сусамов сос за потапяне (гома даре)",
        "2 стръка пролетен лук, нарязани, за украса",
      ],
    },
  },
  {
    slug: "kimchi-jjigae",
    title: "Kimchi Jjigae",
    description:
      "Korea's beloved bubbling kimchi stew, built on well-fermented, sour kimchi simmered with pork belly until the flavors deepen into something rich and complex. Using kimchi that's past its prime and properly sour, not fresh, is the key to an authentic-tasting jjigae.",
    imageEmoji: "🍲",
    cookTimeMinutes: 35,
    servings: 4,
    caloriesPerServing: 340,
    proteinG: 18,
    carbsG: 14,
    fatG: 22,
    ingredients: [
      { text: "2 cups well-fermented napa cabbage kimchi, chopped, with its juice", ingredient: "kimchi", quantity: 2 },
      { text: "8 oz pork belly, sliced", ingredient: "pork belly", quantity: 1 },
      { text: "1 tbsp gochugaru (Korean chili flakes)", ingredient: "gochugaru", quantity: 1 },
      { text: "1 tbsp gochujang (Korean chili paste)", ingredient: "gochujang", quantity: 1 },
      { text: "1 onion, sliced", ingredient: "onion", quantity: 1 },
      { text: "3 cloves garlic, minced", ingredient: "garlic", quantity: 3 },
      { text: "2 cups water or anchovy broth", ingredient: "anchovy broth", quantity: 2 },
      { text: "1 block firm tofu, sliced", ingredient: "firm tofu", quantity: 1 },
      { text: "2 scallions, cut into segments", ingredient: "scallion", quantity: 2 },
      { text: "1 tsp sugar", ingredient: "sugar", quantity: 1 },
      { text: "1 tsp sesame oil", ingredient: "sesame oil", quantity: 1 },
    ],
    steps: [
      "In a pot or shallow clay pot, cook the pork belly over medium heat until some fat renders and the edges brown slightly.",
      "Add the kimchi and stir-fry together with the pork fat for 3-5 minutes, letting the kimchi caramelize slightly - this step deepens the stew's flavor significantly.",
      "Stir in the gochugaru and gochujang, coating the pork and kimchi evenly.",
      "Add the onion, garlic, and water or anchovy broth, along with the kimchi juice.",
      "Bring to a boil, then reduce to a simmer and cook uncovered for 15-20 minutes, until the pork is tender and the broth has reduced and thickened slightly.",
      "Taste and add the sugar if the kimchi is very sour, to balance the acidity.",
      "Add the tofu slices and scallions in the last 5 minutes, simmering gently so the tofu doesn't break apart.",
      "Finish with a drizzle of sesame oil and serve bubbling hot straight from the pot with a bowl of steamed rice.",
    ],
    tags: ["dinner"],
    bg: {
      title: "Кимчи Джигае",
      description: "Обичаната кипяща корейска яхния от кимчи, изградена върху добре ферментирало, кисело кимчи, задушено със свинска гърда, докато вкусовете се задълбочат в нещо богато и сложно. Използването на кимчи, което е леко презряло и наистина кисело, а не прясно, е ключът към автентично джигае.",
      steps: [
        "В тенджера или плитко глинено гърне гответе свинската гърда на средна температура, докато малко мазнина се разтопи и краищата леко покафенеят.",
        "Добавете кимчито и запържете заедно със свинската мазнина 3-5 минути, оставяйки кимчито леко да карамелизира - тази стъпка значително задълбочава вкуса на яхнията.",
        "Разбъркайте гочугару и гочуджанг, покривайки свинското и кимчито равномерно.",
        "Добавете лука, чесъна и водата или бульона от аншоа, заедно със сока от кимчито.",
        "Кипнете, после намалете до къкрене и гответе без капак 15-20 минути, докато свинското омекне и бульонът се редуцира и леко сгъсти.",
        "Опитайте и добавете захарта, ако кимчито е много кисело, за да балансирате киселинността.",
        "Добавете резените тофу и пролетния лук в последните 5 минути, къкрейки леко, за да не се разпадне тофуто.",
        "Завършете с малко сусамово олио и сервирайте кипящо горещо направо от тенджерата с купа варен ориз.",
      ],
      ingredients: [
        "2 чаши добре ферментирало кимчи от китайско зеле, нарязано, със сока си",
        "225г свинска гърда, нарязана",
        "1 с.л. гочугару (корейски люти люспи)",
        "1 с.л. гочуджанг (корейска лютива паста)",
        "1 лук, нарязан",
        "3 скилидки чесън, ситно нарязани",
        "500мл вода или бульон от аншоа",
        "1 блокче твърдо тофу, нарязано",
        "2 стръка пролетен лук, нарязани на парчета",
        "1 ч.л. захар",
        "1 ч.л. сусамово олио",
      ],
    },
  },
  {
    slug: "jajangmyeon",
    title: "Jajangmyeon",
    description:
      "Korea's beloved black bean noodles, thick wheat noodles tossed in a glossy, savory-sweet sauce of pork, potato, and zucchini in fried black bean paste. Frying the raw chunjang paste in oil before anything else is the one non-negotiable step for the right deep, roasted flavor.",
    imageEmoji: "🍜",
    cookTimeMinutes: 45,
    servings: 4,
    caloriesPerServing: 560,
    proteinG: 20,
    carbsG: 78,
    fatG: 18,
    ingredients: [
      { text: "1 lb fresh thick wheat noodles", ingredient: "wheat noodles", quantity: 1 },
      { text: "8 oz pork belly or shoulder, diced small", ingredient: "pork belly", quantity: 1 },
      { text: "1/2 cup chunjang (Korean black bean paste)", ingredient: "chunjang", quantity: 1 },
      { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
      { text: "1 potato, diced", ingredient: "potato", quantity: 1 },
      { text: "1 zucchini, diced", ingredient: "zucchini", quantity: 1 },
      { text: "1 tbsp minced garlic", ingredient: "garlic", quantity: 1 },
      { text: "2 cups water or chicken broth", ingredient: "chicken broth", quantity: 2 },
      { text: "2 tbsp sugar", ingredient: "sugar", quantity: 2 },
      { text: "2 tbsp cornstarch mixed with 3 tbsp water", ingredient: "cornstarch", quantity: 2 },
      { text: "4 tbsp vegetable oil, divided", ingredient: "vegetable oil", quantity: 4 },
      { text: "1 cucumber, julienned, for garnish", ingredient: "cucumber", quantity: 1 },
    ],
    steps: [
      "Heat 3 tbsp oil in a wok over medium heat and add the chunjang directly to the oil, frying it on its own, stirring constantly, for 3-4 minutes until it darkens slightly and smells deeply roasted rather than raw - this step is non-negotiable for authentic flavor.",
      "Scoop the fried paste out into a bowl and set aside; heat the remaining oil in the same wok and stir-fry the garlic and pork until the pork is browned.",
      "Add the onion and stir-fry until translucent, then add the potato and zucchini and stir-fry for 2-3 minutes more.",
      "Return the fried chunjang to the wok, stirring to coat all the vegetables and pork evenly.",
      "Add the water or broth and sugar, bring to a boil, then reduce to a simmer and cook for 15 minutes, until the potato is tender.",
      "Stir in the cornstarch slurry and cook, stirring, until the sauce thickens to a glossy, clingy consistency.",
      "Cook the noodles in boiling water until tender, then drain well and divide among bowls.",
      "Ladle the sauce generously over the noodles, top with julienned cucumber, and mix everything together just before eating.",
    ],
    tags: ["dinner", "lunch"],
    bg: {
      title: "Джаджанмьон",
      description: "Обичаната корейска юфка с черен боб - дебела пшенична юфка, разбъркана в лъскав, солено-сладък сос от свинско, картоф и тиквичка в запържена паста от черен боб. Запържването на суровата чунджанг паста в олио преди всичко останало е задължителната стъпка за правилния дълбок, препечен вкус.",
      steps: [
        "Загрейте 3 с.л. олио в уок на средна температура и добавете чунджанг директно в олиото, запържвайки го сам, разбърквайки постоянно, 3-4 минути, докато леко потъмнее и замирише дълбоко препечено, а не сурово - тази стъпка е задължителна за автентичен вкус.",
        "Извадете запържената паста в купа и оставете настрана; загрейте останалото олио в същия уок и запържете чесъна и свинското, докато свинското покафенее.",
        "Добавете лука и запържете, докато стане прозрачен, после добавете картофа и тиквичката и запържете още 2-3 минути.",
        "Върнете запържения чунджанг в уока, разбърквайки, за да покриете всички зеленчуци и свинското равномерно.",
        "Добавете водата или бульона и захарта, кипнете, после намалете до къкрене и гответе 15 минути, докато картофът омекне.",
        "Разбъркайте разтвора от нишесте и гответе, разбърквайки, докато сосът се сгъсти до лъскава, лепкава консистенция.",
        "Сварете юфката във вряла вода до готовност, после отцедете добре и разпределете в купи.",
        "Залейте обилно юфката със соса, отгоре сложете нарязана на тънки ивици краставица и разбъркайте всичко точно преди хапване.",
      ],
      ingredients: [
        "450г прясна дебела пшенична юфка",
        "225г свинска гърда или рамо, нарязано на малки кубчета",
        "1/2 чаша чунджанг (корейска паста от черен боб)",
        "1 лук, нарязан на кубчета",
        "1 картоф, нарязан на кубчета",
        "1 тиквичка, нарязана на кубчета",
        "1 с.л. ситно нарязан чесън",
        "500мл вода или пилешки бульон",
        "2 с.л. захар",
        "2 с.л. царевично нишесте, смесено с 3 с.л. вода",
        "4 с.л. олио, разделено",
        "1 краставица, нарязана на тънки ивици, за украса",
      ],
    },
  },
  {
    slug: "lu-rou-fan",
    title: "Lu Rou Fan",
    description:
      "Taiwan's iconic braised pork rice, fatty pork belly hand-cut into small cubes and slowly simmered in a soy-and-five-spice sauce until glossy and meltingly tender, spooned over steaming rice. Hand-cutting instead of grinding the pork keeps distinct chunks of fat and meat that render differently as they braise.",
    imageEmoji: "🍚",
    cookTimeMinutes: 90,
    servings: 4,
    caloriesPerServing: 520,
    proteinG: 22,
    carbsG: 48,
    fatG: 28,
    ingredients: [
      { text: "1.5 lb pork belly, hand-cut into small cubes", ingredient: "pork belly", quantity: 1 },
      { text: "3 tbsp sugar", ingredient: "sugar", quantity: 3 },
      { text: "1/2 cup light soy sauce", ingredient: "light soy sauce", quantity: 1 },
      { text: "2 tbsp dark soy sauce", ingredient: "dark soy sauce", quantity: 2 },
      { text: "3 tbsp Shaoxing wine", ingredient: "shaoxing wine", quantity: 3 },
      { text: "6 cloves garlic, minced", ingredient: "garlic", quantity: 6 },
      { text: "4 shallots, thinly sliced and fried until crisp", ingredient: "shallots", quantity: 4 },
      { text: "2 star anise", ingredient: "star anise", quantity: 2 },
      { text: "1 cinnamon stick", ingredient: "cinnamon stick", quantity: 1 },
      { text: "3 hard-boiled eggs, peeled", ingredient: "egg", quantity: 3 },
      { text: "2 cups water", ingredient: "water", quantity: 2 },
      { text: "Steamed white rice, for serving", ingredient: "white rice", quantity: null },
    ],
    steps: [
      "Cut the pork belly by hand into small, roughly 1/2-inch cubes rather than grinding it - this keeps distinct pockets of fat and lean meat that render at different rates for a richer texture.",
      "In a dry pot over medium heat, melt the sugar until it turns a light amber caramel, watching closely so it doesn't burn.",
      "Add the pork belly cubes and stir to coat in the caramel, browning the pork lightly on all sides.",
      "Add the fried shallots and garlic and stir-fry for a minute until fragrant.",
      "Stir in the soy sauces and Shaoxing wine, then add the star anise, cinnamon stick, and water; bring to a boil.",
      "Add the peeled hard-boiled eggs, then reduce to a very low simmer, cover, and braise for 1 to 1.5 hours, stirring occasionally, until the pork is meltingly tender and the sauce has reduced into a thick, glossy gravy.",
      "Taste and adjust seasoning - the sauce should be savory-sweet and deeply aromatic.",
      "Spoon the braised pork, a halved egg, and plenty of the glossy sauce over bowls of hot steamed rice.",
    ],
    tags: ["dinner", "lunch"],
    bg: {
      title: "Лу Жоу Фан",
      description: "Емблематичното тайванско задушено свинско с ориз - тлъста свинска гърда, ръчно нарязана на малки кубчета и бавно къкрена в соево-петаромат сос, докато стане лъскава и разтопено мека, поднесена върху димящ ориз. Ръчното рязане вместо смилане на свинското пази отделни парчета мазнина и месо, които се разтапят различно по време на задушаване.",
      steps: [
        "Нарежете свинската гърда на ръка на малки, приблизително 1.5 см кубчета, вместо да я смилате - това пази отделни джобове мазнина и постно месо, които се разтапят с различна скорост за по-богата текстура.",
        "В суха тенджера на средна температура разтопете захарта, докато стане светъл кехлибарен карамел, наблюдавайки внимателно, за да не изгори.",
        "Добавете кубчетата свинска гърда и разбъркайте, за да ги покриете с карамела, леко покафенявайки свинското от всички страни.",
        "Добавете запържения шалот и чесъна и запържете минута, докато замиришат.",
        "Разбъркайте соевите сосове и шаосинското вино, после добавете звездовидния анасон, канелата и водата; кипнете.",
        "Добавете обелените твърдо сварени яйца, после намалете до много слабо къкрене, покрийте и задушавайте 1 до 1.5 часа, разбърквайки от време на време, докато свинското стане разтопено меко, а сосът се редуцира до гъст, лъскав сос.",
        "Опитайте и коригирайте подправките - сосът трябва да е солено-сладък и дълбоко ароматен.",
        "Сложете задушеното свинско, разполовено яйце и много от лъскавия сос върху купи с горещ варен ориз.",
      ],
      ingredients: [
        "680г свинска гърда, ръчно нарязана на малки кубчета",
        "3 с.л. захар",
        "1/2 чаша светъл соев сос",
        "2 с.л. тъмен соев сос",
        "3 с.л. шаосинско вино",
        "6 скилидки чесън, ситно нарязани",
        "4 шалота, тънко нарязани и запържени до хрупкаво",
        "2 звездовидни анасона",
        "1 пръчка канела",
        "3 твърдо сварени яйца, обелени",
        "500мл вода",
        "Варен бял ориз, за сервиране",
      ],
    },
  },
  {
    slug: "oyster-omelette",
    title: "Oyster Omelette",
    description:
      "A beloved Taiwanese night-market dish of plump oysters set in a translucent, chewy-crisp batter made from sweet potato starch rather than flour, finished with egg and a sweet-savory glaze. The starch slurry is what gives the batter its signature gooey, gelatinous bite around crisp edges.",
    imageEmoji: "🍳",
    cookTimeMinutes: 25,
    servings: 2,
    caloriesPerServing: 340,
    proteinG: 16,
    carbsG: 30,
    fatG: 17,
    ingredients: [
      { text: "1/2 cup sweet potato starch", ingredient: "sweet potato starch", quantity: 1 },
      { text: "1/2 cup water", ingredient: "water", quantity: 1 },
      { text: "10 oz small shucked oysters", ingredient: "oysters", quantity: 1 },
      { text: "3 eggs", ingredient: "egg", quantity: 3 },
      { text: "1 cup baby bok choy or spinach, roughly chopped", ingredient: "bok choy", quantity: 1 },
      { text: "3 tbsp vegetable oil, divided", ingredient: "vegetable oil", quantity: 3 },
      { text: "3 tbsp ketchup", ingredient: "ketchup", quantity: 3 },
      { text: "1 tbsp soy sauce", ingredient: "soy sauce", quantity: 1 },
      { text: "1 tbsp sugar", ingredient: "sugar", quantity: 1 },
      { text: "1 tsp cornstarch mixed with 2 tbsp water", ingredient: "cornstarch", quantity: 1 },
    ],
    steps: [
      "Whisk the sweet potato starch with the water until fully smooth, with no lumps, to make the starch slurry.",
      "Pat the oysters dry and season lightly.",
      "For the sauce, combine the ketchup, soy sauce, sugar, and a splash of water in a small pan; bring to a simmer, stir in the cornstarch slurry, and cook until thickened and glossy; set aside.",
      "Heat 2 tbsp oil in a flat non-stick pan or griddle over medium-high heat, then pour in the starch slurry, swirling to spread it into an even layer.",
      "Once the starch layer starts to turn translucent at the edges, scatter the oysters and bok choy evenly over it.",
      "Crack the eggs directly over the top and gently spread the yolks with a spatula without fully scrambling, letting everything set together.",
      "Once the bottom is golden and crisp, carefully flip the whole omelette (in sections if needed) and cook the other side until the starch layer turns fully translucent and slightly gooey, with crisp edges.",
      "Slide onto a plate and drizzle generously with the sweet-savory sauce before serving hot.",
    ],
    tags: ["dinner", "lunch"],
    bg: {
      title: "Омлет с Стриди",
      description: "Обичано тайванско нощно пазарно ястие с пълни стриди, поставени в прозрачно, дъвчащо-хрупкаво тесто, направено от нишесте от сладък картоф вместо брашно, завършено с яйце и сладко-солена глазура. Разтворът от нишесте придава на тестото характерната си лепкава, желатинова хапка около хрупкави краища.",
      steps: [
        "Разбийте нишестето от сладък картоф с водата, докато стане напълно гладко без бучки, за да направите разтвора от нишесте.",
        "Подсушете стридите и подправете леко.",
        "За соса смесете кетчупа, соевия сос, захарта и малко вода в малък тиган; кипнете леко, разбъркайте разтвора от царевично нишесте и гответе, докато се сгъсти и лъсне; оставете настрана.",
        "Загрейте 2 с.л. олио в плосък незалепващ тиган или скара на средно-силна температура, после изсипете разтвора от нишесте, завъртайки, за да го разпределите в равномерен слой.",
        "След като слоят нишесте започне да става прозрачен по краищата, разпръснете стридите и бок чой равномерно върху него.",
        "Счупете яйцата директно отгоре и внимателно разпределете жълтъците с шпатула, без да ги разбърквате напълно, оставяйки всичко да се стегне заедно.",
        "След като дъното стане златисто и хрупкаво, внимателно обърнете целия омлет (на части, ако е нужно) и гответе другата страна, докато слоят нишесте стане напълно прозрачен и леко лепкав, с хрупкави краища.",
        "Плъзнете в чиния и полейте обилно със сладко-солен сос преди сервиране топло.",
      ],
      ingredients: [
        "1/2 чаша нишесте от сладък картоф",
        "1/2 чаша вода",
        "285г малки обелени стриди",
        "3 яйца",
        "1 чаша бейби бок чой или спанак, едро нарязан",
        "3 с.л. олио, разделено",
        "3 с.л. кетчуп",
        "1 с.л. соев сос",
        "1 с.л. захар",
        "1 ч.л. царевично нишесте, смесено с 2 с.л. вода",
      ],
    },
  },
];

async function main() {
  for (const recipe of newRecipes) {
    const created = await prisma.recipe.create({
      data: {
        slug: recipe.slug,
        title: recipe.title,
        description: recipe.description,
        imageEmoji: recipe.imageEmoji,
        cookTimeMinutes: recipe.cookTimeMinutes,
        servings: recipe.servings,
        steps: JSON.stringify(recipe.steps),
        tags: JSON.stringify(recipe.tags),
        caloriesPerServing: recipe.caloriesPerServing,
        proteinG: recipe.proteinG,
        carbsG: recipe.carbsG,
        fatG: recipe.fatG,
      },
    });

    for (let i = 0; i < recipe.ingredients.length; i++) {
      const ing = recipe.ingredients[i];
      const ingredient = await prisma.ingredient.upsert({
        where: { name: ing.ingredient },
        update: {},
        create: { name: ing.ingredient },
      });
      await prisma.recipeIngredient.create({
        data: {
          recipeId: created.id,
          ingredientId: ingredient.id,
          displayText: ing.text,
          quantity: ing.quantity,
          position: i,
        },
      });
    }

    console.log(`Created ${recipe.slug}`);
  }
  console.log(`Created ${newRecipes.length} recipes total.`);

  await runTranslations(
    newRecipes.map((r) => ({
      slug: r.slug,
      title: r.bg.title,
      description: r.bg.description,
      steps: r.bg.steps,
      ingredients: r.bg.ingredients,
    })),
  );
}

main();
