import { prisma, runTranslations } from "./translate-lib.mjs";

// 10 more recipes from East Asia (China, Japan, Korea, Taiwan),
// finishing out that region from the larger "recipes from the East"
// research project. Each web-researched for authentic technique
// before writing, per standing instructions. Nutrition estimates are
// set directly here (caloriesPerServing/proteinG/carbsG/fatG), per
// standing instruction to never leave new recipes without nutrition.
const newRecipes = [
  {
    slug: "scallion-pancake",
    title: "Scallion Pancake",
    description:
      "A flaky, chewy Chinese flatbread laminated with oil and scallions, coiled into a spiral before rolling flat so it fries up with dozens of thin layers. A hot-water dough is what keeps it pliable enough to laminate without tearing.",
    imageEmoji: "🥞",
    cookTimeMinutes: 45,
    servings: 4,
    caloriesPerServing: 310,
    proteinG: 5,
    carbsG: 40,
    fatG: 14,
    ingredients: [
      { text: "2 cups all-purpose flour", ingredient: "all-purpose flour", quantity: 2 },
      { text: "3/4 cup boiling water", ingredient: "water", quantity: 1 },
      { text: "1/4 cup cold water", ingredient: "water", quantity: 1 },
      { text: "4 tbsp vegetable oil, divided, plus more for frying", ingredient: "vegetable oil", quantity: 4 },
      { text: "3 tbsp all-purpose flour (for the oil paste)", ingredient: "all-purpose flour", quantity: 1 },
      { text: "1 cup scallions, finely chopped", ingredient: "scallion", quantity: 1 },
      { text: "1 tsp salt", ingredient: "salt", quantity: 1 },
      { text: "1 tsp sesame oil", ingredient: "sesame oil", quantity: 1 },
    ],
    steps: [
      "Slowly stir the boiling water into the flour until shaggy, then add the cold water and knead into a smooth, slightly firm dough; rest covered for 30 minutes.",
      "Heat 2 tbsp of the oil in a small pan, whisk in the 3 tbsp flour, and cook briefly to make a thick oil paste; let cool.",
      "Roll the rested dough into a large, thin rectangle, then spread the oil paste evenly over the surface.",
      "Scatter the scallions, salt, and sesame oil evenly over the dough, then roll it up tightly into a long log.",
      "Coil the log into a spiral (like a cinnamon roll), tuck the end underneath, then flatten and roll out gently into a round pancake - this coiling is what creates the many thin, flaky layers.",
      "Repeat to divide into 4 pancakes, letting them rest a few minutes before frying so the layers don't spring back.",
      "Pan-fry each pancake in a generous amount of oil over medium heat, 3-4 minutes per side, until deeply golden and crisp.",
      "Slap the cooked pancake between your palms or against the counter to loosen the layers, then cut into wedges and serve hot.",
    ],
    tags: ["breakfast", "lunch", "vegetarian"],
    bg: {
      title: "Палачинка с Пролетен Лук",
      description: "Хрупкав, пластовиден китайски питка, ламинирана с олио и пролетен лук, навита на спирала преди разточване, за да се изпържи с десетки тънки пластове. Тестото с вряла вода я прави достатъчно гъвкава, за да се ламинира, без да се къса.",
      steps: [
        "Бавно разбъркайте врялата вода в брашното, докато стане на люспи, после добавете студената вода и замесете гладко, леко твърдо тесто; оставете покрито да почине 30 минути.",
        "Загрейте 2 с.л. от олиото в малък тиган, разбийте 3-те с.л. брашно и гответе кратко, за да направите гъста маслена паста; оставете да изстине.",
        "Разточете отпочиналото тесто на голям тънък правоъгълник, после намажете равномерно с маслената паста.",
        "Поръсете пролетния лук, солта и сусамовото олио равномерно върху тестото, после го навийте плътно на дълъг руло.",
        "Навийте рулото на спирала (като кифла с канела), подпъхнете края отдолу, после сплескайте и разточете леко на кръгла палачинка - това навиване създава многото тънки, пластовидни слоеве.",
        "Повторете, за да разделите на 4 палачинки, оставяйки ги да починат няколко минути преди пържене, за да не се свият пластовете.",
        "Изпържете всяка палачинка в достатъчно олио на средна температура, 3-4 минути от всяка страна, докато стане дълбоко златиста и хрупкава.",
        "Плеснете сготвената палачинка между дланите си или в плота, за да разхлабите пластовете, после нарежете на клинове и сервирайте топла.",
      ],
      ingredients: [
        "2 чаши универсално брашно",
        "180мл вряла вода",
        "60мл студена вода",
        "4 с.л. олио, разделено, плюс още за пържене",
        "3 с.л. универсално брашно (за маслената паста)",
        "1 чаша пролетен лук, ситно нарязан",
        "1 ч.л. сол",
        "1 ч.л. сусамово олио",
      ],
    },
  },
  {
    slug: "char-siu-bao",
    title: "Char Siu Bao",
    description:
      "Fluffy steamed Cantonese buns filled with sweet-savory barbecue pork, cracked open at the top from the natural rise of the dough during steaming. A cornstarch-thickened filling keeps the char siu juicy without soaking through the wrapper.",
    imageEmoji: "🥟",
    cookTimeMinutes: 60,
    servings: 6,
    caloriesPerServing: 310,
    proteinG: 12,
    carbsG: 44,
    fatG: 9,
    ingredients: [
      { text: "3 cups bao flour (or all-purpose flour)", ingredient: "bao flour", quantity: 3 },
      { text: "1 tbsp sugar (for dough)", ingredient: "sugar", quantity: 1 },
      { text: "2 1/4 tsp instant yeast", ingredient: "instant yeast", quantity: 2 },
      { text: "1 tsp baking powder", ingredient: "baking powder", quantity: 1 },
      { text: "1 cup warm water", ingredient: "water", quantity: 1 },
      { text: "2 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 2 },
      { text: "2 cups char siu (Chinese BBQ pork), diced small", ingredient: "char siu pork", quantity: 2 },
      { text: "3 tbsp oyster sauce", ingredient: "oyster sauce", quantity: 3 },
      { text: "2 tbsp hoisin sauce", ingredient: "hoisin sauce", quantity: 2 },
      { text: "1 tbsp sugar (for filling)", ingredient: "sugar", quantity: 1 },
      { text: "1 tbsp cornstarch mixed with 3 tbsp water", ingredient: "cornstarch", quantity: 1 },
      { text: "1 tsp sesame oil", ingredient: "sesame oil", quantity: 1 },
    ],
    steps: [
      "Mix the flour, sugar, yeast, and baking powder, then stir in the warm water and oil to form a dough; knead for 8-10 minutes until smooth and elastic.",
      "Cover and let rise in a warm place for about 1 hour, until doubled in size.",
      "For the filling, simmer the diced char siu with oyster sauce, hoisin sauce, and sugar in a small pan until bubbling, then stir in the cornstarch slurry and cook until thickened into a sticky glaze; stir in sesame oil and let cool completely.",
      "Punch down the dough and divide into 12 equal pieces, rolling each into a ball.",
      "Flatten each ball into a disc thicker in the center than at the edges, place a spoonful of the cooled filling in the middle, then gather the edges up and pleat them together to seal at the top, twisting to close.",
      "Place each bun on a square of parchment paper and let rest for 20 minutes to proof again.",
      "Steam over high heat for 12-15 minutes - the buns will naturally crack open slightly at the top as they puff, which is the traditional look for char siu bao.",
      "Let rest 2 minutes off the heat before opening the steamer, then serve hot.",
    ],
    tags: ["breakfast", "lunch"],
    bg: {
      title: "Чар Сиу Бао",
      description: "Пухкави печени кантонски кифлички, пълнени със сладко-солено барбекю свинско, напукани отгоре от естественото втасване на тестото по време на готвене на пара. Плънка, сгъстена с царевично нишесте, пази чар сиуто сочно, без да прокисва обвивката.",
      steps: [
        "Смесете брашното, захарта, маята и бакпулвера, после разбъркайте топлата вода и олиото, за да оформите тесто; месете 8-10 минути, докато стане гладко и еластично.",
        "Покрийте и оставете да втасва на топло място около 1 час, докато се удвои по обем.",
        "За плънката, къкрете нарязаното на кубчета чар сиу с стридения сос, хоисин соса и захарта в малък тиган, докато закипи, после разбъркайте разтвора от нишесте и гответе, докато се сгъсти в лепкава глазура; разбъркайте сусамовото олио и оставете да изстине напълно.",
        "Свалете тестото и разделете на 12 равни части, оформяйки всяка на топче.",
        "Сплескайте всяко топче на диск, по-дебел в средата, отколкото по краищата, поставете лъжица от изстиналата плънка в средата, после съберете краищата и ги надиплете заедно, за да запечатате отгоре, извивайки да затворите.",
        "Поставете всяка кифличка на квадратче хартия за печене и оставете да почине 20 минути за повторно втасване.",
        "Гответе на пара на силен огън 12-15 минути - кифличките естествено ще се напукат леко отгоре, докато набъбват, което е традиционният вид за чар сиу бао.",
        "Оставете да почине 2 минути извън котлона преди отваряне на парния съд, после сервирайте топли.",
      ],
      ingredients: [
        "3 чаши брашно за бао (или универсално брашно)",
        "1 с.л. захар (за тестото)",
        "2.25 ч.л. инстантна мая",
        "1 ч.л. бакпулвер",
        "1 чаша топла вода",
        "2 с.л. олио",
        "2 чаши чар сиу (китайско барбекю свинско), нарязано на малки кубчета",
        "3 с.л. стриден сос",
        "2 с.л. хоисин сос",
        "1 с.л. захар (за плънката)",
        "1 с.л. царевично нишесте, смесено с 3 с.л. вода",
        "1 ч.л. сусамово олио",
      ],
    },
  },
  {
    slug: "lions-head-meatballs",
    title: "Lion's Head Meatballs",
    description:
      "Jiangsu's famous oversized pork meatballs, named for their resemblance to a lion's mane once nestled among braised cabbage leaves. Chopping the pork by hand rather than using pre-ground meat, and folding rather than compacting the mixture, is what keeps them tender instead of dense.",
    imageEmoji: "🍖",
    cookTimeMinutes: 75,
    servings: 4,
    caloriesPerServing: 460,
    proteinG: 26,
    carbsG: 12,
    fatG: 33,
    ingredients: [
      { text: "1.5 lb pork shoulder, hand-chopped or coarsely ground (70/30 fat ratio)", ingredient: "pork shoulder", quantity: 1 },
      { text: "4 water chestnuts, minced", ingredient: "water chestnuts", quantity: 4 },
      { text: "1 egg", ingredient: "egg", quantity: 1 },
      { text: "2 tbsp cornstarch", ingredient: "cornstarch", quantity: 2 },
      { text: "1 tbsp Shaoxing wine", ingredient: "shaoxing wine", quantity: 1 },
      { text: "2 tbsp light soy sauce", ingredient: "light soy sauce", quantity: 2 },
      { text: "1 tbsp ginger, minced", ingredient: "ginger", quantity: 1 },
      { text: "2 scallions, minced", ingredient: "scallion", quantity: 2 },
      { text: "1 tsp salt", ingredient: "salt", quantity: 1 },
      { text: "1 napa cabbage, leaves separated", ingredient: "napa cabbage", quantity: 1 },
      { text: "2 cups chicken broth", ingredient: "chicken broth", quantity: 2 },
      { text: "2 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 2 },
    ],
    steps: [
      "Chop the pork shoulder by hand into a coarse mince (not a smooth paste) - this rougher texture is what gives the meatballs their characteristic loose, tender bite.",
      "Gently combine the pork with water chestnuts, egg, cornstarch, Shaoxing wine, soy sauce, ginger, scallions, and salt, mixing just until combined - overmixing compacts the meat and makes it dense.",
      "Form the mixture into 4 large, loosely packed meatballs, tossing each one lightly between your hands rather than pressing it firmly.",
      "Heat oil in a wide pot and sear the meatballs on all sides until browned, then remove.",
      "Line the bottom of the pot with napa cabbage leaves, place the seared meatballs on top, and tuck more cabbage leaves around and over them.",
      "Pour in the chicken broth, bring to a simmer, then cover and braise on low heat for 45-50 minutes, until the meatballs are cooked through and tender.",
      "Carefully transfer the meatballs and cabbage to a serving bowl, and if desired, reduce the remaining broth briefly before pouring it back over.",
      "Serve hot with steamed rice, spooning the cabbage and broth alongside each meatball.",
    ],
    tags: ["dinner"],
    bg: {
      title: "Кюфтета Лъвска Глава",
      description: "Известните огромни свински кюфтета от Дзянсу, наречени заради приликата с лъвска грива, докато лежат сред задушени листа зеле. Ръчното нарязване на свинското, вместо готово смляно месо, и внимателното сгъване, а не притискане на сместа, ги пази нежни, а не плътни.",
      steps: [
        "Нарежете свинското рамо на ръка на едро смляно месо (не на гладка паста) - тази по-груба текстура придава на кюфтетата характерната им рехава, нежна хапка.",
        "Внимателно смесете свинското с водните кестени, яйцето, царевичното нишесте, шаосинското вино, соевия сос, джинджифила, пролетния лук и солта, разбърквайки само докато се смесят - прекомерното разбъркване уплътнява месото и го прави плътно.",
        "Оформете сместа на 4 големи, рехаво натрупани кюфтета, разклащайки всяко леко между дланите си, вместо да го притискате плътно.",
        "Загрейте олио в широка тенджера и запечете кюфтетата от всички страни, докато покафенеят, после извадете.",
        "Постелете дъното на тенджерата с листа от китайско зеле, поставете запечените кюфтета отгоре и подпъхнете още листа зеле около и върху тях.",
        "Налейте пилешкия бульон, кипнете, после покрийте и задушавайте на слаб огън 45-50 минути, докато кюфтетата се сготвят напълно и омекнат.",
        "Внимателно прехвърлете кюфтетата и зелето в купа за сервиране и, ако желаете, редуцирайте останалия бульон за кратко, преди да го изсипете отново отгоре.",
        "Сервирайте топли с варен ориз, поставяйки зелето и бульона до всяко кюфте.",
      ],
      ingredients: [
        "680г свинско рамо, нарязано на ръка или едро смляно (70/30 съотношение мазнина)",
        "4 водни кестена, ситно нарязани",
        "1 яйце",
        "2 с.л. царевично нишесте",
        "1 с.л. шаосинско вино",
        "2 с.л. светъл соев сос",
        "1 с.л. джинджифил, ситно нарязан",
        "2 стръка пролетен лук, ситно нарязани",
        "1 ч.л. сол",
        "1 китайско зеле, листата разделени",
        "500мл пилешки бульон",
        "2 с.л. олио",
      ],
    },
  },
  {
    slug: "tsukemen",
    title: "Tsukemen",
    description:
      "Japanese dipping ramen - thick, chewy noodles served chilled on the side, dunked bite by bite into a small bowl of intensely concentrated, hot dipping broth. Serving the noodles cold and the broth extra-concentrated is what keeps the dish balanced instead of diluted.",
    imageEmoji: "🍜",
    cookTimeMinutes: 90,
    servings: 4,
    caloriesPerServing: 580,
    proteinG: 26,
    carbsG: 68,
    fatG: 20,
    ingredients: [
      { text: "4 portions thick fresh ramen noodles", ingredient: "ramen noodles", quantity: 4 },
      { text: "4 cups pork and chicken bone broth, reduced", ingredient: "pork chicken broth", quantity: 4 },
      { text: "1/2 cup dried niboshi (sardines) and kombu dashi", ingredient: "niboshi dashi", quantity: 1 },
      { text: "1/2 cup tare (concentrated soy sauce seasoning base)", ingredient: "tare", quantity: 1 },
      { text: "2 tbsp rice vinegar", ingredient: "rice vinegar", quantity: 2 },
      { text: "1 tbsp sugar", ingredient: "sugar", quantity: 1 },
      { text: "8 slices chashu pork", ingredient: "chashu pork", quantity: 8 },
      { text: "2 soft-boiled eggs, marinated, halved", ingredient: "egg", quantity: 2 },
      { text: "1 sheet nori, cut into strips", ingredient: "nori", quantity: 1 },
      { text: "Sliced scallions, for garnish", ingredient: "scallion", quantity: null },
      { text: "Menma (seasoned bamboo shoots), for garnish", ingredient: "menma", quantity: null },
    ],
    steps: [
      "Combine the pork and chicken broth with the niboshi-kombu dashi and simmer together until well infused, then strain.",
      "Stir the tare, rice vinegar, and sugar into the strained broth - tsukemen dipping broth should taste noticeably stronger and more concentrated than a regular ramen soup, since it's not meant to be diluted by the noodle water.",
      "Keep the dipping broth piping hot in a small pot until ready to serve.",
      "Cook the thick noodles in boiling water a minute or two longer than usual, until fully tender with a satisfying chew.",
      "Drain the noodles and immediately rinse them thoroughly under cold running water, rubbing gently to remove surface starch, until fully chilled - this firms up the noodles and is essential to the dish.",
      "Divide the chilled, drained noodles onto serving plates or in bamboo baskets.",
      "Ladle the hot concentrated broth into individual small bowls, and top with chashu, halved egg, menma, nori, and scallions.",
      "To eat, pick up a portion of cold noodles with chopsticks and dip them into the hot broth before eating, alternating bites of broth-soaked noodles with the toppings.",
    ],
    tags: ["dinner", "lunch"],
    bg: {
      title: "Цукемен",
      description: "Японски рамен за потапяне - дебела, дъвчаща юфка, поднесена изстудена отделно, потопявана хапка по хапка в малка купа с интензивно концентриран горещ бульон за потапяне. Сервирането на юфката студена, а бульона извънредно концентриран пази ястието балансирано, а не разредено.",
      steps: [
        "Смесете свинско-пилешкия бульон с дашито от нибоши и комбу и къкрете заедно, докато се напои добре, после прецедете.",
        "Разбъркайте таре, оризовия оцет и захарта в прецедения бульон - бульонът за потапяне на цукемен трябва да е забележимо по-силен и концентриран от обикновената рамен супа, тъй като не е предвиден да се разрежда от водата на юфката.",
        "Поддържайте бульона за потапяне много горещ в малка тенджера до сервиране.",
        "Сварете дебелата юфка във вряла вода минута-две по-дълго от обичайното, докато стане напълно мека с приятна дъвчащост.",
        "Отцедете юфката и веднага я изплакнете старателно под студена течаща вода, разтривайки леко, за да премахнете повърхностното нишесте, докато напълно изстине - това стяга юфката и е задължително за ястието.",
        "Разпределете изстудената, отцедена юфка в чинии за сервиране или бамбукови кошнички.",
        "Налейте горещия концентриран бульон в отделни малки купички и отгоре наредете чашу, разполовено яйце, менма, нори и пролетен лук.",
        "За да ядете, вземете порция студена юфка с пръчици и я потопете в горещия бульон преди хапване, редувайки хапки юфка, напоена с бульон, с гарнитурите.",
      ],
      ingredients: [
        "4 порции дебела прясна рамен юфка",
        "1л свинско-пилешки бульон, редуциран",
        "1/2 чаша дашо от сушени сардини (нибоши) и комбу",
        "1/2 чаша таре (концентрирана соева основа)",
        "2 с.л. оризов оцет",
        "1 с.л. захар",
        "8 резена чашу свинско",
        "2 меко сварени яйца, маринована, разполовени",
        "1 лист нори, нарязан на ивици",
        "Нарязан пролетен лук, за украса",
        "Менма (подправени бамбукови филизи), за украса",
      ],
    },
  },
  {
    slug: "oden",
    title: "Oden",
    description:
      "A comforting Japanese winter hot pot where daikon, boiled eggs, fish cakes, and konjac simmer gently for hours in a light dashi-soy broth until they turn translucent and deeply infused. Letting the pot rest overnight before reheating deepens the flavor even further.",
    imageEmoji: "🍢",
    cookTimeMinutes: 150,
    servings: 6,
    caloriesPerServing: 240,
    proteinG: 16,
    carbsG: 22,
    fatG: 8,
    ingredients: [
      { text: "8 cups dashi stock", ingredient: "dashi stock", quantity: 8 },
      { text: "1/2 cup soy sauce", ingredient: "soy sauce", quantity: 1 },
      { text: "3 tbsp mirin", ingredient: "mirin", quantity: 3 },
      { text: "2 tbsp sake", ingredient: "sake", quantity: 2 },
      { text: "1 large daikon radish, cut into thick rounds", ingredient: "daikon radish", quantity: 1 },
      { text: "6 eggs, hard-boiled and peeled", ingredient: "egg", quantity: 6 },
      { text: "1 block konnyaku (konjac), scored and cut into triangles", ingredient: "konnyaku", quantity: 1 },
      { text: "8 pieces chikuwa (fish cake tubes)", ingredient: "chikuwa fish cake", quantity: 8 },
      { text: "8 pieces hanpen (fluffy fish cake)", ingredient: "hanpen fish cake", quantity: 8 },
      { text: "4 pieces atsuage (fried tofu)", ingredient: "atsuage tofu", quantity: 4 },
      { text: "Japanese mustard, for serving", ingredient: "japanese mustard", quantity: null },
    ],
    steps: [
      "Peel the daikon rounds and bevel the edges slightly, then score a shallow cross into one flat side of each - this helps the broth penetrate evenly.",
      "Parboil the daikon in plain water for 10-15 minutes until slightly softened, then drain (this removes bitterness before it goes into the broth).",
      "Blanch the konnyaku in boiling water for 2 minutes to remove any strong odor, then drain.",
      "Combine the dashi, soy sauce, mirin, and sake in a large pot and bring to a gentle simmer.",
      "Add the daikon first, since it takes longest to absorb flavor, and simmer for 30 minutes.",
      "Add the eggs, konnyaku, and atsuage, and simmer gently for another 30-40 minutes, keeping the heat low so the broth never fully boils.",
      "Add the chikuwa and hanpen in the last 15 minutes, since delicate fish cakes fall apart if simmered too long.",
      "For the best flavor, let the pot cool and rest overnight in the refrigerator, then gently reheat before serving with Japanese mustard on the side.",
    ],
    tags: ["dinner"],
    bg: {
      title: "Оден",
      description: "Успокояващо японско зимно гърне, в което дайкон, варени яйца, рибени кюфтенца и конняку къкрят леко часове в лек бульон от даши и соев сос, докато станат прозрачни и дълбоко напоени. Оставянето на гърнето да почине през нощта преди претопляне задълбочава вкуса още повече.",
      steps: [
        "Обелете кръгчетата дайкон и скосете леко краищата, после направете плитък кръст в едната плоска страна на всяко - това помага бульонът да проникне равномерно.",
        "Бланширайте дайкона в обикновена вода 10-15 минути, докато леко омекне, после отцедете (това премахва горчивината преди да влезе в бульона).",
        "Бланширайте конняку във вряла вода 2 минути, за да премахнете силната миризма, после отцедете.",
        "Смесете дашито, соевия сос, мирина и сакето в голяма тенджера и кипнете леко.",
        "Добавете първо дайкона, тъй като отнема най-дълго да попие вкус, и къкрете 30 минути.",
        "Добавете яйцата, конняку и атсуагето и къкрете леко още 30-40 минути, поддържайки слаб огън, за да не заври бульонът напълно.",
        "Добавете чикува и ханпен в последните 15 минути, тъй като нежните рибени кюфтенца се разпадат, ако къкрят прекалено дълго.",
        "За най-добър вкус оставете гърнето да изстине и почине през нощта в хладилника, после леко претоплете преди сервиране с японска горчица отстрани.",
      ],
      ingredients: [
        "1.9л бульон даши",
        "1/2 чаша соев сос",
        "3 с.л. мирин",
        "2 с.л. саке",
        "1 голям дайкон, нарязан на дебели кръгчета",
        "6 яйца, твърдо сварени и обелени",
        "1 блокче конняку, надрязано и нарязано на триъгълници",
        "8 парчета чикува (тръбички рибено кюфте)",
        "8 парчета ханпен (пухкаво рибено кюфте)",
        "4 парчета атсуаге (пържено тофу)",
        "Японска горчица, за сервиране",
      ],
    },
  },
  {
    slug: "daifuku-mochi",
    title: "Daifuku Mochi",
    description:
      "Soft, pillowy Japanese rice cakes made by pounding steamed glutinous rice into a stretchy dough, then wrapped around sweet red bean paste. Dusting with potato or cornstarch, not flour, is what keeps the sticky mochi from fusing to your hands and the work surface.",
    imageEmoji: "🍡",
    cookTimeMinutes: 50,
    servings: 8,
    caloriesPerServing: 190,
    proteinG: 3,
    carbsG: 42,
    fatG: 1,
    ingredients: [
      { text: "1 1/2 cups mochiko (glutinous rice flour)", ingredient: "mochiko rice flour", quantity: 2 },
      { text: "1/3 cup sugar", ingredient: "sugar", quantity: 1 },
      { text: "1 1/4 cups water", ingredient: "water", quantity: 2 },
      { text: "1 cup potato starch or cornstarch, for dusting", ingredient: "potato starch", quantity: 1 },
      { text: "1 1/2 cups sweet red bean paste (anko), divided into 8 balls", ingredient: "red bean paste", quantity: 2 },
    ],
    steps: [
      "Roll the red bean paste into 8 small balls and chill them while preparing the mochi dough.",
      "Whisk the mochiko and sugar together in a microwave-safe bowl, then gradually whisk in the water until smooth with no lumps.",
      "Cover with plastic wrap and microwave on high for 2 minutes, then remove and stir vigorously with a wet spatula.",
      "Microwave again for 1-2 more minutes, stirring between each interval, until the dough turns translucent, glossy, and very sticky.",
      "Dust a work surface generously with potato starch or cornstarch (not flour, which the sticky mochi won't release from) and turn the hot dough out onto it.",
      "Using a dusted spatula or scraper, divide the dough into 8 portions while it's still warm and pliable.",
      "Flatten each portion in your starch-dusted palm, place a ball of red bean paste in the center, then gather the edges up and pinch to seal completely.",
      "Dust off the excess starch and serve at room temperature, seam-side down; best eaten the same day since mochi hardens as it sits.",
    ],
    tags: ["dessert"],
    bg: {
      title: "Дайфуку Мочи",
      description: "Меки, възглавничести японски оризови кексчета, направени чрез удряне на варен на пара лепкав ориз в еластично тесто, после увити около сладка паста от червен боб. Поръсването с картофено или царевично нишесте, не брашно, пази лепкавото мочи да не залепне за ръцете и повърхността за работа.",
      steps: [
        "Оформете пастата от червен боб на 8 малки топчета и охладете, докато приготвяте тестото за мочи.",
        "Разбъркайте мочико и захарта заедно в купа, подходяща за микровълнова, после постепенно разбъркайте водата, докато стане гладко без бучки.",
        "Покрийте с фолио и загрейте на висока мощност в микровълнова 2 минути, после извадете и разбъркайте енергично с мокра шпатула.",
        "Загрейте отново 1-2 минути, разбърквайки между всеки интервал, докато тестото стане прозрачно, лъскаво и много лепкаво.",
        "Поръсете работна повърхност обилно с картофено или царевично нишесте (не брашно, от което лепкавото мочи не се отделя) и обърнете горещото тесто върху нея.",
        "С поръсена шпатула или стъргалка разделете тестото на 8 части, докато е още топло и гъвкаво.",
        "Сплескайте всяка част в поръсената си с нишесте длан, поставете топче паста от червен боб в средата, после съберете краищата и притиснете, за да запечатате напълно.",
        "Изтупайте излишното нишесте и сервирайте на стайна температура, с шева надолу; най-вкусно е в същия ден, тъй като мочито се втвърдява с времето.",
      ],
      ingredients: [
        "1.5 чаши мочико (брашно от лепкав ориз)",
        "1/3 чаша захар",
        "1.25 чаши вода",
        "1 чаша картофено или царевично нишесте, за поръсване",
        "1.5 чаши сладка паста от червен боб (анко), разделена на 8 топчета",
      ],
    },
  },
  {
    slug: "korean-corn-dog",
    title: "Korean Corn Dog",
    description:
      "Korea's viral street food twist on the corn dog - sausage or chewy rice cake (or both) skewered, dipped in a bready yeasted batter, rolled in crunchy panko or diced potato, deep-fried, then finished with a dusting of sugar and a squeeze of ketchup and mustard.",
    imageEmoji: "🌭",
    cookTimeMinutes: 45,
    servings: 6,
    caloriesPerServing: 420,
    proteinG: 12,
    carbsG: 46,
    fatG: 21,
    ingredients: [
      { text: "6 wooden skewers", ingredient: "wooden skewers", quantity: 6 },
      { text: "6 mozzarella string cheese sticks or hot dog sausages", ingredient: "mozzarella cheese sticks", quantity: 6 },
      { text: "6 pieces tteok (Korean rice cake sticks), optional", ingredient: "tteok rice cake", quantity: 6 },
      { text: "2 cups bread flour", ingredient: "bread flour", quantity: 2 },
      { text: "1 tbsp sugar", ingredient: "sugar", quantity: 1 },
      { text: "2 1/4 tsp instant yeast", ingredient: "instant yeast", quantity: 2 },
      { text: "1 tsp salt", ingredient: "salt", quantity: 1 },
      { text: "1 cup warm milk", ingredient: "milk", quantity: 1 },
      { text: "1 egg", ingredient: "egg", quantity: 1 },
      { text: "2 cups panko breadcrumbs", ingredient: "panko breadcrumbs", quantity: 2 },
      { text: "Vegetable oil, for deep-frying", ingredient: "vegetable oil", quantity: null },
      { text: "1/4 cup sugar, for dusting", ingredient: "sugar", quantity: 1 },
      { text: "Ketchup and mustard, for serving", ingredient: "ketchup", quantity: null },
    ],
    steps: [
      "Mix the bread flour, sugar, yeast, and salt, then stir in the warm milk and egg to form a soft, slightly sticky batter; cover and let rise in a warm place for 45 minutes to 1 hour, until puffy.",
      "Skewer the cheese sticks and/or rice cake pieces, alternating or combining as desired, patting them dry so the batter sticks.",
      "Dust each skewered stick lightly with flour, then dip and roll it in the risen batter, coating it evenly and thickly.",
      "Immediately roll the battered skewer in panko breadcrumbs, pressing gently so the crumbs adhere all over.",
      "Heat oil to 340°F (170°C) in a deep pot and fry the corn dogs, turning occasionally, for 4-5 minutes until deep golden brown and cooked through - keep the heat moderate so the panko browns without burning before the inside finishes.",
      "Drain briefly on a rack or paper towels.",
      "While still warm, roll the corn dogs in the dusting sugar to coat lightly.",
      "Serve immediately with ketchup and mustard drizzled on top or on the side for dipping.",
    ],
    tags: ["snack", "lunch"],
    bg: {
      title: "Корейски Хот Дог на Клечка",
      description: "Вирусният корейски улична закуска, вариант на хот дог на клечка - наденица или дъвчащ оризов кекс (или и двете) на шиш, потопени в хлебно тесто с мая, овалени в хрупкав панко или нарязан на кубчета картоф, изпържени, после завършени с поръсване захар и струйка кетчуп и горчица.",
      steps: [
        "Смесете хлебното брашно, захарта, маята и солта, после разбъркайте топлото мляко и яйцето, за да оформите меко, леко лепкаво тесто; покрийте и оставете да втасва на топло място 45 минути до 1 час, докато набъбне.",
        "Наденете кашкавалените клечки и/или парчетата оризов кекс на шиш, редувайки или комбинирайки по желание, подсушавайки ги, за да залепне тестото.",
        "Поръсете всяка шишче с брашно леко, после потопете и овалете в втасалото тесто, покривайки равномерно и дебело.",
        "Веднага овалете обваленото шишче в панко трохи, притискайки леко, за да залепнат трохите навсякъде.",
        "Загрейте олио до 170°C в дълбока тенджера и изпържете хот договете, обръщайки от време на време, 4-5 минути, докато станат дълбоко златисто кафяви и се сготвят напълно - поддържайте умерена температура, за да покафенее панкото без да изгори, преди вътрешността да се сготви.",
        "Отцедете за кратко на решетка или кухненска хартия.",
        "Докато са още топли, овалете хот договете в захарта за поръсване, за да ги покриете леко.",
        "Сервирайте веднага с кетчуп и горчица отгоре или отстрани за топене.",
      ],
      ingredients: [
        "6 дървени шишчета",
        "6 моцарела кашкавалени пръчици или наденички",
        "6 парчета тток (корейски оризови кексчета), по желание",
        "2 чаши хлебно брашно",
        "1 с.л. захар",
        "2.25 ч.л. инстантна мая",
        "1 ч.л. сол",
        "1 чаша топло мляко",
        "1 яйце",
        "2 чаши панко трохи",
        "Олио, за пържене",
        "1/4 чаша захар, за поръсване",
        "Кетчуп и горчица, за сервиране",
      ],
    },
  },
  {
    slug: "naengmyeon",
    title: "Naengmyeon",
    description:
      "Korea's refreshing cold buckwheat noodle dish, served in an icy, tangy beef and dongchimi (radish water kimchi) broth with tender beef slices, cucumber, and a half egg. Chilling the broth and noodles until nearly frozen is what defines the dish's signature ice-cold bite.",
    imageEmoji: "🍜",
    cookTimeMinutes: 60,
    servings: 4,
    caloriesPerServing: 380,
    proteinG: 22,
    carbsG: 56,
    fatG: 6,
    ingredients: [
      { text: "1 lb beef brisket", ingredient: "beef brisket", quantity: 1 },
      { text: "1 onion, halved", ingredient: "onion", quantity: 1 },
      { text: "4 cloves garlic", ingredient: "garlic", quantity: 4 },
      { text: "2-inch piece ginger, sliced", ingredient: "ginger", quantity: 1 },
      { text: "2 cups dongchimi (radish water kimchi) juice, or substitute extra beef broth with vinegar", ingredient: "dongchimi juice", quantity: 2 },
      { text: "3 tbsp rice vinegar", ingredient: "rice vinegar", quantity: 3 },
      { text: "2 tbsp sugar", ingredient: "sugar", quantity: 2 },
      { text: "1 tbsp soy sauce", ingredient: "soy sauce", quantity: 1 },
      { text: "1 lb naengmyeon noodles (buckwheat noodles)", ingredient: "buckwheat noodles", quantity: 1 },
      { text: "1 Korean pear or Asian pear, thinly sliced", ingredient: "asian pear", quantity: 1 },
      { text: "1/2 cucumber, julienned", ingredient: "cucumber", quantity: 1 },
      { text: "2 eggs, hard-boiled and halved", ingredient: "egg", quantity: 2 },
      { text: "Yellow mustard and vinegar, for serving", ingredient: "yellow mustard", quantity: null },
    ],
    steps: [
      "Simmer the beef brisket with the onion, garlic, and ginger in enough water to cover for 1 to 1.5 hours, until the beef is tender.",
      "Remove the beef and set aside to cool, then slice thinly once cooled.",
      "Strain the beef broth and skim off the fat, then chill it completely in the refrigerator, or over an ice bath for faster cooling.",
      "Combine the chilled beef broth with the dongchimi juice, rice vinegar, sugar, and soy sauce, tasting and adjusting for a bright, tangy-sweet balance.",
      "Freeze the seasoned broth for about 1-2 hours, or until it develops icy slush crystals but is not fully solid.",
      "Cook the naengmyeon noodles in boiling water briefly according to package instructions, then immediately rinse under cold running water and rub the strands to remove excess starch, until fully chilled.",
      "Divide the chilled noodles into bowls, twisting them into a neat mound, then ladle the icy broth around them.",
      "Top with the sliced beef, pear, cucumber, and a halved egg, and serve with mustard and vinegar on the side so each diner can adjust to taste.",
    ],
    tags: ["lunch", "dinner"],
    bg: {
      title: "Ненгмьон",
      description: "Освежаващото корейско студено ястие с елдена юфка, поднесено в леден, кисел бульон от говеждо и донгчими (кимчи от репички), с нежни резени говеждо, краставица и половин яйце. Изстудяването на бульона и юфката почти до замръзване определя характерната леденостудена хапка на ястието.",
      steps: [
        "Къкрете говеждите гърди с лука, чесъна и джинджифила в достатъчно вода да покрие 1 до 1.5 часа, докато говеждото омекне.",
        "Извадете говеждото и оставете настрана да изстине, после нарежете на тънко след изстиване.",
        "Прецедете говеждия бульон и обезмаслете, после охладете напълно в хладилника, или над ледена вода за по-бързо изстудяване.",
        "Смесете охладения говежди бульон с сока от донгчими, оризовия оцет, захарта и соевия сос, опитвайки и коригирайки за ярък, кисело-сладък баланс.",
        "Замразете подправения бульон за около 1-2 часа, или докато се образуват ледени кристали, но не се втвърди напълно.",
        "Сварете ненгмьон юфката във вряла вода за кратко според инструкциите на опаковката, после веднага изплакнете под студена течаща вода и разтрийте нишките, за да премахнете излишното нишесте, докато напълно изстинат.",
        "Разделете изстудената юфка в купи, извивайки я в спретната купчина, после налейте леденото бульон около нея.",
        "Отгоре наредете нарязаното говеждо, крушата, краставицата и разполовено яйце и сервирайте с горчица и оцет отстрани, за да може всеки сътрапезник да коригира на вкус.",
      ],
      ingredients: [
        "450г говежди гърди",
        "1 лук, разполовен",
        "4 скилидки чесън",
        "Парче джинджифил 5 см, нарязано на резени",
        "2 чаши сок от донгчими (кимчи от репички), или заместете с допълнителен говежди бульон с оцет",
        "3 с.л. оризов оцет",
        "2 с.л. захар",
        "1 с.л. соев сос",
        "450г ненгмьон юфка (елдена юфка)",
        "1 корейска круша или азиатска круша, нарязана на тънки резени",
        "1/2 краставица, нарязана на тънки ивици",
        "2 яйца, твърдо сварени и разполовени",
        "Жълта горчица и оцет, за сервиране",
      ],
    },
  },
  {
    slug: "samgyetang",
    title: "Samgyetang",
    description:
      "Korea's restorative ginseng chicken soup, a whole young chicken stuffed with sticky rice, ginseng, jujube, and garlic, then simmered until the meat falls off the bone in a clean, mild broth. Traditionally eaten in the height of summer to fight heat with heat.",
    imageEmoji: "🍲",
    cookTimeMinutes: 105,
    servings: 2,
    caloriesPerServing: 520,
    proteinG: 42,
    carbsG: 38,
    fatG: 20,
    ingredients: [
      { text: "1 small whole young chicken (about 2 lb), cavity cleaned", ingredient: "whole chicken", quantity: 1 },
      { text: "1/2 cup glutinous rice, soaked 1 hour", ingredient: "glutinous rice", quantity: 1 },
      { text: "1 fresh or dried ginseng root", ingredient: "ginseng root", quantity: 1 },
      { text: "6 dried jujubes (red dates)", ingredient: "dried jujubes", quantity: 6 },
      { text: "6 cloves garlic, peeled", ingredient: "garlic", quantity: 6 },
      { text: "2-inch piece ginger, sliced", ingredient: "ginger", quantity: 1 },
      { text: "8 cups water", ingredient: "water", quantity: 8 },
      { text: "2 scallions, sliced, for garnish", ingredient: "scallion", quantity: 2 },
      { text: "Salt and pepper, for serving", ingredient: "salt", quantity: null },
    ],
    steps: [
      "Rinse the chicken well, inside and out, and pat dry.",
      "Stuff the cavity with the soaked glutinous rice, half the garlic cloves, a couple of jujubes, and the ginseng root.",
      "Secure the cavity opening by crossing the legs and tying them together with kitchen twine, or securing with a small skewer, so the stuffing doesn't fall out during cooking.",
      "Place the stuffed chicken in a deep pot and add enough water to fully cover it, along with the remaining garlic, jujubes, and ginger.",
      "Bring to a boil, skimming off any foam that rises to the surface, then reduce to a gentle simmer.",
      "Cover and simmer for 1 to 1.5 hours, until the chicken is completely tender and the rice inside is fully cooked, occasionally skimming excess fat.",
      "Carefully transfer the whole chicken to a large individual serving bowl along with plenty of the broth.",
      "Garnish with scallions and serve with a small dish of salt and pepper on the side for dipping the meat.",
    ],
    tags: ["dinner", "lunch"],
    bg: {
      title: "Самгетанг",
      description: "Възстановяващата корейска супа с пилешко и женшен - цяло младо пиле, пълнено с лепкав ориз, женшен, зизифус и чесън, после къкрено, докато месото се отдели от костта, в чист, лек бульон. Традиционно се яде в разгара на лятото, за да се бори топлината с топлина.",
      steps: [
        "Изплакнете пилето добре, отвътре и отвън, и подсушете.",
        "Напълнете кухината с накиснатия лепкав ориз, половината скилидки чесън, няколко зизифуса и корена женшен.",
        "Затворете отвора на кухината, като кръстосате бутчетата и ги вържете заедно с кухненски канап, или закрепите с малко шишче, за да не изпадне плънката по време на готвене.",
        "Поставете пълненото пиле в дълбока тенджера и добавете достатъчно вода, за да го покрие напълно, заедно с останалия чесън, зизифуси и джинджифил.",
        "Кипнете, обирайки пяната, която се вдига на повърхността, после намалете до леко къкрене.",
        "Покрийте и къкрете 1 до 1.5 часа, докато пилето стане напълно меко, а оризът вътре напълно се сготви, като от време на време обирате излишната мазнина.",
        "Внимателно прехвърлете цялото пиле в голяма индивидуална купа за сервиране заедно с много от бульона.",
        "Украсете с пролетен лук и сервирайте с малка чинийка сол и пипер отстрани за топене на месото.",
      ],
      ingredients: [
        "1 малко цяло младо пиле (около 900г), кухината почистена",
        "1/2 чаша лепкав ориз, накиснат 1 час",
        "1 пресен или сушен корен женшен",
        "6 сушени зизифуса (червени фурми)",
        "6 скилидки чесън, обелени",
        "Парче джинджифил 5 см, нарязано на резени",
        "1.9л вода",
        "2 стръка пролетен лук, нарязани, за украса",
        "Сол и пипер, за сервиране",
      ],
    },
  },
  {
    slug: "taiwanese-popcorn-chicken",
    title: "Taiwanese Popcorn Chicken",
    description:
      "A famous night-market snack of bite-sized fried chicken, marinated in five-spice and garlic, double-fried for shattering crunch, and tossed with a handful of flash-fried Thai basil leaves. Frying the basil in the hot oil at the very end is what gives the dish its distinctive fragrance.",
    imageEmoji: "🍗",
    cookTimeMinutes: 40,
    servings: 4,
    caloriesPerServing: 380,
    proteinG: 26,
    carbsG: 26,
    fatG: 18,
    ingredients: [
      { text: "1.5 lb boneless chicken thighs, cut into bite-sized pieces", ingredient: "chicken thighs", quantity: 1 },
      { text: "3 tbsp soy sauce", ingredient: "soy sauce", quantity: 3 },
      { text: "1 tbsp rice wine", ingredient: "rice wine", quantity: 1 },
      { text: "1 tbsp minced garlic", ingredient: "garlic", quantity: 1 },
      { text: "1 tsp five-spice powder", ingredient: "five spice powder", quantity: 1 },
      { text: "1 tsp white pepper", ingredient: "white pepper", quantity: 1 },
      { text: "1 egg", ingredient: "egg", quantity: 1 },
      { text: "1 cup sweet potato starch (or cornstarch)", ingredient: "sweet potato starch", quantity: 1 },
      { text: "2 cups loosely packed Thai basil leaves", ingredient: "thai basil", quantity: 2 },
      { text: "Vegetable oil, for deep-frying", ingredient: "vegetable oil", quantity: null },
      { text: "Salt and five-spice powder, for dusting", ingredient: "five spice powder", quantity: null },
    ],
    steps: [
      "Marinate the chicken pieces with soy sauce, rice wine, garlic, five-spice powder, and white pepper for at least 30 minutes, ideally longer in the fridge.",
      "Mix the egg into the marinated chicken to help the starch adhere.",
      "Toss the chicken pieces in sweet potato starch, coating each piece thoroughly and shaking off the excess.",
      "Heat oil to 325°F (165°C) and fry the chicken in batches for 3-4 minutes, until cooked through but still pale golden; remove and drain.",
      "Increase the oil temperature to 375°F (190°C) and fry the chicken a second time for 1-2 minutes, until deeply golden and shatteringly crisp - this double-fry is what gives popcorn chicken its crunch.",
      "Drain the chicken on a rack, then quickly fry the basil leaves in the hot oil for about 10-15 seconds, just until they turn translucent and crisp - watch closely, as they burn fast.",
      "Toss the crispy chicken and fried basil together in a large bowl.",
      "Dust with a little extra salt and five-spice powder and serve immediately while hot and crackling.",
    ],
    tags: ["snack", "lunch"],
    bg: {
      title: "Тайванско Пуканково Пиле",
      description: "Известна нощна пазарна закуска от пържено пиле на хапки, маринован с петте аромата и чесън, двойно пържен за хрупкав пукот, разбъркан с шепа бързо изпържени листа тайски босилек. Пърженето на босилека в горещото олио точно накрая придава на ястието характерния аромат.",
      steps: [
        "Маринувайте парчетата пиле със соев сос, оризово вино, чесън, подправка петте аромата и бял пипер за поне 30 минути, идеално по-дълго в хладилника.",
        "Разбъркайте яйцето в маринованото пиле, за да помогне на нишестето да залепне.",
        "Овалете парчетата пиле в нишесте от сладък картоф, покривайки всяко парче старателно и изтръсквайки излишъка.",
        "Загрейте олио до 165°C и изпържете пилето на порции 3-4 минути, докато се сготви напълно, но остане бледо златисто; извадете и отцедете.",
        "Повишете температурата на олиото до 190°C и изпържете пилето втори път за 1-2 минути, докато стане дълбоко златисто и пукащо хрупкаво - това двойно пържене придава на пуканковото пиле хрупкавостта му.",
        "Отцедете пилето на решетка, после бързо изпържете листата босилек в горещото олио за около 10-15 секунди, точно докато станат прозрачни и хрупкави - наблюдавайте внимателно, тъй като изгарят бързо.",
        "Разбъркайте хрупкавото пиле и пържения босилек заедно в голяма купа.",
        "Поръсете с малко допълнителна сол и петте аромата и сервирайте веднага, докато е горещо и пукащо.",
      ],
      ingredients: [
        "680г пилешки бутчета без кости, нарязани на хапки",
        "3 с.л. соев сос",
        "1 с.л. оризово вино",
        "1 с.л. ситно нарязан чесън",
        "1 ч.л. подправка петте аромата",
        "1 ч.л. бял пипер",
        "1 яйце",
        "1 чаша нишесте от сладък картоф (или царевично нишесте)",
        "2 чаши разхлабено натрупани листа тайски босилек",
        "Олио, за пържене",
        "Сол и подправка петте аромата, за поръсване",
      ],
    },
  },
];

async function main() {
  for (const recipe of newRecipes) {
    const created = await prisma.recipe.create({
      data: {
        slug: recipe.slug,
        title: recipe.title,
        description: recipe.description,
        imageEmoji: recipe.imageEmoji,
        cookTimeMinutes: recipe.cookTimeMinutes,
        servings: recipe.servings,
        steps: JSON.stringify(recipe.steps),
        tags: JSON.stringify(recipe.tags),
        caloriesPerServing: recipe.caloriesPerServing,
        proteinG: recipe.proteinG,
        carbsG: recipe.carbsG,
        fatG: recipe.fatG,
      },
    });

    for (let i = 0; i < recipe.ingredients.length; i++) {
      const ing = recipe.ingredients[i];
      const ingredient = await prisma.ingredient.upsert({
        where: { name: ing.ingredient },
        update: {},
        create: { name: ing.ingredient },
      });
      await prisma.recipeIngredient.create({
        data: {
          recipeId: created.id,
          ingredientId: ingredient.id,
          displayText: ing.text,
          quantity: ing.quantity,
          position: i,
        },
      });
    }

    console.log(`Created ${recipe.slug}`);
  }
  console.log(`Created ${newRecipes.length} recipes total.`);

  await runTranslations(
    newRecipes.map((r) => ({
      slug: r.slug,
      title: r.bg.title,
      description: r.bg.description,
      steps: r.bg.steps,
      ingredients: r.bg.ingredients,
    })),
  );
}

main();
