import { prisma, runTranslations } from "./translate-lib.mjs";

// 10 more internationally interesting recipes, spanning Egypt, Lebanon,
// Venezuela, Malaysia/Singapore, Indonesia, South Africa, Germany,
// Mexico, Australia/New Zealand, and India. Each web-researched for
// authentic technique before writing, per standing instructions.
// Nutrition estimates are set directly here (caloriesPerServing/
// proteinG/carbsG/fatG), per standing instruction to never leave new
// recipes without nutrition.
const newRecipes = [
  {
    slug: "koshari",
    title: "Koshari",
    description:
      "Egypt's national dish - layers of rice, lentils, and macaroni topped with a tangy tomato sauce and a sharp garlic-cumin-vinegar dakka, finished with a heap of crispy fried onions. The trick is frying the onions first and cooking the rice and sauce in that same oil.",
    imageEmoji: "🍚",
    cookTimeMinutes: 60,
    servings: 6,
    caloriesPerServing: 520,
    proteinG: 15,
    carbsG: 92,
    fatG: 12,
    ingredients: [
      { text: "1 cup brown or green lentils", ingredient: "lentils", quantity: 1 },
      { text: "1 cup long-grain rice", ingredient: "rice", quantity: 1 },
      { text: "1 cup small elbow macaroni", ingredient: "macaroni", quantity: 1 },
      { text: "1 can (15 oz) chickpeas, drained and rinsed", ingredient: "chickpeas", quantity: 1 },
      { text: "3 large onions, thinly sliced", ingredient: "onion", quantity: 3 },
      { text: "Vegetable oil, for frying (about 1 cup)", ingredient: "vegetable oil", quantity: 1 },
      { text: "2 cans (14 oz each) crushed tomatoes", ingredient: "crushed tomatoes", quantity: 2 },
      { text: "6 cloves garlic, minced, divided", ingredient: "garlic", quantity: 6 },
      { text: "2 tsp ground cumin, divided", ingredient: "cumin", quantity: 2 },
      { text: "3 tbsp white vinegar, divided", ingredient: "white vinegar", quantity: 3 },
      { text: "1 tsp chili flakes or 1 fresh chili, minced", ingredient: "chili", quantity: 1 },
      { text: "Salt and pepper, to taste", ingredient: "salt and pepper", quantity: null },
    ],
    steps: [
      "Fry the sliced onions in about 1 cup oil over medium heat, stirring often, until deep golden brown and crisp, 15-20 minutes - watch closely near the end since they burn fast; drain on paper towels and reserve the flavored oil.",
      "Rinse the lentils and simmer in salted water for about 20 minutes until just tender but not mushy; drain.",
      "In a pot, heat 2 tbsp of the reserved onion oil, add the rice, and stir to coat before adding water (1.5x the rice volume) and salt; cover and simmer 15-18 minutes until the rice has absorbed the onion oil's flavor.",
      "Cook the macaroni in boiling salted water until al dente; drain.",
      "For the tomato sauce, heat 2 tbsp reserved onion oil, saute half the garlic for 30 seconds, add the crushed tomatoes, 1 tsp cumin, salt and pepper, and simmer 15 minutes until thickened.",
      "For the dakka, sizzle the remaining garlic in 1 tbsp reserved onion oil with the remaining cumin and chili, then remove from heat and stir in the vinegar - this sharp, garlicky sauce is what makes koshari taste like koshari.",
      "To assemble, layer the rice, lentils, macaroni, and chickpeas in a bowl, ladle tomato sauce over the top, drizzle with dakka to taste, and finish with a generous pile of the crispy fried onions.",
    ],
    tags: ["dinner", "lunch"],
    bg: {
      title: "Кошари",
      description: "Египетското национално ястие - слоеве от ориз, леща и макарони, залети с пикантен доматен сос и остър сос дака от чесън и кимион, увенчани с купчина хрупкав пържен лук. Тайната е да се пържи лукът в олиото, после да се готвят ориза и соса точно в него, за да поемат аромата му.",
      steps: [
        "Запържете нарязания на резени лук в около 1 чаша олио на средна температура, разбърквайки често, докато стане дълбоко златист и хрупкав, 15-20 минути - следете внимателно към края, защото изгаря бързо; отцедете върху хартиена кърпа и запазете ароматизираното олио.",
        "Изплакнете лещата и я къкрете в подсолена вода около 20 минути, докато омекне, но не се разпадне; отцедете.",
        "В тенджера загрейте 2 с.л. от запазеното лучено олио, добавете ориза и разбъркайте, за да се покрие, преди да добавите вода (1.5 пъти обема на ориза) и сол; покрийте и къкрете 15-18 минути, докато оризът поеме аромата на луковото олио.",
        "Сварете макароните във вряла подсолена вода до готовност \"ал денте\"; отцедете.",
        "За доматения сос загрейте 2 с.л. от запазеното лучено олио, задушете половината чесън за 30 секунди, добавете настърганите домати, 1 ч.л. кимион, сол и пипер и къкрете 15 минути, докато се сгъсти.",
        "За даката запържете останалия чесън в 1 с.л. лучено олио с останалия кимион и лютите чушки, после свалете от котлона и разбъркайте с оцета - този остър, чеснов сос е това, което придава на кошари характерния му вкус.",
        "За сглобяване наредете ориза, лещата, макароните и нахута в купа на слоеве, залейте с доматения сос, поръсете с дака на вкус и завършете с щедра купчина хрупкав пържен лук.",
      ],
      ingredients: [
        "1 чаша кафява или зелена леща",
        "1 чаша дълго зърнест ориз",
        "1 чаша малки макаронени рожкове",
        "1 консерва (425г) нахут, отцеден и изплакнат",
        "3 големи глави лук, нарязани на тънки резени",
        "Олио за пържене (около 1 чаша)",
        "2 консерви (по 400г) настъргани домати",
        "6 скилидки чесън, ситно нарязани, разделени",
        "2 ч.л. смлян кимион, разделени",
        "3 с.л. бял оцет, разделени",
        "1 ч.л. люти чушки на люспи или 1 прясна люта чушка, ситно нарязана",
        "Сол и черен пипер на вкус",
      ],
    },
  },
  {
    slug: "kibbeh",
    title: "Kibbeh",
    description:
      "A Lebanese classic - a shell of seasoned bulgur and ground meat, formed thin by hand and stuffed with spiced meat and toasted pine nuts, then deep-fried to a deep golden crust. Processing the shell mixture to a smooth paste is what lets it stretch thin without tearing.",
    imageEmoji: "🥙",
    cookTimeMinutes: 75,
    servings: 6,
    caloriesPerServing: 340,
    proteinG: 17,
    carbsG: 20,
    fatG: 20,
    ingredients: [
      { text: "1 cup fine bulgur wheat", ingredient: "bulgur", quantity: 1 },
      { text: "1 lb ground lamb or beef, divided", ingredient: "ground lamb", quantity: 1 },
      { text: "1 small onion, grated", ingredient: "onion", quantity: 1 },
      { text: "1 onion, finely diced (for filling)", ingredient: "onion", quantity: 1 },
      { text: "1 tsp ground allspice, divided", ingredient: "allspice", quantity: 1 },
      { text: "1/2 tsp ground cinnamon, divided", ingredient: "cinnamon", quantity: 0.5 },
      { text: "1/4 cup pine nuts", ingredient: "pine nuts", quantity: 0.25 },
      { text: "1 tbsp pomegranate molasses (optional)", ingredient: "pomegranate molasses", quantity: 1 },
      { text: "Vegetable oil, for deep frying", ingredient: "vegetable oil", quantity: null },
      { text: "Salt and pepper, to taste", ingredient: "salt and pepper", quantity: null },
      { text: "Ice water, as needed", ingredient: "ice water", quantity: null },
    ],
    steps: [
      "Rinse the bulgur, cover with warm water, and let soak 30 minutes until softened, then drain and squeeze out as much water as possible by hand.",
      "In a food processor, pulse half the meat (this will be the shell portion) with the grated onion, soaked bulgur, 1/2 tsp allspice, 1/4 tsp cinnamon, salt and pepper until it forms a smooth, cohesive paste - this fine texture is what lets you form a thin shell without it cracking.",
      "For the filling, saute the diced onion in a splash of oil until soft, add the remaining ground meat and cook until browned, then stir in the pine nuts, remaining allspice and cinnamon, and pomegranate molasses if using; season and set aside to cool.",
      "Wet your hands with ice water and take a golf-ball-sized piece of the shell mixture, press your thumb into the center to form a hollow, then rotate and press the walls thin and even, working carefully so it doesn't tear.",
      "Spoon about a tablespoon of filling into the hollow, then pinch the opening closed and shape into a smooth oval or torpedo shape, wetting your hands again as needed.",
      "Heat oil to 350F (175C) in a deep pot - use enough oil to fully submerge the kibbeh and don't overcrowd the pot, frying in batches.",
      "Fry the kibbeh for 4-5 minutes, undisturbed for the first 30 seconds so the shell sets before flipping, until deep golden brown all over, then drain on paper towels and serve hot.",
    ],
    tags: ["dinner", "snack"],
    bg: {
      title: "Кибе",
      description: "Ливанска класика - черупка от заквасен булгур и смляно месо, оформена тънко на ръка и напълнена с подправено месо и печени борови ядки, после запържена до златисто. Финият смлян пълнеж на черупката е тайната за тънка кора, която не се пука.",
      steps: [
        "Изплакнете булгура, залейте го с топла вода и оставете да кисне 30 минути, докато омекне, после отцедете и изстискайте възможно най-много вода с ръце.",
        "В кухненски робот пасирайте половината месо (за черупката) с настъргания лук, накиснатия булгур, 1/2 ч.л. бахар, 1/4 ч.л. канела, сол и пипер, докато се получи гладка, свързана паста - тази фина текстура позволява да оформите тънка черупка, без да се пука.",
        "За пълнежа запържете нарязания лук в малко олио, докато омекне, добавете останалото смляно месо и гответе, докато се запържи, после разбъркайте боровите ядки, останалия бахар и канела, и гранатовия сироп, ако го използвате; подправете и оставете да изстине.",
        "Намокрете ръцете си с ледена вода, вземете парче от смесата за черупка колкото топче за голф, натиснете с палец в центъра, за да оформите вдлъбнатина, после въртете и притискайте стените тънко и равномерно, работейки внимателно, за да не се скъса.",
        "Сложете около супена лъжица пълнеж във вдлъбнатината, после стиснете отвора и оформете гладка овална форма или \"торпедо\", намокряйки ръцете си отново при нужда.",
        "Загрейте олио до 175°C в дълбока тенджера - използвайте достатъчно олио, за да покрие изцяло кибето, и не претоварвайте тенджерата, пържете на партиди.",
        "Пържете кибето 4-5 минути, без да го местите първите 30 секунди, за да се стегне черупката, преди да го обърнете, докато стане дълбоко златисто отвсякъде, после отцедете върху хартиена кърпа и сервирайте горещо.",
      ],
      ingredients: [
        "1 чаша фин булгур",
        "450г смляно агнешко или телешко месо, разделено",
        "1 малка глава лук, настъргана",
        "1 лук, ситно нарязан (за пълнежа)",
        "1 ч.л. смлян бахар, разделен",
        "1/2 ч.л. смляна канела, разделена",
        "1/4 чаша борови ядки",
        "1 с.л. гранатов сироп (по желание)",
        "Олио за дълбоко пържене",
        "Сол и черен пипер на вкус",
        "Ледена вода, колкото е нужно",
      ],
    },
  },
  {
    slug: "cachapa",
    title: "Cachapa",
    description:
      "Venezuelan fresh corn pancakes folded around melting cheese. The key is not over-blending the batter - the corn's natural grain should stay just barely intact, or the texture turns gummy instead of tender.",
    imageEmoji: "🌽",
    cookTimeMinutes: 30,
    servings: 4,
    caloriesPerServing: 380,
    proteinG: 14,
    carbsG: 48,
    fatG: 15,
    ingredients: [
      { text: "4 cups fresh corn kernels (about 6-8 ears), or thawed frozen corn", ingredient: "corn", quantity: 4 },
      { text: "1/2 cup milk", ingredient: "milk", quantity: 0.5 },
      { text: "2 large eggs", ingredient: "egg", quantity: 2 },
      { text: "2 tbsp sugar", ingredient: "sugar", quantity: 2 },
      { text: "1 tsp salt", ingredient: "salt", quantity: 1 },
      { text: "2 tbsp butter, melted, plus more for cooking", ingredient: "butter", quantity: 2 },
      { text: "1/4 cup cornmeal (masarepa or fine cornmeal)", ingredient: "cornmeal", quantity: 0.25 },
      { text: "8 oz queso de mano or fresh mozzarella, sliced", ingredient: "queso de mano", quantity: 8 },
    ],
    steps: [
      "In a blender, combine the milk, corn kernels, eggs, sugar, and salt and blend until mostly smooth, scraping down the sides as needed - stop as soon as it comes together, since overblending breaks down the corn's natural grain and turns the batter gummy.",
      "Add the melted butter and cornmeal and pulse just until incorporated; the batter should be thick, like a loose muffin batter.",
      "Heat a griddle or nonstick skillet over medium heat and rub with butter, then spoon about 1/4 cup of batter onto the griddle, spreading it into a round with the back of the ladle in a circular motion.",
      "Cook for 4-5 minutes per side, flipping once small holes appear on the surface, the underside is golden brown, and the cachapa releases easily from the pan.",
      "While the second side cooks, lay a few slices of cheese over half the cachapa; once cooked through, fold it in half over the cheese so it melts from the residual heat.",
      "Serve warm, with extra butter melted on top if desired.",
    ],
    tags: ["breakfast", "lunch"],
    bg: {
      title: "Качапа",
      description: "Венецуелски палачинки от прясна царевица, сгънати наполовина около топящо се сирене. Ключът е да не се пасира тестото твърде дълго - зърнестата структура на царевицата трябва да остане усетима, иначе тестото става лепкаво.",
      steps: [
        "В блендер смесете млякото, царевичните зърна, яйцата, захарта и солта и пасирайте до почти гладка смес, изстъргвайки стените при нужда - спрете веднага щом се получи хомогенна смес, тъй като прекаленото пасиране разрушава естествената зърнеста структура на царевицата и прави тестото лепкаво.",
        "Добавете разтопеното масло и царевичното брашно и пулсирайте само докато се включат; тестото трябва да е гъсто, като рехаво тесто за мъфини.",
        "Загрейте тиган на средна температура и намажете с масло, после сложете около 1/4 чаша тесто в тигана, разстилайки го в кръг с гърба на черпака с кръгово движение.",
        "Печете 4-5 минути от всяка страна, обръщайки веднага щом на повърхността се появят малки дупчици, долната страна е златиста, а качапата се отделя лесно от тигана.",
        "Докато се пече втората страна, наредете няколко резена сирене върху половината качапа; щом се изпече напълно, сгънете я на две върху сиренето, за да се разтопи от остатъчната топлина.",
        "Сервирайте топла, по желание с още разтопено масло отгоре.",
      ],
      ingredients: [
        "4 чаши зърна прясна царевица (около 6-8 кочана), или размразена замразена царевица",
        "1/2 чаша мляко",
        "2 големи яйца",
        "2 с.л. захар",
        "1 ч.л. сол",
        "2 с.л. масло, разтопено, плюс още за печене",
        "1/4 чаша царевично брашно (масарепа или фино царевично брашно)",
        "225г сирене кесо де мано или прясна моцарела, нарязана на резени",
      ],
    },
  },
  {
    slug: "char-kway-teow",
    title: "Char Kway Teow",
    description:
      "Malaysia and Singapore's smoky stir-fried flat rice noodles, tossed in a wok over blazing heat until they pick up \"wok hei\" - the charred, smoky flavor that only comes from cooking over ferocious heat, never a gentle simmer.",
    imageEmoji: "🍜",
    cookTimeMinutes: 25,
    servings: 4,
    caloriesPerServing: 520,
    proteinG: 22,
    carbsG: 58,
    fatG: 22,
    ingredients: [
      { text: "1 lb fresh flat rice noodles (kway teow), separated", ingredient: "flat rice noodles", quantity: 1 },
      { text: "2 Chinese sausages (lap cheong), thinly sliced on the diagonal", ingredient: "chinese sausage", quantity: 2 },
      { text: "12 medium shrimp, peeled and deveined", ingredient: "shrimp", quantity: 12 },
      { text: "2 eggs", ingredient: "egg", quantity: 2 },
      { text: "2 cups bean sprouts", ingredient: "bean sprouts", quantity: 2 },
      { text: "1 cup garlic chives, cut into 2-inch lengths", ingredient: "garlic chives", quantity: 1 },
      { text: "4 cloves garlic, minced", ingredient: "garlic", quantity: 4 },
      { text: "3 tbsp vegetable oil, divided", ingredient: "vegetable oil", quantity: 3 },
      { text: "2 tbsp dark soy sauce", ingredient: "dark soy sauce", quantity: 2 },
      { text: "1 tbsp light soy sauce", ingredient: "light soy sauce", quantity: 1 },
      { text: "1 tbsp oyster sauce", ingredient: "oyster sauce", quantity: 1 },
      { text: "1 tsp fish sauce", ingredient: "fish sauce", quantity: 1 },
      { text: "1 tsp sugar", ingredient: "sugar", quantity: 1 },
      { text: "White pepper, to taste", ingredient: "white pepper", quantity: null },
    ],
    steps: [
      "Mix the dark soy sauce, light soy sauce, oyster sauce, fish sauce, sugar, and a pinch of white pepper together in a small bowl and set aside.",
      "Heat a wok over the highest heat your stove can produce until lightly smoking - this is the single most important step, since char kway teow depends on \"wok hei,\" the smoky char that only comes from cooking over blazing heat.",
      "Add 1 tbsp oil, then the Chinese sausage, and stir-fry 1 minute until it releases its fat; add the garlic and shrimp and stir-fry another minute until the shrimp turn pink.",
      "Push everything to one side of the wok, add a little more oil, crack in the eggs, and scramble briefly before tossing everything together.",
      "Add the noodles and the sauce mixture, and toss constantly and vigorously with a spatula so the noodles pick up char at the edges without sticking or tearing - work fast and keep the heat high the whole time.",
      "Add the bean sprouts and garlic chives and toss for another 30-45 seconds, just until the sprouts are barely wilted and still crunchy.",
      "Serve immediately, while the wok hei is still fragrant.",
    ],
    tags: ["dinner", "lunch"],
    bg: {
      title: "Чар Кхуей Теоу",
      description: "Малайзийски и сингапурски улични фиде от плосък оризов юфка, запържени в уок на изключително силен огън, за да се получи характерният опушен вкус \"уок хей\", който не може да се постигне на слаб огън.",
      steps: [
        "Смесете тъмния соев сос, светлия соев сос, стридения сос, рибния сос, захарта и щипка бял пипер в малка купа и оставете настрана.",
        "Загрейте уок на най-силния огън, който печката ви позволява, докато леко задими - това е най-важната стъпка, защото чар кхуей теоу зависи от \"уок хей\", опушения вкус, който се получава само при готвене на много силен огън.",
        "Добавете 1 с.л. олио, после китайската наденичка, и запържете 1 минута, докато отдели мазнината си; добавете чесъна и скаридите и запържете още минута, докато скаридите порозовеят.",
        "Избутайте всичко на едната страна на уока, добавете малко още олио, счупете яйцата и ги разбъркайте набързо, преди да смесите всичко заедно.",
        "Добавете юфката и соевата смес и разбърквайте непрекъснато и енергично с лопатка, за да може юфката да поеме леко овъгляване по краищата, без да залепва или да се къса - работете бързо и поддържайте силния огън през цялото време.",
        "Добавете кълновете и чесновия лук и разбърквайте още 30-45 секунди, само докато кълновете леко омекнат, но останат хрупкави.",
        "Сервирайте веднага, докато ароматът на \"уок хей\" е още усетим.",
      ],
      ingredients: [
        "450г прясна плоска оризова юфка, разделена",
        "2 китайски наденички (лап чонг), нарязани на тънки диагонални резени",
        "12 средни скариди, обелени и почистени",
        "2 яйца",
        "2 чаши кълнове от боб мунг",
        "1 чаша чеснов лук, нарязан на парчета по 5 см",
        "4 скилидки чесън, ситно нарязани",
        "3 с.л. олио, разделено",
        "2 с.л. тъмен соев сос",
        "1 с.л. светъл соев сос",
        "1 с.л. соев сос стриди",
        "1 ч.л. рибен сос",
        "1 ч.л. захар",
        "Бял пипер на вкус",
      ],
    },
  },
  {
    slug: "gado-gado",
    title: "Gado-Gado",
    description:
      "Indonesia's \"mixed-up\" vegetable salad - blanched vegetables, tofu, tempeh, and hard-boiled egg draped in a warm peanut sauce traditionally pounded together from roasted peanuts, chili, garlic, and toasted shrimp paste in a mortar and pestle.",
    imageEmoji: "🥜",
    cookTimeMinutes: 40,
    servings: 4,
    caloriesPerServing: 400,
    proteinG: 18,
    carbsG: 32,
    fatG: 24,
    ingredients: [
      { text: "1 cup green beans, trimmed and halved", ingredient: "green beans", quantity: 1 },
      { text: "2 cups shredded cabbage", ingredient: "cabbage", quantity: 2 },
      { text: "2 cups bean sprouts", ingredient: "bean sprouts", quantity: 2 },
      { text: "2 medium potatoes, boiled and sliced", ingredient: "potato", quantity: 2 },
      { text: "8 oz firm tofu, cubed and fried", ingredient: "tofu", quantity: 8 },
      { text: "8 oz tempeh, sliced and fried", ingredient: "tempeh", quantity: 8 },
      { text: "2 hard-boiled eggs, halved", ingredient: "egg", quantity: 2 },
      { text: "1 cucumber, sliced", ingredient: "cucumber", quantity: 1 },
      { text: "1/2 cup roasted peanuts", ingredient: "peanuts", quantity: 0.5 },
      { text: "2 cloves garlic", ingredient: "garlic", quantity: 2 },
      { text: "1-2 red chilies, to taste", ingredient: "red chili", quantity: 1 },
      { text: "1 tbsp palm sugar (or brown sugar)", ingredient: "palm sugar", quantity: 1 },
      { text: "1/2 tsp shrimp paste (terasi), toasted (optional)", ingredient: "shrimp paste", quantity: 0.5 },
      { text: "1 tbsp tamarind water", ingredient: "tamarind water", quantity: 1 },
      { text: "3/4 cup coconut milk, plus water to thin", ingredient: "coconut milk", quantity: 0.75 },
      { text: "Fried shallots, for garnish", ingredient: "fried shallots", quantity: null },
      { text: "Prawn crackers (krupuk), for serving", ingredient: "prawn crackers", quantity: null },
    ],
    steps: [
      "Blanch the green beans, cabbage, and bean sprouts separately in boiling water for 1-2 minutes each, just until bright and barely tender, then plunge into ice water to stop the cooking and keep them crisp.",
      "For the peanut sauce, traditionally the peanuts, chilies, garlic, and toasted shrimp paste are pounded together in a mortar and pestle into a coarse paste - a food processor works too, but pulse rather than puree so some texture remains.",
      "Transfer the paste to a saucepan, stir in the palm sugar, tamarind water, and coconut milk, and simmer gently for 5 minutes, thinning with a splash of water until the sauce coats the back of a spoon but still pours easily.",
      "Arrange the blanched vegetables, boiled potato, fried tofu, fried tempeh, cucumber, and hard-boiled egg on a platter.",
      "Spoon the warm peanut sauce generously over everything - gado-gado means \"mixed up,\" so don't worry about a tidy presentation.",
      "Scatter with fried shallots and serve with prawn crackers on the side.",
    ],
    tags: ["lunch", "dinner"],
    bg: {
      title: "Гадо-Гадо",
      description: "Индонезийска зеленчукова салата с топъл фъстъчен сос - варени зеленчуци, тофу, темпе и твърдо сварено яйце, залети с гъст сос от печени фъстъци, чили, чесън и тамаринд, традиционно стрит в хаван.",
      steps: [
        "Бланширайте зеления фасул, зелето и кълновете поотделно във вряла вода за 1-2 минути всяко, само докато станат ярки и леко омекнат, после ги потопете в ледена вода, за да спрете готвенето и да останат хрупкави.",
        "За фъстъчения сос традиционно фъстъците, лютите чушки, чесънът и препечената скаридена паста се стриват заедно в хаван до груба паста - кухненски робот също върши работа, но пулсирайте, а не пасирайте докрай, за да остане текстура.",
        "Прехвърлете пастата в тенджера, разбъркайте палмовата захар, водата от тамаринд и кокосовото мляко и къкрете леко 5 минути, разреждайки с малко вода, докато сосът покрива гърба на лъжица, но все още се излива лесно.",
        "Наредете бланшираните зеленчуци, варения картоф, пърженото тофу, пърженото темпе, краставицата и твърдо свареното яйце в чиния.",
        "Залейте всичко щедро с топлия фъстъчен сос - \"гадо-гадо\" означава \"разбъркано\", така че не се притеснявайте за спретнато поднасяне.",
        "Поръсете с пържен лук шалот и сервирайте с крекери от скариди отстрани.",
      ],
      ingredients: [
        "1 чаша зелен фасул, почистен и нарязан наполовина",
        "2 чаши настъргано зеле",
        "2 чаши кълнове от боб мунг",
        "2 средни картофа, сварени и нарязани на резени",
        "225г твърдо тофу, нарязано на кубчета и запържено",
        "225г темпе, нарязано на резени и запържено",
        "2 твърдо сварени яйца, разрязани наполовина",
        "1 краставица, нарязана на резени",
        "1/2 чаша печени фъстъци",
        "2 скилидки чесън",
        "1-2 червени люти чушки, на вкус",
        "1 с.л. палмова захар (или кафява захар)",
        "1/2 ч.л. скаридена паста (тераси), препечена (по желание)",
        "1 с.л. вода от тамаринд",
        "3/4 чаша кокосово мляко, плюс вода за разреждане",
        "Пържен лук шалот, за гарнитура",
        "Крекери от скариди (крупук), за сервиране",
      ],
    },
  },
  {
    slug: "malva-pudding",
    title: "Malva Pudding",
    description:
      "South Africa's warm apricot-jam sponge pudding, drenched in a hot cream sauce the instant it leaves the oven - pouring hot sauce over a hot cake is what soaks it all the way through, creating the pudding's signature sticky pockets.",
    imageEmoji: "🍮",
    cookTimeMinutes: 55,
    servings: 8,
    caloriesPerServing: 340,
    proteinG: 4,
    carbsG: 42,
    fatG: 18,
    ingredients: [
      { text: "1 cup sugar", ingredient: "sugar", quantity: 1 },
      { text: "2 eggs", ingredient: "egg", quantity: 2 },
      { text: "1 tbsp apricot jam", ingredient: "apricot jam", quantity: 1 },
      { text: "1 tbsp white vinegar", ingredient: "white vinegar", quantity: 1 },
      { text: "1 tbsp butter, melted", ingredient: "butter", quantity: 1 },
      { text: "1 cup all-purpose flour", ingredient: "flour", quantity: 1 },
      { text: "1 tsp baking soda", ingredient: "baking soda", quantity: 1 },
      { text: "Pinch of salt", ingredient: "salt", quantity: null },
      { text: "1 cup milk", ingredient: "milk", quantity: 1 },
      { text: "1 cup cream (for sauce)", ingredient: "cream", quantity: 1 },
      { text: "1/2 cup butter (for sauce)", ingredient: "butter", quantity: 0.5 },
      { text: "1/2 cup sugar (for sauce)", ingredient: "sugar", quantity: 0.5 },
      { text: "1/2 cup milk (for sauce)", ingredient: "milk", quantity: 0.5 },
      { text: "Pinch of salt (for sauce)", ingredient: "salt", quantity: null },
    ],
    steps: [
      "Preheat the oven to 350F (180C) and grease a baking dish.",
      "Beat the sugar, eggs, and apricot jam together for 3-5 minutes until light, pale, and fluffy - this whipped air is most of what gives the pudding its light crumb.",
      "Stir in the vinegar and melted butter.",
      "Sift the flour, baking soda, and salt together, then fold into the egg mixture alternately with the milk, mixing just until combined.",
      "Pour the batter into the prepared dish and bake for 35-40 minutes, until a skewer inserted in the center comes out clean and the top springs back.",
      "While the pudding bakes, combine the sauce cream, butter, sugar, milk, and salt in a small saucepan and heat, stirring, until the butter melts and the sugar dissolves.",
      "The moment the pudding comes out of the oven, poke holes across the top with a skewer and pour the hot sauce evenly over the hot pudding - pouring hot sauce over a hot cake is what lets it soak all the way through instead of just sitting on top.",
      "Let it rest at least 10 minutes to absorb the sauce before serving warm with custard or cream.",
    ],
    tags: ["dessert", "baking"],
    bg: {
      title: "Малва Пудинг",
      description: "Южноафрикански топъл пудинг с кайсиев мармалад, залят с гореща сметанова глазура веднага щом излезе от фурната - точно тази комбинация от горещ пудинг и горещ сос създава характерните лепкави джобчета вътре.",
      steps: [
        "Загрейте фурната на 180°C и намажете тава за печене.",
        "Разбийте захарта, яйцата и кайсиевия мармалад заедно 3-5 минути, докато сместа стане светла, бледа и пухкава - тъкмо този разбит въздух придава на пудинга лекия трохлив вкус.",
        "Разбъркайте оцета и разтопеното масло.",
        "Пресейте брашното, содата бикарбонат и солта заедно, после ги вмесете в яйчената смес последователно с млякото, разбърквайки само докато се съединят.",
        "Изсипете тестото в подготвената тава и печете 35-40 минути, докато пръчица, забодена в центъра, излезе чиста, а повърхността пружинира.",
        "Докато пудингът се пече, смесете сметаната, маслото, захарта, млякото и солта за соса в малка тенджера и загрейте, разбърквайки, докато маслото се разтопи и захарта се разтвори.",
        "В момента, в който пудингът излезе от фурната, направете дупки по повърхността му с пръчица и залейте равномерно горещия сос върху горещия пудинг - точно това, горещ сос върху горещ кекс, позволява да се напои напълно, вместо просто да остане отгоре.",
        "Оставете да почине поне 10 минути, за да попие соса, преди да сервирате топъл с крем или сметана.",
      ],
      ingredients: [
        "1 чаша захар",
        "2 яйца",
        "1 с.л. кайсиев мармалад",
        "1 с.л. бял оцет",
        "1 с.л. масло, разтопено",
        "1 чаша брашно",
        "1 ч.л. сода бикарбонат",
        "Щипка сол",
        "1 чаша мляко",
        "1 чаша течна сметана (за соса)",
        "1/2 чаша масло (за соса)",
        "1/2 чаша захар (за соса)",
        "1/2 чаша мляко (за соса)",
        "Щипка сол (за соса)",
      ],
    },
  },
  {
    slug: "spaetzle",
    title: "Spaetzle",
    description:
      "Swabian Germany's egg noodle dumplings - a thick, elastic dough beaten until it bubbles, then scraped in thin strips straight off a wet board into boiling water, finished the classic way with butter-caramelized onions.",
    imageEmoji: "🍝",
    cookTimeMinutes: 35,
    servings: 4,
    caloriesPerServing: 360,
    proteinG: 12,
    carbsG: 46,
    fatG: 13,
    ingredients: [
      { text: "2 cups all-purpose flour", ingredient: "flour", quantity: 2 },
      { text: "4 eggs", ingredient: "egg", quantity: 4 },
      { text: "1/2 tsp salt", ingredient: "salt", quantity: 0.5 },
      { text: "1/4 cup sparkling water or milk", ingredient: "sparkling water", quantity: 0.25 },
      { text: "3 tbsp butter", ingredient: "butter", quantity: 3 },
      { text: "1 onion, thinly sliced (optional, for Swabian-style finish)", ingredient: "onion", quantity: 1 },
      { text: "Salt, to taste", ingredient: "salt", quantity: null },
      { text: "Fresh chives, chopped, for garnish", ingredient: "chives", quantity: null },
    ],
    steps: [
      "In a large bowl, whisk the flour, eggs, and salt together, then gradually add the sparkling water while beating vigorously with a wooden spoon until the dough is thick, smooth, elastic, and forms bubbles when lifted with the spoon - this beating develops the gluten that gives spaetzle their springy bite.",
      "Let the dough rest for 10-15 minutes.",
      "Bring a large pot of salted water to a boil. Working in batches, spread a thin layer of dough onto a wet spaetzle board or small cutting board and use a scraper or thin knife to scrape narrow strips directly off the edge into the boiling water - if you don't have a board, press the dough through a colander with large holes or a spaetzle press instead.",
      "The spaetzle are done about 1-2 minutes after they float to the surface; scoop them out with a slotted spoon into a bowl of cold water to stop the cooking, then drain.",
      "For a Swabian-style finish, melt the butter in a skillet, add the sliced onion, and cook over medium-low heat for 10-12 minutes until deeply caramelized.",
      "Add the drained spaetzle to the pan and toss over medium-high heat for a few minutes until lightly golden at the edges.",
      "Season with salt, scatter with chives, and serve hot.",
    ],
    tags: ["dinner", "lunch"],
    bg: {
      title: "Шпецле",
      description: "Германски яйчени кнедли от Швабия - тестото се разбива до еластично и с мехурчета, после се остъргва на тънки ивици направо във вряща вода от намокрена дъска. Финалното запържване с карамелизиран лук в масло е класическият швабски щрих.",
      steps: [
        "В голяма купа разбийте брашното, яйцата и солта заедно, после постепенно добавяйте газираната вода, като разбивате енергично с дървена лъжица, докато тестото стане гъсто, гладко, еластично и образува мехурчета, когато го повдигнете с лъжицата - точно това разбиване развива глутена, който придава на шпецле характерната им еластична хапка.",
        "Оставете тестото да почине 10-15 минути.",
        "Кипнете голяма тенджера подсолена вода. Работейки на партиди, разстелете тънък слой тесто върху намокрена дъска за шпецле или малка дъска за рязане и използвайте остъргвачка или тънък нож, за да остържете тесни ивици направо от ръба във вряща вода - ако нямате дъска, прекарайте тестото през гевгир с големи дупки или преса за шпецле.",
        "Шпецлето е готово около 1-2 минути, след като изплува на повърхността; извадете го с решетъчна лъжица в купа със студена вода, за да спре готвенето, после отцедете.",
        "За швабски финал разтопете маслото в тиган, добавете нарязания лук и гответе на средно-слаб огън 10-12 минути, докато се карамелизира дълбоко.",
        "Добавете отцеденото шпецле в тигана и разбърквайте на средно-силен огън няколко минути, докато леко позлатее по краищата.",
        "Подправете със сол, поръсете с лук резене и сервирайте горещо.",
      ],
      ingredients: [
        "2 чаши брашно",
        "4 яйца",
        "1/2 ч.л. сол",
        "1/4 чаша газирана вода или мляко",
        "3 с.л. масло",
        "1 лук, нарязан на тънки резени (по желание, за швабския финал)",
        "Сол на вкус",
        "Пресен лук резене, нарязан, за гарнитура",
      ],
    },
  },
  {
    slug: "cochinita-pibil",
    title: "Cochinita Pibil",
    description:
      "The Yucatan's signature dish - pork marinated in achiote paste and sour orange juice, wrapped in banana leaves and slow-roasted until it falls apart on its own. The leaves are briefly toasted over a flame first, which softens them and releases their aroma before wrapping the meat.",
    imageEmoji: "🐖",
    cookTimeMinutes: 240,
    servings: 6,
    caloriesPerServing: 380,
    proteinG: 32,
    carbsG: 8,
    fatG: 24,
    ingredients: [
      { text: "3 lbs pork shoulder, cut into large chunks", ingredient: "pork shoulder", quantity: 3 },
      { text: "3.5 oz achiote (annatto) paste", ingredient: "achiote paste", quantity: 3.5 },
      { text: "1 cup sour orange juice (or orange, lime, and grapefruit juice mixed)", ingredient: "sour orange juice", quantity: 1 },
      { text: "4 cloves garlic", ingredient: "garlic", quantity: 4 },
      { text: "1 tsp ground cumin", ingredient: "cumin", quantity: 1 },
      { text: "1/2 tsp ground cinnamon", ingredient: "cinnamon", quantity: 0.5 },
      { text: "1/4 tsp ground cloves", ingredient: "cloves", quantity: 0.25 },
      { text: "1 tsp dried oregano, Mexican if available", ingredient: "oregano", quantity: 1 },
      { text: "1 tsp salt", ingredient: "salt", quantity: 1 },
      { text: "2-3 banana leaves", ingredient: "banana leaves", quantity: 2 },
      { text: "1 red onion, thinly sliced (for pickled onion)", ingredient: "red onion", quantity: 1 },
      { text: "1/2 cup lime juice (for pickled onion)", ingredient: "lime juice", quantity: 0.5 },
      { text: "1/2 tsp salt (for pickled onion)", ingredient: "salt", quantity: 0.5 },
    ],
    steps: [
      "In a blender, combine the achiote paste, sour orange juice, garlic, cumin, cinnamon, cloves, oregano, and salt and blend until smooth.",
      "Place the pork in a large bowl or bag, pour the marinade over it, and massage to coat thoroughly; cover and marinate in the fridge for at least 4 hours, ideally overnight.",
      "Toast the banana leaves briefly over an open flame or in a dry hot skillet, about 30 seconds per side, until they turn deep green and pliable - this releases their aroma and keeps them from tearing when you wrap the meat.",
      "Line a baking dish or Dutch oven with the banana leaves, letting the edges hang over the sides, then add the marinated pork and all its marinade.",
      "Fold the banana leaves over the pork to fully enclose it, cover the dish tightly with foil or a lid, and bake at 325F (165C) for 3 to 3.5 hours, until the pork is completely fall-apart tender.",
      "Meanwhile, combine the sliced red onion, lime juice, and salt in a bowl and let sit at least 30 minutes, until the onion turns bright pink and tangy.",
      "Unwrap the pork, shred it with two forks directly in its juices, and serve piled onto warm tortillas topped with the pickled onion.",
    ],
    tags: ["dinner"],
    bg: {
      title: "Кочинита Пибил",
      description: "Емблематично ястие от Юкатан - свинско, мариновано в анато паста и сок от кисели портокали, увито в бананови листа и бавно печено, докато не се разпадне само. Листата се загряват на открит пламък, за да омекнат и да пуснат аромата си, преди да увият месото.",
      steps: [
        "В блендер смесете анато пастата, сока от кисели портокали, чесъна, кимиона, канелата, карамфила, ригана и солта и пасирайте до гладкост.",
        "Сложете свинското в голяма купа или плик, залейте с маринатата и разтъркайте добре; покрийте и мариновайте в хладилник поне 4 часа, най-добре цяла нощ.",
        "Загрейте бананите листа за кратко на открит пламък или в сух горещ тиган, около 30 секунди от всяка страна, докато потъмнеят до дълбоко зелено и станат гъвкави - това освобождава аромата им и ги пази да не се скъсат, докато увивате месото.",
        "Застелете тава за печене или тежка тенджера с бананите листа, оставяйки краищата да висят отстрани, после добавете маринованото свинско с цялата марината.",
        "Сгънете бананите листа върху свинското, за да го покриете напълно, покрийте плътно тавата с фолио или капак и печете на 165°C за 3 до 3.5 часа, докато свинското се разпадне напълно от мекота.",
        "Междувременно смесете нарязания червен лук, лимоновия сок и солта в купа и оставете да престои поне 30 минути, докато лукът стане ярко розов и кисел.",
        "Развийте свинското, разкъсайте го с две вилици направо в собствения му сос, и сервирайте натрупано върху топли тортили, увенчано с киселия лук.",
      ],
      ingredients: [
        "1.4кг свинско рамо, нарязано на едри парчета",
        "100г анато (ачиоте) паста",
        "1 чаша сок от кисели портокали (или смес от портокалов, лимонов и грейпфрутов сок)",
        "4 скилидки чесън",
        "1 ч.л. смлян кимион",
        "1/2 ч.л. смляна канела",
        "1/4 ч.л. смлян карамфил",
        "1 ч.л. сушен риган, мексикански ако е наличен",
        "1 ч.л. сол",
        "2-3 бананови листа",
        "1 червен лук, нарязан на тънки резени (за киселия лук)",
        "1/2 чаша лимонов сок (за киселия лук)",
        "1/2 ч.л. сол (за киселия лук)",
      ],
    },
  },
  {
    slug: "pavlova",
    title: "Pavlova",
    description:
      "Australia and New Zealand's cloud-like meringue dessert - crisp on the outside, soft and marshmallowy inside thanks to cornstarch and vinegar folded into the meringue. Cooling it slowly inside the switched-off oven is what prevents the shell from cracking.",
    imageEmoji: "🍓",
    cookTimeMinutes: 100,
    servings: 8,
    caloriesPerServing: 230,
    proteinG: 3,
    carbsG: 40,
    fatG: 6,
    ingredients: [
      { text: "6 egg whites, room temperature", ingredient: "egg white", quantity: 6 },
      { text: "1.5 cups superfine sugar", ingredient: "sugar", quantity: 1.5 },
      { text: "1.5 tsp cornstarch", ingredient: "cornstarch", quantity: 1.5 },
      { text: "1.5 tsp white vinegar", ingredient: "white vinegar", quantity: 1.5 },
      { text: "1/2 tsp vanilla extract", ingredient: "vanilla extract", quantity: 0.5 },
      { text: "1.5 cups whipped cream", ingredient: "whipped cream", quantity: 1.5 },
      { text: "Fresh fruit (berries, kiwi, passionfruit), for topping", ingredient: "fresh fruit", quantity: null },
    ],
    steps: [
      "Preheat the oven to 250F (120C) and line a baking sheet with parchment, tracing an 8-inch circle as a guide.",
      "In a clean, dry bowl, whisk the egg whites with an electric mixer until soft peaks form.",
      "With the mixer running, add the sugar one tablespoon at a time, beating well after each addition, until the meringue is thick, glossy, and stiff, and the sugar has fully dissolved.",
      "Sift the cornstarch over the meringue and add the vinegar and vanilla, then gently fold in with a spatula just until combined - the cornstarch and vinegar are what give pavlova its crisp shell and soft, marshmallowy center.",
      "Mound the meringue onto the parchment within the traced circle, smoothing the sides and slightly hollowing the center to cradle the toppings later.",
      "Bake for 1 hour 15 minutes, then turn off the oven and let the pavlova cool completely inside with the door slightly ajar - opening the oven too soon or cooling it too fast is what causes deep cracks.",
      "Once fully cooled, top with whipped cream and fresh fruit just before serving, since the shell will start to soften once it's dressed.",
    ],
    tags: ["dessert", "baking"],
    bg: {
      title: "Павлова",
      description: "Възтушна безе торта от Австралия и Нова Зеландия - хрупкава отвън, мека и лепкава като маршмелоу отвътре благодарение на царевичното нишесте и оцета в сместа. Оставянето да изстине бавно във фурната е тайната да не се напука.",
      steps: [
        "Загрейте фурната на 120°C и застелете тава за печене с хартия за печене, очертавайки кръг с диаметър 20 см като водач.",
        "В чиста, суха купа разбийте белтъците с електрически миксер, докато се образуват меки връхчета.",
        "Докато миксерът работи, добавяйте захарта по една супена лъжица наведнъж, разбивайки добре след всяко добавяне, докато безето стане гъсто, лъскаво и стегнато, а захарта се разтвори напълно.",
        "Пресейте царевичното нишесте върху безето и добавете оцета и ванилията, после внимателно вмесете с шпатула само докато се съединят - царевичното нишесте и оцетът придават на павловата хрупкавата коричка и мекия, подобен на маршмелоу център.",
        "Изсипете безето на купчина върху хартията в очертания кръг, изгладете страните и леко вдлъбнете центъра, за да поеме по-късно украсата.",
        "Печете 1 час и 15 минути, после изключете фурната и оставете павловата да изстине напълно вътре с леко открехната вратичка - отварянето на фурната твърде рано или прекалено бързото изстиване причиняват дълбоки пукнатини.",
        "След като изстине напълно, украсете с разбита сметана и пресни плодове точно преди сервиране, тъй като коричката ще омекне, щом се украси.",
      ],
      ingredients: [
        "6 белтъка, стайна температура",
        "1.5 чаши финна захар",
        "1.5 ч.л. царевично нишесте",
        "1.5 ч.л. бял оцет",
        "1/2 ч.л. ванилова есенция",
        "1.5 чаши разбита сметана",
        "Пресни плодове (боровинки, киви, маракуя), за украса",
      ],
    },
  },
  {
    slug: "dhokla",
    title: "Dhokla",
    description:
      "A light, tangy steamed gram-flour cake from Gujarat, India - a short natural fermentation with yogurt gives it its signature spongy texture, and a hot tempering of mustard seeds and curry leaves poured over the top finishes the flavor.",
    imageEmoji: "🟨",
    cookTimeMinutes: 150,
    servings: 6,
    caloriesPerServing: 160,
    proteinG: 7,
    carbsG: 22,
    fatG: 5,
    ingredients: [
      { text: "1.5 cups gram flour (besan)", ingredient: "gram flour", quantity: 1.5 },
      { text: "3/4 cup plain yogurt, slightly sour", ingredient: "yogurt", quantity: 0.75 },
      { text: "3/4 cup water", ingredient: "water", quantity: 0.75 },
      { text: "1 tsp grated ginger", ingredient: "ginger", quantity: 1 },
      { text: "1 green chili, minced", ingredient: "green chili", quantity: 1 },
      { text: "1/2 tsp turmeric", ingredient: "turmeric", quantity: 0.5 },
      { text: "1 tsp sugar", ingredient: "sugar", quantity: 1 },
      { text: "1 tsp salt", ingredient: "salt", quantity: 1 },
      { text: "1 tsp Eno fruit salt (or baking soda and lemon juice)", ingredient: "eno fruit salt", quantity: 1 },
      { text: "1 tbsp oil", ingredient: "oil", quantity: 1 },
      { text: "2 tbsp oil (for tempering)", ingredient: "oil", quantity: 2 },
      { text: "1 tsp mustard seeds", ingredient: "mustard seeds", quantity: 1 },
      { text: "10 curry leaves", ingredient: "curry leaves", quantity: 10 },
      { text: "2 green chilies, slit", ingredient: "green chili", quantity: 2 },
      { text: "Pinch of asafoetida (hing)", ingredient: "asafoetida", quantity: null },
      { text: "3 tbsp water mixed with 1 tsp sugar", ingredient: "sugar water", quantity: 3 },
      { text: "Fresh cilantro and grated coconut, for garnish", ingredient: "cilantro", quantity: null },
    ],
    steps: [
      "Whisk the gram flour, yogurt, water, ginger, green chili, turmeric, sugar, and salt together into a smooth, thick batter, then cover and let it rest at room temperature for at least 2 hours (or up to overnight) to ferment slightly - this light fermentation, using the yogurt's tang as a starter, is what gives dhokla its characteristic sponge and mild sourness.",
      "Grease a steaming tin or cake pan and bring water to a boil in a steamer or large pot fitted with a rack.",
      "Just before steaming, stir the oil into the batter, then sprinkle the Eno fruit salt over the top and stir gently in one direction only - the batter will immediately turn frothy and bubbly, which is what makes the dhokla rise light and airy.",
      "Pour the batter into the greased tin immediately, before the bubbles subside, and place it in the steamer.",
      "Cover and steam over medium heat for 15-18 minutes, until a toothpick inserted in the center comes out clean and the top springs back when touched.",
      "Let cool slightly, then cut into squares while still in the pan.",
      "For the tempering, heat the oil in a small pan, add the mustard seeds and let them pop, then add the curry leaves, slit green chilies, and asafoetida and sizzle for 30 seconds.",
      "Stir in the sugar water, then pour the hot tempering evenly over the cut dhokla so it seeps into the squares.",
      "Garnish with cilantro and grated coconut before serving.",
    ],
    tags: ["snack", "breakfast"],
    bg: {
      title: "Дхокла",
      description: "Пухкав, леко кисел на вкус задушен сладкиш от нахутено брашно от Гуджарат, Индия - лекото ферментиране с кисело мляко му придава характерната гъбеста текстура, а горещата подправка с горчица и къри листа отгоре завършва вкуса.",
      steps: [
        "Разбийте нахутеното брашно, киселото мляко, водата, джинджифила, лютата чушка, куркумата, захарта и солта заедно в гладко, гъсто тесто, после покрийте и оставете да престои на стайна температура поне 2 часа (или до цяла нощ), за да ферментира леко - тази лека ферментация, използваща киселостта на киселото мляко като закваска, придава на дхоклата характерната гъбеста текстура и лека киселинност.",
        "Намажете с олио тава за задушаване или тава за кекс и кипнете вода в парен съд или голяма тенджера с решетка.",
        "Точно преди задушаване, вмесете олиото в тестото, после поръсете с плодовата сол Eno отгоре и разбъркайте леко само в една посока - тестото веднага ще стане пенливо и с мехурчета, което кара дхоклата да набъбне лека и въздушна.",
        "Изсипете тестото в намазаната тава веднага, преди мехурчетата да спаднат, и я поставете в парния съд.",
        "Покрийте и задушавайте на средна температура 15-18 минути, докато клечка за зъби, забодена в центъра, излезе чиста, а повърхността пружинира при докосване.",
        "Оставете да изстине леко, после нарежете на квадратчета, докато е още в тавата.",
        "За подправката загрейте олиото в малък тиган, добавете семената от горчица и ги оставете да изпукат, после добавете листата къри, срязаните люти чушки и асафетидата и запържете 30 секунди.",
        "Разбъркайте захарната вода, после залейте горещата подправка равномерно върху нарязаната дхокла, за да попие в квадратчетата.",
        "Украсете с кориандър и настърган кокос преди сервиране.",
      ],
      ingredients: [
        "1.5 чаши нахутено брашно (бесан)",
        "3/4 чаша натурално кисело мляко, леко кисело",
        "3/4 чаша вода",
        "1 ч.л. настърган джинджифил",
        "1 зелена люта чушка, ситно нарязана",
        "1/2 ч.л. куркума",
        "1 ч.л. захар",
        "1 ч.л. сол",
        "1 ч.л. плодова сол Eno (или сода бикарбонат и лимонов сок)",
        "1 с.л. олио",
        "2 с.л. олио (за подправката)",
        "1 ч.л. семена от горчица",
        "10 листа къри",
        "2 зелени люти чушки, срязани надлъжно",
        "Щипка асафетида (хинг)",
        "3 с.л. вода, смесена с 1 ч.л. захар",
        "Пресен кориандър и настърган кокос, за украса",
      ],
    },
  },
];

async function main() {
  for (const recipe of newRecipes) {
    const created = await prisma.recipe.create({
      data: {
        slug: recipe.slug,
        title: recipe.title,
        description: recipe.description,
        imageEmoji: recipe.imageEmoji,
        cookTimeMinutes: recipe.cookTimeMinutes,
        servings: recipe.servings,
        steps: JSON.stringify(recipe.steps),
        tags: JSON.stringify(recipe.tags),
        caloriesPerServing: recipe.caloriesPerServing,
        proteinG: recipe.proteinG,
        carbsG: recipe.carbsG,
        fatG: recipe.fatG,
      },
    });

    for (let i = 0; i < recipe.ingredients.length; i++) {
      const ing = recipe.ingredients[i];
      const ingredient = await prisma.ingredient.upsert({
        where: { name: ing.ingredient },
        update: {},
        create: { name: ing.ingredient },
      });
      await prisma.recipeIngredient.create({
        data: {
          recipeId: created.id,
          ingredientId: ingredient.id,
          displayText: ing.text,
          quantity: ing.quantity,
          position: i,
        },
      });
    }

    console.log(`Created ${recipe.slug}`);
  }
  console.log(`Created ${newRecipes.length} recipes total.`);

  await runTranslations(
    newRecipes.map((r) => ({
      slug: r.slug,
      title: r.bg.title,
      description: r.bg.description,
      steps: r.bg.steps,
      ingredients: r.bg.ingredients,
    })),
  );
}

main();
