import { prisma, runTranslations } from "./translate-lib.mjs";

// 10 more Bulgarian recipes, each web-researched for authentic technique
// before writing, per standing instructions.
const newRecipes = [
  {
    slug: "kozunak",
    title: "Kozunak",
    description:
      "Bulgaria's traditional Easter bread - a soft, brioche-like sweet loaf braided and baked golden, studded with rum-soaked raisins and perfumed with lemon zest and vanilla - soaking the raisins in rum first, rather than adding them dry, is what keeps them plump and flavorful instead of drying out and turning tough inside the baked dough.",
    imageEmoji: "🐣",
    cookTimeMinutes: 180,
    servings: 12,
    ingredients: [
      { text: "1/2 cup raisins", ingredient: "raisins", quantity: 0.5 },
      { text: "3 tbsp rum", ingredient: "rum", quantity: 3 },
      { text: "1 cup warm milk", ingredient: "milk", quantity: 1 },
      { text: "2 1/4 tsp yeast", ingredient: "yeast", quantity: 2.25 },
      { text: "1/2 cup sugar (for the dough)", ingredient: "sugar", quantity: 0.5 },
      { text: "5 cups flour", ingredient: "flour", quantity: 5 },
      { text: "4 eggs", ingredient: "eggs", quantity: 4 },
      { text: "1/2 cup melted butter", ingredient: "butter", quantity: 0.5 },
      { text: "1 tsp salt", ingredient: "salt", quantity: 1 },
      { text: "1 tbsp lemon zest", ingredient: "lemon zest", quantity: 1 },
      { text: "1 tsp vanilla extract", ingredient: "vanilla extract", quantity: 1 },
      { text: "1 egg, beaten (for egg wash)", ingredient: "eggs", quantity: 1 },
      { text: "2 tbsp sugar (for topping)", ingredient: "sugar", quantity: 2 },
    ],
    steps: [
      "Soak the raisins in the rum for at least 30 minutes, ideally 1-2 hours, so they plump up and stay soft and flavorful once baked into the dough.",
      "Dissolve the yeast and 1 tbsp of the sugar in the warm milk and let sit for 5-10 minutes until foamy.",
      "In a large bowl, whisk together the flour, remaining sugar, and salt. Add the yeast mixture, 4 eggs, melted butter, lemon zest, and vanilla, and knead for 10-12 minutes until you have a smooth, elastic, slightly tacky dough.",
      "Drain the raisins and knead them into the dough until evenly distributed.",
      "Cover and let rise in a warm place for 1.5-2 hours, until doubled in size.",
      "Punch down the dough, divide into 3 equal strands, and braid them together, tucking the ends underneath. Place in a greased loaf pan or on a baking sheet.",
      "Cover and let rise again for 45-60 minutes, until puffy.",
      "Preheat the oven to 350°F. Brush the loaf all over with the beaten egg and sprinkle with the 2 tbsp sugar.",
      "Bake for 35-40 minutes, until deep golden brown and a skewer inserted into the center comes out clean, tenting with foil partway through if the top browns too quickly.",
      "Let cool completely on a wire rack before slicing.",
    ],
    tags: ["dessert", "baking", "vegetarian"],
    bg: {
      title: "Козунак",
      description:
        "Традиционният български великденски хляб - мек, брошовиден сладък хляб, сплетен на плитка и изпечен до златисто, изпъстрен с накиснати в ром стафиди и ароматизиран с лимонова кора и ванилия - накисването на стафидите в ром първо, вместо да се добавят сухи, е това, което ги пази пухкави и ароматни, вместо да изсъхнат и станат твърди вътре в изпеченото тесто.",
      steps: [
        "Накиснете стафидите в рома поне 30 минути, най-добре 1-2 часа, за да се напухнат и останат меки и ароматни, след като се изпекат в тестото.",
        "Разтворете маята и 1 с.л. от захарта в топлото мляко и оставете за 5-10 минути, докато се разпени.",
        "В голяма купа разбъркайте брашното, останалата захар и солта. Добавете маената смес, 4-те яйца, разтопеното масло, лимоновата кора и ванилията, и месете 10-12 минути, докато се получи гладко, еластично, леко лепкаво тесто.",
        "Отцедете стафидите и ги омесете в тестото, докато се разпределят равномерно.",
        "Покрийте и оставете да втаса на топло място 1.5-2 часа, докато удвои обема си.",
        "Ударете тестото, разделете на 3 равни ленти, и ги сплетете заедно на плитка, прибирайки краищата отдолу. Поставете в намазана тава за хляб или върху тава за печене.",
        "Покрийте и оставете да втаса отново 45-60 минути, докато се надуе.",
        "Загрейте фурната на 175°C. Намажете хляба отвсякъде с разбитото яйце и поръсете с 2-те с.л. захар.",
        "Печете 35-40 минути, докато стане дълбоко златисто кафяво, а шиш, забит в центъра, излезе чист, покривайки с фолио по средата, ако горната част заруменее твърде бързо.",
        "Оставете да изстине напълно върху решетка преди рязане.",
      ],
      ingredients: [
        "1/2 чаша стафиди",
        "3 с.л. ром",
        "1 чаша топло мляко",
        "2 1/4 ч.л. мая",
        "1/2 чаша захар (за тестото)",
        "5 чаши брашно",
        "4 яйца",
        "1/2 чаша разтопено масло",
        "1 ч.л. сол",
        "1 с.л. лимонова кора",
        "1 ч.л. екстракт от ванилия",
        "1 яйце, разбито (за намазване)",
        "2 с.л. захар (за поръсване)",
      ],
    },
  },
  {
    slug: "oriz-na-mlyako",
    title: "Oriz na Mlyako (Bulgarian Rice Pudding)",
    description:
      "A simple Bulgarian rice pudding boiled in milk with just rice, sugar, and cinnamon, then cooled and served cold rather than warm - unlike most Western rice puddings, letting it chill fully before eating is what gives it its familiar, nostalgic texture, and short-grain rice is what makes it genuinely creamy instead of loose and soupy.",
    imageEmoji: "🍮",
    cookTimeMinutes: 40,
    servings: 4,
    ingredients: [
      { text: "2/3 cup short-grain rice", ingredient: "rice", quantity: 0.67 },
      { text: "2 cups water", ingredient: "water", quantity: 2 },
      { text: "3 cups milk", ingredient: "milk", quantity: 3 },
      { text: "1/3 cup sugar", ingredient: "sugar", quantity: 0.33 },
      { text: "1 cinnamon stick", ingredient: "cinnamon stick", quantity: 1 },
      { text: "1 tsp vanilla extract", ingredient: "vanilla extract", quantity: 1 },
      { text: "1/2 tsp cinnamon, for serving", ingredient: "cinnamon", quantity: 0.5 },
    ],
    steps: [
      "Rinse the rice and combine with the water in a saucepan. Bring to a boil, then reduce heat and simmer, covered, for 10 minutes, until the water is mostly absorbed.",
      "Add the milk, sugar, and cinnamon stick, and bring back to a gentle simmer, stirring occasionally to prevent the rice from sticking to the bottom.",
      "Cook uncovered on low heat for 20-25 minutes, stirring often, until the rice is fully tender and the mixture has thickened to a creamy, pourable consistency - short-grain rice is what gives real Bulgarian rice pudding its characteristic creaminess, not long-grain rice.",
      "Remove the cinnamon stick, stir in the vanilla extract, and let cool to room temperature.",
      "Refrigerate for at least 2 hours - Bulgarian rice pudding is traditionally cooled and eaten cold rather than served warm, which is what gives it its familiar set texture.",
      "Dust with a little extra cinnamon before serving.",
    ],
    tags: ["dessert", "vegetarian", "quick"],
    bg: {
      title: "Ориз на мляко",
      description:
        "Обикновен български десерт от ориз, варен в мляко само с ориз, захар и канела, после охладен и сервиран студен, а не топъл - за разлика от повечето западни ризо-пудинги, оставянето му да изстине напълно преди ядене е това, което му дава познатата, носталгична текстура, а късозърнестият ориз е това, което го прави наистина кремообразен, а не рехав и супест.",
      steps: [
        "Изплакнете ориза и го съберете с водата в тенджера. Оставете да заври, после намалете огъня и гответе на слаб огън, покрит, 10 минути, докато водата се поеме почти напълно.",
        "Добавете млякото, захарта и канелената пръчка, и оставете отново да заври леко, като разбърквате от време на време, за да не залепне оризът за дъното.",
        "Гответе без капак на слаб огън 20-25 минути, като разбърквате често, докато оризът напълно омекне, а сместа се сгъсти до кремообразна, течаща консистенция - късозърнестият ориз е това, което дава на истинския български ориз на мляко характерната му кремообразност, не дългозърнест ориз.",
        "Извадете канелената пръчка, разбъркайте ваниловия екстракт, и оставете да изстине до стайна температура.",
        "Охладете в хладилника поне 2 часа - българският ориз на мляко традиционно се охлажда и яде студен, а не се сервира топъл, което е това, което му дава познатата стегната текстура.",
        "Поръсете с малко допълнителна канела преди сервиране.",
      ],
      ingredients: [
        "2/3 чаша късозърнест ориз",
        "2 чаши вода",
        "3 чаши мляко",
        "1/3 чаша захар",
        "1 канелена пръчка",
        "1 ч.л. екстракт от ванилия",
        "1/2 ч.л. канела, за поднасяне",
      ],
    },
  },
  {
    slug: "chushki-byurek",
    title: "Chushki Byurek",
    description:
      "Roasted, peeled bell peppers stuffed with a garlicky cheese-and-meat filling, then breaded and fried until crisp - roasting and peeling the peppers first, rather than frying them raw, is what makes them tender enough to fold around the filling without cracking.",
    imageEmoji: "🫑",
    cookTimeMinutes: 45,
    servings: 4,
    ingredients: [
      { text: "8 small red bell peppers", ingredient: "bell peppers", quantity: 8 },
      { text: "1/2 lb ground pork", ingredient: "ground pork", quantity: 0.5 },
      { text: "7 oz sirene (Bulgarian white brined cheese), crumbled", ingredient: "sirene", quantity: 7 },
      { text: "1 egg (for the filling)", ingredient: "eggs", quantity: 1 },
      { text: "2 cloves garlic, minced", ingredient: "garlic", quantity: 2 },
      { text: "2 tbsp parsley, chopped", ingredient: "parsley", quantity: 2 },
      { text: "1 cup flour", ingredient: "flour", quantity: 1 },
      { text: "2 eggs, beaten (for coating)", ingredient: "eggs", quantity: 2 },
      { text: "1 cup breadcrumbs", ingredient: "breadcrumbs", quantity: 1 },
      { text: "2 cups vegetable oil, for frying", ingredient: "vegetable oil", quantity: 2 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "Pepper to taste", ingredient: "pepper", quantity: null },
    ],
    steps: [
      "Preheat the oven to 400°F and roast the whole peppers for 15-20 minutes, until the skins are blistered and blackened in spots. Transfer to a bowl, cover, and let steam for 10 minutes.",
      "Peel off the skins, then carefully slit each pepper along one side and remove the seeds and core, keeping the pepper otherwise whole - roasting and peeling first is what makes the peppers tender enough to stuff and fold without splitting.",
      "Cook the ground pork in a pan until browned, breaking it up as it cooks, then let cool slightly.",
      "Mix the cooked pork with the crumbled sirene, 1 egg, garlic, parsley, salt, and pepper.",
      "Stuff each roasted pepper with the filling, then gently press closed around the opening.",
      "Set up a breading station: flour in one dish, the 2 beaten eggs in another, and breadcrumbs in a third.",
      "Dredge each stuffed pepper in flour, then egg, then breadcrumbs, pressing gently to coat evenly.",
      "Heat the oil in a large pan over medium heat and fry the peppers for 3-4 minutes per side, until deep golden and crisp.",
      "Drain on paper towels and serve hot.",
    ],
    tags: ["snack", "dinner"],
    bg: {
      title: "Чушки бюрек",
      description:
        "Печени, обелени червени чушки, пълнени с чеснов пълнеж от сирене и месо, после панирани и изпържени до хрупкаво - печенето и белeнето на чушките първо, вместо да се пържат сурови, е това, което ги прави достатъчно меки, за да се сгънат около пълнежа, без да се пукнат.",
      steps: [
        "Загрейте фурната на 200°C и изпечете целите чушки 15-20 минути, докато кожата им се напука и почернее на места. Прехвърлете в купа, покрийте и оставете да се задушат на пара 10 минути.",
        "Обелете кожата, после внимателно разрежете всяка чушка от едната страна и премахнете семките и сърцевината, като запазите чушката иначе цяла - печенето и белeнето първо е това, което прави чушките достатъчно меки, за да се пълнят и сгъват, без да се пукнат.",
        "Запържете свинската кайма в тиган до зачервяване, разчупвайки я, докато се готви, после оставете да изстине леко.",
        "Смесете сготвената кайма с натрошеното сирене, 1-то яйце, чесъна, магданоза, солта и пипера.",
        "Напълнете всяка печена чушка с пълнежа, после внимателно притиснете затворено около отвора.",
        "Подгответе станция за паниране: брашно в едно блюдо, 2-та разбити яйца в друго, и галета в трето.",
        "Обваляйте всяка пълнена чушка в брашно, после в яйце, после в галета, притискайки леко за равномерно покритие.",
        "Загрейте олиото в голям тиган на среден огън и пържете чушките по 3-4 минути от всяка страна, докато станат дълбоко златисти и хрупкави.",
        "Отцедете върху хартиени кърпи и сервирайте горещи.",
      ],
      ingredients: [
        "8 малки червени чушки",
        "225 г свинска кайма",
        "200 г сирене, натрошено",
        "1 яйце (за пълнежа)",
        "2 скилидки чесън, ситно нарязани",
        "2 с.л. магданоз, нарязан",
        "1 чаша брашно",
        "2 яйца, разбити (за панирането)",
        "1 чаша галета",
        "2 чаши олио за пържене",
        "Сол на вкус",
        "Черен пипер на вкус",
      ],
    },
  },
  {
    slug: "sach",
    title: "Sach",
    description:
      "Bulgaria's sizzling clay-plate dish - thin slices of pork and chicken seared with mushrooms, peppers, and onion, brought to the table still popping in the hot clay itself - preheating the clay plate thoroughly before adding anything, rather than treating it like a regular skillet, is what keeps the dish audibly sizzling all the way through the meal instead of going quiet and cool.",
    imageEmoji: "🥘",
    cookTimeMinutes: 40,
    servings: 4,
    ingredients: [
      { text: "1 lb pork shoulder, thinly sliced", ingredient: "pork shoulder", quantity: 1 },
      { text: "1 lb chicken breast, thinly sliced", ingredient: "chicken breast", quantity: 1 },
      { text: "1 lb mushrooms, sliced", ingredient: "mushroom", quantity: 1 },
      { text: "2 bell peppers, sliced", ingredient: "bell peppers", quantity: 2 },
      { text: "1 onion, sliced", ingredient: "onion", quantity: 1 },
      { text: "3 cloves garlic, minced", ingredient: "garlic", quantity: 3 },
      { text: "2 tbsp paprika", ingredient: "paprika", quantity: 2 },
      { text: "1 tsp cumin", ingredient: "cumin", quantity: 1 },
      { text: "3 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 3 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "Pepper to taste", ingredient: "pepper", quantity: null },
    ],
    steps: [
      "Season the sliced pork and chicken with the paprika, cumin, salt, and pepper, and let marinate for at least 20 minutes.",
      "If using a clay sach plate, preheat it thoroughly over low heat for 10 minutes before increasing to medium-high - a fully preheated plate is what keeps the dish sizzling audibly at the table, rather than starting hot and quickly going quiet.",
      "Add the oil to the hot plate (or a large skillet) and sear the pork and chicken for 5-7 minutes, turning occasionally, until browned on all sides.",
      "Add the onion and cook for 2 minutes, then add the mushrooms and peppers and cook for another 5-6 minutes, until the vegetables are softened.",
      "Stir in the garlic and cook for 1 minute more, until fragrant.",
      "If using a clay plate, transfer it directly to a heatproof stand at the table so it keeps sizzling while serving. Serve hot with bread and a simple yogurt-garlic dip or Shopska salad.",
    ],
    tags: ["dinner"],
    bg: {
      title: "Сач",
      description:
        "Съскащото българско ястие в глинена чиния - тънки резени свинско и пилешко, запържени с гъби, чушки и лук, донесени на масата все още цвърчащи в самата гореща глина - доброто предварително загряване на глинената чиния, преди да се добави каквото и да е, вместо да се третира като обикновен тиган, е това, което пази ястието да цвърчи чуто през цялото хранене, вместо да утихне и изстине.",
      steps: [
        "Подправете нарязаните свинско и пилешко с червения пипер, кимиона, солта и пипера, и оставете да мариноват поне 20 минути.",
        "Ако използвате глинена сач чиния, загрейте я добре на слаб огън 10 минути, преди да увеличите на среден-силен - напълно предварително загрятата чиния е това, което пази ястието да цвърчи чуто на масата, вместо да започне горещо и бързо да утихне.",
        "Добавете олиото в горещата чиния (или голям тиган) и запържете свинското и пилешкото 5-7 минути, обръщайки от време на време, докато се зачервят от всички страни.",
        "Добавете лука и гответе 2 минути, после добавете гъбите и чушките и гответе още 5-6 минути, докато зеленчуците омекнат.",
        "Разбъркайте чесъна и гответе още 1 минута, докато замирише.",
        "Ако използвате глинена чиния, прехвърлете я директно върху топлоустойчива стойка на масата, за да продължи да цвърчи, докато сервирате. Сервирайте горещо с хляб и лек дип от кисело мляко и чесън или шопска салата.",
      ],
      ingredients: [
        "450 г свинска плешка, нарязана на тънки резени",
        "450 г пилешки гърди, нарязани на тънки резени",
        "450 г гъби, нарязани",
        "2 чушки, нарязани",
        "1 лук, нарязан",
        "3 скилидки чесън, ситно нарязани",
        "2 с.л. червен пипер",
        "1 ч.л. кимион",
        "3 с.л. олио",
        "Сол на вкус",
        "Черен пипер на вкус",
      ],
    },
  },
  {
    slug: "tsatsa",
    title: "Tsatsa",
    description:
      "Bulgaria's Black Sea coast answer to fish and chips - whole small sprats, salted and lightly floured, then deep-fried heads-on until crisp - frying them whole, without gutting or beheading, is the authentic street-side method (they're small enough to eat bones and all), and pushing a skewer through several heads before frying keeps the delicate fish from sticking together in the hot oil.",
    imageEmoji: "🐟",
    cookTimeMinutes: 25,
    servings: 4,
    ingredients: [
      { text: "1.5 lb sprats", ingredient: "sprats", quantity: 1.5 },
      { text: "1 cup flour", ingredient: "flour", quantity: 1 },
      { text: "1 tbsp salt", ingredient: "salt", quantity: 1 },
      { text: "3 cups vegetable oil, for frying", ingredient: "vegetable oil", quantity: 3 },
      { text: "1 lemon, cut into wedges", ingredient: "lemon", quantity: 1 },
    ],
    steps: [
      "Rinse the sprats well and pat dry - unlike most fried fish, tsatsa is traditionally left whole, heads and all, since the fish are small enough to eat bones and all once fried crisp.",
      "Toss the sprats with the salt and let sit for 10 minutes.",
      "Thread 5-6 sprats at a time onto a skewer through the heads - this simple step is what keeps the small, delicate fish from sticking together in clumps once they hit the hot oil.",
      "Dredge the skewered sprats lightly in the flour, shaking off any excess.",
      "Heat the oil to 350°F in a deep pan and fry the sprats in batches for 3-4 minutes, until golden and crisp.",
      "Drain on paper towels, slide off the skewers, and serve immediately with lemon wedges - traditionally alongside fries and a cold beer.",
    ],
    tags: ["snack", "lunch"],
    bg: {
      title: "Цаца",
      description:
        "Българският черноморски отговор на пържена риба с картофи - цели малки цаци, посолени и леко подбрашнени, после дълбоко изпържени с главите до хрупкаво - пърженето им цели, без изкормяне или обезглавяване, е автентичният крайморски метод (достатъчно малки са, за да се ядат с костите), а прекарването на шиш през няколко глави преди пържене пази нежната риба да не залепне заедно в горещото олио.",
      steps: [
        "Изплакнете добре цацата и подсушете - за разлика от повечето пържени риби, цацата традиционно се оставя цяла, с главите, тъй като рибките са достатъчно малки, за да се изядат с костите, след като се изпържат хрупкави.",
        "Разбъркайте цацата със солта и оставете за 10 минути.",
        "Набодете по 5-6 цаци наведнъж на шиш през главите - тази проста стъпка е това, което пази малката, нежна риба да не залепне на бучки, щом попадне в горещото олио.",
        "Обваляйте набодената на шиш цаца леко в брашното, изтръсквайки излишъка.",
        "Загрейте олиото до 175°C в дълбок тиган и пържете цацата на порции 3-4 минути, докато стане златиста и хрупкава.",
        "Отцедете върху хартиени кърпи, свалете от шишовете, и сервирайте веднага с резени лимон - традиционно заедно с пържени картофи и студена бира.",
      ],
      ingredients: [
        "700 г цаца",
        "1 чаша брашно",
        "1 с.л. сол",
        "3 чаши олио за пържене",
        "1 лимон, нарязан на резени",
      ],
    },
  },
  {
    slug: "kachamak",
    title: "Kachamak",
    description:
      "A Rhodope Mountain cornmeal porridge, cooked down thick and dense until it holds a mound shape, then topped with melted butter and crumbled sirene - stirring in the cornmeal in stages and cooking it much longer than a quick polenta is what gives real kachamak its dense, sliceable texture instead of a loose, soupy mush.",
    imageEmoji: "🌽",
    cookTimeMinutes: 40,
    servings: 4,
    ingredients: [
      { text: "2 cups cornmeal", ingredient: "cornmeal", quantity: 2 },
      { text: "4 cups water", ingredient: "water", quantity: 4 },
      { text: "1 tsp salt", ingredient: "salt", quantity: 1 },
      { text: "5 tbsp butter", ingredient: "butter", quantity: 5 },
      { text: "7 oz sirene (Bulgarian white brined cheese), crumbled", ingredient: "sirene", quantity: 7 },
    ],
    steps: [
      "Bring the water and salt to a boil in a heavy pot.",
      "Reduce the heat to low and sprinkle in the cornmeal a little at a time, whisking constantly to prevent lumps.",
      "Once all the cornmeal is added, switch to a wooden spoon and cook, stirring frequently, for 25-30 minutes, until the mixture pulls away from the sides of the pot and holds together in a dense mass - this much longer cooking time, well beyond a quick polenta, is what gives kachamak its characteristic dense, sliceable texture.",
      "Mash and stir vigorously for the last few minutes to work out any remaining lumps.",
      "Turn the kachamak out onto a plate, mounding it into a dome shape.",
      "Melt the butter in a small pan until it just starts to foam, then pour it over the top of the mound.",
      "Top generously with the crumbled sirene and serve hot, scooping from the mound at the table.",
    ],
    tags: ["dinner", "vegetarian"],
    bg: {
      title: "Качамак",
      description:
        "Родопска царевична каша, сготвена гъсто и плътно, докато задържи форма на купчина, после покрита с разтопено масло и натрошено сирене - забъркването на царевичното брашно на етапи и готвенето му много по-дълго от бърза поленка е това, което дава на истинския качамак неговата плътна, режеща се текстура, вместо рехава, супеста каша.",
      steps: [
        "Оставете водата и солта да заврат в тежка тенджера.",
        "Намалете огъня на слаб и поръсвайте царевичното брашно малко по малко, разбърквайки постоянно, за да не се образуват бучки.",
        "След като цялото царевично брашно е добавено, преминете на дървена лъжица и гответе, разбърквайки често, 25-30 минути, докато сместа се отдели от стените на тенджерата и се задържи заедно в плътна маса - това много по-дълго време на готвене, далеч отвъд бърза поленка, е това, което дава на качамака характерната му плътна, режеща се текстура.",
        "Смачквайте и разбърквайте енергично последните няколко минути, за да изгладите останалите бучки.",
        "Обърнете качамака върху чиния, оформяйки го на купчина.",
        "Разтопете маслото в малък тиган, докато точно започне да се запени, после го излейте върху купчината.",
        "Покрийте щедро с натрошеното сирене и сервирайте горещ, загребвайки от купчината на масата.",
      ],
      ingredients: [
        "2 чаши царевично брашно",
        "4 чаши вода",
        "1 ч.л. сол",
        "5 с.л. масло",
        "200 г сирене, натрошено",
      ],
    },
  },
  {
    slug: "gabena-yahnia",
    title: "Gabena Yahnia (Bulgarian Mushroom Stew)",
    description:
      "A simple, hearty Bulgarian mushroom stew of mushrooms, onion, carrot, and pepper simmered together and lightly thickened with a flour slurry - sautéing the onion and carrot first before adding the mushrooms, rather than dumping everything in at once, is what builds a deeper base flavor instead of a flat, watery stew.",
    imageEmoji: "🍄",
    cookTimeMinutes: 45,
    servings: 4,
    ingredients: [
      { text: "1.5 lb mushrooms, sliced", ingredient: "mushroom", quantity: 1.5 },
      { text: "1 onion, finely chopped", ingredient: "onion", quantity: 1 },
      { text: "1 carrot, grated", ingredient: "carrot", quantity: 1 },
      { text: "1 red bell pepper, diced", ingredient: "red pepper", quantity: 1 },
      { text: "3 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 3 },
      { text: "1 tbsp flour", ingredient: "flour", quantity: 1 },
      { text: "1 cup water", ingredient: "water", quantity: 1 },
      { text: "1 tsp paprika", ingredient: "paprika", quantity: 1 },
      { text: "2 tbsp dill, chopped", ingredient: "dill", quantity: 2 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "Pepper to taste", ingredient: "pepper", quantity: null },
    ],
    steps: [
      "Heat the oil in a large pot and sauté the onion and grated carrot over medium heat for 5-6 minutes, until softened - building this base first, before the mushrooms go in, is what gives the stew a deeper flavor instead of tasting flat and watery.",
      "Add the diced red pepper and cook for 2-3 minutes more.",
      "Add the sliced mushrooms and paprika, and cook, stirring occasionally, for 10-12 minutes, until the mushrooms release their liquid and it mostly cooks off.",
      "Whisk the flour into the 1 cup of water until smooth, then pour into the pot, stirring constantly.",
      "Simmer for 8-10 minutes, until the stew has thickened slightly and the mushrooms are fully tender.",
      "Season with salt and pepper, stir in the dill, and serve hot with bread.",
    ],
    tags: ["dinner", "vegetarian", "vegan"],
    bg: {
      title: "Гъбена яхния",
      description:
        "Проста, засищаща българска яхния от гъби, лук, морков и чушка, задушени заедно и леко сгъстени с разтвор от брашно - запържването на лука и моркова първо, преди да се добавят гъбите, вместо да се хвърли всичко наведнъж, е това, което изгражда по-дълбок основен вкус, вместо плоска, водниста яхния.",
      steps: [
        "Загрейте олиото в голяма тенджера и запържете лука и настъргания морков на среден огън 5-6 минути, докато омекнат - изграждането на тази основа първо, преди да влязат гъбите, е това, което дава на яхнията по-дълбок вкус, вместо да е плоска и водниста.",
        "Добавете нарязаната на кубчета червена чушка и гответе още 2-3 минути.",
        "Добавете нарязаните гъби и червения пипер, и гответе, разбърквайки от време на време, 10-12 минути, докато гъбите пуснат течността си и тя почти се изпари.",
        "Разбъркайте брашното в 1-та чаша вода до гладкост, после изсипете в тенджерата, като бъркате постоянно.",
        "Гответе на слаб огън 8-10 минути, докато яхнията леко се сгъсти, а гъбите напълно омекнат.",
        "Подправете със сол и пипер, разбъркайте копъра, и сервирайте горещо с хляб.",
      ],
      ingredients: [
        "700 г гъби, нарязани",
        "1 лук, ситно нарязан",
        "1 морков, настърган",
        "1 червена чушка, нарязана на кубчета",
        "3 с.л. олио",
        "1 с.л. брашно",
        "1 чаша вода",
        "1 ч.л. червен пипер",
        "2 с.л. копър, нарязан",
        "Сол на вкус",
        "Черен пипер на вкус",
      ],
    },
  },
  {
    slug: "rozovo-sladko",
    title: "Rozovo Sladko (Bulgarian Rose Petal Jam)",
    description:
      "A delicate, fragrant preserve made from fresh Rosa damascena petals from Bulgaria's famous Rose Valley, simmered with sugar and a little lemon juice until thin and syrupy - using only the fragrant petals, with the bitter white base at the petal's stem trimmed away, is what keeps the jam sweetly floral instead of bitter.",
    imageEmoji: "🌹",
    cookTimeMinutes: 60,
    servings: 8,
    ingredients: [
      { text: "4 cups fresh rose petals (Rosa damascena)", ingredient: "rose petals", quantity: 4 },
      { text: "3 cups sugar", ingredient: "sugar", quantity: 3 },
      { text: "1 cup water", ingredient: "water", quantity: 1 },
      { text: "2 tbsp lemon juice", ingredient: "lemon juice", quantity: 2 },
    ],
    steps: [
      "Trim off the small pale, bitter base of each rose petal where it attaches to the flower, keeping only the fragrant colored part - skipping this trim is what makes rose jam taste bitter instead of purely floral.",
      "Rinse the petals gently and pat dry. Toss them with 1 cup of the sugar in a bowl, gently bruising them with your hands, and let sit for 2-3 hours, until they release their fragrant liquid and soften.",
      "Combine the remaining sugar and water in a pot and bring to a boil, stirring until the sugar dissolves, to make a syrup.",
      "Add the softened rose petals and their liquid to the syrup and bring back to a gentle boil.",
      "Simmer on low heat for 30-35 minutes, skimming off any foam, until the syrup has thickened slightly and turned a deep pink, and the petals look translucent.",
      "Stir in the lemon juice during the last 5 minutes - the acidity is what keeps the jam's color bright and helps it set properly.",
      "Ladle into sterilized jars while hot and seal. Let cool completely before storing; refrigerate after opening.",
    ],
    tags: ["snack"],
    bg: {
      title: "Розово сладко",
      description:
        "Деликатно, ароматно сладко от свежи листенца маслодайна роза (Rosa damascena) от прочутата българска Розова долина, варено със захар и малко лимонов сок, докато стане рехаво и сиропено - използването само на ароматната част на листенцата, с изрязана горчива бяла основа при дръжката, е това, което пази сладкото сладко-цветно, а не горчиво.",
      steps: [
        "Изрежете малката бледа, горчива основа на всяко листенце роза, където се свързва с цветето, като запазите само ароматната цветна част - пропускането на това изрязване е това, което прави розовото сладко горчиво, вместо чисто цветно.",
        "Изплакнете листенцата внимателно и подсушете. Разбъркайте ги с 1 чаша от захарта в купа, леко ги мачкайки с ръце, и оставете за 2-3 часа, докато пуснат ароматната си течност и омекнат.",
        "Съберете останалата захар и водата в тенджера и оставете да заврат, разбърквайки, докато захарта се разтвори, за да направите сироп.",
        "Добавете омекналите листенца роза и течността им към сиропа и оставете отново да заври леко.",
        "Гответе на слаб огън 30-35 минути, обирайки евентуалната пяна, докато сиропът леко се сгъсти и стане дълбоко розов, а листенцата изглеждат прозрачни.",
        "Разбъркайте лимоновия сок през последните 5 минути - киселинността е това, което пази цвета на сладкото ярък и помага да се стегне правилно.",
        "Разпределете в стерилизирани буркани, докато е горещо, и затворете. Оставете да изстине напълно преди съхранение; след отваряне съхранявайте в хладилник.",
      ],
      ingredients: [
        "4 чаши свежи листенца от маслодайна роза",
        "3 чаши захар",
        "1 чаша вода",
        "2 с.л. лимонов сок",
      ],
    },
  },
  {
    slug: "leshta-yahnia",
    title: "Leshta Yahnia (Bulgarian Lentil Stew)",
    description:
      "A hearty Bulgarian brown lentil stew simmered gently with tomato, carrot, and chubritsa (Bulgarian savory) until thick and stew-like rather than soupy - keeping it at a bare simmer instead of a hard boil is what keeps the lentils intact and creamy rather than breaking down into a thin, mushy puree.",
    imageEmoji: "🍲",
    cookTimeMinutes: 45,
    servings: 4,
    ingredients: [
      { text: "2 cups brown lentils", ingredient: "lentils", quantity: 2 },
      { text: "1 onion, finely chopped", ingredient: "onion", quantity: 1 },
      { text: "1 carrot, grated", ingredient: "carrot", quantity: 1 },
      { text: "2 cloves garlic, minced", ingredient: "garlic", quantity: 2 },
      { text: "2 tomatoes, grated", ingredient: "tomato", quantity: 2 },
      { text: "3 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 3 },
      { text: "1 tsp paprika", ingredient: "paprika", quantity: 1 },
      { text: "1 tsp chubritsa", ingredient: "chubritsa", quantity: 1 },
      { text: "1 bay leaf", ingredient: "bay leaf", quantity: 1 },
      { text: "2 tbsp parsley, chopped", ingredient: "parsley", quantity: 2 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "Pepper to taste", ingredient: "pepper", quantity: null },
    ],
    steps: [
      "Rinse the lentils well and set aside.",
      "Heat the oil in a large pot and sauté the onion and grated carrot for 5-6 minutes, until softened.",
      "Stir in the garlic and paprika and cook for 1 minute more, until fragrant.",
      "Add the grated tomatoes, lentils, bay leaf, and enough water to cover everything by about an inch.",
      "Bring to a boil, then reduce the heat to a bare simmer, cover partially, and cook for 30-35 minutes, stirring occasionally, until the lentils are tender - keeping this at a gentle simmer rather than a hard boil is what keeps the lentils intact and creamy instead of breaking down into mush.",
      "Stir in the chubritsa during the last 5 minutes of cooking.",
      "Discard the bay leaf, season with salt and pepper, and stir in the parsley just before serving with bread.",
    ],
    tags: ["dinner", "vegetarian", "vegan"],
    bg: {
      title: "Леща яхния",
      description:
        "Засищаща българска яхния от кафява леща, задушена внимателно с домат, морков и чубрица, докато стане гъста и яхниеподобна, а не супена - поддържането ѝ на едва забележимо къкрене, вместо силно кипене, е това, което пази лещата цяла и кремообразна, вместо да се разпадне в рехаво пюре.",
      steps: [
        "Изплакнете лещата добре и оставете настрана.",
        "Загрейте олиото в голяма тенджера и запържете лука и настъргания морков 5-6 минути, докато омекнат.",
        "Разбъркайте чесъна и червения пипер и гответе още 1 минута, докато замирише.",
        "Добавете настърганите домати, лещата, дафиновия лист и достатъчно вода, за да покрие всичко с около 2-3 см.",
        "Оставете да заври, после намалете огъня до едва забележимо къкрене, покрийте частично, и гответе 30-35 минути, като разбърквате от време на време, докато лещата омекне - поддържането на леко къкрене, вместо силно кипене, е това, което пази лещата цяла и кремообразна, вместо да се разпадне в каша.",
        "Разбъркайте чубрицата през последните 5 минути от готвенето.",
        "Изхвърлете дафиновия лист, подправете със сол и пипер, и разбъркайте магданоза точно преди сервиране с хляб.",
      ],
      ingredients: [
        "400 г кафява леща",
        "1 лук, ситно нарязан",
        "1 морков, настърган",
        "2 скилидки чесън, ситно нарязани",
        "2 домата, настъргани",
        "3 с.л. олио",
        "1 ч.л. червен пипер",
        "1 ч.л. чубрица",
        "1 дафинов лист",
        "2 с.л. магданоз, нарязан",
        "Сол на вкус",
        "Черен пипер на вкус",
      ],
    },
  },
  {
    slug: "pacha",
    title: "Pacha",
    description:
      "A traditional Bulgarian pork trotter and ear soup, simmered for hours until the collagen-rich cuts turn falling-apart tender and thicken the broth into a rich, gelatinous soup - simmering this long and gently, never at a hard boil, is what fully renders the collagen into the broth instead of leaving it tough and rubbery; served warm, it stays a soup, but chilled, it naturally sets into a savory jelly.",
    imageEmoji: "🥣",
    cookTimeMinutes: 180,
    servings: 6,
    ingredients: [
      { text: "2 lb pig's feet, cleaned and split", ingredient: "pig's feet", quantity: 2 },
      { text: "1 lb pig's ears, cleaned", ingredient: "pig's ears", quantity: 1 },
      { text: "1 onion, halved", ingredient: "onion", quantity: 1 },
      { text: "2 bay leaves", ingredient: "bay leaves", quantity: 2 },
      { text: "1 tsp black peppercorns", ingredient: "black peppercorns", quantity: 1 },
      { text: "8 cups water", ingredient: "water", quantity: 8 },
      { text: "4 cloves garlic, minced", ingredient: "garlic", quantity: 4 },
      { text: "2 tbsp vinegar", ingredient: "vinegar", quantity: 2 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
    ],
    steps: [
      "Rinse the pig's feet and ears thoroughly, then place in a large pot with the onion, bay leaves, and peppercorns. Cover with the water.",
      "Bring to a boil, skimming off any foam that rises to the surface, then reduce the heat to a bare simmer.",
      "Cover partially and simmer very gently for 3-4 hours, never at a hard boil, until the meat is falling off the bone and the broth has thickened and turned rich and milky-white from the rendered collagen - a hard boil here is what leaves the connective tissue tough instead of fully breaking down into the broth.",
      "Remove the feet and ears, let cool slightly, then pick the meat off the bones and cut into small pieces, discarding the bones and any cartilage you don't want. Discard the onion and bay leaves.",
      "Return the meat to the pot, season with salt, and stir in half the minced garlic.",
      "Serve hot in bowls, with the vinegar, remaining raw garlic, and extra black pepper stirred in at the table to taste - traditionally, pacha is eaten warm as a soup, since it firms into a savory jelly once it cools.",
    ],
    tags: ["dinner"],
    bg: {
      title: "Пача",
      description:
        "Традиционна българска супа от свински крачета и уши, къкрила часове наред, докато богатите на колаген парчета станат толкова крехки, че се разпадат, и сгъстят бульона в богата, желатинова супа - дългото и внимателно къкрене, никога на силно кипене, е това, което напълно разгражда колагена в бульона, вместо да остане жилав и гумен; сервирана топла, тя остава супа, но охладена, естествено се стяга в солено желе.",
      steps: [
        "Изплакнете добре свинските крачета и уши, после ги поставете в голяма тенджера с лука, дафиновите листа и черния пипер на зърна. Залейте с водата.",
        "Оставете да заври, обирайки евентуалната пяна, която се вдига на повърхността, после намалете огъня до едва забележимо къкрене.",
        "Покрийте частично и къкрете много внимателно 3-4 часа, никога на силно кипене, докато месото се отдели от костта, а бульонът се сгъсти и стане богат и млечнобял от разградения колаген - силното кипене тук е това, което оставя съединителната тъкан жилава, вместо напълно да се разгради в бульона.",
        "Извадете крачетата и ушите, оставете да изстинат леко, после откъснете месото от костите и го нарежете на малки парчета, изхвърляйки костите и всеки хрущял, който не искате. Изхвърлете лука и дафиновите листа.",
        "Върнете месото в тенджерата, подправете със сол, и разбъркайте половината от ситно нарязания чесън.",
        "Сервирайте горещо в купички, с оцета, останалия суров чесън и допълнителен черен пипер, разбъркани на масата на вкус - традиционно пачата се яде топла като супа, тъй като се стяга в солено желе, след като изстине.",
      ],
      ingredients: [
        "900 г свински крачета, почистени и разцепени",
        "450 г свински уши, почистени",
        "1 лук, разрязан наполовина",
        "2 дафинови листа",
        "1 ч.л. черен пипер на зърна",
        "8 чаши вода",
        "4 скилидки чесън, ситно нарязани",
        "2 с.л. оцет",
        "Сол на вкус",
      ],
    },
  },
];

async function main() {
  for (const recipe of newRecipes) {
    const created = await prisma.recipe.create({
      data: {
        slug: recipe.slug,
        title: recipe.title,
        description: recipe.description,
        imageEmoji: recipe.imageEmoji,
        cookTimeMinutes: recipe.cookTimeMinutes,
        servings: recipe.servings,
        steps: JSON.stringify(recipe.steps),
        tags: JSON.stringify(recipe.tags),
      },
    });

    for (let i = 0; i < recipe.ingredients.length; i++) {
      const { text, ingredient, quantity } = recipe.ingredients[i];
      const ingredientRow = await prisma.ingredient.upsert({
        where: { name: ingredient },
        update: {},
        create: { name: ingredient },
      });
      await prisma.recipeIngredient.create({
        data: {
          recipeId: created.id,
          ingredientId: ingredientRow.id,
          displayText: text,
          quantity,
          position: i,
        },
      });
    }
    console.log(`Created ${recipe.slug}`);
  }
  console.log(`Created ${newRecipes.length} recipes total.`);

  // runTranslations disconnects prisma when done, so it must run last.
  await runTranslations(newRecipes.map((r) => ({ slug: r.slug, ...r.bg })));
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
