import { prisma, runTranslations } from "./translate-lib.mjs";

// 10 internationally lesser-known recipes, spanning Jamaica, Reunion
// Island, Nepal, Azerbaijan, Brazil, Pakistan, Denmark, Austria,
// Malaysia/Indonesia, and Morocco. Each web-researched for authentic
// technique before writing, per standing instructions. Nutrition
// estimates are set directly here (caloriesPerServing/proteinG/carbsG/
// fatG), per standing instruction to never leave new recipes without
// nutrition.
const newRecipes = [
  {
    slug: "ackee-and-saltfish",
    title: "Ackee and Saltfish",
    description:
      "Jamaica's national dish - salt cod soaked overnight to pull out the cure, then folded gently with ackee at the very end so the fruit's delicate, buttery flesh stays intact instead of turning to mush.",
    imageEmoji: "🐟",
    cookTimeMinutes: 45,
    servings: 4,
    caloriesPerServing: 280,
    proteinG: 22,
    carbsG: 8,
    fatG: 18,
    ingredients: [
      { text: "1 lb salted cod, soaked overnight", ingredient: "salted cod", quantity: 1 },
      { text: "1 can (19 oz) ackee, drained", ingredient: "ackee", quantity: 1 },
      { text: "3 tbsp butter or oil", ingredient: "butter", quantity: 3 },
      { text: "1 onion, sliced", ingredient: "onion", quantity: 1 },
      { text: "1 bell pepper, sliced", ingredient: "bell pepper", quantity: 1 },
      { text: "1-2 scotch bonnet peppers, seeded and minced", ingredient: "scotch bonnet pepper", quantity: 1 },
      { text: "2 tomatoes, chopped", ingredient: "tomato", quantity: 2 },
      { text: "3 scallions, sliced", ingredient: "scallion", quantity: 3 },
      { text: "2 sprigs fresh thyme", ingredient: "thyme", quantity: 2 },
      { text: "Black pepper, to taste", ingredient: "black pepper", quantity: null },
    ],
    steps: [
      "Soak the salted cod in cold water overnight (or at least 8 hours), changing the water two or three times, to draw out most of the salt.",
      "Drain, cover with fresh water, and simmer gently for 20 minutes until tender, then drain, remove any skin and bones, and flake the flesh.",
      "Melt the butter in a large skillet and cook the onion, bell pepper, scotch bonnet, and thyme for about 3 minutes until softened.",
      "Add the tomatoes and flaked fish and cook, stirring, for 8-10 minutes until the tomatoes break down.",
      "Add the drained ackee and gently fold it in - don't stir vigorously, since ackee is delicate and will break into mush if handled roughly.",
      "Cook just until heated through, a couple of minutes, then stir in the scallions and season with black pepper.",
      "Serve hot with fried dumplings, breadfruit, or boiled green bananas.",
    ],
    tags: ["breakfast", "dinner"],
    bg: {
      title: "Аки и осолена риба",
      description: "Националното ястие на Ямайка - осолена треска, накисната цяла нощ, за да се извади солта, после внимателно смесена с аки в самия край, за да остане нежната, маслена плодова каша цяла, а не да се разпадне.",
      steps: [
        "Накиснете осолената треска в студена вода цяла нощ (или поне 8 часа), сменяйки водата два-три пъти, за да извадите по-голямата част от солта.",
        "Отцедете, залейте с прясна вода и къкрете леко 20 минути, докато стане мека, после отцедете, отстранете кожата и костите и разкъсайте месото на люспи.",
        "Разтопете маслото в голям тиган и гответе лука, чушката, скоч бонета и мащерката около 3 минути, докато омекнат.",
        "Добавете доматите и разкъсаната риба и гответе, разбърквайки, 8-10 минути, докато доматите се разпаднат.",
        "Добавете отцеденото аки и го вмесете внимателно - не разбърквайте енергично, тъй като аки е нежно и лесно се разпада на каша при грубо боравене.",
        "Гответе само докато се затопли, няколко минути, после разбъркайте пролетния лук и подправете с черен пипер.",
        "Сервирайте горещо с пържени кнедли, хлебен плод или варени зелени банани.",
      ],
      ingredients: [
        "450г осолена треска, накисната цяла нощ",
        "1 консерва (540г) аки, отцедено",
        "3 с.л. масло или олио",
        "1 лук, нарязан на резени",
        "1 чушка, нарязана на резени",
        "1-2 люти чушки скоч бонет, без семки, нарязани ситно",
        "2 домата, нарязани",
        "3 стръка пролетен лук, нарязани",
        "2 клонки прясна мащерка",
        "Черен пипер на вкус",
      ],
    },
  },
  {
    slug: "rougail-saucisse",
    title: "Rougail Saucisse",
    description:
      "Reunion Island's Creole sausage stew - the sausages are boiled first to purge excess fat and salt, then browned and simmered in a garlic-ginger-tomato base until the sauce turns rich and glossy.",
    imageEmoji: "🌭",
    cookTimeMinutes: 50,
    servings: 4,
    caloriesPerServing: 420,
    proteinG: 18,
    carbsG: 14,
    fatG: 32,
    ingredients: [
      { text: "1.5 lb smoked pork sausages, pricked all over", ingredient: "pork sausage", quantity: 1.5 },
      { text: "2 tbsp oil", ingredient: "vegetable oil", quantity: 2 },
      { text: "1 large onion, chopped", ingredient: "onion", quantity: 1 },
      { text: "4 garlic cloves, minced", ingredient: "garlic", quantity: 4 },
      { text: "1 tbsp grated fresh ginger", ingredient: "ginger", quantity: 1 },
      { text: "2 tomatoes, chopped (or 1 cup crushed tomatoes)", ingredient: "tomato", quantity: 2 },
      { text: "1-2 red chilies, crushed", ingredient: "red chili", quantity: 1 },
      { text: "1 tsp dried thyme", ingredient: "thyme", quantity: 1 },
      { text: "Salt, to taste", ingredient: "salt", quantity: null },
    ],
    steps: [
      "Prick the sausages all over with the tip of a knife, then boil them in water for about 15-20 minutes to purge excess fat and salt - this step is what keeps the finished stew from tasting greasy.",
      "Drain the sausages, let cool slightly, and slice into thick rounds.",
      "Heat the oil in a large pot and brown the sausage pieces on all sides, then remove and set aside.",
      "In the same pot, cook the onion, garlic, and ginger until soft and fragrant, letting the onion turn sweet and deeply golden rather than just translucent.",
      "Add the tomatoes, crushed chilies, and thyme, and cook down until the sauce thickens and turns a rich red.",
      "Return the sausages to the pot, season with salt, and simmer uncovered for 20 minutes so the sauce reduces further and clings to the sausage.",
      "Serve hot with steamed white rice and lentils or beans on the side.",
    ],
    tags: ["dinner"],
    bg: {
      title: "Ружай със наденица",
      description: "Креолско яхния с наденица от остров Реюнион - наденицата се вари първо, за да се отцедят излишната мазнина и сол, после се запържва и къкри в основа от чесън, джинджифил и домати, докато сосът стане богат и лъскав.",
      steps: [
        "Набодете наденицата навсякъде с върха на нож, после я варете във вода около 15-20 минути, за да се отцедят излишната мазнина и сол - тази стъпка пази готовата яхния да не стане мазна.",
        "Отцедете наденицата, оставете да поизстине леко и нарежете на дебели резени.",
        "Загрейте олиото в голяма тенджера и запържете парчетата наденица от всички страни, после ги извадете настрана.",
        "В същата тенджера гответе лука, чесъна и джинджифила, докато омекнат и станат ароматни, оставяйки лука да стане сладък и наситено златист, а не просто прозрачен.",
        "Добавете доматите, натрошените люти чушки и мащерката и гответе, докато сосът се сгъсти и стане наситено червен.",
        "Върнете наденицата в тенджерата, подправете със сол и къкрете без капак 20 минути, за да се редуцира сосът още повече и да полепне по наденицата.",
        "Сервирайте горещо с варен бял ориз и леща или боб отстрани.",
      ],
      ingredients: [
        "680г пушени свински наденици, набодени навсякъде",
        "2 с.л. олио",
        "1 голям лук, нарязан",
        "4 скилидки чесън, смачкани",
        "1 с.л. настърган пресен джинджифил",
        "2 домата, нарязани (или 1 чаша пасирани домати)",
        "1-2 люти червени чушки, натрошени",
        "1 ч.л. сушена мащерка",
        "Сол на вкус",
      ],
    },
  },
  {
    slug: "kwati",
    title: "Kwati",
    description:
      "Nepal's nine-bean soup, traditionally eaten at the Janai Purnima festival - the beans are sprouted for a couple of days before cooking, which is what gives the soup its distinctive earthy sweetness and digestibility.",
    imageEmoji: "🍲",
    cookTimeMinutes: 60,
    servings: 6,
    caloriesPerServing: 240,
    proteinG: 14,
    carbsG: 38,
    fatG: 4,
    ingredients: [
      { text: "2 1/4 cups mixed dried beans (black gram, mung, soybean, chickpea, field pea, black-eyed pea, garden pea, brown lentil, kidney bean)", ingredient: "mixed beans", quantity: 2.25 },
      { text: "2 tbsp ghee or mustard oil", ingredient: "ghee", quantity: 2 },
      { text: "1/2 tsp fenugreek seeds", ingredient: "fenugreek seeds", quantity: 0.5 },
      { text: "1 onion, chopped", ingredient: "onion", quantity: 1 },
      { text: "1 tsp cumin powder", ingredient: "cumin powder", quantity: 1 },
      { text: "1/2 tsp turmeric", ingredient: "turmeric", quantity: 0.5 },
      { text: "1 tsp coriander powder", ingredient: "coriander powder", quantity: 1 },
      { text: "1-2 green chilies, chopped", ingredient: "green chili", quantity: 1 },
      { text: "Salt, to taste", ingredient: "salt", quantity: null },
      { text: "Fresh cilantro, for garnish", ingredient: "cilantro", quantity: null },
    ],
    steps: [
      "Wash the mixed beans and soak them in water overnight.",
      "Drain, then wrap the beans in a damp cloth and let them sprout in a warm spot for 2-3 days, rinsing once a day, until each bean shows a small tail about 1/2 inch long - this sprouting step is what gives kwati its name and its characteristic texture.",
      "Heat the ghee or mustard oil in a heavy pot and add the fenugreek seeds, letting them darken slightly until fragrant.",
      "Add the chopped onion and cook until golden, about 5 minutes.",
      "Add the sprouted beans along with the cumin, turmeric, coriander, and green chilies, and fry for 5 minutes so the beans get coated in the spices.",
      "Add enough water to cover generously, bring to a boil, then reduce heat and simmer for 40-45 minutes until the beans are tender (a pressure cooker cuts this to about 20 minutes).",
      "Season with salt and garnish with fresh cilantro before serving.",
    ],
    tags: ["dinner", "vegetarian", "vegan"],
    bg: {
      title: "Кюати",
      description: "Непалска супа от девет вида боб, традиционно ядена на фестивала Джанай Пурнима - бобът се прораства два-три дни преди готвене, което придава на супата характерната земна сладост и лесна смилаемост.",
      steps: [
        "Измийте смесения боб и го накиснете във вода цяла нощ.",
        "Отцедете, после увийте боба във влажна кърпа и оставете да проникне на топло място 2-3 дни, изплаквайки веднъж дневно, докато всяко зърно покаже малка опашка около 1.25 см - тази стъпка на проникване дава на кюати името и характерната му текстура.",
        "Загрейте гхи или горчично олио в тежка тенджера и добавете семената от сминдух, оставяйки ги да потъмнеят леко, докато замиришат.",
        "Добавете нарязания лук и гответе, докато стане златист, около 5 минути.",
        "Добавете проникналия боб заедно с кимиона, куркумата, кориандъра и люти чушки и запържете 5 минути, за да се покрие бобът с подправките.",
        "Добавете достатъчно вода да покрие обилно, доведете до кипене, после намалете котлона и къкрете 40-45 минути, докато бобът омекне (тенджера под налягане съкращава това до около 20 минути).",
        "Подправете със сол и гарнирайте с прясна кинза преди сервиране.",
      ],
      ingredients: [
        "2 1/4 чаши смесен сух боб (черен грам, мунг, соя, нахут, полски грах, боб с черно око, градински грах, кафява леща, червен боб)",
        "2 с.л. гхи или горчично олио",
        "1/2 ч.л. семена от сминдух",
        "1 лук, нарязан",
        "1 ч.л. кимион на прах",
        "1/2 ч.л. куркума",
        "1 ч.л. кориандър на прах",
        "1-2 зелени люти чушки, нарязани",
        "Сол на вкус",
        "Прясна кинза, за гарнитура",
      ],
    },
  },
  {
    slug: "piti",
    title: "Piti",
    description:
      "Azerbaijan's lamb and chickpea soup, traditionally cooked and served in individual clay pots - each portion simmers slowly on its own, which is what gives piti its rich, concentrated broth.",
    imageEmoji: "🍖",
    cookTimeMinutes: 150,
    servings: 4,
    caloriesPerServing: 460,
    proteinG: 32,
    carbsG: 28,
    fatG: 24,
    ingredients: [
      { text: "1.5 lb lamb shoulder or lamb on the bone, cut into chunks", ingredient: "lamb shoulder", quantity: 1.5 },
      { text: "1 cup dried chickpeas, soaked overnight", ingredient: "chickpeas", quantity: 1 },
      { text: "2 onions, chopped", ingredient: "onion", quantity: 2 },
      { text: "2 potatoes, cubed", ingredient: "potato", quantity: 2 },
      { text: "2 tomatoes, chopped (or 2 tbsp tomato paste)", ingredient: "tomato", quantity: 2 },
      { text: "4-5 dried plums (prunes), or 1 quince, cubed", ingredient: "dried plums", quantity: 5 },
      { text: "1 tsp saffron threads, steeped in 2 tbsp hot water", ingredient: "saffron", quantity: 1 },
      { text: "Salt and black pepper, to taste", ingredient: "salt", quantity: null },
    ],
    steps: [
      "Soak the dried chickpeas overnight in plenty of water.",
      "In a deep pot (or individual clay pots if you have them), combine the lamb, drained chickpeas, and one chopped onion, cover with water, bring to a boil, and skim off any foam.",
      "Simmer over low heat for about 1 hour until the chickpeas begin to soften.",
      "Add the potatoes, remaining onion, tomatoes, and dried plums, and continue simmering for another hour, until the lamb is fork-tender and the broth has reduced and concentrated - the dried plums are what give piti its distinctive light sourness, so don't skip them.",
      "Stir in the saffron water in the last 10 minutes for color and aroma, and season with salt and pepper.",
      "If using individual pots, ladle the soup into bowls or pots and serve with flatbread, traditionally mashing some of the meat and chickpeas into the broth with a spoon before eating.",
    ],
    tags: ["dinner"],
    bg: {
      title: "Пити",
      description: "Азербайджанска супа от агнешко и нахут, традиционно готвена и сервирана в индивидуални глинени гърнета - всяка порция къкри бавно сама за себе си, което дава на пити богат, концентриран бульон.",
      steps: [
        "Накиснете сухия нахут цяла нощ в обилно количество вода.",
        "В дълбока тенджера (или индивидуални глинени гърнета, ако имате) смесете агнешкото, отцедения нахут и един нарязан лук, залейте с вода, доведете до кипене и отстранете пяната.",
        "Къкрете на слаб огън около 1 час, докато нахутът започне да омеква.",
        "Добавете картофите, останалия лук, доматите и сушените сливи и продължете да къкрите още час, докато агнешкото стане крехко, а бульонът се редуцира и концентрира - сушените сливи са това, което дава на пити характерната лека киселинност, така че не ги пропускайте.",
        "Разбъркайте шафрановата вода през последните 10 минути за цвят и аромат и подправете със сол и черен пипер.",
        "Ако използвате индивидуални гърнета, разпределете супата по купи или гърнета и сервирайте с питка, като традиционно се разбива част от месото и нахута в бульона с лъжица преди хранене.",
      ],
      ingredients: [
        "680г агнешко плешка или агнешко с кост, нарязано на парчета",
        "1 чаша сух нахут, накиснат цяла нощ",
        "2 лука, нарязани",
        "2 картофа, нарязани на кубчета",
        "2 домата, нарязани (или 2 с.л. доматено пюре)",
        "4-5 сушени сливи или 1 дюля, нарязана на кубчета",
        "1 ч.л. нишки шафран, накиснати в 2 с.л. гореща вода",
        "Сол и черен пипер на вкус",
      ],
    },
  },
  {
    slug: "vatapa",
    title: "Vatapa",
    description:
      "Bahia's velvety Afro-Brazilian shrimp stew - stale bread soaked in coconut milk gives vatapa its signature thick, porridge-like body, while dende palm oil supplies the color and flavor real vatapa can't be made without.",
    imageEmoji: "🍤",
    cookTimeMinutes: 55,
    servings: 4,
    caloriesPerServing: 420,
    proteinG: 20,
    carbsG: 30,
    fatG: 26,
    ingredients: [
      { text: "4 slices stale white bread, torn", ingredient: "bread", quantity: 4 },
      { text: "1 cup coconut milk", ingredient: "coconut milk", quantity: 1 },
      { text: "1/2 cup dried shrimp, soaked 20 minutes", ingredient: "dried shrimp", quantity: 0.5 },
      { text: "1 lb raw shrimp, peeled", ingredient: "shrimp", quantity: 1 },
      { text: "1 onion, chopped", ingredient: "onion", quantity: 1 },
      { text: "3 garlic cloves", ingredient: "garlic", quantity: 3 },
      { text: "1-inch piece ginger", ingredient: "ginger", quantity: 1 },
      { text: "1/2 cup roasted peanuts", ingredient: "roasted peanuts", quantity: 0.5 },
      { text: "1/4 cup cashews", ingredient: "cashews", quantity: 0.25 },
      { text: "3 tbsp dende (red palm) oil", ingredient: "palm oil", quantity: 3 },
      { text: "Salt and chili, to taste", ingredient: "salt", quantity: null },
    ],
    steps: [
      "Tear the stale bread into pieces and soak it in the coconut milk for about 10 minutes until softened.",
      "Drain the soaked dried shrimp, then blend them with the onion, garlic, ginger, peanuts, and cashews into a coarse paste.",
      "Heat the dende oil in a large pot over medium heat and cook the blended paste for a few minutes until fragrant.",
      "Add the soaked bread and coconut milk, and cook, stirring constantly, until the mixture thickens into a smooth, porridge-like paste - keep stirring so it doesn't catch on the bottom.",
      "Stir in the raw shrimp and cook for another 5-8 minutes until just cooked through and the stew has thickened further.",
      "Season with salt and chili, and serve hot over rice, traditionally alongside acaraje or as part of a Bahian feast.",
    ],
    tags: ["dinner"],
    bg: {
      title: "Ватапа",
      description: "Кадифена афро-бразилска яхния от скариди от Баия - остарял хляб, накиснат в кокосово мляко, дава на ватапа характерното плътно тяло, наподобяващо каша, докато палмовото масло дендê придава цвета и вкуса, без които истинска ватапа не може да се направи.",
      steps: [
        "Разкъсайте остарелия хляб на парчета и го накиснете в кокосовото мляко около 10 минути, докато омекне.",
        "Отцедете накиснатите сушени скариди, после ги блендирайте с лука, чесъна, джинджифила, фъстъците и кашуто до груба паста.",
        "Загрейте палмовото масло в голяма тенджера на средно силен огън и гответе блендираната паста няколко минути, докато замирише.",
        "Добавете накиснатия хляб и кокосовото мляко и гответе, разбърквайки постоянно, докато сместа се сгъсти до гладка каша - продължавайте да разбърквате, за да не загори на дъното.",
        "Разбъркайте суровите скариди и гответе още 5-8 минути, докато се сготвят и яхнията се сгъсти още повече.",
        "Подправете със сол и люта чушка и сервирайте горещо върху ориз, традиционно заедно с акараже или като част от празненство от Баия.",
      ],
      ingredients: [
        "4 филии остарял бял хляб, разкъсани",
        "1 чаша кокосово мляко",
        "1/2 чаша сушени скариди, накиснати 20 минути",
        "450г сурови скариди, обелени",
        "1 лук, нарязан",
        "3 скилидки чесън",
        "Парче джинджифил (2.5 см)",
        "1/2 чаша печени фъстъци",
        "1/4 чаша кашу",
        "3 с.л. палмово масло дендê",
        "Сол и лют пипер на вкус",
      ],
    },
  },
  {
    slug: "chapli-kebab",
    title: "Chapli Kebab",
    description:
      "Peshawar's flat, spiced meat patty - the meat is worked with finely chopped tomato, coriander, and pomegranate seeds until it turns pasty, then shallow-fried rather than grilled, giving the classic crisp, craggy edge.",
    imageEmoji: "🥩",
    cookTimeMinutes: 40,
    servings: 4,
    caloriesPerServing: 380,
    proteinG: 24,
    carbsG: 12,
    fatG: 26,
    ingredients: [
      { text: "1 lb ground beef (20-30% fat)", ingredient: "ground beef", quantity: 1 },
      { text: "1 small onion, very finely chopped", ingredient: "onion", quantity: 1 },
      { text: "1 tomato, seeded and finely chopped", ingredient: "tomato", quantity: 1 },
      { text: "2 green chilies, finely chopped", ingredient: "green chili", quantity: 2 },
      { text: "1/4 cup fresh cilantro, finely chopped", ingredient: "cilantro", quantity: 0.25 },
      { text: "2 tbsp pomegranate seeds, lightly crushed", ingredient: "pomegranate seeds", quantity: 2 },
      { text: "1 tbsp coriander seeds, crushed", ingredient: "coriander seeds", quantity: 1 },
      { text: "1 tsp cumin seeds, crushed", ingredient: "cumin seeds", quantity: 1 },
      { text: "1 tsp red chili flakes", ingredient: "chili flakes", quantity: 1 },
      { text: "1 egg", ingredient: "egg", quantity: 1 },
      { text: "2 tbsp cornmeal or gram flour", ingredient: "cornmeal", quantity: 2 },
      { text: "Salt, to taste", ingredient: "salt", quantity: null },
      { text: "Oil, for shallow-frying", ingredient: "vegetable oil", quantity: null },
    ],
    steps: [
      "Finely chop the onion, tomato (seeded to keep the mixture from getting too wet), chilies, and cilantro - everything should be chopped very fine, not just diced, since coarse pieces will make the patties fall apart.",
      "Combine the ground beef with the chopped vegetables, pomegranate seeds, crushed coriander and cumin seeds, chili flakes, egg, and cornmeal in a large bowl.",
      "Knead the mixture by hand for several minutes until it turns pasty and sticky - this working of the meat is what holds the flat patties together without needing breadcrumbs.",
      "Shape into flat, wide patties, about 1/2 inch thick.",
      "Heat a generous layer of oil in a heavy skillet over medium heat and shallow-fry the kebabs for 4-5 minutes per side, until deeply browned and crisp on the outside but still juicy inside.",
      "Drain briefly on paper towels and serve hot with naan, yogurt, and sliced onion.",
    ],
    tags: ["dinner", "lunch"],
    bg: {
      title: "Чапли кебап",
      description: "Плоският, пикантен кюфтета от Пешавар - месото се работи с ситно нарязан домат, кориандър и нарови зърна, докато стане лепкаво, после се запържва плитко, а не се пече на скара, което дава класическия хрупкав, назъбен ръб.",
      steps: [
        "Нарежете ситно лука, домата (без семки, за да не омокри сместа), чушките и кинзата - всичко трябва да е нарязано много ситно, а не просто на кубчета, защото по-едри парчета ще накарат кюфтетата да се разпаднат.",
        "Смесете смляното говеждо с нарязаните зеленчуци, наровите зърна, натрошените семена от кориандър и кимион, лютите люспи, яйцето и царевичното брашно в голяма купа.",
        "Месете сместа на ръка няколко минути, докато стане лепкава и пастообразна - тази работа с месото е това, което държи плоските кюфтета заедно, без да са нужни галета.",
        "Оформете на плоски, широки кюфтета, около 1.25 см дебели.",
        "Загрейте обилен слой олио в тежък тиган на средно силен огън и запържете кебапите плитко по 4-5 минути на страна, докато станат тъмно кафяви и хрупкави отвън, но все още сочни отвътре.",
        "Отцедете за кратко на кухненска хартия и сервирайте горещи с наан, кисело мляко и нарязан лук.",
      ],
      ingredients: [
        "450г смляно говеждо (20-30% масленост)",
        "1 малък лук, нарязан много ситно",
        "1 домат, без семки, нарязан ситно",
        "2 зелени люти чушки, нарязани ситно",
        "1/4 чаша прясна кинза, нарязана ситно",
        "2 с.л. нарови зърна, леко натрошени",
        "1 с.л. семена от кориандър, натрошени",
        "1 ч.л. семена от кимион, натрошени",
        "1 ч.л. лют пипер на люспи",
        "1 яйце",
        "2 с.л. царевично брашно или нахутено брашно",
        "Сол на вкус",
        "Олио, за плитко пържене",
      ],
    },
  },
  {
    slug: "aebleskiver",
    title: "Aebleskiver",
    description:
      "Denmark's spherical pancake balls - egg whites are whipped separately and folded in for lightness, then the batter is turned mid-cook with a skewer so it puffs into a perfect sphere instead of a flat disc.",
    imageEmoji: "🥞",
    cookTimeMinutes: 35,
    servings: 4,
    caloriesPerServing: 320,
    proteinG: 9,
    carbsG: 38,
    fatG: 14,
    ingredients: [
      { text: "2 cups flour", ingredient: "flour", quantity: 2 },
      { text: "2 tbsp sugar", ingredient: "sugar", quantity: 2 },
      { text: "1 tsp baking powder", ingredient: "baking powder", quantity: 1 },
      { text: "1/4 tsp baking soda", ingredient: "baking soda", quantity: 0.25 },
      { text: "1/4 tsp salt", ingredient: "salt", quantity: 0.25 },
      { text: "1/4 tsp ground cardamom", ingredient: "cardamom", quantity: 0.25 },
      { text: "2 eggs, separated", ingredient: "eggs", quantity: 2 },
      { text: "2 cups buttermilk", ingredient: "buttermilk", quantity: 2 },
      { text: "1/4 cup melted butter, plus more for the pan", ingredient: "butter", quantity: 0.25 },
      { text: "Powdered sugar and jam, for serving", ingredient: "powdered sugar", quantity: null },
    ],
    steps: [
      "Whisk together the flour, sugar, baking powder, baking soda, salt, and cardamom in a bowl.",
      "In a separate bowl, whisk the egg yolks with the buttermilk and melted butter, then stir into the dry ingredients until just combined.",
      "Beat the egg whites to soft peaks in a clean bowl, then gently fold them into the batter - this is what makes aebleskiver fluffy rather than dense.",
      "Heat an aebleskiver pan over medium heat and brush each cup generously with butter.",
      "Fill each cup about two-thirds full with batter, and cook until bubbles form around the edges and the bottom is golden, about 2 minutes.",
      "Using a wooden skewer or chopstick, turn each ball a quarter turn, letting the uncooked batter flow into the space - keep turning every minute or so until the ball is golden and cooked through on all sides, forming a full sphere.",
      "Dust with powdered sugar and serve warm with jam.",
    ],
    tags: ["breakfast", "dessert"],
    bg: {
      title: "Ебльоскивер",
      description: "Датските сферични palачинkови топчета - белтъците се разбиват отделно и се вмесват за лекота, после тестото се обръща в средата на печенето с шиш, за да се издуе в перфектна сфера, вместо плосък диск.",
      steps: [
        "Разбъркайте брашното, захарта, бакпулвера, содата за хляб, солта и кардамона в купа.",
        "В отделна купа разбийте жълтъците с мътеницата и разтопеното масло, после ги вмесете в сухите съставки само докато се съединят.",
        "Разбийте белтъците до меки върхове в чиста купа, после ги вмесете внимателно в тестото - това е, което прави ебльоскивер пухкав, а не плътен.",
        "Загрейте тиган за ебльоскивер на среден огън и намажете обилно всяко гнездо с масло.",
        "Напълнете всяко гнездо около две трети с тесто и гответе, докато се образуват мехурчета по краищата, а дъното стане златисто, около 2 минути.",
        "С дървен шиш или клечка за хранене обърнете всяко топче на четвърт оборот, оставяйки несготвеното тесто да изтече в пространството - продължавайте да обръщате на всяка минута, докато топчето стане златисто и се сготви от всички страни, оформяйки пълна сфера.",
        "Поръсете с пудра захар и сервирайте топли с конфитюр.",
      ],
      ingredients: [
        "2 чаши брашно",
        "2 с.л. захар",
        "1 ч.л. бакпулвер",
        "1/4 ч.л. сода за хляб",
        "1/4 ч.л. сол",
        "1/4 ч.л. смлян кардамон",
        "2 яйца, разделени",
        "2 чаши мътеница",
        "1/4 чаша разтопено масло, плюс още за тигана",
        "Пудра захар и конфитюр, за сервиране",
      ],
    },
  },
  {
    slug: "kaiserschmarrn",
    title: "Kaiserschmarrn",
    description:
      "Austria's \"torn pancake\" dessert - egg whites are whipped and folded in separately for lift, then once the pancake sets in the pan it's torn into pieces and caramelized in butter and sugar rather than served whole.",
    imageEmoji: "🥞",
    cookTimeMinutes: 30,
    servings: 4,
    caloriesPerServing: 380,
    proteinG: 11,
    carbsG: 42,
    fatG: 18,
    ingredients: [
      { text: "4 eggs, separated", ingredient: "eggs", quantity: 4 },
      { text: "1 cup milk", ingredient: "milk", quantity: 1 },
      { text: "1 cup flour", ingredient: "flour", quantity: 1 },
      { text: "3 tbsp sugar, divided", ingredient: "sugar", quantity: 3 },
      { text: "1/4 tsp salt", ingredient: "salt", quantity: 0.25 },
      { text: "1/2 tsp vanilla extract", ingredient: "vanilla extract", quantity: 0.5 },
      { text: "1/4 cup raisins, soaked in rum (optional)", ingredient: "raisins", quantity: 0.25 },
      { text: "3 tbsp butter", ingredient: "butter", quantity: 3 },
      { text: "Powdered sugar, for dusting", ingredient: "powdered sugar", quantity: null },
      { text: "Applesauce or fruit compote, for serving", ingredient: "applesauce", quantity: null },
    ],
    steps: [
      "Whisk the egg yolks with the milk, flour, 2 tablespoons of the sugar, salt, and vanilla until smooth.",
      "In a separate clean bowl, beat the egg whites to soft peaks.",
      "Gently fold the egg whites into the batter using slow, sweeping motions to keep as much air in as possible - this is the key technique that gives kaiserschmarrn its fluffy texture.",
      "If using, drain the soaked raisins and stir them into the batter.",
      "Melt half the butter in a large skillet over medium heat, pour in the batter, and cook until the underside is golden and the top is mostly set, about 3-4 minutes.",
      "Flip the pancake (in sections if needed) and cook the other side for another 2-3 minutes.",
      "Using two forks, tear the pancake into bite-sized irregular pieces directly in the pan.",
      "Add the remaining butter and sugar, and toss the torn pieces over the heat for a couple of minutes until caramelized and golden at the edges.",
      "Dust with powdered sugar and serve hot with applesauce or fruit compote.",
    ],
    tags: ["dessert", "breakfast"],
    bg: {
      title: "Кайзершмарн",
      description: "Австрийският десерт от \"разкъсана палачинка\" - белтъците се разбиват и вмесват отделно за въздушност, после, щом палачинката се стегне в тигана, се разкъсва на парчета и се карамелизира в масло и захар, вместо да се сервира цяла.",
      steps: [
        "Разбийте жълтъците с млякото, брашното, 2 супени лъжици от захарта, солта и ванилията до гладкост.",
        "В отделна чиста купа разбийте белтъците до меки върхове.",
        "Вмесете внимателно белтъците в тестото с бавни, широки движения, за да запазите колкото се може повече въздух - това е ключовата техника, която прави кайзершмарн пухкав.",
        "Ако използвате, отцедете накиснатото стафиди и ги разбъркайте в тестото.",
        "Разтопете половината от маслото в голям тиган на среден огън, изсипете тестото и гответе, докато долната страна стане златиста, а горната - почти стегната, около 3-4 минути.",
        "Обърнете палачинката (на части, ако е нужно) и гответе другата страна още 2-3 минути.",
        "С две вилици разкъсайте палачинката на неравни хапки директно в тигана.",
        "Добавете останалото масло и захар и разбъркайте разкъсаните парчета на огъня няколко минути, докато се карамелизират и златеят по краищата.",
        "Поръсете с пудра захар и сервирайте горещо с ябълково пюре или плодов компот.",
      ],
      ingredients: [
        "4 яйца, разделени",
        "1 чаша мляко",
        "1 чаша брашно",
        "3 с.л. захар, разделени",
        "1/4 ч.л. сол",
        "1/2 ч.л. ванилова есенция",
        "1/4 чаша стафиди, накиснати в ром (по желание)",
        "3 с.л. масло",
        "Пудра захар, за поръсване",
        "Ябълково пюре или плодов компот, за сервиране",
      ],
    },
  },
  {
    slug: "otak-otak",
    title: "Otak-Otak",
    description:
      "Southeast Asia's grilled fish cake - fresh fish paste is bound with tapioca starch and spice paste, wrapped in softened banana leaf, and grilled low and slow so the leaf chars fragrantly without burning before the custard-like filling cooks through.",
    imageEmoji: "🐠",
    cookTimeMinutes: 45,
    servings: 4,
    caloriesPerServing: 220,
    proteinG: 20,
    carbsG: 10,
    fatG: 12,
    ingredients: [
      { text: "1 lb white fish fillet (mackerel or cod), finely minced", ingredient: "white fish", quantity: 1 },
      { text: "2 tbsp tapioca starch", ingredient: "tapioca starch", quantity: 2 },
      { text: "1/2 cup coconut milk", ingredient: "coconut milk", quantity: 0.5 },
      { text: "1 egg", ingredient: "egg", quantity: 1 },
      { text: "3 shallots", ingredient: "shallot", quantity: 3 },
      { text: "2 garlic cloves", ingredient: "garlic", quantity: 2 },
      { text: "2-3 dried chilies, soaked", ingredient: "dried chili", quantity: 3 },
      { text: "1 stalk lemongrass, sliced", ingredient: "lemongrass", quantity: 1 },
      { text: "1 tsp turmeric", ingredient: "turmeric", quantity: 1 },
      { text: "1 tsp shrimp paste (belacan)", ingredient: "shrimp paste", quantity: 1 },
      { text: "Banana leaves, softened in hot water", ingredient: "banana leaves", quantity: null },
      { text: "Salt and sugar, to taste", ingredient: "salt", quantity: null },
    ],
    steps: [
      "Blend the shallots, garlic, soaked chilies, lemongrass, turmeric, and shrimp paste into a smooth spice paste.",
      "Combine the minced fish with the spice paste, tapioca starch, coconut milk, and egg, and mix well until it forms a smooth, slightly sticky paste - the tapioca starch and egg are what hold the mixture together like a custard once cooked.",
      "Season with salt and a touch of sugar to balance the spice.",
      "Soften the banana leaves by dipping them briefly in hot water so they become pliable without tearing.",
      "Spoon a portion of the fish paste onto the center of each leaf, fold the sides over to enclose it, and secure with toothpicks to make flat parcels.",
      "Grill the parcels over medium-low heat, about 4-5 minutes per side, until the leaves char lightly and the filling is firm and cooked through - keeping the heat moderate prevents the leaves from burning before the inside sets.",
      "Serve warm, unwrapped at the table.",
    ],
    tags: ["dinner", "lunch"],
    bg: {
      title: "Отак-Отак",
      description: "Гриловано рибено кюфте от Югоизточна Азия - прясна рибена паста, свързана с тапиока нишесте и подправена паста, увита в омекнало бананово листо и печена на слаб огън, за да овъгли листото ароматно, без да изгори, преди пълнежът, наподобяващ крем, да се сготви.",
      steps: [
        "Блендирайте шалота, чесъна, накиснатите люти чушки, лимоновата трева, куркумата и пастата от скариди до гладка подправена паста.",
        "Смесете смляната риба с подправената паста, тапиока нишестето, кокосовото мляко и яйцето и разбъркайте добре, докато се получи гладка, леко лепкава паста - тапиока нишестето и яйцето са това, което държи сместа заедно като крем, след като се сготви.",
        "Подправете със сол и малко захар, за да балансирате пикантността.",
        "Омекотете банановите листа, потапяйки ги за кратко в гореща вода, за да станат гъвкави, без да се скъсат.",
        "Сложете порция от рибената паста в центъра на всяко листо, сгънете страните, за да я затворите, и закрепете с клечки за зъби, за да направите плоски пакетчета.",
        "Печете пакетчетата на среден до слаб огън, около 4-5 минути на страна, докато листата леко овъглеят, а пълнежът стане стегнат и сготвен - поддържането на умерена температура пази листата да не изгорят, преди вътрешността да се стегне.",
        "Сервирайте топли, разопаковани на масата.",
      ],
      ingredients: [
        "450г филе от бяла риба (скумрия или треска), смляно ситно",
        "2 с.л. тапиока нишесте",
        "1/2 чаша кокосово мляко",
        "1 яйце",
        "3 шалота",
        "2 скилидки чесън",
        "2-3 сушени люти чушки, накиснати",
        "1 стрък лимонова трева, нарязан",
        "1 ч.л. куркума",
        "1 ч.л. паста от скариди (беладжан)",
        "Бананови листа, омекотени в гореща вода",
        "Сол и захар на вкус",
      ],
    },
  },
  {
    slug: "bastilla",
    title: "Bastilla",
    description:
      "Morocco's sweet-and-savory chicken pie - the filling is slow-braised in warm spices until falling-apart tender, then wrapped in paper-thin warqa pastry and finished with a dusting of cinnamon and sugar over the golden crust.",
    imageEmoji: "🥧",
    cookTimeMinutes: 100,
    servings: 6,
    caloriesPerServing: 480,
    proteinG: 26,
    carbsG: 38,
    fatG: 26,
    ingredients: [
      { text: "2 lb bone-in chicken thighs", ingredient: "chicken thigh", quantity: 2 },
      { text: "2 onions, chopped", ingredient: "onion", quantity: 2 },
      { text: "3 tbsp butter", ingredient: "butter", quantity: 3 },
      { text: "1 tsp ground cinnamon, plus more for topping", ingredient: "cinnamon", quantity: 1 },
      { text: "1/2 tsp ground ginger", ingredient: "ginger", quantity: 0.5 },
      { text: "1/4 tsp saffron threads", ingredient: "saffron", quantity: 0.25 },
      { text: "4 eggs, beaten", ingredient: "eggs", quantity: 4 },
      { text: "1/2 cup ground almonds, toasted", ingredient: "ground almonds", quantity: 0.5 },
      { text: "2 tbsp sugar, plus more for topping", ingredient: "sugar", quantity: 2 },
      { text: "10-12 sheets phyllo dough", ingredient: "phyllo dough", quantity: 12 },
      { text: "1/4 cup melted butter, for brushing", ingredient: "butter", quantity: 0.25 },
      { text: "Powdered sugar, for dusting", ingredient: "powdered sugar", quantity: null },
    ],
    steps: [
      "In a large pot, combine the chicken, onions, butter, cinnamon, ginger, and saffron with about 1 cup water, and simmer covered over low heat for 45 minutes to an hour, until the chicken is falling-apart tender.",
      "Remove the chicken, let it cool slightly, then shred the meat and discard the bones, reserving the braising liquid.",
      "Return the braising liquid to the heat and simmer uncovered until reduced by about half, then pour in the beaten eggs and stir gently over low heat until they form soft, creamy curds - this spiced egg-onion mixture is the pie's signature savory layer.",
      "Combine the toasted ground almonds with the 2 tablespoons of sugar and a pinch of cinnamon for the sweet topping layer.",
      "Layer sheets of phyllo in a buttered pie dish, brushing each sheet with melted butter and overlapping them to cover the base and sides with overhang.",
      "Layer in the shredded chicken, then the egg mixture, then the almond mixture, and fold the overhanging phyllo over the top, brushing with more butter, adding a few more buttered sheets on top to seal.",
      "Bake at 375F (190C) for 25-30 minutes until deep golden and crisp.",
      "Dust the hot pie generously with powdered sugar and a dusting of cinnamon in a crosshatch pattern before serving.",
    ],
    tags: ["dinner"],
    bg: {
      title: "Бастиля",
      description: "Мароканската сладко-солена пилешка баница - пълнежът се задушава бавно в топли подправки, докато стане разпадащо крехък, после се увива в тънко като хартия тесто варка и се завършва с поръсване от канела и захар върху златистата коричка.",
      steps: [
        "В голяма тенджера смесете пилето, лука, маслото, канелата, джинджифила и шафрана с около 1 чаша вода и къкрете покрито на слаб огън 45 минути до час, докато пилето стане разпадащо крехко.",
        "Извадете пилето, оставете да поизстине леко, после разкъсайте месото на нишки и изхвърлете костите, като запазите бульона от задушаването.",
        "Върнете бульона на огъня и къкрете без капак, докато се редуцира наполовина, после изсипете разбитите яйца и разбърквайте внимателно на слаб огън, докато образуват меки, кремообразни люспи - тази подправена смес от яйца и лук е характерният солен слой на баницата.",
        "Смесете печените смлени бадеми с 2-те супени лъжици захар и щипка канела за сладкия горен слой.",
        "Наредете кори варка (юфка) в намаслена форма за баница, намазвайки всяка кора с разтопено масло и застъпвайки ги, за да покриете дъното и стените с излишък.",
        "Наредете разкъсаното пилешко, после сместа от яйца, после бадемовата смес, и сгънете излишните кори отгоре, намазвайки с още масло, добавяйки още няколко намазани кори отгоре, за да запечатате.",
        "Печете на 190°C за 25-30 минути, докато стане дълбоко златиста и хрупкава.",
        "Поръсете горещата баница обилно с пудра захар и канела в кръстосан десен, преди да сервирате.",
      ],
      ingredients: [
        "900г пилешки бутчета с кост",
        "2 лука, нарязани",
        "3 с.л. масло",
        "1 ч.л. смляна канела, плюс още за поръсване",
        "1/2 ч.л. джинджифил на прах",
        "1/4 ч.л. нишки шафран",
        "4 яйца, разбити",
        "1/2 чаша смлени бадеми, препечени",
        "2 с.л. захар, плюс още за поръсване",
        "10-12 кори за баница (варка)",
        "1/4 чаша разтопено масло, за намазване",
        "Пудра захар, за поръсване",
      ],
    },
  },
];

async function main() {
  for (const recipe of newRecipes) {
    const created = await prisma.recipe.create({
      data: {
        slug: recipe.slug,
        title: recipe.title,
        description: recipe.description,
        imageEmoji: recipe.imageEmoji,
        cookTimeMinutes: recipe.cookTimeMinutes,
        servings: recipe.servings,
        steps: JSON.stringify(recipe.steps),
        tags: JSON.stringify(recipe.tags),
        caloriesPerServing: recipe.caloriesPerServing,
        proteinG: recipe.proteinG,
        carbsG: recipe.carbsG,
        fatG: recipe.fatG,
      },
    });

    for (let i = 0; i < recipe.ingredients.length; i++) {
      const ing = recipe.ingredients[i];
      const ingredient = await prisma.ingredient.upsert({
        where: { name: ing.ingredient },
        update: {},
        create: { name: ing.ingredient },
      });
      await prisma.recipeIngredient.create({
        data: {
          recipeId: created.id,
          ingredientId: ingredient.id,
          displayText: ing.text,
          quantity: ing.quantity,
          position: i,
        },
      });
    }

    console.log(`Created ${recipe.slug}`);
  }
  console.log(`Created ${newRecipes.length} recipes total.`);

  await runTranslations(
    newRecipes.map((r) => ({
      slug: r.slug,
      title: r.bg.title,
      description: r.bg.description,
      steps: r.bg.steps,
      ingredients: r.bg.ingredients,
    })),
  );
}

main();
