import { prisma, runTranslations } from "./translate-lib.mjs";

// 10 popular international recipes, each web-researched for authentic
// technique before writing, per standing instructions.
const newRecipes = [
  {
    slug: "croissant",
    title: "Croissant",
    description:
      "Classic French laminated pastry, built by folding a block of cold butter into yeasted dough through three single folds to create dozens of paper-thin layers - keeping the butter and dough at the same cool, pliable temperature throughout is what lets the layers stay distinct instead of the butter melting into the dough or cracking apart under the rolling pin.",
    imageEmoji: "🥐",
    cookTimeMinutes: 180,
    servings: 8,
    ingredients: [
      { text: "3 1/2 cups flour", ingredient: "flour", quantity: 3.5 },
      { text: "2 1/4 tsp yeast", ingredient: "yeast", quantity: 2.25 },
      { text: "1/4 cup sugar", ingredient: "sugar", quantity: 0.25 },
      { text: "1 1/4 cups cold milk", ingredient: "milk", quantity: 1.25 },
      { text: "1 1/2 tsp salt", ingredient: "salt", quantity: 1.5 },
      { text: "2 tbsp butter, softened (for the dough)", ingredient: "butter", quantity: 2 },
      { text: "1 1/2 cups cold butter (for the butter block)", ingredient: "butter", quantity: 1.5 },
      { text: "1 egg, beaten (for egg wash)", ingredient: "eggs", quantity: 1 },
    ],
    steps: [
      "Dissolve the yeast and sugar in the cold milk and let sit for 5 minutes.",
      "Mix the flour and salt in a large bowl, add the yeast mixture and the 2 tbsp softened butter, and knead for 6-8 minutes into a smooth, slightly firm dough. Wrap and refrigerate for at least 1 hour.",
      "Meanwhile, pound the cold butter between two sheets of parchment into a flat 8x8-inch square, then chill it - it needs to stay cold but flexible enough to bend without cracking, the same consistency as the chilled dough.",
      "Roll the dough into a rectangle roughly twice the size of the butter block. Place the butter block in the center and fold the dough over it to fully enclose it, pinching the seams shut.",
      "Roll the dough-wrapped butter out into a long rectangle, then fold it in thirds like a letter - this is the first single fold. Wrap and chill for 30-45 minutes.",
      "Repeat the roll-and-fold two more times, chilling for 30-45 minutes between each fold - keeping the butter and dough at the same cool, pliable temperature throughout these folds is what keeps the layers distinct instead of the butter melting into the dough or cracking apart.",
      "After the final fold and chill, roll the dough out into a large rectangle about 1/4 inch thick. Cut into triangles, then roll each triangle up from the wide end to the point to shape the croissants.",
      "Place on a baking sheet, cover loosely, and let rise in a warm spot for 1.5-2 hours, until visibly puffy and jiggly.",
      "Preheat the oven to 400°F. Brush the croissants with the egg wash and bake for 15-18 minutes, until deep golden brown and the layers are visible on the ends.",
    ],
    tags: ["breakfast", "baking", "vegetarian"],
    bg: {
      title: "Кроасан",
      description:
        "Класическо френско многослойно тесто, направено чрез сгъване на блок студено масло в мая тесто през три единични сгъвания, за да се създадат десетки тънки като хартия слоеве - поддържането на маслото и тестото на еднаква хладна, гъвкава температура през целия процес е това, което пази слоевете отделни, вместо маслото да се разтопи в тестото или да се напука под точилката.",
      steps: [
        "Разтворете маята и захарта в студеното мляко и оставете за 5 минути.",
        "Смесете брашното и солта в голяма купа, добавете маената смес и 2-те с.л. омекнало масло, и месете 6-8 минути в гладко, леко стегнато тесто. Увийте и охладете поне 1 час.",
        "Междувременно разбийте студеното масло между два листа хартия за печене в плосък квадрат 20х20 см, после охладете - трябва да остане студено, но достатъчно гъвкаво, за да се огъва без да се напука, същата консистенция като охладеното тесто.",
        "Разточете тестото в правоъгълник приблизително два пъти по-голям от блока масло. Поставете блока масло в центъра и сгънете тестото върху него, за да го затворите напълно, притискайки шевовете.",
        "Разточете тестото, увито около маслото, в дълъг правоъгълник, после го сгънете на трети като писмо - това е първото единично сгъване. Увийте и охладете 30-45 минути.",
        "Повторете разточването и сгъването още два пъти, охлаждайки 30-45 минути между всяко сгъване - поддържането на маслото и тестото на еднаква хладна, гъвкава температура през тези сгъвания е това, което пази слоевете отделни, вместо маслото да се разтопи в тестото или да се напука.",
        "След последното сгъване и охлаждане, разточете тестото в голям правоъгълник около 0.6 см дебелина. Нарежете на триъгълници, после навийте всеки триъгълник от широкия край към върха, за да оформите кроасаните.",
        "Поставете върху тава за печене, покрийте свободно, и оставете да втасат на топло място 1.5-2 часа, докато видимо се надуят и разтреперят.",
        "Загрейте фурната на 200°C. Намажете кроасаните с яйчената глазура и печете 15-18 минути, докато станат дълбоко златисти кафяви, а слоевете се виждат в краищата.",
      ],
      ingredients: [
        "3 1/2 чаши брашно",
        "2 1/4 ч.л. мая",
        "1/4 чаша захар",
        "1 1/4 чаши студено мляко",
        "1 1/2 ч.л. сол",
        "2 с.л. масло, омекнало (за тестото)",
        "1 1/2 чаши студено масло (за блока масло)",
        "1 яйце, разбито (за намазване)",
      ],
    },
  },
  {
    slug: "quiche-lorraine",
    title: "Quiche Lorraine",
    description:
      "The original French quiche - a blind-baked pastry shell filled with just bacon, eggs, and cream, no cheese in the traditional version - blind-baking the crust before the custard goes in is what keeps the bottom from turning soggy under the wet filling, and using a precise egg-to-cream ratio is what lets the custard set into clean, sliceable wedges instead of staying loose or turning rubbery.",
    imageEmoji: "🥧",
    cookTimeMinutes: 90,
    servings: 8,
    ingredients: [
      { text: "1 pie crust", ingredient: "pie crust", quantity: 1 },
      { text: "8 oz bacon, cut into small pieces", ingredient: "bacon", quantity: 8 },
      { text: "1 onion, thinly sliced", ingredient: "onion", quantity: 1 },
      { text: "3 eggs", ingredient: "eggs", quantity: 3 },
      { text: "1 1/4 cups heavy cream", ingredient: "heavy cream", quantity: 1.25 },
      { text: "1/4 tsp nutmeg", ingredient: "nutmeg", quantity: 0.25 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "Pepper to taste", ingredient: "pepper", quantity: null },
    ],
    steps: [
      "Preheat the oven to 425°F. Line the pie crust with parchment paper, fill with pie weights or dried beans, and blind-bake for 12-15 minutes.",
      "Remove the weights and parchment, then bake for another 5 minutes, until the bottom looks dry and just barely golden - this blind-baking step is what keeps the crust from turning soggy under the wet custard filling.",
      "While the crust bakes, cook the bacon in a skillet over medium heat until just starting to crisp, then add the onion and cook for 5 minutes, until softened. Drain off excess fat.",
      "Reduce the oven temperature to 375°F.",
      "Whisk the eggs and heavy cream together until smooth, then season with the nutmeg, salt, and pepper - this precise egg-to-cream ratio is what lets the custard set into clean, sliceable wedges instead of staying loose.",
      "Scatter the bacon and onion evenly over the bottom of the baked crust, then pour the egg-cream mixture over the top.",
      "Bake for 30-35 minutes, until the custard is set but still has a slight jiggle in the center.",
      "Let cool for at least 15 minutes before slicing, and serve warm or at room temperature.",
    ],
    tags: ["breakfast", "lunch", "baking"],
    bg: {
      title: "Киш Лорен",
      description:
        "Оригиналният френски киш - предварително изпечена черупка тесто, пълнена само с бекон, яйца и сметана, без сирене в традиционната версия - предварителното изпичане на черупката, преди да се добави пълнежът, е това, което пази дъното от разкисване под мокрия пълнеж, а точното съотношение яйца към сметана е това, което позволява на крема да се стегне в чисти, режещи се резени, вместо да остане рехав или да стане гумен.",
      steps: [
        "Загрейте фурната на 220°C. Постелете черупката тесто с хартия за печене, напълнете с тежести за печене или сух боб, и предварително изпечете 12-15 минути.",
        "Извадете тежестите и хартията, после печете още 5 минути, докато дъното изглежда сухо и едва позлатяло - тази стъпка на предварително печене е това, което пази черупката от разкисване под мокрия крем пълнеж.",
        "Докато черупката се пече, гответе бекона в тиган на среден огън, докато точно започне да захрупва, после добавете лука и гответе 5 минути, докато омекне. Отцедете излишната мазнина.",
        "Намалете температурата на фурната на 190°C.",
        "Разбийте яйцата и течната сметана заедно до гладкост, после подправете с индийското орехче, солта и пипера - това точно съотношение яйца към сметана е това, което позволява на крема да се стегне в чисти, режещи се резени, вместо да остане рехав.",
        "Разпръснете бекона и лука равномерно на дъното на изпечената черупка, после изсипете яйчено-сметановата смес отгоре.",
        "Печете 30-35 минути, докато кремът се стегне, но все още леко трепери в центъра.",
        "Оставете да изстине поне 15 минути преди рязане, и сервирайте топъл или на стайна температура.",
      ],
      ingredients: [
        "1 черупка тесто за пай",
        "225 г бекон, нарязан на малки парчета",
        "1 лук, нарязан на тънко",
        "3 яйца",
        "1 1/4 чаши течна сметана",
        "1/4 ч.л. индийско орехче",
        "Сол на вкус",
        "Черен пипер на вкус",
      ],
    },
  },
  {
    slug: "creme-brulee",
    title: "Crème Brûlée",
    description:
      "A silky French baked custard topped with a thin, brittle sheet of caramelized sugar - baking the custard in a water bath is what regulates the heat around it so the eggs set slowly and evenly instead of curdling, and torching a thin, even layer of sugar right before serving is what gives the top its signature crackling snap instead of a soft or burnt crust.",
    imageEmoji: "🍮",
    cookTimeMinutes: 60,
    servings: 4,
    ingredients: [
      { text: "2 cups heavy cream", ingredient: "heavy cream", quantity: 2 },
      { text: "5 egg yolks", ingredient: "egg yolks", quantity: 5 },
      { text: "1/2 cup sugar, divided", ingredient: "sugar", quantity: 0.5 },
      { text: "1 tsp vanilla extract", ingredient: "vanilla extract", quantity: 1 },
      { text: "Pinch of salt", ingredient: "salt", quantity: null },
      { text: "4 tbsp sugar, for the caramelized topping", ingredient: "sugar", quantity: 4 },
    ],
    steps: [
      "Preheat the oven to 325°F. Heat the cream in a saucepan until just steaming, but not boiling.",
      "Whisk the egg yolks, 1/4 cup of the sugar, and the salt together in a bowl until pale.",
      "Slowly pour the hot cream into the egg mixture while whisking constantly, to temper the eggs without scrambling them.",
      "Stir in the vanilla, then strain the mixture through a fine-mesh sieve into a pitcher, skimming off any foam on top - straining and skimming is what keeps the finished custard perfectly silky instead of bumpy.",
      "Divide the custard among 4 ramekins and place them in a deep baking dish. Pour hot water into the dish until it reaches halfway up the sides of the ramekins.",
      "Bake for 30-35 minutes, until the custards are set around the edges but still slightly jiggly in the center.",
      "Remove the ramekins from the water bath and let cool, then refrigerate for at least 2 hours, until fully chilled.",
      "Just before serving, sprinkle a thin, even layer of the remaining sugar over each custard and caramelize it with a kitchen torch, moving constantly, until deep amber and crackling - covering the custard completely with sugar is what keeps it from curdling under the flame.",
    ],
    tags: ["dessert", "vegetarian"],
    bg: {
      title: "Крем брюле",
      description:
        "Копринен френски печен крем, покрит с тънък, чуплив слой карамелизирана захар - печенето на крема на водна баня е това, което регулира топлината около него, за да се стегнат яйцата бавно и равномерно, вместо да се пресекат, а изгарянето на тънък, равномерен слой захар точно преди сервиране е това, което дава на повърхността характерното ѝ пращящо хрупкане, вместо мека или изгоряла коричка.",
      steps: [
        "Загрейте фурната на 165°C. Загрейте сметаната в тенджера, докато точно започне да пуши, но без да заври.",
        "Разбийте жълтъците, 1/4 чаша от захарта и солта заедно в купа, докато побледнеят.",
        "Бавно изсипете горещата сметана в яйчената смес, разбърквайки постоянно, за да темперирате яйцата, без да се пресекат.",
        "Разбъркайте ванилията, после прецедете сместа през фина цедка в кана, обирайки евентуалната пяна отгоре - прецеждането и обирането на пяната е това, което пази готовия крем перфектно копринен, вместо надупчен.",
        "Разпределете крема в 4 купички за печене и ги поставете в дълбока тава за печене. Изсипете гореща вода в тавата, докато достигне до половината на купичките.",
        "Печете 30-35 минути, докато кремовете се стегнат по краищата, но все още леко треперят в центъра.",
        "Извадете купичките от водната баня и оставете да изстинат, после охладете в хладилника поне 2 часа, докато напълно изстинат.",
        "Точно преди сервиране, поръсете тънък, равномерен слой от останалата захар върху всеки крем и карамелизирайте с кухненска горелка, движейки постоянно, докато стане дълбоко кехлибарено и запращи - пълното покриване на крема със захар е това, което го пази от пресичане под пламъка.",
      ],
      ingredients: [
        "2 чаши течна сметана",
        "5 жълтъка",
        "1/2 чаша захар, разделена",
        "1 ч.л. екстракт от ванилия",
        "Щипка сол",
        "4 с.л. захар, за карамелизираната повърхност",
      ],
    },
  },
  {
    slug: "wiener-schnitzel",
    title: "Wiener Schnitzel",
    description:
      "Austria's classic breaded veal cutlet, pounded paper-thin and fried in enough butter to float, so the loose breading puffs up around the meat instead of sticking flat to it - coating the cutlets loosely rather than pressing the breadcrumbs on firmly is what lets the crust soufflé away from the meat as it fries, the detail that separates a real Wiener Schnitzel from an ordinary breaded cutlet.",
    imageEmoji: "🥩",
    cookTimeMinutes: 30,
    servings: 4,
    ingredients: [
      { text: "4 veal cutlets", ingredient: "veal", quantity: 4 },
      { text: "1/2 cup flour", ingredient: "flour", quantity: 0.5 },
      { text: "2 eggs, beaten", ingredient: "eggs", quantity: 2 },
      { text: "1 cup breadcrumbs", ingredient: "breadcrumbs", quantity: 1 },
      { text: "1 cup butter, for frying", ingredient: "butter", quantity: 1 },
      { text: "1 lemon, cut into wedges", ingredient: "lemon", quantity: 1 },
      { text: "2 tbsp parsley, chopped", ingredient: "parsley", quantity: 2 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "Pepper to taste", ingredient: "pepper", quantity: null },
    ],
    steps: [
      "Place each veal cutlet between two sheets of plastic wrap and pound with a meat mallet until about 1/8 inch thick - this thinness is what lets the schnitzel cook through in just a couple of minutes, so the crust can turn golden without the meat drying out.",
      "Season the cutlets on both sides with salt and pepper.",
      "Set up a breading station: flour in one dish, beaten eggs in another, and breadcrumbs in a third.",
      "Dredge each cutlet in flour, then egg, then breadcrumbs, coating loosely rather than pressing the crumbs on firmly - a loose coating is what lets the crust puff away from the meat and soufflé in the hot fat instead of sticking flat.",
      "Heat the butter in a large skillet over medium-high heat until it shimmers and a breadcrumb dropped in sizzles immediately.",
      "Fry the cutlets one at a time in the hot butter, spooning fat over the top as they cook, for about 2 minutes per side, until deep golden and the crust has puffed away from the meat. Turn only once.",
      "Drain briefly on paper towels, but don't cover them, which would soften the crust.",
      "Serve immediately with lemon wedges and a sprinkle of parsley.",
    ],
    tags: ["dinner"],
    bg: {
      title: "Виенски шницел",
      description:
        "Класическият австрийски паниран телешки котлет, разбит тънко като хартия и запържен в достатъчно масло, за да плува, така че рехавата панировка се издува около месото, вместо да залепне плоско към него - покриването на котлетите рехаво, вместо да се притиска галетата силно, е това, което позволява на коричката да се 'изсуфлира' от месото, докато се пържи, детайлът, който отличава истинския виенски шницел от обикновен паниран котлет.",
      steps: [
        "Поставете всеки телешки котлет между два листа фолио и разбийте с чук за месо, докато стане около 0.3 см дебелина - тази тънкост е това, което позволява на шницела да се сготви само за няколко минути, за да може коричката да позлатее, без месото да изсъхне.",
        "Подправете котлетите от двете страни със сол и пипер.",
        "Подгответе станция за паниране: брашно в едно блюдо, разбити яйца в друго, и галета в трето.",
        "Обваляйте всеки котлет в брашно, после в яйце, после в галета, покривайки рехаво, вместо да притискате галетата силно - рехавото покритие е това, което позволява на коричката да се издуе от месото и да се 'изсуфлира' в горещата мазнина, вместо да залепне плоско.",
        "Загрейте маслото в голям тиган на среден-силен огън, докато заблести, а пусната галета веднага засъска.",
        "Пържете котлетите един по един в горещото масло, поливайки с мазнината отгоре, докато се готвят, около 2 минути от всяка страна, докато станат дълбоко златисти, а коричката се издуе от месото. Обръщайте само веднъж.",
        "Отцедете за кратко върху хартиени кърпи, но не ги покривайте, което би омекотило коричката.",
        "Сервирайте веднага с резени лимон и поръсен магданоз.",
      ],
      ingredients: [
        "4 телешки котлета",
        "1/2 чаша брашно",
        "2 яйца, разбити",
        "1 чаша галета",
        "1 чаша масло, за пържене",
        "1 лимон, нарязан на резени",
        "2 с.л. магданоз, нарязан",
        "Сол на вкус",
        "Черен пипер на вкус",
      ],
    },
  },
  {
    slug: "birria-tacos",
    title: "Birria Tacos",
    description:
      "Slow-braised, deeply spiced Mexican beef stew, shredded and folded into tortillas dipped in the braising consommé, then pan-fried until crisp - toasting the dried chilies in a dry skillet before blending them into the braising liquid is what gives birria its deep, complex red color and flavor instead of a flat, one-note heat.",
    imageEmoji: "🌮",
    cookTimeMinutes: 240,
    servings: 6,
    ingredients: [
      { text: "3 lb beef chuck, cut into large chunks", ingredient: "beef chuck", quantity: 3 },
      { text: "4 guajillo chiles, stemmed and seeded", ingredient: "guajillo chiles", quantity: 4 },
      { text: "3 ancho chile, stemmed and seeded", ingredient: "ancho chile", quantity: 3 },
      { text: "2 chile de arbol, stemmed", ingredient: "chile de arbol", quantity: 2 },
      { text: "1 onion, quartered", ingredient: "onion", quantity: 1 },
      { text: "6 cloves garlic", ingredient: "garlic", quantity: 6 },
      { text: "2 tomatoes", ingredient: "tomato", quantity: 2 },
      { text: "1 cinnamon stick", ingredient: "cinnamon stick", quantity: 1 },
      { text: "2 bay leaves", ingredient: "bay leaves", quantity: 2 },
      { text: "1 tbsp cumin", ingredient: "cumin", quantity: 1 },
      { text: "1 tbsp oregano", ingredient: "oregano", quantity: 1 },
      { text: "6 cups beef broth", ingredient: "beef broth", quantity: 6 },
      { text: "16 corn tortillas", ingredient: "corn tortillas", quantity: 16 },
      { text: "8 oz oaxaca cheese, shredded", ingredient: "oaxaca cheese", quantity: 8 },
      { text: "1/2 cup cilantro, chopped", ingredient: "cilantro", quantity: 0.5 },
      { text: "1 onion, finely chopped, for serving", ingredient: "onion", quantity: 1 },
      { text: "2 limes, cut into wedges", ingredient: "lime", quantity: 2 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
    ],
    steps: [
      "Toast the guajillo, ancho, and chile de arbol in a dry skillet over medium heat for 2-3 minutes, pressing them flat, until fragrant and slightly darker - toasting the chilies first is what gives birria its deep, complex red color instead of a flat, one-note heat.",
      "Soak the toasted chilies in hot water for 15 minutes, until softened, then drain.",
      "Blend the softened chilies with the quartered onion, garlic, tomatoes, cumin, and oregano, adding a splash of water as needed, into a smooth, thick paste.",
      "Season the beef chunks with salt, then sear them in a large pot over high heat until browned on all sides.",
      "Add the chile paste, cinnamon stick, bay leaves, and beef broth to the pot with the beef. Bring to a boil, then reduce heat and simmer, covered, for 3-3.5 hours, until the beef is completely fork-tender.",
      "Remove the beef and shred it with two forks. Skim the fat off the top of the braising liquid (the consommé) and reserve some of the fat separately.",
      "Dip each tortilla into the consommé to coat, then fill with shredded beef and cheese, and fold in half.",
      "Heat the reserved fat in a skillet and fry the filled tortillas for 2-3 minutes per side, until crisp and the cheese melts.",
      "Serve the tacos with the warm consommé for dipping, topped with cilantro, chopped onion, and lime wedges.",
    ],
    tags: ["dinner"],
    bg: {
      title: "Тако бирия",
      description:
        "Бавно задушено, дълбоко подправено мексиканско говеждо яхния, накъсано и сгънато в тортили, потопени в бульона от задушаването, после запържени в тиган до хрупкаво - препичането на сушените чушки в сух тиган, преди да се пуснат в течността за задушаване, е това, което дава на бирията дълбокия, сложен червен цвят и вкус, вместо плоска, еднообразна лютивина.",
      steps: [
        "Препечете гуахийо, анчо и чили де арбол в сух тиган на среден огън 2-3 минути, притискайки ги плоски, докато замиришат и леко потъмнеят - препичането на чушките първо е това, което дава на бирията дълбокия, сложен червен цвят, вместо плоска, еднообразна лютивина.",
        "Накиснете препечените чушки в гореща вода за 15 минути, докато омекнат, после отцедете.",
        "Пуснете омекналите чушки с нарязания на четвъртинки лук, чесъна, доматите, кимиона и оригано, добавяйки малко вода при нужда, в гладка, гъста паста.",
        "Подправете говеждите парчета със сол, после ги запържете в голяма тенджера на силен огън, докато се зачервят от всички страни.",
        "Добавете чили пастата, канелената пръчка, дафиновите листа и говеждия бульон в тенджерата с месото. Оставете да заври, после намалете огъня и гответе на слаб огън, покрито, 3-3.5 часа, докато говеждото стане напълно крехко.",
        "Извадете месото и го накъсайте с две вилици. Обирайте мазнината от повърхността на течността за задушаване (консомето) и запазете част от мазнината отделно.",
        "Потопете всяка тортила в консомето, за да я покриете, после напълнете с накъсаното говеждо и сирене, и сгънете наполовина.",
        "Загрейте запазената мазнина в тиган и запържете напълнените тортили по 2-3 минути от всяка страна, докато станат хрупкави, а сиренето се разтопи.",
        "Сервирайте такосите с топлото консоме за топене, гарнирани с кориандър, нарязан лук и резени лайм.",
      ],
      ingredients: [
        "1.4 кг говеждо плешка, нарязано на едри парчета",
        "4 чушки гуахийо, без дръжки и семки",
        "3 чушки анчо, без дръжки и семки",
        "2 чушки чили де арбол, без дръжки",
        "1 лук, нарязан на четвъртинки",
        "6 скилидки чесън",
        "2 домата",
        "1 канелена пръчка",
        "2 дафинови листа",
        "1 с.л. кимион",
        "1 с.л. риган",
        "6 чаши говежди бульон",
        "16 царевични тортили",
        "225 г сирене оахака, настъргано",
        "1/2 чаша кориандър, нарязан",
        "1 лук, ситно нарязан, за сервиране",
        "2 лайма, нарязани на резени",
        "Сол на вкус",
      ],
    },
  },
  {
    slug: "borscht",
    title: "Borscht",
    description:
      "Ukraine's iconic beet soup, built on a base of beets and carrots sautéed together until deeply caramelized before the broth goes in - this sautéing step, called zazharka, is what gives borscht its rich color and depth of flavor, and a splash of vinegar stirred in near the end is what keeps the earthy sweetness of the beets balanced instead of one-note.",
    imageEmoji: "🍲",
    cookTimeMinutes: 90,
    servings: 6,
    ingredients: [
      { text: "1.5 lb beef chuck, cut into chunks", ingredient: "beef chuck", quantity: 1.5 },
      { text: "8 cups water", ingredient: "water", quantity: 8 },
      { text: "3 beets, peeled and grated", ingredient: "beets", quantity: 3 },
      { text: "2 carrots, grated", ingredient: "carrot", quantity: 2 },
      { text: "1 onion, chopped", ingredient: "onion", quantity: 1 },
      { text: "2 potatoes, cubed", ingredient: "potato", quantity: 2 },
      { text: "2 cups cabbage, shredded", ingredient: "cabbage", quantity: 2 },
      { text: "2 tbsp tomato paste", ingredient: "tomato paste", quantity: 2 },
      { text: "3 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 3 },
      { text: "2 cloves garlic, minced", ingredient: "garlic", quantity: 2 },
      { text: "1 tbsp vinegar", ingredient: "vinegar", quantity: 1 },
      { text: "2 bay leaves", ingredient: "bay leaves", quantity: 2 },
      { text: "1/4 cup dill, chopped", ingredient: "dill", quantity: 0.25 },
      { text: "Sour cream, for serving", ingredient: "sour cream", quantity: null },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "Pepper to taste", ingredient: "pepper", quantity: null },
    ],
    steps: [
      "Place the beef in a large pot with the water and bay leaves, bring to a boil, skimming off any foam, then reduce heat and simmer for 45-60 minutes, until the beef is tender. Remove the beef, shred or cube it, and set aside, keeping the broth in the pot.",
      "Heat the oil in a skillet and sauté the grated beets and carrots together over medium heat for 10-12 minutes, until deeply softened and caramelized - this step, called zazharka, is what gives borscht its rich color and depth of flavor rather than a thin, watery one.",
      "Add the onion to the skillet and cook for 3-4 minutes more, then stir in the tomato paste and garlic and cook for 1 minute.",
      "Add the potatoes to the simmering broth and cook for 10 minutes, then add the cabbage and the sautéed beet mixture.",
      "Simmer for 15-20 minutes, until the potatoes and cabbage are tender.",
      "Return the shredded beef to the pot, stir in the vinegar - which keeps the earthy sweetness of the beets balanced instead of one-note - and season with salt and pepper.",
      "Simmer for 5 more minutes, then discard the bay leaves.",
      "Ladle into bowls and top each with a dollop of sour cream and a sprinkle of fresh dill.",
    ],
    tags: ["dinner", "lunch"],
    bg: {
      title: "Борш",
      description:
        "Емблематичната украинска супа от цвекло, изградена на основа от цвекло и моркови, запържени заедно, докато дълбоко карамелизират, преди да се добави бульонът - тази стъпка на запържване, наречена зажарка, е това, което дава на борша богатия му цвят и дълбочина на вкуса, а струйка оцет, разбъркана към края, е това, което пази земната сладост на цвеклото балансирана, вместо еднообразна.",
      steps: [
        "Поставете говеждото в голяма тенджера с водата и дафиновите листа, оставете да заври, обирайки евентуалната пяна, после намалете огъня и гответе на слаб огън 45-60 минути, докато говеждото омекне. Извадете месото, накъсайте го или нарежете на кубчета, и оставете настрана, като запазите бульона в тенджерата.",
        "Загрейте олиото в тиган и запържете настърганото цвекло и моркови заедно на среден огън 10-12 минути, докато дълбоко омекнат и карамелизират - тази стъпка, наречена зажарка, е това, което дава на борша богатия му цвят и дълбочина на вкуса, вместо рехав, воднист резултат.",
        "Добавете лука в тигана и гответе още 3-4 минути, после разбъркайте доматеното пюре и чесъна и гответе 1 минута.",
        "Добавете картофите в къкрещия бульон и гответе 10 минути, после добавете зелето и запържената цвеклова смес.",
        "Гответе на слаб огън 15-20 минути, докато картофите и зелето омекнат.",
        "Върнете накъсаното говеждо в тенджерата, разбъркайте оцета - който пази земната сладост на цвеклото балансирана, вместо еднообразна - и подправете със сол и пипер.",
        "Гответе на слаб огън още 5 минути, после изхвърлете дафиновите листа.",
        "Разпределете в купички и покрийте всяка с лъжица заквасена сметана и поръсен пресен копър.",
      ],
      ingredients: [
        "700 г говеждо плешка, нарязано на парчета",
        "8 чаши вода",
        "3 цвекла, обелени и настъргани",
        "2 моркова, настъргани",
        "1 лук, нарязан",
        "2 картофа, нарязани на кубчета",
        "2 чаши зеле, нарязано",
        "2 с.л. доматено пюре",
        "3 с.л. олио",
        "2 скилидки чесън, ситно нарязани",
        "1 с.л. оцет",
        "2 дафинови листа",
        "1/4 чаша копър, нарязан",
        "Заквасена сметана, за сервиране",
        "Сол на вкус",
        "Черен пипер на вкус",
      ],
    },
  },
  {
    slug: "tempura",
    title: "Tempura",
    description:
      "Japan's featherlight fried shrimp and vegetables, coated in a barely-mixed, ice-cold batter and fried until crisp but pale gold - keeping the batter ice-cold and lumpy rather than smooth is what prevents the flour's gluten from developing, which is exactly what gives tempura its shatteringly light, non-greasy crust instead of a heavy, bread-like one.",
    imageEmoji: "🍤",
    cookTimeMinutes: 40,
    servings: 4,
    ingredients: [
      { text: "12 shrimp, peeled and deveined, tails on", ingredient: "shrimp", quantity: 12 },
      { text: "1 sweet potato, sliced", ingredient: "sweet potato", quantity: 1 },
      { text: "1 zucchini, sliced", ingredient: "zucchini", quantity: 1 },
      { text: "1 bell peppers, sliced", ingredient: "bell peppers", quantity: 1 },
      { text: "1 cup flour", ingredient: "flour", quantity: 1 },
      { text: "1 egg", ingredient: "eggs", quantity: 1 },
      { text: "1 cup ice water", ingredient: "water", quantity: 1 },
      { text: "4 cups vegetable oil, for frying", ingredient: "vegetable oil", quantity: 4 },
      { text: "1/2 cup dashi", ingredient: "dashi", quantity: 0.5 },
      { text: "2 tbsp soy sauce", ingredient: "soy sauce", quantity: 2 },
      { text: "2 tbsp mirin", ingredient: "mirin", quantity: 2 },
      { text: "2 tbsp daikon, grated", ingredient: "daikon", quantity: 2 },
    ],
    steps: [
      "Combine the dashi, soy sauce, and mirin in a small pot, bring to a brief simmer, then remove from heat and let cool - this is the dipping sauce, tentsuyu.",
      "Pat the shrimp and vegetables completely dry with paper towels - any surface moisture will make the batter slide off or cause dangerous oil splatter.",
      "Heat the oil in a deep, heavy pot to 350°F.",
      "Just before frying, whisk the egg into the ice water, then add the flour all at once and stir with just a few strokes - the batter should still be lumpy; overmixing develops gluten, which is what makes tempura heavy instead of light and crisp.",
      "Working in small batches, dip the shrimp and vegetable pieces into the batter and lower them gently into the hot oil.",
      "Fry for 1-2 minutes, until the batter is crisp and just barely golden - real tempura should stay pale, not deep brown.",
      "Drain on a wire rack (not paper towels, which trap steam and soften the crust).",
      "Serve immediately with the warm tentsuyu dipping sauce and grated daikon.",
    ],
    tags: ["dinner", "asian"],
    bg: {
      title: "Темпура",
      description:
        "Японските леки като перце пържени скариди и зеленчуци, покрити с едва размесено, ледено студено тесто и изпържени до хрупкаво, но бледо златисто - поддържането на тестото ледено студено и на бучки, вместо гладко, е това, което предотвратява развитието на глутена в брашното, което е точно това, което дава на темпурата нейната пращящо лека, немазна коричка, вместо тежка, подобна на хляб.",
      steps: [
        "Съберете дашито, соевия сос и мирина в малка тенджера, оставете да заврат за кратко, после свалете от огъня и оставете да изстинат - това е сосът за топене, тенцую.",
        "Подсушете скаридите и зеленчуците напълно с хартиени кърпи - всяка повърхностна влага ще накара тестото да се плъзне или ще причини опасно пръскане на олиото.",
        "Загрейте олиото в дълбока, тежка тенджера до 175°C.",
        "Точно преди пържене, разбийте яйцето в ледената вода, после добавете брашното наведнъж и разбъркайте само с няколко движения - тестото трябва да остане на бучки; прекомерното разбъркване развива глутена, което е това, което прави темпурата тежка, вместо лека и хрупкава.",
        "Работейки на малки порции, потапяйте парчетата скариди и зеленчуци в тестото и ги спускайте внимателно в горещото олио.",
        "Пържете 1-2 минути, докато тестото стане хрупкаво и едва позлатяло - истинската темпура трябва да остане бледа, не дълбоко кафява.",
        "Отцедете върху решетка (не хартиени кърпи, които задържат парата и омекотяват коричката).",
        "Сервирайте веднага с топлия сос тенцую и настърган дайкон.",
      ],
      ingredients: [
        "12 скариди, обелени и почистени, с опашки",
        "1 сладък картоф, нарязан",
        "1 тиквичка, нарязана",
        "1 чушка, нарязана",
        "1 чаша брашно",
        "1 яйце",
        "1 чаша ледена вода",
        "4 чаши олио за пържене",
        "1/2 чаша даши",
        "2 с.л. соев сос",
        "2 с.л. мирин",
        "2 с.л. дайкон, настърган",
      ],
    },
  },
  {
    slug: "takoyaki",
    title: "Takoyaki",
    description:
      "Japanese octopus balls cooked in a special molded pan, turned repeatedly with skewers rather than flipped once, so each ball builds up in layers into a perfect sphere - rotating the balls a quarter-turn every couple of minutes, letting excess raw batter pour out and re-set each time, is what gives takoyaki its signature crisp shell around a molten, custardy center.",
    imageEmoji: "🐙",
    cookTimeMinutes: 45,
    servings: 4,
    ingredients: [
      { text: "1 cup flour", ingredient: "flour", quantity: 1 },
      { text: "2 cups dashi", ingredient: "dashi", quantity: 2 },
      { text: "2 eggs", ingredient: "eggs", quantity: 2 },
      { text: "1 tbsp soy sauce", ingredient: "soy sauce", quantity: 1 },
      { text: "1 cup octopus, cooked and diced", ingredient: "octopus", quantity: 1 },
      { text: "3 scallions, chopped", ingredient: "scallion", quantity: 3 },
      { text: "2 tbsp vegetable oil, for the pan", ingredient: "vegetable oil", quantity: 2 },
      { text: "1/4 cup okonomiyaki sauce", ingredient: "okonomiyaki sauce", quantity: 0.25 },
      { text: "2 tbsp mayonnaise", ingredient: "mayonnaise", quantity: 2 },
      { text: "2 tbsp bonito flakes", ingredient: "bonito flakes", quantity: 2 },
      { text: "1 tbsp beni shoga, chopped", ingredient: "beni shoga", quantity: 1 },
    ],
    steps: [
      "Whisk the flour, dashi, eggs, and soy sauce together into a thin, pourable batter. Let rest for 30 minutes so the flour fully hydrates.",
      "Heat a takoyaki pan over medium-high heat until smoking hot, then brush the oil generously into each mold.",
      "Fill each mold completely with batter, letting it overflow slightly onto the surface of the pan, then drop a piece of octopus and a pinch of scallion into each.",
      "Once the batter at the bottom of each mold is set and lightly crisp, use skewers or chopsticks to cut and rotate each ball a quarter turn, tucking in the overflow batter as you go.",
      "Continue rotating each ball a quarter turn every 2-3 minutes, letting any excess raw batter pour out and re-set each time - this repeated rotation, not a single flip, is what builds takoyaki into a round shell around a molten center.",
      "Keep rotating for 8-10 minutes total, until each ball is a crisp, golden sphere.",
      "Transfer to a plate and drizzle with the okonomiyaki sauce and mayonnaise, then top with bonito flakes and beni shoga.",
      "Serve immediately, while the centers are still molten - the bonito flakes will visibly wave in the residual heat.",
    ],
    tags: ["snack", "asian"],
    bg: {
      title: "Такояки",
      description:
        "Японски топчета от октопод, приготвени в специален тиган с вдлъбнатини, обръщани многократно с шишчета, вместо еднократно, така че всяко топче се изгражда на слоеве в перфектна сфера - завъртането на топчетата на четвърт оборот на всеки няколко минути, оставяйки излишното сурово тесто да изтече и да се стегне отново всеки път, е това, което дава на такоякито характерната му хрупкава черупка около разтопен, кремообразен център.",
      steps: [
        "Разбийте брашното, дашито, яйцата и соевия сос заедно в тънко, лееещо се тесто. Оставете да почине 30 минути, за да се хидратира брашното напълно.",
        "Загрейте тиган за такояки на среден-силен огън, докато стане пушещо горещ, после намажете щедро олио във всяка вдлъбнатина.",
        "Напълнете всяка вдлъбнатина напълно с тесто, оставяйки го леко да прелее върху повърхността на тигана, после пуснете парче октопод и щипка пресен лук във всяка.",
        "След като тестото на дъното на всяка вдлъбнатина се стегне и леко захрупне, използвайте шишчета или клечки за хранене, за да срежете и завъртите всяко топче на четвърт оборот, прибирайки прелялото тесто, докато работите.",
        "Продължавайте да въртите всяко топче на четвърт оборот на всеки 2-3 минути, оставяйки излишното сурово тесто да изтече и да се стегне отново всеки път - това повтарящо се въртене, не еднократно обръщане, е това, което изгражда такоякито в кръгла черупка около разтопен център.",
        "Продължавайте да въртите общо 8-10 минути, докато всяко топче стане хрупкава, златиста сфера.",
        "Прехвърлете в чиния и полейте със соса окономияки и майонезата, после поръсете с люспи бонито и бени шога.",
        "Сервирайте веднага, докато центровете са все още разтопени - люспите бонито видимо ще се вълнуват в остатъчната топлина.",
      ],
      ingredients: [
        "1 чаша брашно",
        "2 чаши даши",
        "2 яйца",
        "1 с.л. соев сос",
        "1 чаша октопод, сготвен и нарязан на кубчета",
        "3 стръка пресен лук, нарязани",
        "2 с.л. олио, за тигана",
        "1/4 чаша сос окономияки",
        "2 с.л. майонеза",
        "2 с.л. люспи бонито",
        "1 с.л. бени шога, нарязана",
      ],
    },
  },
  {
    slug: "kake-udon",
    title: "Kake Udon (Japanese Udon Noodle Soup)",
    description:
      "The simplest form of Japanese udon noodle soup - thick, chewy noodles in a clean dashi broth seasoned with just soy sauce and mirin - never letting the dashi come to a full boil while steeping the bonito flakes is what keeps the broth clear and delicate instead of turning cloudy and bitter.",
    imageEmoji: "🍜",
    cookTimeMinutes: 30,
    servings: 2,
    ingredients: [
      { text: "4 cups dashi", ingredient: "dashi", quantity: 4 },
      { text: "3 tbsp soy sauce", ingredient: "soy sauce", quantity: 3 },
      { text: "2 tbsp mirin", ingredient: "mirin", quantity: 2 },
      { text: "1 lb udon noodles", ingredient: "udon noodles", quantity: 1 },
      { text: "2 scallions, thinly sliced", ingredient: "scallion", quantity: 2 },
      { text: "2 tbsp bonito flakes, for garnish", ingredient: "bonito flakes", quantity: 2 },
    ],
    steps: [
      "Heat the dashi in a pot over medium heat until small bubbles just begin to appear around the edges - never let it come to a full boil, since boiling the bonito-based dashi is what turns it cloudy and bitter instead of clean and delicate.",
      "Stir in the soy sauce and mirin to make the kakejiru broth, and keep it warm over low heat.",
      "Bring a separate large pot of water to a boil and cook the udon noodles according to the package directions, stirring occasionally with chopsticks to keep them separated.",
      "Drain the noodles and divide them between two serving bowls.",
      "Ladle the hot broth over the noodles, filling each bowl.",
      "Top with the sliced scallions and a sprinkle of bonito flakes, and serve immediately while hot.",
    ],
    tags: ["dinner", "asian", "quick"],
    bg: {
      title: "Каке удон (Японска супа с юфка удон)",
      description:
        "Най-простата форма на японска супа с юфка удон - дебели, дъвчащи се юфки в чист бульон от даши, подправен само със соев сос и мирин - никога да не оставяте дашито да заври напълно, докато отлежава с люспите бонито, е това, което пази бульона бистър и деликатен, вместо да помътнее и стане горчив.",
      steps: [
        "Загрейте дашито в тенджера на среден огън, докато точно започнат да се появяват малки мехурчета по краищата - никога не го оставяйте да заври напълно, тъй като кипенето на дашито на основата на бонито е това, което го прави мътно и горчиво, вместо чисто и деликатно.",
        "Разбъркайте соевия сос и мирина, за да направите бульона какеджиру, и го дръжте топъл на слаб огън.",
        "Оставете отделна голяма тенджера с вода да заври и сварете юфката удон според указанията на опаковката, разбърквайки от време на време с клечки за хранене, за да останат разделени.",
        "Отцедете юфката и я разпределете в две купички за сервиране.",
        "Залейте горещия бульон върху юфката, пълнейки всяка купичка.",
        "Гарнирайте с нарязания пресен лук и поръсени люспи бонито, и сервирайте веднага, докато е горещо.",
      ],
      ingredients: [
        "4 чаши даши",
        "3 с.л. соев сос",
        "2 с.л. мирин",
        "450 г юфка удон",
        "2 стръка пресен лук, нарязани на тънко",
        "2 с.л. люспи бонито, за гарнитура",
      ],
    },
  },
  {
    slug: "yorkshire-pudding",
    title: "Yorkshire Pudding",
    description:
      "The tall, crisp-edged British side that puffs up dramatically in a blazing-hot oven - pouring cold batter into smoking-hot beef drippings is what creates the burst of steam that makes Yorkshire pudding rise, and keeping the oven door shut the entire time is just as critical, since a single blast of cool air can collapse the puddings in seconds.",
    imageEmoji: "🍞",
    cookTimeMinutes: 40,
    servings: 6,
    ingredients: [
      { text: "1 cup flour", ingredient: "flour", quantity: 1 },
      { text: "3 eggs", ingredient: "eggs", quantity: 3 },
      { text: "1 cup milk", ingredient: "milk", quantity: 1 },
      { text: "1/2 tsp salt", ingredient: "salt", quantity: 0.5 },
      { text: "6 tbsp beef drippings", ingredient: "beef drippings", quantity: 6 },
    ],
    steps: [
      "Whisk the flour, eggs, milk, and salt together into a smooth, thin batter. Cover and let rest at room temperature for at least 30 minutes, ideally longer - resting lets the flour fully absorb the liquid, which is what gives the finished pudding a lighter texture.",
      "Preheat the oven to 450°F, as hot as it will reliably hold.",
      "Divide the beef drippings evenly among the cups of a muffin tin or individual Yorkshire pudding tins, then place the tin in the oven for 8-10 minutes, until the fat is smoking hot - the fat has to be genuinely smoking, not just warm, for the puddings to rise properly.",
      "Working quickly, pull the hot tin out and pour the batter evenly into each cup, filling about halfway - the batter should sizzle loudly as it hits the fat.",
      "Return the tin to the oven immediately and bake for 20-25 minutes, without opening the oven door at any point - a single blast of cool air is enough to collapse the puddings in seconds.",
      "The puddings are done when they've puffed up tall and turned deep golden brown and crisp.",
      "Serve immediately, straight from the oven, alongside a roast dinner.",
    ],
    tags: ["dinner"],
    bg: {
      title: "Йоркширски пудинг",
      description:
        "Високата, хрупкава по краищата британска гарнитура, която драматично се издува в пламтящо гореща фурна - изсипването на студено тесто в пушещо гореща говежда мазнина е това, което създава изблика пара, който кара йоркширския пудинг да се издигне, а държането на вратичката на фурната затворена през цялото време е също толкова критично, тъй като един-единствен полъх студен въздух може да срине пудингите за секунди.",
      steps: [
        "Разбийте брашното, яйцата, млякото и солта заедно в гладко, рехаво тесто. Покрийте и оставете да почине на стайна температура поне 30 минути, най-добре по-дълго - почивката позволява на брашното напълно да поеме течността, което е това, което дава на готовия пудинг по-лека текстура.",
        "Загрейте фурната на 230°C, колкото се може по-горещо.",
        "Разпределете говеждата мазнина равномерно в чашките на тава за мъфини или отделни тавички за йоркширски пудинг, после поставете тавата във фурната за 8-10 минути, докато мазнината стане пушещо гореща - мазнината трябва наистина да пуши, не само да е топла, за да могат пудингите да се издигнат правилно.",
        "Работейки бързо, извадете горещата тава и изсипете тестото равномерно във всяка чашка, пълнейки около наполовина - тестото трябва силно да засъска, щом докосне мазнината.",
        "Върнете тавата във фурната веднага и печете 20-25 минути, без да отваряте вратичката на фурната в нито един момент - един-единствен полъх студен въздух е достатъчен, за да срине пудингите за секунди.",
        "Пудингите са готови, когато са се издули високо и станали дълбоко златисто кафяви и хрупкави.",
        "Сервирайте веднага, направо от фурната, заедно с печено месо за неделен обяд.",
      ],
      ingredients: [
        "1 чаша брашно",
        "3 яйца",
        "1 чаша мляко",
        "1/2 ч.л. сол",
        "6 с.л. говежда мазнина",
      ],
    },
  },
];

async function main() {
  for (const recipe of newRecipes) {
    const created = await prisma.recipe.create({
      data: {
        slug: recipe.slug,
        title: recipe.title,
        description: recipe.description,
        imageEmoji: recipe.imageEmoji,
        cookTimeMinutes: recipe.cookTimeMinutes,
        servings: recipe.servings,
        steps: JSON.stringify(recipe.steps),
        tags: JSON.stringify(recipe.tags),
      },
    });

    for (let i = 0; i < recipe.ingredients.length; i++) {
      const { text, ingredient, quantity } = recipe.ingredients[i];
      const ingredientRow = await prisma.ingredient.upsert({
        where: { name: ingredient },
        update: {},
        create: { name: ingredient },
      });
      await prisma.recipeIngredient.create({
        data: {
          recipeId: created.id,
          ingredientId: ingredientRow.id,
          displayText: text,
          quantity,
          position: i,
        },
      });
    }
    console.log(`Created ${recipe.slug}`);
  }
  console.log(`Created ${newRecipes.length} recipes total.`);

  // runTranslations disconnects prisma when done, so it must run last.
  await runTranslations(newRecipes.map((r) => ({ slug: r.slug, ...r.bg })));
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
