import { prisma, runTranslations } from "./translate-lib.mjs";

// 10 tomato-forward recipes from different cuisines, each web-researched for
// authentic technique before writing, per standing instructions.
const newRecipes = [
  {
    slug: "pappa-al-pomodoro",
    title: "Pappa al Pomodoro",
    description:
      "Tuscan tomato-bread soup that's really more of a thick porridge - stale country bread is torn into hot tomato broth, then covered and rested off the heat so it fully absorbs the liquid instead of staying soupy or turning to mush.",
    imageEmoji: "🍅",
    cookTimeMinutes: 40,
    servings: 4,
    ingredients: [
      { text: "6 ripe tomatoes (or 2 cans whole peeled tomatoes), crushed by hand", ingredient: "tomato", quantity: 6 },
      { text: "4 cups stale country bread, torn into chunks", ingredient: "bread", quantity: 4 },
      { text: "1/3 cup olive oil, plus more for drizzling", ingredient: "olive oil", quantity: 0.33 },
      { text: "4 cloves garlic, sliced", ingredient: "garlic", quantity: 4 },
      { text: "3 cups vegetable broth", ingredient: "vegetable broth", quantity: 3 },
      { text: "1/2 tsp red pepper flakes", ingredient: "red pepper flakes", quantity: 0.5 },
      { text: "1 cup fresh basil leaves, torn, divided", ingredient: "basil", quantity: 1 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
    ],
    steps: [
      "Heat the olive oil in a large pot and cook the garlic and red pepper flakes over low heat until fragrant, about 1 minute - do not let the garlic brown or it turns bitter.",
      "Add the tomatoes, crushing them with your hands or a spoon as they go in, and simmer for 15 minutes until they break down into a chunky sauce.",
      "Stir in the vegetable broth and bring to a gentle simmer.",
      "Add the torn stale bread and stir to coat it in the tomato broth.",
      "Cover the pot and let it rest off the heat for 10-15 minutes so the bread fully absorbs the liquid and softens into a thick, porridge-like consistency - this resting step is what gives pappa al pomodoro its signature texture.",
      "Stir in most of the basil and season with salt to taste.",
      "Ladle into bowls, drizzle with olive oil, and top with the remaining basil.",
    ],
    tags: ["dinner", "italian", "vegetarian"],
    bg: {
      title: "Папа ал Помодоро",
      description:
        "Тосканска доматено-хлебна супа, която всъщност е повече гъста каша - стар селски хляб се накъсва в горещ доматен бульон, после се покрива и се оставя да почине настрана от котлона, за да попие напълно течността, вместо да остане рядка или да се разпадне.",
      steps: [
        "Загрейте зехтина в голяма тенджера и запържете чесъна и червения пипер на люспи на слаб огън за около 1 минута, докато замирише - не оставяйте чесъна да покафенее, защото ще стане горчив.",
        "Добавете доматите, смачквайки ги с ръце или лъжица, докато ги слагате, и къкрете 15 минути, докато се разпаднат в гъст сос.",
        "Прибавете зеленчуковия бульон и оставете да къкри леко.",
        "Добавете накъсания стар хляб и разбъркайте, за да се покрие с доматения бульон.",
        "Покрийте тенджерата и оставете да почине настрана от котлона за 10-15 минути, за да попие хлябът напълно течността и да омекне до гъста, кашеста консистенция - тази почивка е тайната на характерната текстура на папа ал помодоро.",
        "Разбъркайте по-голямата част от босилека и подправете със сол на вкус.",
        "Сипете в купички, полейте със зехтин и гарнирайте с останалия босилек.",
      ],
      ingredients: [
        "6 узрели домата (или 2 консерви цели белени домати), смачкани на ръка",
        "4 чаши стар селски хляб, накъсан на парчета",
        "1/3 чаша зехтин, плюс още за поливане",
        "4 скилидки чесън, нарязани на резенчета",
        "3 чаши зеленчуков бульон",
        "1/2 ч.л. червен пипер на люспи",
        "1 чаша свеж босилек, накъсан, разделен",
        "Сол на вкус",
      ],
    },
  },
  {
    slug: "pasta-puttanesca",
    title: "Pasta alla Puttanesca",
    description:
      "Bold Neapolitan pantry pasta built on garlic-infused oil, anchovies melted until they dissolve into savory depth rather than fishiness, plus briny Gaeta olives and capers - a punchy sauce that comes together faster than the pasta water boils.",
    imageEmoji: "🍝",
    cookTimeMinutes: 25,
    servings: 4,
    ingredients: [
      { text: "1 lb spaghetti", ingredient: "spaghetti", quantity: 1 },
      { text: "1/4 cup olive oil", ingredient: "olive oil", quantity: 0.25 },
      { text: "4 cloves garlic, lightly crushed", ingredient: "garlic", quantity: 4 },
      { text: "6 anchovy fillets, chopped", ingredient: "anchovy", quantity: 6 },
      { text: "1/2 cup black olives (preferably Gaeta), pitted", ingredient: "black olives", quantity: 0.5 },
      { text: "3 tbsp capers, rinsed", ingredient: "capers", quantity: 3 },
      { text: "1/2 tsp red pepper flakes", ingredient: "red pepper flakes", quantity: 0.5 },
      { text: "1 can crushed tomatoes", ingredient: "tomato", quantity: 1 },
      { text: "1/4 cup chopped parsley", ingredient: "parsley", quantity: 0.25 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
    ],
    steps: [
      "Bring a large pot of salted water to a boil and cook the spaghetti until al dente, reserving 1 cup of pasta water before draining.",
      "While the pasta cooks, heat the olive oil in a large skillet over medium heat and add the garlic, keeping it whole or lightly crushed so it flavors the oil without burning.",
      "Once the garlic starts to sizzle, remove it, lower the heat, and add the anchovies, stirring until they dissolve into the oil, about 1 minute.",
      "Add the capers and olives and sauté for 2 minutes.",
      "Stir in the crushed tomatoes and red pepper flakes, bring to a simmer, and cook uncovered for 10 minutes until the sauce thickens slightly.",
      "Toss the drained spaghetti into the sauce with a splash of pasta water, tossing until glossy.",
      "Stir in the parsley, taste and adjust salt (the anchovies, olives, and capers are already salty), and serve immediately.",
    ],
    tags: ["dinner", "italian"],
    bg: {
      title: "Паста ала Путанеска",
      description:
        "Дръзка неаполитанска паста от домашни продукти, изградена върху зехтин, ароматизиран с чесън, аншоа, разтопени докато се стопят в наситен вкус вместо в рибен привкус, плюс солени маслини Гаета и капари - остър сос, който се приготвя по-бързо, отколкото завира водата за пастата.",
      steps: [
        "Заврете голяма тенджера подсолена вода и сварете спагетите до ал денте, като запазите 1 чаша от водата за пастата преди отцеждане.",
        "Докато пастата се вари, загрейте зехтина в голям тиган на среден огън и добавете чесъна, оставяйки го цял или леко смачкан, за да ароматизира олиото, без да изгори.",
        "Щом чесънът започне да съска, извадете го, намалете котлона и добавете аншоата, разбърквайки, докато се разтопят в олиото, около 1 минута.",
        "Добавете капарите и маслините и запържете за 2 минути.",
        "Прибавете нарязаните домати и червения пипер на люспи, оставете да заври и гответе без капак 10 минути, докато сосът леко се сгъсти.",
        "Прехвърлете отцедените спагети в соса с малко от водата за пастата, разбърквайки, докато станат лъскави.",
        "Разбъркайте магданоза, опитайте и коригирайте солта (аншоата, маслините и капарите вече са солени) и сервирайте веднага.",
      ],
      ingredients: [
        "1 lb (450г) спагети",
        "1/4 чаша зехтин",
        "4 скилидки чесън, леко смачкани",
        "6 филенца аншоа, нарязани",
        "1/2 чаша черни маслини (за предпочитане Гаета), обезкостени",
        "3 с.л. капари, изплакнати",
        "1/2 ч.л. червен пипер на люспи",
        "1 консерва нарязани домати",
        "1/4 чаша нарязан магданоз",
        "Сол на вкус",
      ],
    },
  },
  {
    slug: "menemen",
    title: "Menemen",
    description:
      "Turkish breakfast of eggs folded straight into a butter-cooked pepper and tomato mixture until soft-curdled and creamy - unlike shakshuka's whole poached eggs, menemen's eggs are stirred through the sauce, giving it a completely different texture.",
    imageEmoji: "🍳",
    cookTimeMinutes: 15,
    servings: 2,
    ingredients: [
      { text: "3 tbsp butter", ingredient: "butter", quantity: 3 },
      { text: "1 green bell pepper, diced (or Turkish sivri biber if available)", ingredient: "green bell pepper", quantity: 1 },
      { text: "4 tomatoes, diced", ingredient: "tomato", quantity: 4 },
      { text: "1/2 tsp salt", ingredient: "salt", quantity: 0.5 },
      { text: "4 eggs, lightly beaten", ingredient: "eggs", quantity: 4 },
      { text: "Black pepper to taste", ingredient: "black pepper", quantity: null },
      { text: "Crumbled feta cheese, for serving (optional)", ingredient: "feta cheese", quantity: null },
    ],
    steps: [
      "Melt the butter in a skillet over medium heat and cook the diced green pepper until softened, about 5 minutes.",
      "Add the tomatoes and salt, and cook, stirring occasionally, until they break down into a thick, jammy sauce, 8-10 minutes.",
      "Pour in the beaten eggs and immediately begin folding them into the tomato mixture with a spatula - unlike shakshuka, the eggs are stirred through rather than left whole, so they turn soft and slightly curdled rather than poached.",
      "Cook, stirring gently, until the eggs are just set but still creamy, about 1-2 minutes - remove from the heat while they still look slightly underdone, since they'll keep cooking in the residual heat.",
      "Season with black pepper, top with crumbled feta if using, and serve immediately with crusty bread.",
    ],
    tags: ["breakfast", "vegetarian"],
    bg: {
      title: "Менемен",
      description:
        "Турска закуска от яйца, разбъркани направо в задушена с масло смес от чушки и домати до меко пресечени и кремообразни - за разлика от целите яйца в шакшуката, тук яйцата се разбъркват в соса, което дава напълно различна текстура.",
      steps: [
        "Разтопете маслото в тиган на среден огън и запържете нарязаната зелена чушка до омекване, около 5 минути.",
        "Добавете доматите и солта и гответе, разбърквайки от време на време, докато се разпаднат в гъст, конфитюрен сос, 8-10 минути.",
        "Изсипете разбитите яйца и веднага започнете да ги вкарвате в доматената смес с шпатула - за разлика от шакшуката, яйцата се разбъркват, вместо да останат цели, така че стават меки и леко пресечени вместо поширани.",
        "Гответе, разбърквайки леко, докато яйцата се стегнат, но останат кремообразни, около 1-2 минути - свалете от котлона, докато все още изглеждат леко недопечени, тъй като ще продължат да се готвят от остатъчната топлина.",
        "Подправете с черен пипер, поръсете с натрошено сирене, ако използвате, и сервирайте веднага с хрупкав хляб.",
      ],
      ingredients: [
        "3 с.л. масло",
        "1 зелена чушка, нарязана на кубчета (или турска чушка сиври бибер, ако е налична)",
        "4 домата, нарязани на кубчета",
        "1/2 ч.л. сол",
        "4 яйца, леко разбити",
        "Черен пипер на вкус",
        "Натрошено сирене, за сервиране (по желание)",
      ],
    },
  },
  {
    slug: "tomato-rasam",
    title: "Tomato Rasam",
    description:
      "Tangy, peppery South Indian soup built from tamarind and tomato rather than tomato alone - a quick lentil-tomato base gets finished with a sizzling mustard-seed and curry-leaf tempering poured in right before serving, which is what gives real rasam its aroma.",
    imageEmoji: "🍲",
    cookTimeMinutes: 35,
    servings: 4,
    ingredients: [
      { text: "1/4 cup tamarind paste, dissolved in 2 cups warm water", ingredient: "tamarind paste", quantity: 0.25 },
      { text: "4 tomatoes, chopped", ingredient: "tomato", quantity: 4 },
      { text: "1/4 cup lentils (toor dal), rinsed", ingredient: "lentils", quantity: 0.25 },
      { text: "2 tsp rasam powder", ingredient: "rasam powder", quantity: 2 },
      { text: "1/2 tsp turmeric", ingredient: "turmeric", quantity: 0.5 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "2 tbsp ghee", ingredient: "ghee", quantity: 2 },
      { text: "1 tsp mustard seeds", ingredient: "mustard seeds", quantity: 1 },
      { text: "1/2 tsp cumin seeds", ingredient: "cumin seeds", quantity: 0.5 },
      { text: "2 dried red chilies", ingredient: "dried red chili", quantity: 2 },
      { text: "1 sprig curry leaves", ingredient: "curry leaves", quantity: 1 },
      { text: "1/4 tsp asafoetida (hing)", ingredient: "asafoetida", quantity: 0.25 },
      { text: "Fresh cilantro, chopped, for garnish", ingredient: "cilantro", quantity: null },
    ],
    steps: [
      "In a pot, cook the rinsed lentils with the turmeric and 2 cups of water until soft and starting to fall apart, about 15 minutes, then lightly mash them.",
      "Add the chopped tomatoes, tamarind water, rasam powder, and salt to the pot and simmer for 10 minutes until the tomatoes soften and the flavors meld - a properly made rasam should taste distinctly tangy from the tamarind, not just tomato-forward.",
      "In a small pan, heat the ghee and add the mustard seeds; once they start to pop, add the cumin seeds, dried red chilies, curry leaves, and asafoetida, and sizzle for 30 seconds until fragrant.",
      "Pour this tempering over the rasam and stir it in immediately so the aromatics don't burn.",
      "Simmer for 2 more minutes, taste and adjust salt and tang, and garnish with cilantro.",
      "Serve hot with steamed rice or on its own as a warming soup.",
    ],
    tags: ["dinner", "lunch", "vegetarian"],
    bg: {
      title: "Доматен Расам",
      description:
        "Пикантна, остра южноиндийска супа, изградена от тамаринд и домати, а не само от домати - бърза основа от леща и домати се завършва с цвъртяща подправка от синапено семе и къри листа, изсипана точно преди сервиране, което придава на истинския расам характерния му аромат.",
      steps: [
        "В тенджера сгответе изплакнатата леща с куркумата и 2 чаши вода, докато омекне и започне да се разпада, около 15 минути, после леко я смачкайте.",
        "Добавете нарязаните домати, тамариндовата вода, праха расам и солта в тенджерата и къкрете 10 минути, докато доматите омекнат и вкусовете се съчетаят - правилно приготвеният расам трябва да има отчетливо кисел вкус от тамаринда, а не само доматен.",
        "В малък тиган загрейте гхи и добавете синапеното семе; щом започне да пука, добавете кимион на семена, сушени червени чушки, къри листа и асафетида и запържете за 30 секунди, докато замирише.",
        "Изсипете тази подправка върху расама и веднага разбъркайте, за да не изгорят ароматите.",
        "Къкрете още 2 минути, опитайте и коригирайте солта и киселостта, и гарнирайте с кориандър.",
        "Сервирайте горещо с варен ориз или самостоятелно като топла супа.",
      ],
      ingredients: [
        "1/4 чаша тамариндова паста, разтворена в 2 чаши топла вода",
        "4 домата, нарязани",
        "1/4 чаша леща (тоор дал), изплакната",
        "2 ч.л. прах расам",
        "1/2 ч.л. куркума",
        "Сол на вкус",
        "2 с.л. гхи",
        "1 ч.л. синапено семе",
        "1/2 ч.л. кимион на семена",
        "2 сушени червени чушки",
        "1 клонче къри листа",
        "1/4 ч.л. асафетида (хинг)",
        "Свеж кориандър, нарязан, за гарнитура",
      ],
    },
  },
  {
    slug: "chakalaka",
    title: "Chakalaka",
    description:
      "South African tomato-and-vegetable relish that started as an improvised mineworkers' pot of whatever was on hand - carrots, peppers, and tomato simmered with curry spices, finished with the now-essential addition of canned baked beans for body.",
    imageEmoji: "🌶️",
    cookTimeMinutes: 30,
    servings: 6,
    ingredients: [
      { text: "3 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 3 },
      { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
      { text: "3 carrots, grated", ingredient: "carrot", quantity: 3 },
      { text: "2 bell peppers, diced", ingredient: "bell peppers", quantity: 2 },
      { text: "4 tomatoes, diced (or 1 can diced tomatoes)", ingredient: "tomato", quantity: 4 },
      { text: "3 cloves garlic, minced", ingredient: "garlic", quantity: 3 },
      { text: "1 tbsp grated ginger", ingredient: "ginger", quantity: 1 },
      { text: "1 tsp chili powder", ingredient: "chili powder", quantity: 1 },
      { text: "1 tbsp curry powder", ingredient: "curry powder", quantity: 1 },
      { text: "1 tsp paprika", ingredient: "paprika", quantity: 1 },
      { text: "1 can baked beans", ingredient: "baked beans", quantity: 1 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
    ],
    steps: [
      "Heat the oil in a large pot and sauté the onion until translucent, about 5 minutes.",
      "Add the carrots and bell peppers and cook for 5 minutes until they begin to soften.",
      "Stir in the garlic, ginger, chili powder, curry powder, and paprika and cook for 1 minute until fragrant.",
      "Add the tomatoes and simmer for 10 minutes, stirring occasionally, until they break down into a thick sauce.",
      "Stir in the baked beans - the not-quite-traditional but now-essential addition that gives chakalaka its body - and simmer for 5 more minutes.",
      "Season with salt and serve warm alongside pap, bread, or grilled meat.",
    ],
    tags: ["dinner", "lunch", "vegetarian"],
    bg: {
      title: "Чакалака",
      description:
        "Южноафрикански доматено-зеленчуков релиш, започнал като импровизирано гърне на миньори с каквото имало под ръка - моркови, чушки и домати, къкрещи с къри подправки, завършени с вече задължителната добавка от консервиран боб в доматен сос за плътност.",
      steps: [
        "Загрейте олиото в голяма тенджера и запържете лука до омекване, около 5 минути.",
        "Добавете морковите и чушките и гответе 5 минути, докато започнат да омекват.",
        "Прибавете чесъна, джинджифила, лютия червен пипер, къри на прах и паприката и гответе 1 минута, докато замирише.",
        "Добавете доматите и къкрете 10 минути, разбърквайки от време на време, докато се разпаднат в гъст сос.",
        "Прибавете консервирания боб в доматен сос - не съвсем традиционната, но вече задължителна добавка, която придава плътност на чакалаката - и къкрете още 5 минути.",
        "Подправете със сол и сервирайте топло с пап, хляб или печено месо.",
      ],
      ingredients: [
        "3 с.л. олио",
        "1 лук, нарязан на кубчета",
        "3 моркова, настъргани",
        "2 чушки, нарязани на кубчета",
        "4 домата, нарязани на кубчета (или 1 консерва нарязани домати)",
        "3 скилидки чесън, смлени",
        "1 с.л. настърган джинджифил",
        "1 ч.л. лют червен пипер на прах",
        "1 с.л. къри на прах",
        "1 ч.л. паприка",
        "1 консерва боб в доматен сос",
        "Сол на вкус",
      ],
    },
  },
  {
    slug: "salsa-roja",
    title: "Salsa Roja",
    description:
      "Fresh Mexican red salsa built on charred, not raw, vegetables - tomatoes, chilies, onion, and garlic are blackened on a hot dry skillet before blending, which is what turns them sweet and smoky instead of tasting like plain blended produce.",
    imageEmoji: "🌶️",
    cookTimeMinutes: 20,
    servings: 6,
    ingredients: [
      { text: "6 roma tomatoes", ingredient: "tomato", quantity: 6 },
      { text: "2 jalapeños (or serrano chilies)", ingredient: "jalapeno", quantity: 2 },
      { text: "1/2 onion", ingredient: "onion", quantity: 0.5 },
      { text: "3 cloves garlic, unpeeled", ingredient: "garlic", quantity: 3 },
      { text: "1/4 cup cilantro", ingredient: "cilantro", quantity: 0.25 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "1 tbsp lime juice (optional)", ingredient: "lime juice", quantity: 1 },
    ],
    steps: [
      "Heat a dry skillet or comal over medium-high heat and char the tomatoes, jalapeños, onion, and unpeeled garlic, turning occasionally, until blackened in spots and softened, about 8-10 minutes - this charring is what gives salsa roja its deep, slightly smoky flavor instead of tasting like plain blended tomatoes.",
      "Let the garlic cool slightly, then peel it.",
      "Transfer the charred tomatoes, chilies, onion, and garlic to a blender along with the cilantro and salt.",
      "Pulse until you reach your preferred texture - a few short pulses for a chunky salsa, longer for smooth.",
      "Stir in lime juice if using, then taste and adjust salt.",
      "Let the salsa rest for at least 15 minutes before serving so the flavors meld.",
    ],
    tags: ["snack", "mexican", "vegan", "vegetarian"],
    bg: {
      title: "Салса Роха",
      description:
        "Прясна мексиканска червена салса, приготвена от изпечени, а не сурови зеленчуци - домати, чушки, лук и чесън се почерняват на сух горещ тиган преди смилане, което ги прави сладки и леко димни, вместо да имат вкус на обикновени смлени продукти.",
      steps: [
        "Загрейте сух тиган или комал на среден до силен огън и изпечете доматите, лютите чушки, лука и необеления чесън, обръщайки от време на време, докато почернеят на места и омекнат, около 8-10 минути - това изпичане придава на салса роха дълбок, леко димен вкус, вместо да има вкус на обикновено смлени домати.",
        "Оставете чесъна да поизстине леко, после го обелете.",
        "Прехвърлете изпечените домати, чушки, лук и чесън в блендер заедно с кориандъра и солта.",
        "Пулсирайте, докато постигнете желаната текстура - няколко кратки пулсации за по-едра салса, по-дълго за гладка.",
        "Разбъркайте лимонов сок, ако използвате, после опитайте и коригирайте солта.",
        "Оставете салсата да почине поне 15 минути преди сервиране, за да се съчетаят вкусовете.",
      ],
      ingredients: [
        "6 домата тип рома",
        "2 люти чушки халапеньо (или серано)",
        "1/2 лук",
        "3 скилидки чесън, необелени",
        "1/4 чаша кориандър",
        "Сол на вкус",
        "1 с.л. лимонов сок (по желание)",
      ],
    },
  },
  {
    slug: "tomato-egg-stir-fry",
    title: "Tomato and Egg Stir-Fry",
    description:
      "China's everyday home-cooking staple, taught from parent to child as a first stir-fry - eggs are scrambled separately and set aside so they stay tender, then folded back into tomatoes cooked down with sugar and salt until juicy and jammy.",
    imageEmoji: "🍅",
    cookTimeMinutes: 15,
    servings: 2,
    ingredients: [
      { text: "4 eggs", ingredient: "eggs", quantity: 4 },
      { text: "1 tsp Shaoxing wine", ingredient: "shaoxing wine", quantity: 1 },
      { text: "1/2 tsp sesame oil", ingredient: "sesame oil", quantity: 0.5 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "4 tomatoes, cut into wedges", ingredient: "tomato", quantity: 4 },
      { text: "2 tbsp vegetable oil, divided", ingredient: "vegetable oil", quantity: 2 },
      { text: "1 tsp sugar", ingredient: "sugar", quantity: 1 },
      { text: "2 green onions, sliced", ingredient: "green onion", quantity: 2 },
    ],
    steps: [
      "Beat the eggs in a bowl with the Shaoxing wine, sesame oil, and a pinch of salt for about a minute until aerated and slightly foamy.",
      "Heat half the vegetable oil in a wok over high heat until shimmering, pour in the eggs, and scramble briefly until just barely set but still glossy; remove to a plate immediately so they don't overcook.",
      "Add the remaining oil to the wok and add the tomato wedges, cooking undisturbed for a minute before stirring.",
      "Add the sugar and salt and cook, stirring occasionally, until the tomatoes break down into a juicy pulp and release their liquid, 5-7 minutes.",
      "Return the eggs to the wok, breaking them into large curds, and toss with the tomatoes until just combined and heated through, about 1 minute.",
      "Stir in the green onions and serve immediately over steamed rice.",
    ],
    tags: ["dinner", "lunch", "asian", "quick", "vegetarian"],
    bg: {
      title: "Пържени Домати с Яйца",
      description:
        "Ежедневно китайско домашно ястие, предавано от родител на дете като първото пържено ястие - яйцата се бъркат отделно и се оставят настрана, за да останат крехки, после се връщат в доматите, задушени със захар и сол, докато станат сочни и конфитюрени.",
      steps: [
        "Разбийте яйцата в купа с виното шаосин, сусамовото олио и щипка сол за около минута, докато се напоят с въздух и леко разпенят.",
        "Загрейте половината олио в уок на силен огън, докато заблести, изсипете яйцата и ги разбъркайте набързо, докато едва се стегнат, но останат лъскави; веднага ги извадете на чиния, за да не се препекат.",
        "Добавете останалото олио в уока и сложете доматите на резени, готвейки без разбъркване за минута преди да разбъркате.",
        "Добавете захарта и солта и гответе, разбърквайки от време на време, докато доматите се разпаднат в сочна каша и пуснат течността си, 5-7 минути.",
        "Върнете яйцата в уока, разчупвайки ги на едри бучки, и разбъркайте с доматите, докато се съчетаят и загреят, около 1 минута.",
        "Разбъркайте пролука и сервирайте веднага с варен ориз.",
      ],
      ingredients: [
        "4 яйца",
        "1 ч.л. вино шаосин",
        "1/2 ч.л. сусамово олио",
        "Сол на вкус",
        "4 домата, нарязани на резени",
        "2 с.л. олио, разделено",
        "1 ч.л. захар",
        "2 стръка пролук, нарязани",
      ],
    },
  },
  {
    slug: "kachumbari",
    title: "Kachumbari",
    description:
      "Kenyan fresh tomato and onion salad, kept bright by a quick trick: the sliced onion gets a short salt-water soak before joining the bowl, which mellows its raw bite without cooking it or dulling the salad's crunch.",
    imageEmoji: "🍅",
    cookTimeMinutes: 15,
    servings: 4,
    ingredients: [
      { text: "1 red onion, thinly sliced", ingredient: "red onion", quantity: 1 },
      { text: "4 tomatoes, diced", ingredient: "tomato", quantity: 4 },
      { text: "1 cucumber, diced", ingredient: "cucumber", quantity: 1 },
      { text: "1 green chili, minced (optional)", ingredient: "green chili", quantity: 1 },
      { text: "1/4 cup cilantro, chopped", ingredient: "cilantro", quantity: 0.25 },
      { text: "2 tbsp lime juice", ingredient: "lime juice", quantity: 2 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
    ],
    steps: [
      "Place the sliced onion in a bowl of cold water with a generous pinch of salt and let it sit for 30 minutes - this brief brine mellows the onion's sharp bite without cooking it, which is the small trick that separates a good kachumbari from a raw, overpowering one.",
      "Drain the onion well and pat dry.",
      "In a large bowl, combine the onion, tomatoes, cucumber, and green chili if using.",
      "Add the cilantro and lime juice and toss gently.",
      "Season with salt to taste and let the salad sit for a few minutes before serving so the flavors combine.",
      "Serve fresh alongside grilled meats, pilau, or biryani.",
    ],
    tags: ["salad", "african", "vegan", "vegetarian", "quick"],
    bg: {
      title: "Качумбари",
      description:
        "Кенийска прясна салата от домати и лук, поддържана свежа с бърз трик: нарязаният лук се накисва за кратко в подсолена вода, преди да се добави в купата, което омекотява суровата му острота, без да го готви или притъпява хрупкавостта на салатата.",
      steps: [
        "Сложете нарязания лук в купа със студена вода и щедра щипка сол и оставете за 30 минути - тази кратка саламура омекотява острия вкус на лука, без да го готви, което е малкият трик, който отличава добрата качумбари от сурова и прекалено остра.",
        "Отцедете добре лука и го подсушете.",
        "В голяма купа смесете лука, доматите, краставицата и лютата чушка, ако използвате.",
        "Добавете кориандъра и лимоновия сок и разбъркайте леко.",
        "Подправете със сол на вкус и оставете салатата да постои няколко минути преди сервиране, за да се съчетаят вкусовете.",
        "Сервирайте прясна с печено месо, пилау или бирияни.",
      ],
      ingredients: [
        "1 червен лук, нарязан на тънко",
        "4 домата, нарязани на кубчета",
        "1 краставица, нарязана на кубчета",
        "1 люта чушка, нарязана (по желание)",
        "1/4 чаша кориандър, нарязан",
        "2 с.л. лимонов сок",
        "Сол на вкус",
      ],
    },
  },
  {
    slug: "tomato-chutney",
    title: "Tomato Chutney",
    description:
      "South Indian condiment for dosa and idli, thickened not by long simmering but by searing the tomatoes on high heat first - the char drives off excess moisture and adds smoky depth before a mustard-seed and curry-leaf tempering finishes it.",
    imageEmoji: "🍅",
    cookTimeMinutes: 25,
    servings: 6,
    ingredients: [
      { text: "2 tbsp vegetable oil, divided", ingredient: "vegetable oil", quantity: 2 },
      { text: "1 tsp mustard seeds", ingredient: "mustard seeds", quantity: 1 },
      { text: "1/2 tsp lentils (urad dal)", ingredient: "lentils", quantity: 0.5 },
      { text: "2 dried red chilies", ingredient: "dried red chili", quantity: 2 },
      { text: "1 sprig curry leaves", ingredient: "curry leaves", quantity: 1 },
      { text: "1/2 tsp asafoetida (hing)", ingredient: "asafoetida", quantity: 0.5 },
      { text: "1/2 onion, chopped", ingredient: "onion", quantity: 0.5 },
      { text: "3 cloves garlic, minced", ingredient: "garlic", quantity: 3 },
      { text: "5 tomatoes, chopped", ingredient: "tomato", quantity: 5 },
      { text: "1/2 tsp turmeric", ingredient: "turmeric", quantity: 0.5 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
    ],
    steps: [
      "Heat 1 tablespoon of the oil in a pan and sear the chopped tomatoes over high heat until they pick up light char spots and release most of their moisture, 6-8 minutes - this searing step is what keeps the finished chutney thick rather than watery, and it deepens the flavor beyond a plain simmer.",
      "Remove the seared tomatoes and set aside.",
      "In the same pan, heat the remaining oil and add the mustard seeds; once they pop, add the lentils and dried red chilies and sauté until the lentils turn light golden.",
      "Add the curry leaves and asafoetida and sizzle for a few seconds, then add the onion and garlic and sauté until softened.",
      "Return the seared tomatoes to the pan along with the turmeric and salt, and simmer for 5 minutes.",
      "Let cool slightly, then blend to your preferred consistency - thicker for idli, slightly looser for dosa.",
      "Serve with idli, dosa, or uttapam.",
    ],
    tags: ["snack", "vegan", "vegetarian"],
    bg: {
      title: "Доматен Чътни",
      description:
        "Южноиндийска подправка за доса и идли, сгъстена не чрез дълго къкрене, а чрез изпичане на доматите на силен огън първо - изгарянето отнема излишната влага и добавя димна дълбочина, преди подправка от синапено семе и къри листа да я завърши.",
      steps: [
        "Загрейте 1 супена лъжица от олиото в тиган и изпечете нарязаните домати на силен огън, докато придобият леки почернели петна и пуснат по-голямата част от влагата си, 6-8 минути - това изпичане запазва готовия чътни гъст, а не воднист, и задълбочава вкуса отвъд обикновеното къкрене.",
        "Извадете изпечените домати и оставете настрана.",
        "В същия тиган загрейте останалото олио и добавете синапеното семе; щом започне да пука, добавете лещата и сушените червени чушки и запържете, докато лещата стане светло златиста.",
        "Добавете къри листата и асафетидата и запържете няколко секунди, после добавете лука и чесъна и запържете до омекване.",
        "Върнете изпечените домати в тигана заедно с куркумата и солта и къкрете 5 минути.",
        "Оставете да поизстине леко, после блендирайте до желаната консистенция - по-гъста за идли, малко по-рядка за доса.",
        "Сервирайте с идли, доса или утапам.",
      ],
      ingredients: [
        "2 с.л. олио, разделено",
        "1 ч.л. синапено семе",
        "1/2 ч.л. леща (урад дал)",
        "2 сушени червени чушки",
        "1 клонче къри листа",
        "1/2 ч.л. асафетида (хинг)",
        "1/2 лук, нарязан",
        "3 скилидки чесън, смлени",
        "5 домата, нарязани",
        "1/2 ч.л. куркума",
        "Сол на вкус",
      ],
    },
  },
  {
    slug: "shrimp-creole",
    title: "Shrimp Creole",
    description:
      "New Orleans classic built on the Cajun-Creole \"holy trinity\" of onion, celery, and bell pepper - simmered into a rich tomato gravy until it deepens to a dark crimson, then finished with plump Gulf shrimp added just long enough to turn pink.",
    imageEmoji: "🍤",
    cookTimeMinutes: 45,
    servings: 6,
    ingredients: [
      { text: "3 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 3 },
      { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
      { text: "1/2 green bell pepper, diced", ingredient: "green bell pepper", quantity: 0.5 },
      { text: "2/3 cup celery, diced", ingredient: "celery", quantity: 0.67 },
      { text: "4 cloves garlic, minced", ingredient: "garlic", quantity: 4 },
      { text: "1 can crushed tomatoes", ingredient: "tomato", quantity: 1 },
      { text: "1 tbsp tomato paste", ingredient: "tomato paste", quantity: 1 },
      { text: "2 cups chicken broth", ingredient: "chicken broth", quantity: 2 },
      { text: "2 tsp cajun seasoning", ingredient: "cajun seasoning", quantity: 2 },
      { text: "1 bay leaf", ingredient: "bay leaf", quantity: 1 },
      { text: "1 1/2 lb shrimp, peeled and deveined", ingredient: "shrimp", quantity: 1.5 },
      { text: "3 cups cooked rice, for serving", ingredient: "rice", quantity: 3 },
      { text: "2 tbsp chopped parsley", ingredient: "parsley", quantity: 2 },
    ],
    steps: [
      "Heat the oil in a large pot and cook the onion, bell pepper, and celery (the \"holy trinity\") over medium heat until softened, about 8 minutes - using roughly 3 parts onion to 2 parts celery to 1 part bell pepper is what gives Creole and Cajun cooking its identifiable base flavor.",
      "Add the garlic and cook for 1 minute until fragrant.",
      "Stir in the crushed tomatoes, tomato paste, chicken broth, cajun seasoning, and bay leaf, and bring to a simmer.",
      "Cook uncovered for 20-25 minutes, stirring occasionally, until the sauce thickens and deepens to a rich, dark red color.",
      "Add the shrimp and cook until just pink and opaque, 3-4 minutes - do not overcook or they'll turn rubbery.",
      "Remove the bay leaf, taste and adjust seasoning, and serve over rice topped with fresh parsley.",
    ],
    tags: ["dinner", "american"],
    bg: {
      title: "Скариди Креол",
      description:
        "Класика от Ню Орлиънс, изградена върху каджунско-креолската „свещена троица“ от лук, целина и чушка - къкрещи в наситен доматен сос, докато потъмнее до тъмночервено, после завършен с едри скариди, добавени точно колкото да порозовеят.",
      steps: [
        "Загрейте олиото в голяма тенджера и гответе лука, чушката и целината („свещената троица“) на среден огън до омекване, около 8 минути - използването на приблизително 3 части лук към 2 части целина към 1 част чушка е това, което придава на креолската и каджунска кухня характерния ѝ основен вкус.",
        "Добавете чесъна и гответе 1 минута, докато замирише.",
        "Прибавете нарязаните домати, доматеното пюре, пилешкия бульон, подправката каджун и дафиновия лист и оставете да заври.",
        "Гответе без капак 20-25 минути, разбърквайки от време на време, докато сосът се сгъсти и потъмнее до наситено тъмночервено.",
        "Добавете скаридите и гответе, докато точно порозовеят и станат непрозрачни, 3-4 минути - не преварявайте, за да не станат гумени.",
        "Извадете дафиновия лист, опитайте и коригирайте подправките и сервирайте върху ориз, поръсени със свеж магданоз.",
      ],
      ingredients: [
        "3 с.л. олио",
        "1 лук, нарязан на кубчета",
        "1/2 зелена чушка, нарязана на кубчета",
        "2/3 чаша целина, нарязана на кубчета",
        "4 скилидки чесън, смлени",
        "1 консерва нарязани домати",
        "1 с.л. доматено пюре",
        "2 чаши пилешки бульон",
        "2 ч.л. подправка каджун",
        "1 дафинов лист",
        "1 1/2 lb (680г) скариди, обелени и почистени",
        "3 чаши сварен ориз, за сервиране",
        "2 с.л. нарязан магданоз",
      ],
    },
  },
];

async function main() {
  for (const recipe of newRecipes) {
    const created = await prisma.recipe.create({
      data: {
        slug: recipe.slug,
        title: recipe.title,
        description: recipe.description,
        imageEmoji: recipe.imageEmoji,
        cookTimeMinutes: recipe.cookTimeMinutes,
        servings: recipe.servings,
        steps: JSON.stringify(recipe.steps),
        tags: JSON.stringify(recipe.tags),
      },
    });

    for (let i = 0; i < recipe.ingredients.length; i++) {
      const ing = recipe.ingredients[i];
      const ingredient = await prisma.ingredient.upsert({
        where: { name: ing.ingredient },
        update: {},
        create: { name: ing.ingredient },
      });
      await prisma.recipeIngredient.create({
        data: {
          recipeId: created.id,
          ingredientId: ingredient.id,
          displayText: ing.text,
          quantity: ing.quantity,
          position: i,
        },
      });
    }

    console.log(`Created ${recipe.slug}`);
  }
  console.log(`Created ${newRecipes.length} recipes total.`);

  await runTranslations(
    newRecipes.map((r) => ({
      slug: r.slug,
      title: r.bg.title,
      description: r.bg.description,
      steps: r.bg.steps,
      ingredients: r.bg.ingredients,
    })),
  );
}

main();
