import { prisma, runTranslations } from "./translate-lib.mjs";

// 10 more Bulgarian recipes, each web-researched for authentic technique
// before writing, per standing instructions. Distinct from the 22 Bulgarian
// dishes already added in earlier batches (shopska-salad, banitsa, tarator,
// kavarma, sarmi, kyufte, kebapche, bob-chorba, bulgarian-musaka,
// snezhanka-salad, mekitsi, lyutenitsa, shkembe-chorba, gyuvech,
// pulneni-chushki, ayran, bulgarian-fish-soup, mish-mash, garash-cake,
// kyopoolu, ovcharska-salad, tutmanik, popara, drob-sarma, tikvenik,
// panagyurski-eggs, sirene-po-shopski, boza, kozunak, oriz-na-mlyako, sach,
// tsatsa, gabena-yahnia, rozovo-sladko, leshta-yahnia, pacha).
const newRecipes = [
  {
    slug: "patatnik",
    title: "Patatnik (Rhodope Potato and Cheese Bake)",
    description:
      "A rustic Rhodope Mountain dish of grated potatoes baked into a thick, golden cake with crumbled sirene, onion, egg, and fresh mint - squeezing the excess liquid out of the grated potatoes first, rather than baking them wet, is what lets the cake set into a dense, custardy interior instead of turning watery and falling apart.",
    imageEmoji: "🥔",
    cookTimeMinutes: 60,
    servings: 4,
    ingredients: [
      { text: "2 lb potatoes, peeled and grated", ingredient: "potato", quantity: 2 },
      { text: "1 onion, grated", ingredient: "onion", quantity: 1 },
      { text: "7 oz sirene (Bulgarian white brined cheese), crumbled", ingredient: "sirene", quantity: 7 },
      { text: "2 eggs", ingredient: "eggs", quantity: 2 },
      { text: "2 tbsp fresh mint, chopped", ingredient: "mint", quantity: 2 },
      { text: "3 tbsp vegetable oil, divided", ingredient: "vegetable oil", quantity: 3 },
      { text: "1 tsp salt", ingredient: "salt", quantity: 1 },
      { text: "1/2 tsp black pepper", ingredient: "black pepper", quantity: 0.5 },
    ],
    steps: [
      "Grate the potatoes coarsely, then squeeze them firmly in a clean kitchen towel or cheesecloth to wring out as much liquid as possible - skipping this step is what makes patatnik turn soggy instead of setting into a dense cake.",
      "In a large bowl, mix the squeezed potatoes with the grated onion, crumbled sirene, eggs, chopped mint, salt, and pepper until evenly combined.",
      "Heat 2 tbsp of the oil in a wide oven-safe skillet or shallow baking pan over medium heat, then spread the potato mixture in evenly and press it down into a flat, even layer.",
      "Cook on the stovetop for 8-10 minutes, until the bottom is deep golden brown - use a thin spatula to check underneath without disturbing the cake.",
      "Preheat the oven to 400°F. Drizzle the remaining oil over the top, then transfer the skillet to the oven and bake for 30-35 minutes, until the top is golden brown and a knife inserted into the center comes out clean.",
      "Let rest for 10 minutes before slicing into wedges and serving warm, traditionally with a dollop of yogurt on the side.",
    ],
    tags: ["vegetarian", "dinner"],
    bg: {
      title: "Пататник",
      description:
        "Селско ястие от Родопите от настърган картоф, изпечен в дебел, златист сладкиш с натрошено сирене, лук, яйце и прясна мента - изцеждането на излишната течност от настъргания картоф първо, вместо да се пече мокър, е това, което позволява на сладкиша да се стегне в плътна, кремообразна вътрешност, вместо да стане воднист и да се разпадне.",
      steps: [
        "Настържете картофите едро, после ги изстискайте силно в чиста кухненска кърпа или марля, за да извадите колкото се може повече течност - пропускането на тази стъпка е това, което прави пататника воднист, вместо да се стегне в плътен сладкиш.",
        "В голяма купа смесете изцедените картофи с настъргания лук, натрошеното сирене, яйцата, нарязаната мента, солта и черния пипер, докато се смесят равномерно.",
        "Загрейте 2 с.л. от олиото в широк тиган за фурна или плитка тава за печене на среден огън, после разстелете картофената смес равномерно и я притиснете в плосък, равен пласт.",
        "Гответе на котлона 8-10 минути, докато дъното стане дълбоко златисто кафяво - използвайте тънка шпатула, за да проверите отдолу, без да разбърквате сладкиша.",
        "Загрейте фурната на 200°C. Полейте отгоре с останалото олио, после прехвърлете тигана във фурната и печете 30-35 минути, докато повърхността стане златисто кафява, а нож, забит в центъра, излезе чист.",
        "Оставете да почине 10 минути преди да нарежете на парчета и сервирайте топъл, традиционно с лъжица кисело мляко отстрани.",
      ],
      ingredients: [
        "900 г картофи, обелени и настъргани",
        "1 лук, настърган",
        "200 г сирене, натрошено",
        "2 яйца",
        "2 с.л. прясна мента, нарязана",
        "3 с.л. олио, разделено",
        "1 ч.л. сол",
        "1/2 ч.л. черен пипер",
      ],
    },
  },
  {
    slug: "zelnik",
    title: "Zelnik (Bulgarian Leek and Spinach Pastry)",
    description:
      "A savory Bulgarian pastry of leavened dough rolled thin and coiled around a filling of sautéed leeks, spinach, and sorrel with egg and sirene - using a soft yeasted dough instead of banitsa's usual filo is what gives zelnik its thicker, breadier layers, closer to a savory cinnamon-roll spiral than banitsa's crisp, flaky sheets.",
    imageEmoji: "🥬",
    cookTimeMinutes: 90,
    servings: 8,
    ingredients: [
      { text: "3 cups flour", ingredient: "flour", quantity: 3 },
      { text: "1 tsp instant yeast", ingredient: "yeast", quantity: 1 },
      { text: "1 tsp sugar", ingredient: "sugar", quantity: 1 },
      { text: "1 tsp salt (for the dough)", ingredient: "salt", quantity: 1 },
      { text: "1 cup warm water", ingredient: "water", quantity: 1 },
      { text: "3 tbsp vegetable oil, divided", ingredient: "vegetable oil", quantity: 3 },
      { text: "2 leeks, white and light green parts, sliced", ingredient: "leek", quantity: 2 },
      { text: "1 bunch spinach, chopped", ingredient: "spinach", quantity: 1 },
      { text: "1 bunch sorrel, chopped (or extra spinach)", ingredient: "sorrel", quantity: 1 },
      { text: "2 eggs", ingredient: "eggs", quantity: 2 },
      { text: "7 oz sirene, crumbled", ingredient: "sirene", quantity: 7 },
      { text: "1/2 tsp black pepper", ingredient: "black pepper", quantity: 0.5 },
    ],
    steps: [
      "Dissolve the yeast and sugar in the warm water and let sit for 5-10 minutes, until foamy.",
      "In a large bowl, mix the flour and salt, then add the yeast mixture and 1 tbsp of the oil. Knead for 8-10 minutes into a soft, smooth dough. Cover and let rise for 45-60 minutes, until doubled.",
      "Meanwhile, heat the remaining oil in a pan and sauté the leeks for 5 minutes until soft. Add the spinach and sorrel and cook for 3-4 minutes more, just until wilted. Let cool slightly, then mix in the eggs, crumbled sirene, and black pepper.",
      "Punch down the dough and divide into 4 pieces. Roll each piece out into a thin rectangle.",
      "Spread a quarter of the filling evenly over each rectangle, then roll it up tightly into a log, jelly-roll style.",
      "Coil each log into a spiral and place in a greased round baking pan, fitting the spirals together to fill the pan - this coiled, leavened-dough shape is what makes zelnik look and eat differently from banitsa's stacked, buttery filo sheets.",
      "Preheat the oven to 375°F and bake for 35-40 minutes, until deep golden brown on top.",
      "Let cool for 10 minutes before serving warm, traditionally with a glass of ayran or yogurt.",
    ],
    tags: ["vegetarian", "breakfast", "baking"],
    bg: {
      title: "Зелник",
      description:
        "Солен български сладкиш от втасало тесто, разточено тънко и навито около плънка от задушен праз, спанак и киселец с яйце и сирене - използването на меко втасало тесто вместо обичайните за баница кори е това, което дава на зелника по-дебели, хлебести пластове, по-близки до солен рулет на спирала, отколкото до хрупкавите тънки кори на баницата.",
      steps: [
        "Разтворете маята и захарта в топлата вода и оставете за 5-10 минути, докато се разпени.",
        "В голяма купа смесете брашното и солта, после добавете маената смес и 1 с.л. от олиото. Месете 8-10 минути до меко, гладко тесто. Покрийте и оставете да втаса 45-60 минути, докато удвои обема си.",
        "Междувременно загрейте останалото олио в тиган и запържете праза 5 минути, докато омекне. Добавете спанака и киселеца и гответе още 3-4 минути, само докато повехнат. Оставете да изстинат леко, после разбъркайте яйцата, натрошеното сирене и черния пипер.",
        "Ударете тестото и разделете на 4 части. Разточете всяка част в тънък правоъгълник.",
        "Разстелете четвърт от плънката равномерно върху всеки правоъгълник, после го навийте стегнато на руло, като руло с конфитюр.",
        "Навийте всяко руло на спирала и подредете в намазана кръгла тава, побирайки спиралите една до друга, за да запълните тавата - тази навита форма от втасало тесто е това, което прави зелника различен на вид и вкус от подредените маслени кори на баницата.",
        "Загрейте фурната на 190°C и печете 35-40 минути, докато повърхността стане дълбоко златисто кафява.",
        "Оставете да изстине 10 минути преди да сервирате топъл, традиционно с чаша айран или кисело мляко.",
      ],
      ingredients: [
        "3 чаши брашно",
        "1 ч.л. суха мая",
        "1 ч.л. захар",
        "1 ч.л. сол",
        "1 чаша топла вода",
        "3 с.л. олио, разделено",
        "2 стъбла праз, бялата и светлозелената част, нарязани",
        "1 връзка спанак, нарязан",
        "1 връзка киселец, нарязан (или допълнителен спанак)",
        "2 яйца",
        "200 г сирене, натрошено",
        "1/2 ч.л. черен пипер",
      ],
    },
  },
  {
    slug: "przheno-sirene",
    title: "Pŭrzheno Sirene (Fried Bulgarian Cheese)",
    description:
      "A classic Bulgarian tavern appetizer of thick sirene slices dredged in flour and egg and pan-fried until the crust turns golden and crisp - sirene doesn't melt the way mozzarella does, so it firms back up as it cools, which is why this is always plated and eaten hot, straight out of the pan.",
    imageEmoji: "🧀",
    cookTimeMinutes: 20,
    servings: 4,
    ingredients: [
      { text: "1 lb sirene, cut into 1/2-inch slices", ingredient: "sirene", quantity: 1 },
      { text: "1/2 cup flour", ingredient: "flour", quantity: 0.5 },
      { text: "2 eggs, beaten", ingredient: "eggs", quantity: 2 },
      { text: "3 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 3 },
      { text: "1 tbsp sesame seeds, for serving (optional)", ingredient: "sesame seeds", quantity: 1 },
      { text: "2 tbsp honey, for serving (optional)", ingredient: "honey", quantity: 2 },
    ],
    steps: [
      "Pat the sirene slices dry with a paper towel.",
      "Dredge each slice in the flour, shaking off the excess, then dip in the beaten egg, coating all sides.",
      "Heat the oil in a nonstick skillet over medium heat until shimmering.",
      "Fry the slices for 2-3 minutes per side, until the coating is deep golden brown and crisp and the cheese is warmed through but still holding its shape.",
      "Transfer straight to plates - sirene firms back up as it cools rather than staying melty, so this is meant to be eaten hot, right out of the pan.",
      "Serve as is, or sprinkle with sesame seeds and drizzle with honey for a sweet-savory version.",
    ],
    tags: ["appetizer", "vegetarian", "quick"],
    bg: {
      title: "Пържено сирене",
      description:
        "Класическа българска мезета от дебели резени сирене, овалени в брашно и яйце и запържени, докато коричката стане златиста и хрупкава - сиренето не се топи като моцарелата, а се стяга отново, докато изстива, затова винаги се сервира и яде топло, направо от тигана.",
      steps: [
        "Подсушете резените сирене с хартиена кърпа.",
        "Овалайте всеки резен в брашното, изтърсвайки излишното, после потопете в разбитото яйце, покривайки от всички страни.",
        "Загрейте олиото в тиган с незалепващо покритие на среден огън, докато заблести.",
        "Пържете резените 2-3 минути от всяка страна, докато панировката стане дълбоко златисто кафява и хрупкава, а сиренето се затопли, но запази формата си.",
        "Прехвърлете направо в чинии - сиренето се стяга отново, докато изстива, вместо да остане разтопено, затова е предвидено да се яде топло, направо от тигана.",
        "Сервирайте така, или поръсете със сусам и полейте с мед за сладко-солена версия.",
      ],
      ingredients: [
        "450 г сирене, нарязано на резени по 1 см",
        "1/2 чаша брашно",
        "2 яйца, разбити",
        "3 с.л. олио",
        "1 с.л. сусам, за сервиране (по желание)",
        "2 с.л. мед, за сервиране (по желание)",
      ],
    },
  },
  {
    slug: "revane",
    title: "Revane (Bulgarian Semolina Syrup Cake)",
    description:
      "A Bulgarian semolina cake baked light and slightly coarse, then soaked through with cold lemon syrup while still hot from the oven - pouring cold syrup over a hot cake, rather than the other way around, is what lets it soak in evenly without ever turning gummy or too wet.",
    imageEmoji: "🍰",
    cookTimeMinutes: 60,
    servings: 9,
    ingredients: [
      { text: "1 cup semolina", ingredient: "semolina", quantity: 1 },
      { text: "1 cup flour", ingredient: "flour", quantity: 1 },
      { text: "1 tsp baking powder", ingredient: "baking powder", quantity: 1 },
      { text: "1 cup plain yogurt", ingredient: "yogurt", quantity: 1 },
      { text: "3 eggs", ingredient: "eggs", quantity: 3 },
      { text: "3/4 cup sugar (for the cake)", ingredient: "sugar", quantity: 0.75 },
      { text: "1/2 cup vegetable oil", ingredient: "vegetable oil", quantity: 0.5 },
      { text: "1 tsp vanilla extract", ingredient: "vanilla extract", quantity: 1 },
      { text: "1 1/2 cups sugar (for the syrup)", ingredient: "sugar", quantity: 1.5 },
      { text: "1 1/2 cups water", ingredient: "water", quantity: 1.5 },
      { text: "1 tbsp lemon juice", ingredient: "lemon juice", quantity: 1 },
    ],
    steps: [
      "Preheat the oven to 350°F and grease a 9x9-inch baking pan.",
      "Make the syrup first so it has time to cool: combine the syrup sugar and water in a small pot, bring to a boil, and simmer for 5 minutes. Stir in the lemon juice, then set aside to cool completely, ideally in the fridge - the syrup needs to be cold by the time the cake comes out of the oven.",
      "Whisk the eggs and cake sugar together until pale, then whisk in the yogurt, oil, and vanilla.",
      "In a separate bowl, mix the semolina, flour, and baking powder, then fold into the wet ingredients until just combined.",
      "Pour the batter into the prepared pan and bake for 30-35 minutes, until golden and a toothpick inserted in the center comes out clean.",
      "While the cake is still hot, cut it into squares directly in the pan, then slowly ladle the cold syrup evenly over the top, letting it soak in fully before serving - hot cake with cold syrup is what lets the semolina absorb it evenly instead of turning soggy on top and dry underneath.",
    ],
    tags: ["dessert", "baking", "vegetarian"],
    bg: {
      title: "Реване",
      description:
        "Българска торта от грис, изпечена лека и леко зърнеста, после напоена докрай със студен лимонов сироп, докато е още топла от фурната - поливането на топлата торта със студен сироп, а не обратното, е това, което позволява да се напои равномерно, без никога да стане лепкава или прекалено мокра.",
      steps: [
        "Загрейте фурната на 180°C и намажете тава 23х23 см.",
        "Направете първо сиропа, за да има време да изстине: съберете захарта за сиропа и водата в малка тенджера, оставете да заври и гответе на слаб огън 5 минути. Разбъркайте лимоновия сок, после оставете настрана да изстине напълно, най-добре в хладилника - сиропът трябва да е студен, докато тортата излезе от фурната.",
        "Разбийте яйцата и захарта за тортата, докато побледнеят, после разбъркайте киселото мляко, олиото и ванилията.",
        "В отделна купа смесете гриса, брашното и бакпулвера, после внимателно ги вмесете във влажните съставки, докато се съединят.",
        "Изсипете тестото в подготвената тава и печете 30-35 минути, докато стане златисто и клечка, забита в центъра, излезе чиста.",
        "Докато тортата е още топла, нарежете я на квадратчета директно в тавата, после бавно полейте студения сироп равномерно отгоре, оставяйки го да се напои напълно преди сервиране - топла торта със студен сироп е това, което позволява на гриса да го попие равномерно, вместо да стане лигав отгоре и сух отдолу.",
      ],
      ingredients: [
        "1 чаша грис",
        "1 чаша брашно",
        "1 ч.л. бакпулвер",
        "1 чаша кисело мляко",
        "3 яйца",
        "3/4 чаша захар (за тестото)",
        "1/2 чаша олио",
        "1 ч.л. екстракт от ванилия",
        "1 1/2 чаши захар (за сиропа)",
        "1 1/2 чаши вода",
        "1 с.л. лимонов сок",
      ],
    },
  },
  {
    slug: "fasul-yahnia",
    title: "Fasul Yahnia (Bulgarian Bean Stew)",
    description:
      "Dried beans cooked down slowly with onion, carrot, tomato, and dzhodzhen (dried spearmint) until thick enough to hold its shape on a plate rather than pool like a soup - simmering it uncovered once the beans are tender, rather than keeping the lid on throughout like its soupier cousin bob chorba, is what lets the stew reduce down into a thick, clingy yahnia instead of a broth.",
    imageEmoji: "🫘",
    cookTimeMinutes: 105,
    servings: 4,
    ingredients: [
      { text: "2 cups dried white beans, soaked overnight", ingredient: "white beans", quantity: 2 },
      { text: "1 onion, finely chopped", ingredient: "onion", quantity: 1 },
      { text: "1 carrot, diced", ingredient: "carrot", quantity: 1 },
      { text: "1 red bell pepper, diced", ingredient: "red pepper", quantity: 1 },
      { text: "2 tomatoes, grated", ingredient: "tomato", quantity: 2 },
      { text: "4 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 4 },
      { text: "1 tsp paprika", ingredient: "paprika", quantity: 1 },
      { text: "1 tsp dried dzhodzhen (spearmint)", ingredient: "spearmint", quantity: 1 },
      { text: "1 bay leaf", ingredient: "bay leaf", quantity: 1 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "Pepper to taste", ingredient: "pepper", quantity: null },
    ],
    steps: [
      "Drain the soaked beans, rinse, and place in a pot with fresh water to cover by 2 inches. Bring to a boil, then reduce to a simmer and cook for 45-60 minutes, until just tender. Drain, reserving 1 cup of the cooking liquid.",
      "Heat the oil in a wide pot and sauté the onion, carrot, and bell pepper for 8-10 minutes, until softened.",
      "Stir in the paprika and cook for 30 seconds, until fragrant, then add the grated tomatoes and cook for 5 minutes, until slightly reduced.",
      "Add the cooked beans, bay leaf, and the reserved cooking liquid. Bring to a simmer.",
      "Cook uncovered on low heat for 25-30 minutes, stirring occasionally, until the liquid has reduced and thickened enough to cling to the beans rather than pool around them - this uncovered reduction is what turns it into a proper yahnia instead of a bean soup.",
      "Stir in the dzhodzhen during the last 5 minutes, discard the bay leaf, and season with salt and pepper before serving with bread.",
    ],
    tags: ["dinner", "vegetarian", "vegan"],
    bg: {
      title: "Фасул яхния",
      description:
        "Сух фасул, дълго задушен с лук, морков, домат и джоджен, докато стане достатъчно гъст, за да си държи формата в чинията, а не да се разлива като супа - готвенето без капак, след като фасулът омекне, вместо да се държи капакът през цялото време като при по-супената ѝ братовчедка боб чорба, е това, което позволява на яхнията да се сгъсти в гъста, лепкава яхния, вместо в бульон.",
      steps: [
        "Отцедете накиснатия фасул, изплакнете и поставете в тенджера с прясна вода, покриваща с около 5 см. Оставете да заври, после намалете до леко къкрене и гответе 45-60 минути, докато омекне точно колкото трябва. Отцедете, запазвайки 1 чаша от течността за готвене.",
        "Загрейте олиото в широка тенджера и запържете лука, моркова и чушката 8-10 минути, докато омекнат.",
        "Разбъркайте червения пипер и гответе 30 секунди, докато замирише, после добавете настърганите домати и гответе 5 минути, докато леко се сгъстят.",
        "Добавете сварения фасул, дафиновия лист и запазената течност за готвене. Оставете да заври леко.",
        "Гответе без капак на слаб огън 25-30 минути, като разбърквате от време на време, докато течността се сгъсти достатъчно, за да облепва фасула, вместо да се разлива около него - това готвене без капак е това, което го превръща в истинска яхния, вместо в боб супа.",
        "Разбъркайте джоджена през последните 5 минути, изхвърлете дафиновия лист, и подправете със сол и пипер преди сервиране с хляб.",
      ],
      ingredients: [
        "400 г сух бял фасул, накиснат за една нощ",
        "1 лук, ситно нарязан",
        "1 морков, нарязан на кубчета",
        "1 червена чушка, нарязана на кубчета",
        "2 домата, настъргани",
        "4 с.л. олио",
        "1 ч.л. червен пипер",
        "1 ч.л. сух джоджен",
        "1 дафинов лист",
        "Сол на вкус",
        "Черен пипер на вкус",
      ],
    },
  },
  {
    slug: "katmi",
    title: "Katmi (Bulgarian Yeasted Pancakes)",
    description:
      "Thick, spongy Bulgarian pancakes made from a rested yeasted batter and cooked in a completely dry pan rather than a greased one - the batter itself has enough fat that a dry pan is what gives katmi their characteristic golden, slightly blistered surface, and brushing them with butter only after they come off the heat is what keeps them soft instead of greasy.",
    imageEmoji: "🥞",
    cookTimeMinutes: 45,
    servings: 4,
    ingredients: [
      { text: "2 cups flour", ingredient: "flour", quantity: 2 },
      { text: "1 1/2 cups warm milk", ingredient: "milk", quantity: 1.5 },
      { text: "2 eggs", ingredient: "eggs", quantity: 2 },
      { text: "2 tsp instant yeast", ingredient: "yeast", quantity: 2 },
      { text: "1 tbsp sugar", ingredient: "sugar", quantity: 1 },
      { text: "1/2 tsp salt", ingredient: "salt", quantity: 0.5 },
      { text: "3 tbsp butter, melted, for brushing", ingredient: "butter", quantity: 3 },
      { text: "Honey or jam, for serving", ingredient: "honey", quantity: null },
    ],
    steps: [
      "Dissolve the yeast and sugar in the warm milk and let sit for 5-10 minutes, until foamy.",
      "Whisk in the eggs, then gradually whisk in the flour and salt until you have a smooth, thick, pourable batter - thicker than a crepe batter but still easily spreadable.",
      "Cover and let rest in a warm place for 30-40 minutes, until bubbly and visibly puffed.",
      "Heat a dry, ungreased nonstick skillet over medium heat - no oil or butter in the pan is what lets katmi develop their characteristic golden, slightly bubbled surface instead of frying up greasy.",
      "Ladle in a portion of batter, swirling gently to spread it into a thick round, and cook for 2-3 minutes, until bubbles form on top and the underside is golden.",
      "Flip and cook for 1-2 minutes more, until golden on the second side. Repeat with the remaining batter.",
      "Brush each katma with melted butter as soon as it comes off the pan - buttering them after cooking, not before, is what keeps them soft and pliable instead of greasy.",
      "Stack and serve warm with honey or jam.",
    ],
    tags: ["breakfast", "vegetarian", "quick"],
    bg: {
      title: "Катми",
      description:
        "Дебели, пухкави български палачинки от отпочинало втасало тесто, изпечени в напълно сух тиган, вместо в намазан - самото тесто съдържа достатъчно мазнина, така че сухият тиган е това, което дава на катмите характерната им златиста, леко надупчена повърхност, а намазването им с масло едва след като се свалят от огъня е това, което ги пази меки, вместо мазни.",
      steps: [
        "Разтворете маята и захарта в топлото мляко и оставете за 5-10 минути, докато се разпени.",
        "Разбъркайте яйцата, после постепенно разбърквайте брашното и солта, докато се получи гладко, гъсто, лееещо се тесто - по-гъсто от тесто за палачинки, но все пак лесно за разстилане.",
        "Покрийте и оставете да почине на топло място 30-40 минути, докато се разпени и видимо набъбне.",
        "Загрейте сух, ненамазан тиган с незалепващо покритие на среден огън - липсата на олио или масло в тигана е това, което позволява на катмите да развият характерната си златиста, леко надупчена повърхност, вместо да се изпържат мазни.",
        "Сипете черпак тесто, завъртайки леко, за да се разстели в дебел кръг, и гответе 2-3 минути, докато се образуват мехурчета отгоре, а долната страна стане златиста.",
        "Обърнете и гответе още 1-2 минути, докато и другата страна стане златиста. Повторете с останалото тесто.",
        "Намажете всяка катма с разтопено масло веднага щом се свали от тигана - намазването след готвене, а не преди, е това, което ги пази меки и гъвкави, вместо мазни.",
        "Подредете на купчина и сервирайте топли с мед или сладко.",
      ],
      ingredients: [
        "2 чаши брашно",
        "1 1/2 чаши топло мляко",
        "2 яйца",
        "2 ч.л. суха мая",
        "1 с.л. захар",
        "1/2 ч.л. сол",
        "3 с.л. масло, разтопено, за намазване",
        "Мед или сладко, за сервиране",
      ],
    },
  },
  {
    slug: "domashno-kiselo-mlyako",
    title: "Domashno Kiselo Mlyako (Homemade Bulgarian Yogurt)",
    description:
      "Bulgaria's signature yogurt, cultured at home with the country's own Lactobacillus bulgaricus strain - boiling the milk fully before cooling it back down to just body-warm, rather than starting from cold milk, is what kills off competing bacteria so the culture can set the yogurt into a thick, tangy custard instead of a thin, inconsistent one.",
    imageEmoji: "🥛",
    cookTimeMinutes: 480,
    servings: 6,
    ingredients: [
      { text: "4 cups whole milk", ingredient: "milk", quantity: 4 },
      {
        text: "3 tbsp plain Bulgarian yogurt with live cultures, at room temperature",
        ingredient: "yogurt",
        quantity: 3,
      },
    ],
    steps: [
      "Pour the milk into a pot and bring it to a gentle boil, stirring occasionally to prevent scorching. Let it boil for 1-2 minutes - this kills off any competing bacteria that would otherwise fight with the yogurt culture.",
      "Remove from the heat and let cool until just warm to the touch, about 113°F - if you can hold your finger in it comfortably for a few seconds, it's ready. Too hot and it will kill the culture; too cool and it won't set properly.",
      "Whisk 2-3 tablespoons of the warm milk into the yogurt starter in a small bowl until smooth, then whisk this mixture back into the rest of the warm milk.",
      "Pour into a clean jar or a few small jars, cover, and wrap in a towel or blanket to hold the warmth.",
      "Set in a warm, draft-free spot (like an oven with just the light on) and leave completely undisturbed for 6-8 hours - moving or jostling the jars during this time is what keeps the culture from setting into a smooth, firm curd.",
      "Once set, refrigerate for at least 4 hours before eating - it firms up further and develops its full tang once chilled. Save 2-3 tablespoons of this batch to start the next one.",
    ],
    tags: ["breakfast", "vegetarian"],
    bg: {
      title: "Домашно кисело мляко",
      description:
        "Емблематичното българско кисело мляко, ферментирало у дома с родния щам Lactobacillus bulgaricus - завирането на млякото напълно, преди да го охладите обратно до едва топло, вместо да тръгвате от студено мляко, е това, което убива конкуриращите бактерии, за да може закваската да стегне млякото в гъст, кисел крем, а не в рехав, неравномерен резултат.",
      steps: [
        "Излейте млякото в тенджера и оставете да заври леко, като разбърквате от време на време, за да не загори. Оставете да ври 1-2 минути - това убива всички конкуриращи бактерии, които иначе биха се борили със закваската.",
        "Свалете от огъня и оставете да изстине до едва топло на допир, около 45°C - ако можете да задържите пръста си в него удобно за няколко секунди, е готово. Прекалено горещо ще убие закваската; прекалено студено няма да позволи правилно стягане.",
        "Разбъркайте 2-3 супени лъжици от топлото мляко със закваската в малка купа до гладкост, после разбъркайте тази смес обратно в останалото топло мляко.",
        "Излейте в чист буркан или няколко малки буркана, покрийте и увийте в кърпа или одеяло, за да задържите топлината.",
        "Оставете на топло, защитено от течение място (например фурна само с включена лампичка) и не докосвайте напълно 6-8 часа - местенето или разклащането на бурканите през това време е това, което пречи на закваската да се стегне в гладък, плътен съсирек.",
        "След като се стегне, охладете поне 4 часа преди ядене - стяга се допълнително и развива пълния си вкус, след като изстине. Запазете 2-3 супени лъжици от тази партида, за да заквасите следващата.",
      ],
      ingredients: ["1 литър пълномаслено мляко", "3 с.л. кисело мляко с живи култури, стайна температура"],
    },
  },
  {
    slug: "pulneni-tikvichki",
    title: "Pulneni Tikvichki (Stuffed Zucchini with Rice and Meat)",
    description:
      "Zucchini halves hollowed out and packed with a rice, ground meat, and carrot filling, then baked sitting in a shallow pool of tomato sauce and water - that surrounding liquid is what lets the rice fully cook through and soften inside the shell, rather than staying undercooked and grainy the way it would baking dry.",
    imageEmoji: "🥒",
    cookTimeMinutes: 75,
    servings: 4,
    ingredients: [
      { text: "4 medium zucchini", ingredient: "zucchini", quantity: 4 },
      { text: "1/2 lb ground pork or beef", ingredient: "ground pork", quantity: 0.5 },
      { text: "1/2 cup rice", ingredient: "rice", quantity: 0.5 },
      { text: "1 onion, finely chopped", ingredient: "onion", quantity: 1 },
      { text: "1 carrot, grated", ingredient: "carrot", quantity: 1 },
      { text: "2 tomatoes, grated, divided", ingredient: "tomato", quantity: 2 },
      { text: "2 tbsp parsley, chopped", ingredient: "parsley", quantity: 2 },
      { text: "1 tsp chubritsa (savory)", ingredient: "chubritsa", quantity: 1 },
      { text: "1 tsp paprika", ingredient: "paprika", quantity: 1 },
      { text: "3 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 3 },
      { text: "1 cup water", ingredient: "water", quantity: 1 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "Pepper to taste", ingredient: "pepper", quantity: null },
    ],
    steps: [
      "Halve the zucchini lengthwise and scoop out the centers with a spoon, leaving a shell about 1/2-inch thick. Finely chop the scooped-out flesh and set aside.",
      "Heat the oil in a pan and sauté the onion and carrot for 5 minutes, until softened. Add the chopped zucchini flesh and cook for 3-4 minutes more.",
      "Stir in the ground meat and cook, breaking it up, until browned. Add the rice, half the grated tomatoes, paprika, chubritsa, parsley, salt, and pepper, and cook for 2 minutes to combine - the rice stays raw here and finishes cooking in the oven with the surrounding liquid.",
      "Preheat the oven to 375°F. Arrange the zucchini shells in a baking dish and fill each one generously with the meat and rice mixture, mounding it slightly.",
      "Pour the remaining grated tomato and the water into the bottom of the dish around the zucchini, not over the filling - this surrounding liquid is what steams the rice fully tender inside the shells instead of leaving it crunchy.",
      "Cover with foil and bake for 40-45 minutes, until the zucchini is tender and the rice inside is fully cooked. Uncover for the last 10 minutes to let the tops brown lightly.",
      "Serve warm, spooning some of the pan sauce over each portion.",
    ],
    tags: ["dinner"],
    bg: {
      title: "Пълнени тиквички",
      description:
        "Половинки тиквички, издълбани и напълнени с плънка от ориз, кайма и морков, после изпечени, потопени в плитка локвичка доматен сос и вода - тази заобикаляща течност е това, което позволява на ориза да се сготви напълно и да омекне вътре в черупката, вместо да остане недоварен и зърнест, както би станало при печене на сухо.",
      steps: [
        "Разрежете тиквичките наполовина по дължина и издълбайте центровете с лъжица, оставяйки черупка около 1-1.5 см дебелина. Нарежете ситно извадената месеста част и оставете настрана.",
        "Загрейте олиото в тиган и запържете лука и моркова 5 минути, докато омекнат. Добавете нарязаната тиквичкова плът и гответе още 3-4 минути.",
        "Разбъркайте каймата и гответе, разбивайки я, докато се запържи. Добавете ориза, половината от настърганите домати, червения пипер, чубрицата, магданоза, солта и пипера, и гответе 2 минути, за да се съединят - оризът остава суров тук и се доготвя във фурната със заобикалящата течност.",
        "Загрейте фурната на 190°C. Подредете черупките от тиквички в тава за печене и напълнете всяка обилно с месно-оризовата смес, оформяйки леко хълмче.",
        "Изсипете останалия настърган домат и водата в дъното на тавата около тиквичките, не върху плънката - тази заобикаляща течност е това, което задушава ориза напълно мек вътре в черупките, вместо да остане хрупкав.",
        "Покрийте с фолио и печете 40-45 минути, докато тиквичките омекнат, а оризът вътре напълно се сготви. Разкрийте през последните 10 минути, за да се зачервят леко отгоре.",
        "Сервирайте топли, поливайки всяка порция със сос от тавата.",
      ],
      ingredients: [
        "4 средни тиквички",
        "225 г кайма от свинско или говеждо",
        "1/2 чаша ориз",
        "1 лук, ситно нарязан",
        "1 морков, настърган",
        "2 домата, настъргани, разделени",
        "2 с.л. магданоз, нарязан",
        "1 ч.л. чубрица",
        "1 ч.л. червен пипер",
        "3 с.л. олио",
        "1 чаша вода",
        "Сол на вкус",
        "Черен пипер на вкус",
      ],
    },
  },
  {
    slug: "kiselo-zele",
    title: "Kiselo Zele (Bulgarian Whole-Head Fermented Cabbage)",
    description:
      "Bulgaria's traditional sauerkraut, made by fermenting whole heads of cabbage in brine rather than shredding them first - keeping the heads intact, weighted down and fully submerged for about a month, is what lets the brine penetrate all the way through in layers, so the leaves come out whole and pliable enough to use as sarmi wrappers, not just chopped as a side.",
    imageEmoji: "🫙",
    cookTimeMinutes: 40,
    servings: 10,
    ingredients: [
      { text: "4 small heads green cabbage, outer leaves removed", ingredient: "cabbage", quantity: 4 },
      { text: "1 apple, quartered (optional)", ingredient: "apple", quantity: 1 },
      { text: "1 small horseradish root, peeled (optional)", ingredient: "horseradish root", quantity: 1 },
      { text: "2 carrots (optional)", ingredient: "carrot", quantity: 2 },
      { text: "Water, enough to submerge", ingredient: "water", quantity: null },
      { text: "Salt, about 3 tbsp per liter of water", ingredient: "salt", quantity: 3 },
    ],
    steps: [
      "Remove any dark or damaged outer leaves from the cabbages. Cut a deep X into the core of each head, at least 2 inches deep, to help the brine penetrate.",
      "Pack the cabbage heads tightly into a large food-safe crock or bucket, tucking the apple, horseradish, and carrots (if using) into the gaps between them.",
      "Measure out enough water to fully submerge the cabbages, then dissolve salt into it at a rate of about 3 tablespoons per liter (a 3% brine) - getting this ratio right is what lets the cabbage ferment safely and evenly instead of turning soft or moldy.",
      "Pour the brine over the cabbages until fully covered, then weigh them down with a plate or wooden board so they stay submerged.",
      "Store in a cool spot, checking every day or two to skim any foam off the surface and top up with more brine if needed to keep everything submerged.",
      "Ferment for about 4 weeks, until the cabbage turns pleasantly sour and the color lightens - taste a leaf from the outside after 3 weeks to check.",
      "Once ready, the whole leaves can be peeled off to wrap sarmi, or the head chopped and served as a tangy side, drizzled with a little oil.",
    ],
    tags: ["vegan", "vegetarian"],
    bg: {
      title: "Кисело зеле",
      description:
        "Традиционното българско кисело зеле, ферментирало като цели зелки в саламура, вместо настъргано - запазването на зелките цели, притиснати и напълно потопени за около месец, е това, което позволява на саламурата да проникне слой по слой докрай, така че листата излизат цели и достатъчно гъвкави, за да се използват за сарми, а не само нарязани за гарнитура.",
      steps: [
        "Отстранете тъмните или повредени външни листа от зелките. Направете дълбок кръст в основата на всяка глава, поне 5 см дълбок, за да помогне на саламурата да проникне.",
        "Наредете зелките плътно в голям съд за туршия или буре, като напъхате ябълката, хряна и морковите (ако използвате) в пролуките между тях.",
        "Отмерете достатъчно вода, за да покрие напълно зелките, после разтворете сол в нея в съотношение около 3 с.л. на литър (3% саламура) - точното съотношение е това, което позволява на зелето да ферментира безопасно и равномерно, вместо да омекне или мухляса.",
        "Залейте зелките със саламурата, докато се покрият напълно, после ги притиснете с чиния или дървена дъска, за да останат потопени.",
        "Съхранявайте на хладно място, проверявайки на всеки ден-два, за да обирате евентуалната пяна от повърхността и да доливате саламура, ако е нужно, за да останат всички потопени.",
        "Ферментирайте около 4 седмици, докато зелето стане приятно кисело, а цветът светне - опитайте лист отвън след 3 седмици, за да проверите.",
        "Щом е готово, целите листа могат да се обелят за сарми, или главата да се нареже и сервира като кисела гарнитура, полята с малко олио.",
      ],
      ingredients: [
        "4 малки глави зеле, обелени от външните листа",
        "1 ябълка, разрязана на четвъртинки (по желание)",
        "1 малък корен хрян, обелен (по желание)",
        "2 моркова (по желание)",
        "Вода, колкото да покрие",
        "Сол, около 3 с.л. на литър вода",
      ],
    },
  },
  {
    slug: "chorba-ot-kiselec",
    title: "Chorba ot Kiselets (Bulgarian Sorrel Soup)",
    description:
      "A tangy spring soup built from sorrel simmered with rice, then finished with an egg-and-yogurt liaison tempered in gradually off the heat - adding the yogurt mixture straight into the boiling soup, instead of tempering it first, is what would curdle it, so it's whisked with hot broth off the heat before going back in.",
    imageEmoji: "🥣",
    cookTimeMinutes: 30,
    servings: 4,
    ingredients: [
      { text: "1 large bunch sorrel, stems removed, chopped", ingredient: "sorrel", quantity: 1 },
      { text: "1/4 cup rice", ingredient: "rice", quantity: 0.25 },
      { text: "1 onion, finely chopped", ingredient: "onion", quantity: 1 },
      { text: "2 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 2 },
      { text: "5 cups water", ingredient: "water", quantity: 5 },
      { text: "2 egg yolks", ingredient: "egg yolks", quantity: 2 },
      { text: "1/2 cup plain yogurt", ingredient: "yogurt", quantity: 0.5 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "Pepper to taste", ingredient: "pepper", quantity: null },
      { text: "Crumbled sirene, for serving", ingredient: "sirene", quantity: null },
    ],
    steps: [
      "Heat the oil in a pot and sauté the onion for 4-5 minutes, until soft and translucent.",
      "Add the water and rice, bring to a boil, then reduce to a simmer and cook for 12-15 minutes, until the rice is tender.",
      "Stir in the chopped sorrel and simmer for 3-4 minutes more, until wilted and the soup turns a soft olive-green.",
      "Remove the pot from the heat. In a separate bowl, whisk the egg yolks and yogurt together until smooth.",
      "Ladle a cup of the hot soup into the egg-yogurt mixture, whisking constantly, to gradually warm it up without curdling - adding the yogurt mixture cold, straight into the pot, is what would make it curdle instead of blending in smoothly.",
      "Whisk the tempered egg-yogurt mixture back into the pot, off the heat, until fully combined and silky.",
      "Season with salt and pepper, and serve hot or lightly chilled, topped with crumbled sirene.",
    ],
    tags: ["dinner", "vegetarian", "quick"],
    bg: {
      title: "Чорба от киселец",
      description:
        "Кисела пролетна супа от киселец, къкрян с ориз, после доизкусурена с яйчено-кисело-млечна смес, темперирана постепенно извън огъня - добавянето на млечната смес направо във врящата супа, вместо да се темперира първо, би я пресякло, затова се разбърква с горещ бульон извън огъня, преди да се върне обратно.",
      steps: [
        "Загрейте олиото в тенджера и запържете лука 4-5 минути, докато омекне и стане прозрачен.",
        "Добавете водата и ориза, оставете да заври, после намалете до леко къкрене и гответе 12-15 минути, докато оризът омекне.",
        "Разбъркайте нарязания киселец и гответе още 3-4 минути, докато повехне, а супата стане меко маслинено-зелена.",
        "Свалете тенджерата от огъня. В отделна купа разбийте жълтъците и киселото мляко до гладкост.",
        "Прибавете черпак от горещата супа към яйчено-млечната смес, разбърквайки непрекъснато, за да я затоплите постепенно, без да се пресече - добавянето на млечната смес студена, направо в тенджерата, е това, което би я пресякло, вместо да се смеси гладко.",
        "Разбъркайте темперираната яйчено-млечна смес обратно в тенджерата, извън огъня, докато се съедини напълно и стане кадифена.",
        "Подправете със сол и пипер, и сервирайте топла или леко охладена, гарнирана с натрошено сирене.",
      ],
      ingredients: [
        "1 голяма връзка киселец, без стъблата, нарязан",
        "1/4 чаша ориз",
        "1 лук, ситно нарязан",
        "2 с.л. олио",
        "5 чаши вода",
        "2 жълтъка",
        "1/2 чаша кисело мляко",
        "Сол на вкус",
        "Черен пипер на вкус",
        "Натрошено сирене, за сервиране",
      ],
    },
  },
];

async function main() {
  for (const recipe of newRecipes) {
    const created = await prisma.recipe.create({
      data: {
        slug: recipe.slug,
        title: recipe.title,
        description: recipe.description,
        imageEmoji: recipe.imageEmoji,
        cookTimeMinutes: recipe.cookTimeMinutes,
        servings: recipe.servings,
        steps: JSON.stringify(recipe.steps),
        tags: JSON.stringify(recipe.tags),
      },
    });

    for (let i = 0; i < recipe.ingredients.length; i++) {
      const { text, ingredient, quantity } = recipe.ingredients[i];
      const ingredientRow = await prisma.ingredient.upsert({
        where: { name: ingredient },
        update: {},
        create: { name: ingredient },
      });
      await prisma.recipeIngredient.create({
        data: {
          recipeId: created.id,
          ingredientId: ingredientRow.id,
          displayText: text,
          quantity,
          position: i,
        },
      });
    }
    console.log(`Created ${recipe.slug}`);
  }
  console.log(`Created ${newRecipes.length} recipes total.`);

  // runTranslations disconnects prisma when done, so it must run last.
  await runTranslations(newRecipes.map((r) => ({ slug: r.slug, ...r.bg })));
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
