import { prisma, runTranslations } from "./translate-lib.mjs";

// 10 more Bulgarian recipes, each web-researched for authentic technique
// before writing, per standing instructions. Cheverme uses a bone-in leg of
// lamb roasted low and slow instead of a whole spit-roasted animal, since a
// full spit setup isn't practical for most kitchens - substitution stated
// in its own description.
const newRecipes = [
  {
    slug: "milinki",
    title: "Milinki",
    description:
      "Small, fluffy Bulgarian pull-apart rolls baked snugly together in one pan and finished with a buttery, cheese-flecked topping brushed on partway through baking - baking the rolls touching each other, rather than spaced apart, is what keeps their sides soft while the tops turn golden, the texture that makes them pull-apart rolls instead of separate buns.",
    imageEmoji: "🥐",
    cookTimeMinutes: 60,
    servings: 8,
    ingredients: [
      { text: "3 1/2 cups flour", ingredient: "flour", quantity: 3.5 },
      { text: "2 1/4 tsp yeast", ingredient: "yeast", quantity: 2.25 },
      { text: "2 tbsp sugar", ingredient: "sugar", quantity: 2 },
      { text: "1 cup warm milk", ingredient: "milk", quantity: 1 },
      { text: "1 egg", ingredient: "eggs", quantity: 1 },
      { text: "3 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 3 },
      { text: "1 tsp salt", ingredient: "salt", quantity: 1 },
      { text: "4 tbsp butter, melted (for the topping)", ingredient: "butter", quantity: 4 },
      { text: "5 oz sirene (Bulgarian white brined cheese), crumbled", ingredient: "sirene", quantity: 5 },
      { text: "2 tbsp milk (for the topping)", ingredient: "milk", quantity: 2 },
    ],
    steps: [
      "Dissolve the yeast and sugar in the warm milk and let sit for 5-10 minutes until foamy.",
      "Mix the flour and salt in a large bowl, then add the yeast mixture, egg, and oil. Knead for 8-10 minutes until smooth and elastic.",
      "Cover and let rise in a warm place for 1 hour, until doubled in size.",
      "Punch down the dough and divide into 12 equal pieces. Roll each into a smooth ball.",
      "Arrange the balls snugly touching each other in a greased round or square baking pan - baking them touching, rather than spaced apart, is what makes them pull-apart rolls with soft sides instead of separate, all-around-crusty buns.",
      "Cover and let rise again for 30-40 minutes, until puffy.",
      "Preheat the oven to 375°F and bake for 15 minutes.",
      "Meanwhile, whisk together the melted butter, crumbled sirene, and 2 tbsp milk to make the topping.",
      "Remove the rolls from the oven, brush or spoon the cheese topping evenly over the top, and return to the oven for another 10-12 minutes, until deep golden and the topping is set.",
      "Let cool slightly, then pull apart to serve.",
    ],
    tags: ["breakfast", "baking", "vegetarian"],
    bg: {
      title: "Милинки",
      description:
        "Малки, пухкави български хлебчета за откъсване, изпечени плътно едно до друго в един тиган и завършени с маслена, изпъстрена със сирене глазура, намазана по средата на печенето - печенето на хлебчетата, докосващи се едно друго, вместо на разстояние, е това, което пази страните им меки, докато отгоре позлатеят, текстурата, която ги прави хлебчета за откъсване, вместо отделни, напълно коричести кифлички.",
      steps: [
        "Разтворете маята и захарта в топлото мляко и оставете за 5-10 минути, докато се разпени.",
        "Смесете брашното и солта в голяма купа, после добавете маената смес, яйцето и олиото. Месете 8-10 минути, докато стане гладко и еластично.",
        "Покрийте и оставете да втаса на топло място 1 час, докато удвои обема си.",
        "Ударете тестото и го разделете на 12 равни части. Оформете всяка в гладка топка.",
        "Наредете топките плътно, докосващи се една друга, в намазана кръгла или квадратна тава за печене - печенето им докосващи се, вместо на разстояние, е това, което ги прави хлебчета за откъсване с меки страни, вместо отделни, изцяло коричести кифлички.",
        "Покрийте и оставете да втасат отново 30-40 минути, докато се надуят.",
        "Загрейте фурната на 190°C и печете 15 минути.",
        "Междувременно разбийте заедно разтопеното масло, натрошеното сирене и 2-та с.л. мляко, за да направите глазурата.",
        "Извадете хлебчетата от фурната, намажете или разпределете сиренената глазура равномерно отгоре, и върнете във фурната още 10-12 минути, докато станат дълбоко златисти, а глазурата се стегне.",
        "Оставете да изстинат леко, после разкъсайте, за да сервирате.",
      ],
      ingredients: [
        "3 1/2 чаши брашно",
        "2 1/4 ч.л. мая",
        "2 с.л. захар",
        "1 чаша топло мляко",
        "1 яйце",
        "3 с.л. олио",
        "1 ч.л. сол",
        "4 с.л. масло, разтопено (за глазурата)",
        "150 г сирене, натрошено",
        "2 с.л. мляко (за глазурата)",
      ],
    },
  },
  {
    slug: "cheverme",
    title: "Cheverme",
    description:
      "Bulgaria's festive spit-roasted lamb, traditionally a whole animal turned slowly over open coals for 8-10 hours - this home version uses a bone-in leg of lamb roasted low and slow instead, since a full spit setup isn't practical for most kitchens; the long, low roast and frequent basting are what render the fat and keep the meat falling-apart tender, the same principle behind the original all-day spit.",
    imageEmoji: "🍖",
    cookTimeMinutes: 300,
    servings: 8,
    ingredients: [
      { text: "5 lb bone-in leg of lamb", ingredient: "lamb", quantity: 5 },
      { text: "6 cloves garlic, slivered", ingredient: "garlic", quantity: 6 },
      { text: "2 tbsp salt", ingredient: "salt", quantity: 2 },
      { text: "1 tbsp black pepper", ingredient: "black pepper", quantity: 1 },
      { text: "2 tbsp dried oregano", ingredient: "oregano", quantity: 2 },
      { text: "1/4 cup olive oil", ingredient: "olive oil", quantity: 0.25 },
      { text: "1 cup white wine", ingredient: "white wine", quantity: 1 },
      { text: "2 lemons, juiced", ingredient: "lemon juice", quantity: 2 },
    ],
    steps: [
      "Using a small knife, cut slits all over the lamb leg and insert the garlic slivers into them.",
      "Rub the lamb all over with the salt, pepper, oregano, and olive oil, then let it come to room temperature for 30-45 minutes before roasting.",
      "Preheat the oven to 325°F. Place the lamb on a rack in a roasting pan and pour the white wine and lemon juice into the bottom of the pan.",
      "Roast for 4-5 hours, basting every 45 minutes with the pan juices, until the meat is deeply browned outside and falls off the bone with a fork - it's this long, slow roast with frequent basting that stands in for the original all-day spit, rendering the fat and keeping the meat tender instead of just cooking it through.",
      "Tent with foil if the outside browns too much before the inside is tender.",
      "Let rest for 15-20 minutes before carving or pulling the meat off the bone. Serve with the pan juices spooned over the top.",
    ],
    tags: ["dinner"],
    bg: {
      title: "Чеверме",
      description:
        "Празничното българско агнешко на шиш, традиционно цяло животно, въртяно бавно над жарава 8-10 часа - тази домашна версия използва агнешки бут с кост, печен бавно и на слаба температура вместо това, тъй като пълна инсталация за шиш не е практична за повечето кухни; дългото, бавно печене и честото поливане са това, което разтопява мазнината и пази месото толкова крехко, че се разпада, същият принцип зад оригиналното целодневно печене на шиш.",
      steps: [
        "С малко ножче нарежете прорези навсякъде по агнешкия бут и напъхайте резенчетата чесън в тях.",
        "Натрийте агнешкото отвсякъде със солта, пипера, риган и зехтина, после оставете да достигне стайна температура 30-45 минути преди печене.",
        "Загрейте фурната на 160°C. Поставете агнешкото на решетка в тава за печене и изсипете бялото вино и лимоновия сок на дъното на тавата.",
        "Печете 4-5 часа, поливайки на всеки 45 минути със сока от тавата, докато месото стане дълбоко зачервено отвън и се отделя от костта с вилица - именно това дълго, бавно печене с често поливане замества оригиналното целодневно печене на шиш, разтопявайки мазнината и пазейки месото крехко, вместо просто да го сготви.",
        "Покрийте с фолио, ако отвън стане твърде тъмно, преди отвътре да омекне.",
        "Оставете да почине 15-20 минути преди да нарежете или откъснете месото от костта. Сервирайте, поливайки със сока от тавата отгоре.",
      ],
      ingredients: [
        "2.3 кг агнешки бут с кост",
        "6 скилидки чесън, нарязани на резенчета",
        "2 с.л. сол",
        "1 с.л. черен пипер",
        "2 с.л. сушен риган",
        "1/4 чаша зехтин",
        "1 чаша бяло вино",
        "2 лимона, сок",
      ],
    },
  },
  {
    slug: "kurban-chorba",
    title: "Kurban Chorba",
    description:
      "A hearty Bulgarian ritual lamb soup, traditionally made for religious feasts and family celebrations, simmered with tomato, carrot, celery, and onion until rich, then finished with a beaten-egg and lemon liaison stirred in off the heat - tempering the eggs with hot broth before adding them to the pot, rather than pouring them in directly, is what thickens the soup into a silky liaison instead of scrambling into shreds.",
    imageEmoji: "🍜",
    cookTimeMinutes: 90,
    servings: 6,
    ingredients: [
      { text: "2 lb lamb shoulder, cut into chunks", ingredient: "lamb", quantity: 2 },
      { text: "1 onion, chopped", ingredient: "onion", quantity: 1 },
      { text: "2 carrots, diced", ingredient: "carrot", quantity: 2 },
      { text: "2 celery stalks, diced", ingredient: "celery", quantity: 2 },
      { text: "2 tomatoes, grated", ingredient: "tomato", quantity: 2 },
      { text: "2 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 2 },
      { text: "8 cups water", ingredient: "water", quantity: 8 },
      { text: "2 eggs", ingredient: "eggs", quantity: 2 },
      { text: "2 tbsp lemon juice", ingredient: "lemon juice", quantity: 2 },
      { text: "2 tbsp parsley, chopped", ingredient: "parsley", quantity: 2 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "Pepper to taste", ingredient: "pepper", quantity: null },
    ],
    steps: [
      "Heat the oil in a large pot and brown the lamb chunks on all sides, about 8-10 minutes.",
      "Add the onion, carrots, and celery, and sauté for 5-6 minutes, until softened.",
      "Stir in the grated tomatoes and cook for 2-3 minutes.",
      "Add the water, bring to a boil, then reduce heat and simmer, partially covered, for 50-60 minutes, until the lamb is very tender.",
      "Whisk the eggs and lemon juice together in a bowl. Ladle a cup of the hot broth into the egg mixture very slowly, whisking constantly, to temper it - adding the eggs directly to the hot pot instead of tempering them first is what causes them to scramble into shreds instead of thickening the soup smoothly.",
      "Remove the pot from the heat and slowly stir the tempered egg mixture back into the soup.",
      "Season with salt and pepper, stir in the parsley, and serve immediately - once the eggs are in, the soup shouldn't be reheated to a full boil, or it will curdle.",
    ],
    tags: ["dinner"],
    bg: {
      title: "Курбан чорба",
      description:
        "Засищаща българска обредна агнешка чорба, традиционно приготвяна за религиозни празници и семейни тържества, задушена с домат, морков, целина и лук, докато стане богата, после завършена с разбити яйца и лимон, разбъркани извън котлона - темперирането на яйцата с горещ бульон, преди да се добавят в тенджерата, вместо да се изсипят директно, е това, което сгъстява чорбата в копринена смес, вместо да се пресекат на люспи.",
      steps: [
        "Загрейте олиото в голяма тенджера и запържете агнешките парчета от всички страни, около 8-10 минути.",
        "Добавете лука, морковите и целината, и запържете 5-6 минути, докато омекнат.",
        "Разбъркайте настърганите домати и гответе 2-3 минути.",
        "Добавете водата, оставете да заври, после намалете огъня и гответе на слаб огън, частично покрито, 50-60 минути, докато агнешкото стане много крехко.",
        "Разбийте яйцата и лимоновия сок заедно в купа. Прибавете чаша от горещия бульон в яйчната смес много бавно, разбърквайки постоянно, за да я темперирате - добавянето на яйцата директно в горещата тенджера, вместо първо да ги темперирате, е това, което ги кара да се пресекат на люспи, вместо гладко да сгъстят чорбата.",
        "Свалете тенджерата от котлона и бавно разбъркайте темперираната яйчна смес обратно в чорбата.",
        "Подправете със сол и пипер, разбъркайте магданоза, и сервирайте веднага - след като яйцата са вътре, чорбата не бива да се загрява отново до кипене, иначе ще се пресече.",
      ],
      ingredients: [
        "900 г агнешка плешка, нарязана на парчета",
        "1 лук, нарязан",
        "2 моркова, нарязани на кубчета",
        "2 стъбла целина, нарязани на кубчета",
        "2 домата, настъргани",
        "2 с.л. олио",
        "8 чаши вода",
        "2 яйца",
        "2 с.л. лимонов сок",
        "2 с.л. магданоз, нарязан",
        "Сол на вкус",
        "Черен пипер на вкус",
      ],
    },
  },
  {
    slug: "koledna-pitka",
    title: "Koledna Pitka",
    description:
      "Bulgaria's traditional Christmas Eve bread - a round, enriched loaf hand-shaped with symbolic ridges and patterns, traditionally baked with a coin hidden inside for good luck - shaping the surface into ridges and coils rather than leaving it smooth is what gives koledna pitka its distinctive, decorative look, and hiding the coin (wrapped so it stays food-safe) is the tradition that makes finding your slice a small piece of luck for the year ahead.",
    imageEmoji: "🍞",
    cookTimeMinutes: 120,
    servings: 10,
    ingredients: [
      { text: "4 cups flour", ingredient: "flour", quantity: 4 },
      { text: "2 1/4 tsp yeast", ingredient: "yeast", quantity: 2.25 },
      { text: "2 tbsp sugar", ingredient: "sugar", quantity: 2 },
      { text: "1 1/4 cups warm water", ingredient: "water", quantity: 1.25 },
      { text: "1/3 cup vegetable oil", ingredient: "vegetable oil", quantity: 0.33 },
      { text: "1 tsp salt", ingredient: "salt", quantity: 1 },
      { text: "1 egg, beaten (for egg wash)", ingredient: "eggs", quantity: 1 },
    ],
    steps: [
      "Dissolve the yeast and sugar in the warm water and let sit for 5-10 minutes until foamy.",
      "Mix the flour and salt in a large bowl, add the yeast mixture and oil, and knead for 8-10 minutes until smooth and elastic.",
      "Cover and let rise in a warm place for 1 hour, until doubled in size.",
      "Punch down the dough and set aside about 1/4 of it for decoration. Shape the larger piece into a smooth, flat round loaf on a baking sheet.",
      "Roll the reserved dough into thin ropes and arrange them over the top in a decorative pattern - traditional patterns include crosses, spirals, and shapes representing the sun, crops, or livestock, each carrying its own symbolic wish for the year ahead. If including a coin for good luck, wrap it tightly in foil first and tuck it into the underside of the dough before the final rise, so it stays food-safe.",
      "Cover and let rise again for 30-40 minutes.",
      "Preheat the oven to 375°F. Brush the loaf all over with the beaten egg.",
      "Bake for 30-35 minutes, until deep golden brown and it sounds hollow when tapped on the bottom.",
      "Let cool before slicing, and let the oldest member of the table break the bread by hand, as is traditional, setting aside the first piece for the household before serving everyone else.",
    ],
    tags: ["dinner", "baking", "vegetarian"],
    bg: {
      title: "Коледна питка",
      description:
        "Традиционният български хляб за Бъдни вечер - кръгъл, обогатен хляб, ръчно оформен със символни ръбове и шарки, традиционно изпичан с монета, скрита вътре за късмет - оформянето на повърхността в ръбове и спирали, вместо да се остави гладка, е това, което дава на коледната питка нейния характерен, декоративен вид, а скриването на монетата (увита, за да остане безопасна за храна) е традицията, която прави намирането на твоето парче малко късче късмет за годината напред.",
      steps: [
        "Разтворете маята и захарта в топлата вода и оставете за 5-10 минути, докато се разпени.",
        "Смесете брашното и солта в голяма купа, добавете маената смес и олиото, и месете 8-10 минути, докато стане гладко и еластично.",
        "Покрийте и оставете да втаса на топло място 1 час, докато удвои обема си.",
        "Ударете тестото и отделете около 1/4 от него за украса. Оформете по-голямата част в гладък, плосък кръгъл хляб върху тава за печене.",
        "Разточете запазеното тесто на тънки въженца и ги наредете отгоре в декоративен десен - традиционните шарки включват кръстове, спирали и форми, представляващи слънцето, реколтата или добитъка, всяка носеща собствено символично пожелание за годината напред. Ако включвате монета за късмет, увийте я плътно във фолио първо и я напъхайте в долната страна на тестото преди последното втасване, за да остане безопасна за храна.",
        "Покрийте и оставете да втаса отново 30-40 минути.",
        "Загрейте фурната на 190°C. Намажете хляба отвсякъде с разбитото яйце.",
        "Печете 30-35 минути, докато стане дълбоко златисто кафяво и звучи кухо, когато се почука отдолу.",
        "Оставете да изстине преди рязане, и оставете най-възрастния на масата да разчупи хляба на ръка, както е традиционно, като запазите първото парче за домакинството, преди да сервирате на всички останали.",
      ],
      ingredients: [
        "4 чаши брашно",
        "2 1/4 ч.л. мая",
        "2 с.л. захар",
        "1 1/4 чаши топла вода",
        "1/3 чаша олио",
        "1 ч.л. сол",
        "1 яйце, разбито (за намазване)",
      ],
    },
  },
  {
    slug: "medenki",
    title: "Medenki",
    description:
      "Soft, cake-like Bulgarian honey and cinnamon cookies, dipped halfway in melted chocolate once cooled - beating the eggs and powdered sugar together until pale and thick before adding the honey is what gives medenki their soft, slightly cakey crumb instead of a hard, snappy cookie texture.",
    imageEmoji: "🍪",
    cookTimeMinutes: 40,
    servings: 10,
    ingredients: [
      { text: "2 eggs", ingredient: "eggs", quantity: 2 },
      { text: "3/4 cup powdered sugar", ingredient: "powdered sugar", quantity: 0.75 },
      { text: "1/2 cup honey", ingredient: "honey", quantity: 0.5 },
      { text: "1/4 cup vegetable oil", ingredient: "vegetable oil", quantity: 0.25 },
      { text: "1 tsp vanilla extract", ingredient: "vanilla extract", quantity: 1 },
      { text: "3 cups flour", ingredient: "flour", quantity: 3 },
      { text: "1 tsp baking soda", ingredient: "baking soda", quantity: 1 },
      { text: "1 tbsp cinnamon", ingredient: "cinnamon", quantity: 1 },
      { text: "1/4 tsp salt", ingredient: "salt", quantity: 0.25 },
      { text: "4 oz dark chocolate, chopped", ingredient: "dark chocolate", quantity: 4 },
      { text: "4 oz white chocolate, chopped", ingredient: "white chocolate", quantity: 4 },
    ],
    steps: [
      "Beat the eggs and powdered sugar together until pale and noticeably thickened, about 3-4 minutes - this is what gives medenki their soft, cake-like crumb rather than a hard, crisp cookie texture.",
      "Beat in the honey, oil, and vanilla until smooth.",
      "In a separate bowl, whisk together the flour, baking soda, cinnamon, and salt, then fold into the wet mixture until a soft dough forms.",
      "Cover and chill the dough for 20 minutes to make it easier to handle.",
      "Preheat the oven to 350°F. Roll the dough into 2-tablespoon balls, place on a lined baking sheet, and flatten slightly with your palm.",
      "Bake for 12-14 minutes, until just set and lightly golden on the bottom - they'll still look slightly underdone on top, which is normal; overbaking is what turns them hard instead of keeping them soft.",
      "Let cool completely on the baking sheet.",
      "Melt the dark and white chocolate separately. Dip half of each cooled cookie into one of the melted chocolates and set on parchment paper until the chocolate sets.",
    ],
    tags: ["dessert", "baking", "vegetarian"],
    bg: {
      title: "Меденки",
      description:
        "Меки, кексоподобни български бисквити с мед и канела, потопени наполовина в разтопен шоколад, след като изстинат - разбиването на яйцата и пудрата захар заедно, докато побледнеят и осезаемо сгъстеят, преди да се добави медът, е това, което дава на меденките техния мек, леко кексоподобен трохест вид, вместо твърда, чуплива бисквитена текстура.",
      steps: [
        "Разбийте яйцата и пудрата захар заедно, докато побледнеят и осезаемо се сгъстят, около 3-4 минути - това е това, което дава на меденките техния мек, кексоподобен вид, вместо твърда, хрупкава бисквитена текстура.",
        "Разбийте меда, олиото и ванилията, докато стане гладко.",
        "В отделна купа разбъркайте брашното, содата бикарбонат, канелата и солта, после прибавете към мократа смес, докато се получи меко тесто.",
        "Покрийте и охладете тестото 20 минути, за да е по-лесно за работа.",
        "Загрейте фурната на 175°C. Оформете тестото на топчета по 2 с.л., поставете върху застлана тава за печене, и леко сплескайте с дланта си.",
        "Печете 12-14 минути, докато точно се стегнат и леко позлатеят отдолу - отгоре все още ще изглеждат леко недопечени, което е нормално; препичането е това, което ги прави твърди, вместо да останат меки.",
        "Оставете да изстинат напълно върху тавата за печене.",
        "Разтопете тъмния и белия шоколад отделно. Потопете половината от всяка изстинала бисквита в един от разтопените шоколади и поставете върху хартия за печене, докато шоколадът се стегне.",
      ],
      ingredients: [
        "2 яйца",
        "3/4 чаша пудра захар",
        "1/2 чаша мед",
        "1/4 чаша олио",
        "1 ч.л. екстракт от ванилия",
        "3 чаши брашно",
        "1 ч.л. сода бикарбонат",
        "1 с.л. канела",
        "1/4 ч.л. сол",
        "115 г тъмен шоколад, нарязан",
        "115 г бял шоколад, нарязан",
      ],
    },
  },
  {
    slug: "katak",
    title: "Katak",
    description:
      "A tangy Bulgarian dip of yogurt blended with sirene, roasted red peppers, and garlic - traditionally served alongside rakia - char-roasting the peppers under a broiler or open flame until fully blackened before peeling, rather than using raw or plain sautéed peppers, is what gives katak its deep, smoky sweetness instead of a flat, purely tangy flavor.",
    imageEmoji: "🧄",
    cookTimeMinutes: 25,
    servings: 4,
    ingredients: [
      { text: "2 red bell peppers", ingredient: "bell peppers", quantity: 2 },
      { text: "1 cup plain yogurt", ingredient: "yogurt", quantity: 1 },
      { text: "5 oz sirene (Bulgarian white brined cheese), crumbled", ingredient: "sirene", quantity: 5 },
      { text: "2 cloves garlic, minced", ingredient: "garlic", quantity: 2 },
      { text: "2 tbsp sunflower oil", ingredient: "sunflower oil", quantity: 2 },
      { text: "1/2 tsp paprika", ingredient: "paprika", quantity: 0.5 },
      { text: "2 tbsp parsley, chopped", ingredient: "parsley", quantity: 2 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
    ],
    steps: [
      "Char the peppers directly over a gas flame or under a broiler, turning occasionally, until the skins are fully blackened all over.",
      "Transfer to a bowl, cover, and let steam for 10 minutes, then peel off the blackened skin, remove the seeds, and finely chop the flesh - full charring first, rather than just softening the peppers, is what gives katak its deep, smoky sweetness.",
      "Mash the crumbled sirene with the yogurt until mostly smooth, with some small chunks remaining.",
      "Stir in the chopped roasted peppers, garlic, sunflower oil, and paprika.",
      "Season with salt to taste, top with the parsley, and serve chilled or at room temperature with bread - traditionally alongside a glass of rakia.",
    ],
    tags: ["snack", "vegetarian"],
    bg: {
      title: "Катък",
      description:
        "Пикантен български дип от кисело мляко, разбито със сирене, печени червени чушки и чесън - традиционно сервиран заедно с ракия - изгарянето на чушките под грил или на открит пламък, докато напълно почернеят, преди белене, вместо да се използват сурови или леко запържени чушки, е това, което дава на катъка неговата дълбока, димна сладост, вместо плоска, чисто кисела нотка.",
      steps: [
        "Изгорете чушките директно на газов пламък или под грил, обръщайки от време на време, докато кожата им напълно почернее навсякъде.",
        "Прехвърлете в купа, покрийте и оставете да се задушат на пара 10 минути, после обелете почернялата кожа, отстранете семките, и нарежете месестата част ситно - пълното изгаряне първо, вместо просто омекотяване на чушките, е това, което дава на катъка неговата дълбока, димна сладост.",
        "Разбийте натрошеното сирене с киселото мляко, докато стане предимно гладко, с останали няколко малки бучки.",
        "Разбъркайте нарязаните печени чушки, чесъна, слънчогледовото олио и червения пипер.",
        "Подправете със сол на вкус, поръсете с магданоза, и сервирайте охладено или на стайна температура с хляб - традиционно заедно с чаша ракия.",
      ],
      ingredients: [
        "2 червени чушки",
        "1 чаша кисело мляко",
        "150 г сирене, натрошено",
        "2 скилидки чесън, ситно нарязани",
        "2 с.л. слънчогледово олио",
        "1/2 ч.л. червен пипер",
        "2 с.л. магданоз, нарязан",
        "Сол на вкус",
      ],
    },
  },
  {
    slug: "spanacheva-banitsa",
    title: "Spanacheva Banitsa (Spinach Banitsa)",
    description:
      "A Bulgarian banitsa filled with wilted spinach, sirene, and egg instead of the classic plain-cheese filling, rolled in phyllo and baked until golden - wringing the cooked spinach completely dry before mixing it with the cheese and egg is what keeps the filling from turning the phyllo layers soggy in the oven.",
    imageEmoji: "🥬",
    cookTimeMinutes: 70,
    servings: 8,
    ingredients: [
      { text: "2 lb spinach", ingredient: "spinach", quantity: 2 },
      { text: "1 onion, finely chopped", ingredient: "onion", quantity: 1 },
      { text: "2 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 2 },
      { text: "10 oz sirene (Bulgarian white brined cheese), crumbled", ingredient: "sirene", quantity: 10 },
      { text: "3 eggs", ingredient: "eggs", quantity: 3 },
      { text: "1/2 cup plain yogurt", ingredient: "yogurt", quantity: 0.5 },
      { text: "1 lb phyllo dough", ingredient: "phyllo dough", quantity: 1 },
      { text: "1 cup melted butter", ingredient: "butter", quantity: 1 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "Pepper to taste", ingredient: "pepper", quantity: null },
    ],
    steps: [
      "Sauté the onion in the oil until softened, then add the spinach in batches, cooking until fully wilted.",
      "Transfer the spinach to a colander and let cool slightly, then wring it out firmly by handfuls to remove as much liquid as possible - skipping this step is what makes the finished banitsa soggy instead of properly flaky.",
      "Chop the wrung-out spinach and mix with the crumbled sirene, 2 of the eggs, salt, and pepper.",
      "Whisk the remaining egg with the yogurt to make an egg wash for the layers.",
      "Lay out a sheet of phyllo, brush with melted butter, top with a second sheet, and spread a thin line of the spinach filling along one edge.",
      "Roll the phyllo up around the filling into a rope, then coil it into a spiral in a buttered round baking pan. Repeat with the remaining phyllo and filling, coiling each new rope around the last.",
      "Pour the egg-yogurt wash evenly over the top and brush with any remaining butter.",
      "Bake at 375°F for 35-40 minutes, until deep golden brown and crisp.",
      "Let cool slightly before slicing and serving warm.",
    ],
    tags: ["breakfast", "baking", "vegetarian"],
    bg: {
      title: "Спаначена баница",
      description:
        "Българска баница, пълнена с задушен спанак, сирене и яйце вместо класическия обикновен сиренен пълнеж, навита в кори и изпечена до златисто - изстискването на сготвения спанак напълно сух, преди да се смеси със сиренето и яйцето, е това, което пази пълнежа да не разкисне корите във фурната.",
      steps: [
        "Запържете лука в олиото до омекване, после добавете спанака на порции, готвейки, докато напълно завехне.",
        "Прехвърлете спанака в цедка и оставете да изстине леко, после го изстискайте здраво на шепи, за да отстраните колкото се може повече течност - пропускането на тази стъпка е това, което прави готовата баница разкисната, вместо правилно ронлива.",
        "Нарежете изстискания спанак и смесете с натрошеното сирене, 2-те от яйцата, солта и пипера.",
        "Разбийте останалото яйце с киселото мляко, за да направите яйчена глазура за слоевете.",
        "Разстелете лист кори, намажете с разтопено масло, покрийте с втори лист, и разпределете тънка ивица от спаначения пълнеж по единия ръб.",
        "Навийте корите около пълнежа на руло, после навийте на спирала в намазана кръгла тава за печене. Повторете с останалите кори и пълнеж, навивайки всяко ново руло около предишното.",
        "Изсипете яйчено-кисело-млечната глазура равномерно отгоре и намажете с останалото масло.",
        "Печете на 190°C 35-40 минути, докато стане дълбоко златисто кафяво и хрупкаво.",
        "Оставете да изстине леко преди рязане и сервиране топла.",
      ],
      ingredients: [
        "900 г спанак",
        "1 лук, ситно нарязан",
        "2 с.л. олио",
        "280 г сирене, натрошено",
        "3 яйца",
        "1/2 чаша кисело мляко",
        "450 г кори за баница",
        "1 чаша разтопено масло",
        "Сол на вкус",
        "Черен пипер на вкус",
      ],
    },
  },
  {
    slug: "pileshko-s-oriz",
    title: "Pileshko s Oriz (Bulgarian Chicken with Rice)",
    description:
      "Bulgaria's everyday one-pan dinner of chicken pieces baked directly on a bed of rice and broth - an Ottoman-era dish adapted into Bulgarian home cooking - nestling the raw rice under the chicken instead of cooking it separately is what lets it soak up the rendered chicken fat and broth as it bakes, turning richer than plain steamed rice ever could.",
    imageEmoji: "🍗",
    cookTimeMinutes: 60,
    servings: 4,
    ingredients: [
      { text: "3 lb chicken thighs and drumsticks, bone-in", ingredient: "chicken thighs", quantity: 3 },
      { text: "1 1/2 cups rice", ingredient: "rice", quantity: 1.5 },
      { text: "1 onion, chopped", ingredient: "onion", quantity: 1 },
      { text: "1 carrot, diced", ingredient: "carrot", quantity: 1 },
      { text: "3 cups chicken broth", ingredient: "chicken broth", quantity: 3 },
      { text: "3 tbsp butter, melted", ingredient: "butter", quantity: 3 },
      { text: "1 tsp paprika", ingredient: "paprika", quantity: 1 },
      { text: "1 bay leaf", ingredient: "bay leaf", quantity: 1 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "Pepper to taste", ingredient: "pepper", quantity: null },
    ],
    steps: [
      "Preheat the oven to 375°F. Season the chicken pieces all over with salt, pepper, and paprika.",
      "Spread the rice, onion, and carrot in an even layer across the bottom of a deep baking dish.",
      "Arrange the chicken pieces skin-side up on top of the rice.",
      "Pour the warm chicken broth evenly around the chicken, not directly over it, and tuck in the bay leaf - nestling the raw rice under the chicken like this is what lets it soak up the rendered fat and broth as everything bakes together, turning richer than rice cooked separately ever could.",
      "Drizzle the melted butter over the chicken skin.",
      "Cover tightly with foil and bake for 35 minutes.",
      "Uncover and bake for another 15-20 minutes, until the chicken skin is golden and the rice has absorbed all the liquid and is tender.",
      "Let rest for 5 minutes before serving directly from the dish.",
    ],
    tags: ["dinner"],
    bg: {
      title: "Пиле с ориз",
      description:
        "Всекидневната българска вечеря от една тава - парчета пиле, изпечени директно върху легло от ориз и бульон - ястие от османската епоха, пригодено към българската домашна кухня - настаняването на суровия ориз под пилето, вместо да се готви отделно, е това, което му позволява да попие разтопената пилешка мазнина и бульона, докато се пече, ставайки по-богат, отколкото обикновен варен ориз някога би могъл.",
      steps: [
        "Загрейте фурната на 190°C. Подправете парчетата пиле отвсякъде със сол, пипер и червен пипер.",
        "Разстелете ориза, лука и моркова в равен пласт на дъното на дълбока тава за печене.",
        "Наредете парчетата пиле с кожата нагоре върху ориза.",
        "Залейте с топлия пилешки бульон равномерно около пилето, не директно върху него, и напъхайте дафиновия лист - настаняването на суровия ориз под пилето по този начин е това, което му позволява да попие разтопената мазнина и бульона, докато всичко се пече заедно, ставайки по-богат от ориз, варен отделно.",
        "Полейте с разтопеното масло върху кожата на пилето.",
        "Покрийте плътно с фолио и печете 35 минути.",
        "Разкрийте и печете още 15-20 минути, докато кожата на пилето стане златиста, а оризът попие цялата течност и омекне.",
        "Оставете да почине 5 минути преди да сервирате директно от тавата.",
      ],
      ingredients: [
        "1.3 кг пилешки бутчета и кълки, с кости",
        "1 1/2 чаши ориз",
        "1 лук, нарязан",
        "1 морков, нарязан на кубчета",
        "3 чаши пилешки бульон",
        "3 с.л. масло, разтопено",
        "1 ч.л. червен пипер",
        "1 дафинов лист",
        "Сол на вкус",
        "Черен пипер на вкус",
      ],
    },
  },
  {
    slug: "pecheni-chushki-s-chesan",
    title: "Pecheni Chushki s Chesan (Roasted Peppers with Garlic)",
    description:
      "One of Bulgaria's most distinctive salads - whole peppers roasted until fully blackened, peeled, then marinated overnight in garlic, oil, and vinegar - letting the peeled peppers sit in the marinade in the fridge overnight, rather than serving them right away, is what actually lets the garlic and vinegar penetrate the flesh instead of just coating the surface.",
    imageEmoji: "🫑",
    cookTimeMinutes: 30,
    servings: 4,
    ingredients: [
      { text: "6 red bell peppers", ingredient: "bell peppers", quantity: 6 },
      { text: "3 cloves garlic, minced", ingredient: "garlic", quantity: 3 },
      { text: "3 tbsp olive oil", ingredient: "olive oil", quantity: 3 },
      { text: "1 1/2 tsp vinegar", ingredient: "vinegar", quantity: 1.5 },
      { text: "2 tbsp parsley, chopped", ingredient: "parsley", quantity: 2 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
    ],
    steps: [
      "Preheat the oven to 400°F. Char the whole peppers directly over a gas flame or roast them in the oven, turning occasionally, until the skins are fully blackened and blistered all over.",
      "Transfer to a bowl, cover tightly, and let steam for 10-15 minutes - the trapped steam is what loosens the skins enough to peel off cleanly.",
      "Peel off the blackened skins, then cut each pepper open and remove the seeds and core, keeping the flesh in large pieces.",
      "Toss the peeled peppers with the minced garlic, olive oil, vinegar, and salt.",
      "Cover and refrigerate for at least a few hours, ideally overnight - this resting time is what actually lets the garlic and vinegar penetrate the peppers, rather than just sitting on the surface.",
      "Top with fresh parsley and serve chilled or at room temperature with bread.",
    ],
    tags: ["snack", "vegetarian", "vegan"],
    bg: {
      title: "Печени чушки с чесън",
      description:
        "Една от най-характерните български салати - цели чушки, печени докато напълно почернеят, обелени, после мариновани през нощта в чесън, олио и оцет - оставянето на обелените чушки в марината в хладилника през нощта, вместо да се сервират веднага, е това, което наистина позволява на чесъна и оцета да проникнат в месестата част, вместо просто да покрият повърхността.",
      steps: [
        "Загрейте фурната на 200°C. Изгорете целите чушки директно на газов пламък или ги изпечете във фурната, обръщайки от време на време, докато кожата им напълно почернее и се напука навсякъде.",
        "Прехвърлете в купа, покрийте плътно и оставете да се задушат на пара 10-15 минути - задържаната пара е това, което разхлабва кожата достатъчно, за да се обели чисто.",
        "Обелете почернялата кожа, после разрежете всяка чушка и отстранете семките и сърцевината, като запазите месестата част на едри парчета.",
        "Разбъркайте обелените чушки с ситно нарязания чесън, зехтина, оцета и солта.",
        "Покрийте и охладете в хладилника поне няколко часа, най-добре през нощта - това време за престояване е това, което наистина позволява на чесъна и оцета да проникнат в чушките, вместо просто да останат на повърхността.",
        "Поръсете с пресен магданоз и сервирайте охладени или на стайна температура с хляб.",
      ],
      ingredients: [
        "6 червени чушки",
        "3 скилидки чесън, ситно нарязани",
        "3 с.л. зехтин",
        "1 1/2 ч.л. оцет",
        "2 с.л. магданоз, нарязан",
        "Сол на вкус",
      ],
    },
  },
  {
    slug: "keks",
    title: "Keks (Bulgarian Marble Loaf Cake)",
    description:
      "A dense, buttery Bulgarian loaf cake layered with a cinnamon-walnut filling for a marbled swirl inside - beating the butter, sugar, and vanilla until pale and fluffy before adding the eggs is what gives keks its tender, close crumb, and layering the cinnamon filling between spoonfuls of batter rather than stirring it in is what keeps the swirl distinct instead of blending into a uniform brown.",
    imageEmoji: "🍰",
    cookTimeMinutes: 70,
    servings: 10,
    ingredients: [
      { text: "1/2 cup butter, room temperature", ingredient: "butter", quantity: 0.5 },
      { text: "1 cup sugar", ingredient: "sugar", quantity: 1 },
      { text: "1/2 tsp vanilla extract", ingredient: "vanilla extract", quantity: 0.5 },
      { text: "2 eggs", ingredient: "eggs", quantity: 2 },
      { text: "2 cups flour", ingredient: "flour", quantity: 2 },
      { text: "1 tsp baking powder", ingredient: "baking powder", quantity: 1 },
      { text: "1 tsp baking soda", ingredient: "baking soda", quantity: 1 },
      { text: "1/4 cup sour cream", ingredient: "sour cream", quantity: 0.25 },
      { text: "1/3 cup brown sugar", ingredient: "brown sugar", quantity: 0.33 },
      { text: "1 tbsp cinnamon", ingredient: "cinnamon", quantity: 1 },
      { text: "1/2 cup walnuts, chopped", ingredient: "walnuts", quantity: 0.5 },
    ],
    steps: [
      "Preheat the oven to 350°F and grease a loaf pan.",
      "Beat the butter, sugar, and vanilla together until pale and fluffy, about 3-4 minutes - this is what gives keks its tender, close crumb rather than a dense, heavy one.",
      "Beat in the eggs one at a time, then mix in the sour cream.",
      "In a separate bowl, whisk together the flour, baking powder, and baking soda, then fold into the wet ingredients until just combined.",
      "In a small bowl, mix the brown sugar, cinnamon, and walnuts for the filling.",
      "Spoon a third of the batter into the prepared pan, scatter half the cinnamon-walnut mixture over it, add another third of the batter, scatter the remaining cinnamon mixture, then top with the last of the batter - layering it in like this, rather than stirring the filling directly into the batter, is what keeps the swirl distinct instead of turning the whole cake uniformly brown.",
      "Bake for 50-55 minutes, until a toothpick inserted into the center comes out clean, tenting with foil if the top browns too quickly.",
      "Let cool in the pan for 10 minutes, then turn out onto a rack to cool completely before slicing.",
    ],
    tags: ["dessert", "baking", "vegetarian"],
    bg: {
      title: "Кекс",
      description:
        "Плътен, маслен български кекс, послоен с плънка от канела и орехи за мраморен ефект вътре - разбиването на маслото, захарта и ванилията, докато побледнеят и станат пухкави, преди да се добавят яйцата, е това, което дава на кекса неговата нежна, плътна средина, а послояването на канелената плънка между лъжици тесто, вместо да се разбърква в него, е това, което пази вихрушката отчетлива, вместо да се слее в еднородно кафяво.",
      steps: [
        "Загрейте фурната на 175°C и намажете тава за кекс.",
        "Разбийте маслото, захарта и ванилията заедно, докато побледнеят и станат пухкави, около 3-4 минути - това е това, което дава на кекса неговата нежна, плътна средина, вместо тежка и плътна.",
        "Разбийте яйцата едно по едно, после разбъркайте заквасената сметана.",
        "В отделна купа разбъркайте брашното, бакпулвера и содата бикарбонат, после прибавете към мократа смес, докато се съединят.",
        "В малка купа смесете кафявата захар, канелата и орехите за плънката.",
        "Сложете с лъжица трета от тестото в подготвената тава, поръсете половината от канелено-ореховата смес отгоре, добавете още трета от тестото, поръсете останалата канелена смес, после завършете с останалото тесто - послояването по този начин, вместо разбъркването на плънката директно в тестото, е това, което пази вихрушката отчетлива, вместо да превърне целия кекс в еднородно кафяво.",
        "Печете 50-55 минути, докато клечка за зъби, забита в центъра, излезе чиста, покривайки с фолио, ако горната част заруменее твърде бързо.",
        "Оставете да изстине в тавата 10 минути, после обърнете върху решетка да изстине напълно преди рязане.",
      ],
      ingredients: [
        "1/2 чаша масло, стайна температура",
        "1 чаша захар",
        "1/2 ч.л. екстракт от ванилия",
        "2 яйца",
        "2 чаши брашно",
        "1 ч.л. бакпулвер",
        "1 ч.л. сода бикарбонат",
        "1/4 чаша заквасена сметана",
        "1/3 чаша кафява захар",
        "1 с.л. канела",
        "1/2 чаша орехи, нарязани",
      ],
    },
  },
];

async function main() {
  for (const recipe of newRecipes) {
    const created = await prisma.recipe.create({
      data: {
        slug: recipe.slug,
        title: recipe.title,
        description: recipe.description,
        imageEmoji: recipe.imageEmoji,
        cookTimeMinutes: recipe.cookTimeMinutes,
        servings: recipe.servings,
        steps: JSON.stringify(recipe.steps),
        tags: JSON.stringify(recipe.tags),
      },
    });

    for (let i = 0; i < recipe.ingredients.length; i++) {
      const { text, ingredient, quantity } = recipe.ingredients[i];
      const ingredientRow = await prisma.ingredient.upsert({
        where: { name: ingredient },
        update: {},
        create: { name: ingredient },
      });
      await prisma.recipeIngredient.create({
        data: {
          recipeId: created.id,
          ingredientId: ingredientRow.id,
          displayText: text,
          quantity,
          position: i,
        },
      });
    }
    console.log(`Created ${recipe.slug}`);
  }
  console.log(`Created ${newRecipes.length} recipes total.`);

  // runTranslations disconnects prisma when done, so it must run last.
  await runTranslations(newRecipes.map((r) => ({ slug: r.slug, ...r.bg })));
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
