import { applyRecipeUpdates } from "./update-lib.mjs";

// Research-verified corrections to the 5 recipes added in add_recipes_batch1.mjs,
// which were written from trained knowledge without verification. See findings:
// - chicken-adobo: vinegar:soy ratio was backwards (more vinegar than soy is correct)
// - mapo-tofu: traditionally ground beef not pork; needs Pixian doubanjiang,
//   freshly toasted Sichuan peppercorns, and a two-stage cornstarch slurry
// - pierogi: traditional dough has no egg/sour cream (flour+hot water+salt+fat);
//   traditional filling cheese is farmer's cheese/twaróg, not cheddar
// - hungarian-goulash: what's commonly called "goulash" (thick stew) is actually
//   pörkölt; real gulyás is a brothy soup with csipetke dumplings
// - khachapuri: Imeretian khachapuri is oven-baked, not pan-fried
const updates = [
  {
    en: {
      slug: "chicken-adobo",
      title: "Chicken Adobo",
      description:
        "Chicken seared then braised in a sauce with more vinegar than soy sauce, boiled uncovered without stirring at first to mellow its raw sharpness, then reduced into a glaze - getting the vinegar-to-soy ratio backwards, which most non-Filipino recipes do, is what leaves adobo tasting like salty soy chicken instead of the real thing.",
      imageEmoji: "🍗",
      cookTimeMinutes: 45,
      servings: 4,
      ingredients: [
        { text: "2 lb chicken thighs, bone-in and skin-on", ingredient: "chicken thighs", quantity: 2 },
        { text: "1 onion, sliced", ingredient: "onion", quantity: 1 },
        { text: "6 cloves garlic, smashed", ingredient: "garlic", quantity: 6 },
        { text: "1/2 cup cane vinegar or coconut vinegar", ingredient: "vinegar", quantity: 0.5 },
        { text: "1/4 cup soy sauce", ingredient: "soy sauce", quantity: 0.25 },
        { text: "3 bay leaves", ingredient: "bay leaf", quantity: 3 },
        { text: "1 tsp whole black peppercorns", ingredient: "black peppercorns", quantity: 1 },
        { text: "1 tbsp brown sugar", ingredient: "brown sugar", quantity: 1 },
        { text: "1 cup water", ingredient: "water", quantity: 1 },
        { text: "2 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 2 },
      ],
      steps: [
        "Heat the oil in a pot and sauté the onion and garlic until fragrant and lightly softened.",
        "Add the chicken and sear on all sides until lightly browned - searing renders the skin's fat and builds deeper flavor before braising.",
        "Pour in the vinegar, soy sauce, water, bay leaves, peppercorns, and brown sugar. Bring to a boil and let it boil, uncovered and without stirring, for 5 minutes - this is what mellows the vinegar's raw sharpness instead of trapping a harsh, sour bite in the sauce.",
        "Stir, then reduce the heat, cover, and simmer for 20-25 minutes until the chicken is cooked through.",
        "Uncover and simmer for another 10-15 minutes, spooning the sauce over the chicken occasionally, until it reduces into a glaze.",
        "Serve over rice.",
      ],
      tags: ["dinner", "asian"],
    },
    bg: {
      title: "Пилешко адобо",
      description:
        "Пиле, запечено и после задушено в сос с повече оцет, отколкото соев сос, вряло без разбъркване в началото, за да омекне суровата острота, после сгъстено до глазура - обръщането на съотношението оцет:соев сос, което правят повечето рецепти извън Филипините, е причината адобото да остане на вкус като солено соево пиле, вместо истинското ястие.",
      steps: [
        "Загрейте олиото в тенджера и запържете лука и чесъна до ароматизиране и леко омекване.",
        "Добавете пилето и запечете от всички страни до леко зачервяване - запичането разтопява мазнината от кожата и изгражда по-дълбок вкус преди задушаването.",
        "Долейте оцета, соевия сос, водата, дафиновите листа, черния пипер на зърна и кафявата захар. Оставете да заври и врете без капак и без разбъркване 5 минути - това е, което омекотява суровата острота на оцета, вместо да я затвори в соса.",
        "Разбъркайте, после намалете котлона, покрийте и къкрете 20-25 минути, докато пилето се сготви напълно.",
        "Отворете капака и къкрете още 10-15 минути, поливайки от време на време със соса, докато се сгъсти до глазура.",
        "Сервирайте върху ориз.",
      ],
      ingredients: [
        "900 г пилешки бутчета с кост и кожа",
        "1 лук, нарязан на резени",
        "6 скилидки чесън, натрошени",
        "1/2 чаша оцет от захарна тръстика или кокосов оцет",
        "1/4 чаша соев сос",
        "3 дафинови листа",
        "1 ч.л. черен пипер на зърна",
        "1 с.л. кафява захар",
        "1 чаша вода",
        "2 с.л. олио",
      ],
    },
  },
  {
    en: {
      slug: "mapo-tofu",
      title: "Mapo Tofu",
      description:
        "Silken tofu and crisped ground beef in a numbing, fiery Sichuan sauce built on Pixian doubanjiang and freshly toasted Sichuan peppercorns - jarred pre-ground pepper and a shake of chili powder are why most versions outside Sichuan taste hot but never actually numbing.",
      imageEmoji: "🌶️",
      cookTimeMinutes: 30,
      servings: 4,
      ingredients: [
        { text: "14 oz soft or silken tofu, cubed", ingredient: "tofu", quantity: 14 },
        { text: "1/2 lb ground beef", ingredient: "ground beef", quantity: 0.5 },
        { text: "3 tbsp Pixian doubanjiang (fermented broad bean chili paste)", ingredient: "doubanjiang", quantity: 3 },
        { text: "1 tbsp fermented black beans, chopped", ingredient: "fermented black beans", quantity: 1 },
        { text: "3 cloves garlic, minced", ingredient: "garlic", quantity: 3 },
        { text: "1 tbsp fresh ginger, minced", ingredient: "ginger", quantity: 1 },
        { text: "2 green onions, sliced, white and green parts separated", ingredient: "green onion", quantity: 2 },
        { text: "1 tsp Sichuan peppercorns, toasted and freshly ground", ingredient: "sichuan peppercorns", quantity: 1 },
        { text: "1 cup chicken broth", ingredient: "chicken broth", quantity: 1 },
        { text: "1 tbsp soy sauce", ingredient: "soy sauce", quantity: 1 },
        { text: "2 tsp cornstarch mixed with 1/4 cup water", ingredient: "cornstarch", quantity: 2 },
        { text: "3 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 3 },
      ],
      steps: [
        "Toast the Sichuan peppercorns in a dry pan for 1 minute until fragrant, then grind them - toasting and grinding them fresh is what gives real mapo tofu its numbing \"mala\" effect, which pre-ground jarred pepper has usually lost.",
        "Bring a pot of lightly salted water to a boil and gently blanch the tofu cubes for 2 minutes, then drain - this firms the tofu and removes its raw bean taste so it holds together in the sauce instead of crumbling.",
        "Heat the oil in a wok and fry the ground beef until browned and the edges turn slightly crisp, not just cooked through - that bit of crispness is one of the traditional hallmarks of real mapo tofu.",
        "Add the doubanjiang, fermented black beans, garlic, ginger, and the white parts of the green onion; stir-fry for 1 minute until fragrant and the oil turns red.",
        "Pour in the chicken broth and soy sauce, then gently slide in the tofu and simmer for 5 minutes, stirring gently to avoid breaking the cubes.",
        "Stir in half the cornstarch slurry and simmer for 1 minute, then add the rest - thickening in two additions instead of all at once is what gives the sauce its glossy, restaurant-style sheen.",
        "Sprinkle with the ground Sichuan peppercorns and the green onion tops before serving.",
      ],
      tags: ["dinner", "asian", "quick"],
    },
    bg: {
      title: "Мапо тофу",
      description:
        "Копринено тофу и хрупкаво запържена говежда кайма в изтръпващ, огнен съчуански сос, изграден върху доубандзян от Пиксиен и прясно препечен и смлян съчуански пипер - предварително смлян пипер от бурканче и щипка чили на прах е причината повечето версии извън Съчуан да имат вкус на лютиво, но никога наистина изтръпващо.",
      steps: [
        "Препечете съчуанския пипер в сух тиган за 1 минута до ароматизиране, после го смелете - прясното препичане и смилане е това, което дава на истинското мапо тофу неговия изтръпващ ефект \"мала\", който предварително смленият пипер от бурканче обикновено е загубил.",
        "Оставете тенджера леко подсолена вода да заври и бланширайте тофуто на кубчета за 2 минути, после отцедете - това стяга тофуто и премахва суровия боб вкус, за да се задържи цяло в соса, вместо да се рони.",
        "Загрейте олиото в уок и запържете говеждата кайма до зачервяване и леко хрупкави краища, не само до сготвяне - тази лека хрупкавост е един от традиционните белези на истинското мапо тофу.",
        "Добавете доубандзяна, ферментиралия черен боб, чесъна, джинджифила и бялата част на зеления лук; запържете 1 минута до ароматизиране и почервеняване на олиото.",
        "Долейте пилешкия бульон и соевия сос, после внимателно сложете тофуто и къкрете 5 минути, разбърквайки внимателно, за да не се счупят кубчетата.",
        "Разбъркайте половината от разтвора с нишесте и къкрете 1 минута, после добавете останалото - сгъстяването на два пъти вместо наведнъж е това, което дава на соса неговия лъскав, ресторантски блясък.",
        "Поръсете със смления съчуански пипер и зелената част на лука преди сервиране.",
      ],
      ingredients: [
        "400 г меко или копринено тофу, нарязано на кубчета",
        "225 г говежда кайма",
        "3 с.л. доубандзян от Пиксиен (ферментирала чили паста от боб)",
        "1 с.л. ферментирал черен боб, нарязан",
        "3 скилидки чесън, ситно нарязани",
        "1 с.л. пресен джинджифил, ситно нарязан",
        "2 стръка зелен лук, нарязани, бяло и зелено разделени",
        "1 ч.л. съчуански пипер, препечен и прясно смлян",
        "1 чаша пилешки бульон",
        "1 с.л. соев сос",
        "2 ч.л. нишесте, разбъркано с 1/4 чаша вода",
        "3 с.л. олио",
      ],
    },
  },
  {
    en: {
      slug: "pierogi",
      title: "Pierogi",
      description:
        "Polish dumplings made with a simple hot-water dough (no egg, no sour cream) and filled with mashed potato, farmer's cheese, and caramelized onion, then boiled and pan-fried in butter - traditional pierogi dough is just flour, hot water, salt, and a little fat, not the egg-and-sour-cream dough most Americanized recipes use.",
      imageEmoji: "🥟",
      cookTimeMinutes: 60,
      servings: 4,
      ingredients: [
        { text: "3 cups flour", ingredient: "flour", quantity: 3 },
        { text: "3/4 cup hot water", ingredient: "water", quantity: 0.75 },
        { text: "1 tsp salt (for the dough)", ingredient: "salt", quantity: 1 },
        { text: "2 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 2 },
        { text: "2 cups mashed potatoes, cooled", ingredient: "mashed potatoes", quantity: 2 },
        { text: "1 cup farmer's cheese or dry curd cottage cheese (or cheddar if unavailable)", ingredient: "farmer's cheese", quantity: 1 },
        { text: "1 onion, finely diced, divided", ingredient: "onion", quantity: 1 },
        { text: "3 tbsp butter", ingredient: "butter", quantity: 3 },
        { text: "Salt to taste (for the filling)", ingredient: "salt", quantity: null },
        { text: "Pepper to taste", ingredient: "pepper", quantity: null },
      ],
      steps: [
        "Sauté half the diced onion in 1 tbsp of the butter until deeply golden, then mix into the mashed potatoes with the farmer's cheese, salt, and pepper to make the filling.",
        "Combine the flour and salt, then stir in the hot water and oil and mix into a dough - hot water, not cold, is what makes traditional pierogi dough soft and pliable, unlike the stiffer texture an egg-enriched dough gives.",
        "Knead until smooth, about 5-7 minutes, then cover and rest for 20-30 minutes.",
        "Roll the dough thin and cut into rounds. Spoon a small amount of filling onto each round, fold over, and pinch the edges tightly to seal - a well-sealed edge is what keeps the filling from leaking out into the boiling water.",
        "Boil the pierogi in batches in salted water until they float to the top, about 3-4 minutes.",
        "Sauté the remaining onion in the rest of the butter until golden, then toss the boiled pierogi in the pan to lightly brown before serving.",
      ],
      tags: ["dinner", "vegetarian"],
    },
    bg: {
      title: "Пироги",
      description:
        "Полски кнедли с проста тестена основа от гореща вода (без яйце, без заквасена сметана), пълнени с картофено пюре, извара и карамелизиран лук, сварени и после запържени в масло - традиционното тесто за пироги е само брашно, гореща вода, сол и малко мазнина, а не тестото с яйце и заквасена сметана, което повечето американизирани рецепти използват.",
      steps: [
        "Запържете половината нарязан лук в 1 с.л. от маслото до дълбоко златист цвят, после смесете с картофеното пюре, изварата и черния пипер за пълнежа.",
        "Смесете брашното и солта, после разбъркайте горещата вода и олиото и омесете тесто - горещата, а не студена вода, е това, което прави традиционното тесто за пироги меко и еластично, за разлика от по-твърдата текстура на тесто с яйце.",
        "Месете до гладкост, около 5-7 минути, после покрийте и оставете да почине 20-30 минути.",
        "Разточете тестото тънко и изрежете кръгове. Сложете малко пълнеж върху всеки кръг, сгънете наполовина и стегнато прищипете краищата, за да запечатате - добре запечатан край е това, което пази пълнежа да не изтече във врящата вода.",
        "Варете пирогите на партиди в подсолена вода, докато изплуват, около 3-4 минути.",
        "Запържете останалия лук в останалото масло до златисто, после разбъркайте сварените пироги в тигана, за да леко се зачервят преди сервиране.",
      ],
      ingredients: [
        "3 чаши брашно",
        "3/4 чаша гореща вода",
        "1 ч.л. сол (за тестото)",
        "2 с.л. олио",
        "2 чаши картофено пюре, изстинало",
        "1 чаша извара или чедър, ако изварата не е налична",
        "1 лук, ситно нарязан, разделен",
        "3 с.л. масло",
        "Сол на вкус (за пълнежа)",
        "Черен пипер на вкус",
      ],
    },
  },
  {
    en: {
      slug: "hungarian-goulash",
      title: "Hungarian Goulash (Gulyás)",
      description:
        "The genuine herdsman's soup Hungarians actually call gulyás - a brothy beef, paprika, and caraway soup with pinched egg-dough dumplings (csipetke), not the thick, gravy-like stew most non-Hungarian recipes serve under the goulash name (that thicker dish is properly called pörkölt).",
      imageEmoji: "🍲",
      cookTimeMinutes: 160,
      servings: 6,
      ingredients: [
        { text: "2 lb beef chuck, cubed", ingredient: "beef chuck", quantity: 2 },
        { text: "2 tbsp lard or vegetable oil", ingredient: "lard", quantity: 2 },
        { text: "3 onions, diced", ingredient: "onion", quantity: 3 },
        { text: "3 tbsp sweet Hungarian paprika", ingredient: "paprika", quantity: 3 },
        { text: "1 tbsp caraway seeds", ingredient: "caraway seeds", quantity: 1 },
        { text: "3 cloves garlic, minced", ingredient: "garlic", quantity: 3 },
        { text: "1 green bell pepper, diced", ingredient: "green pepper", quantity: 1 },
        { text: "1 tomato, diced", ingredient: "tomato", quantity: 1 },
        { text: "4 potatoes, cubed", ingredient: "potato", quantity: 4 },
        { text: "8 cups beef broth", ingredient: "beef broth", quantity: 8 },
        { text: "1/2 cup flour (for the csipetke dumplings)", ingredient: "flour", quantity: 0.5 },
        { text: "1 egg (for the csipetke dumplings)", ingredient: "eggs", quantity: 1 },
        { text: "Salt to taste", ingredient: "salt", quantity: null },
        { text: "Pepper to taste", ingredient: "pepper", quantity: null },
      ],
      steps: [
        "Heat the lard or oil in a large pot and cook the onions over low heat until deeply softened and golden, about 15 minutes.",
        "Remove the pot from the heat briefly and stir in the paprika, caraway seeds, and garlic - taking the pot off the heat before adding the paprika keeps it from scorching and turning bitter.",
        "Return the pot to the stove, add the beef, tomato, and bell pepper, and stir to coat.",
        "Pour in the beef broth, bring to a boil, then reduce heat, cover, and simmer for 1.5 hours until the beef is tender - keeping the pot covered so it stays brothy instead of reducing down is what makes this genuine gulyás soup rather than the thick stew most non-Hungarian recipes call goulash.",
        "Add the potatoes and simmer for another 20-25 minutes until tender.",
        "Meanwhile, mix the flour, egg, and a pinch of salt into a stiff dough for the csipetke. Pinch off small, pea-sized pieces and drop them into the simmering soup for the final 8-10 minutes until they float and are cooked through.",
        "Season with salt and pepper before serving.",
      ],
      tags: ["dinner"],
    },
    bg: {
      title: "Унгарски гулаш (Gulyás)",
      description:
        "Истинската овчарска супа, която унгарците наричат гулаш - бульонена супа от телешко, чушка и кимион с накъснати юфкови кнедли (чипетке), а не гъстото, соусоподобно яхнийно ястие, което повечето рецепти извън Унгария поднасят под името гулаш (по-гъстото ястие се нарича правилно пьоркьолт).",
      steps: [
        "Загрейте свинската мас или олиото в голяма тенджера и гответе лука на слаб огън до дълбоко омекване и златист цвят, около 15 минути.",
        "Свалете тенджерата за кратко от котлона и разбъркайте чушката, кимиона и чесъна - свалянето от котлона преди добавянето на чушката пази от загаряне и горчивина.",
        "Върнете тенджерата на котлона, добавете телешкото, домата и чушката, и разбъркайте да се покрият.",
        "Долейте телешкия бульон, оставете да заври, после намалете котлона, покрийте и къкрете 1.5 часа, докато телешкото омекне - държането на капака затворен, за да остане бульонена, вместо да се сгъсти, е това, което я прави истинска гулаш супа, а не гъстото ястие, което повечето рецепти извън Унгария наричат гулаш.",
        "Добавете картофите и къкрете още 20-25 минути до омекване.",
        "Междувременно смесете брашното, яйцето и щипка сол в твърдо тесто за чипетке. Отчупвайте малки парченца с размер на грахово зърно и ги пускайте във врящата супа през последните 8-10 минути, докато изплуват и се сготвят.",
        "Подправете със сол и черен пипер преди сервиране.",
      ],
      ingredients: [
        "900 г телешко плешка, нарязано на кубчета",
        "2 с.л. свинска мас или олио",
        "3 лука, нарязани на кубчета",
        "3 с.л. сладка унгарска чушка",
        "1 с.л. кимион",
        "3 скилидки чесън, ситно нарязани",
        "1 зелена чушка, нарязана на кубчета",
        "1 домат, нарязан на кубчета",
        "4 картофа, нарязани на кубчета",
        "8 чаши телешки бульон",
        "1/2 чаша брашно (за чипетке кнедлите)",
        "1 яйце (за чипетке кнедлите)",
        "Сол на вкус",
        "Черен пипер на вкус",
      ],
    },
  },
  {
    en: {
      slug: "khachapuri",
      title: "Khachapuri",
      description:
        "Imeretian-style Georgian cheese bread baked in a hot oven rather than pan-fried, with a roughly two-to-one mozzarella-to-feta blend standing in for sulguni and Imeretian cheese - baking, not stovetop searing, is what gives it its traditional bready, chewy crust.",
      imageEmoji: "🫓",
      cookTimeMinutes: 90,
      servings: 4,
      ingredients: [
        { text: "2 1/2 cups flour", ingredient: "flour", quantity: 2.5 },
        { text: "1 tsp instant yeast", ingredient: "yeast", quantity: 1 },
        { text: "1 tsp sugar", ingredient: "sugar", quantity: 1 },
        { text: "3/4 tsp salt", ingredient: "salt", quantity: 0.75 },
        { text: "3/4 cup warm milk", ingredient: "milk", quantity: 0.75 },
        { text: "2 tbsp melted butter (for the dough)", ingredient: "butter", quantity: 2 },
        { text: "2 cups shredded mozzarella", ingredient: "mozzarella", quantity: 2 },
        { text: "1 cup crumbled feta", ingredient: "feta cheese", quantity: 1 },
        { text: "1 egg, beaten, for egg wash", ingredient: "eggs", quantity: 1 },
        { text: "2 tbsp melted butter, for brushing", ingredient: "butter", quantity: 2 },
      ],
      steps: [
        "Mix the flour, yeast, sugar, and salt, then stir in the warm milk and melted butter to form a soft dough; knead for 8-10 minutes until smooth.",
        "Cover and let rise in a warm place for 1 hour, until doubled.",
        "Preheat oven to 475°F.",
        "Combine the mozzarella and feta for the filling - a roughly two-to-one blend of a melty cheese and a salty, tangy one is the standard stand-in for sulguni and Imeretian cheese outside Georgia.",
        "Divide the dough into 4 pieces, roll each into a round, and place a portion of the cheese filling in the center. Gather the edges up and over the filling, pinch to seal, then gently flatten into a disc.",
        "Place the discs on a baking sheet, brush with the egg wash, and bake for 15-20 minutes until puffed and deeply golden - baking in a hot oven rather than pan-frying on the stovetop is the traditional method and what gives Imeretian khachapuri its bready, chewy crust.",
        "Brush with the remaining melted butter as it comes out of the oven, then slice and serve warm.",
      ],
      tags: ["dinner", "vegetarian"],
    },
    bg: {
      title: "Хачапури",
      description:
        "Имеретински грузински хляб със сирене, изпечен във фурна, а не запържен в тиган, с приблизително съотношение две към едно моцарела към фета вместо сулугуни и имеретинско сирене - печенето, а не запичането в тиган, е това, което му дава традиционната хлебна, дъвчаща коричка.",
      steps: [
        "Смесете брашното, маята, захарта и солта, после разбъркайте топлото мляко и разтопеното масло, за да образувате меко тесто; месете 8-10 минути до гладкост.",
        "Покрийте и оставете да втаса на топло място 1 час, докато се удвои.",
        "Загрейте фурната на 245°C.",
        "Смесете моцарелата и фетата за пълнежа - приблизително съотношение две към едно от топящо се сирене и солено, пикантно сирене е стандартният заместител на сулугуни и имеретинското сирене извън Грузия.",
        "Разделете тестото на 4 части, разточете всяка на кръг и сложете порция от сиренения пълнеж в средата. Съберете краищата отгоре над пълнежа, прищипете, за да запечатате, после леко сплескайте на диск.",
        "Наредете дисковете на тава, намажете с разбитото яйце и печете 15-20 минути, докато набъбнат и станат дълбоко златисти - печенето във фурна, а не запичането в тиган, е традиционният метод и това, което дава на имеретинското хачапури неговата хлебна, дъвчаща коричка.",
        "Намажете с останалото разтопено масло веднага след като излезе от фурната, после нарежете и сервирайте топло.",
      ],
      ingredients: [
        "2 1/2 чаши брашно",
        "1 ч.л. инстантна мая",
        "1 ч.л. захар",
        "3/4 ч.л. сол",
        "3/4 чаша топло мляко",
        "2 с.л. разтопено масло (за тестото)",
        "2 чаши настъргана моцарела",
        "1 чаша натрошена фета",
        "1 яйце, разбито, за намазване",
        "2 с.л. разтопено масло, за намазване накрая",
      ],
    },
  },
];

applyRecipeUpdates(updates).catch((err) => {
  console.error(err);
  process.exit(1);
});
