import { applyRecipeUpdates } from "./update-lib.mjs";

const updates = [
  {
    en: {
      slug: "chicken-tikka-masala",
      title: "Chicken Tikka Masala",
      description:
        "Chicken marinated in spiced yogurt, charred until smoky, then simmered in a deep, creamy tomato-onion sauce finished with kasoori methi.",
      imageEmoji: "🍛",
      cookTimeMinutes: 60,
      servings: 4,
      ingredients: [
        { text: "1 1/2 lb chicken breast, cubed", ingredient: "chicken breast", quantity: 1.5 },
        { text: "1/2 cup plain yogurt (for the marinade)", ingredient: "yogurt", quantity: 0.5 },
        { text: "1 tbsp lemon juice (for the marinade)", ingredient: "lemon juice", quantity: 1 },
        { text: "1 tbsp ginger-garlic paste (for the marinade)", ingredient: "ginger garlic paste", quantity: 1 },
        { text: "1 tsp garam masala (for the marinade)", ingredient: "garam masala", quantity: 1 },
        { text: "1 tsp coriander powder (for the marinade)", ingredient: "coriander powder", quantity: 1 },
        { text: "1/2 tsp cumin powder (for the marinade)", ingredient: "cumin powder", quantity: 0.5 },
        { text: "1/2 tsp Kashmiri chili powder or paprika (for the marinade)", ingredient: "chili powder", quantity: 0.5 },
        { text: "1/4 tsp turmeric", ingredient: "turmeric", quantity: 0.25 },
        { text: "3 tbsp ghee or oil", ingredient: "ghee", quantity: 3 },
        { text: "1 1/2 cups chopped onion", ingredient: "onion", quantity: 1.5 },
        { text: "1 tbsp ginger-garlic paste (for the sauce)", ingredient: "ginger garlic paste", quantity: 1 },
        { text: "1 tbsp coriander powder (for the sauce)", ingredient: "coriander powder", quantity: 1 },
        { text: "2 tsp garam masala (for the sauce)", ingredient: "garam masala", quantity: 2 },
        { text: "1 tsp cumin powder (for the sauce)", ingredient: "cumin powder", quantity: 1 },
        { text: "1/2 tsp Kashmiri chili powder or paprika (for the sauce)", ingredient: "chili powder", quantity: 0.5 },
        { text: "1 lb tomatoes, pureed (or 1 can crushed tomatoes)", ingredient: "tomato", quantity: 1 },
        { text: "1/2 cup heavy cream", ingredient: "heavy cream", quantity: 0.5 },
        { text: "1 tbsp kasoori methi (dried fenugreek leaves)", ingredient: "kasoori methi", quantity: 1 },
        { text: "1 tsp sugar", ingredient: "sugar", quantity: 1 },
        { text: "Fresh cilantro, for garnish", ingredient: "cilantro", quantity: null },
      ],
      steps: [
        "Combine the chicken with the yogurt, lemon juice, ginger-garlic paste, garam masala, coriander, cumin, chili powder, and turmeric; marinate in the fridge for at least 3 hours, ideally overnight.",
        "Broil or grill the marinated chicken at high heat for 3-4 minutes per side until charred at the edges and just cooked through; set aside.",
        "Sauté the onion in ghee until deep golden, about 10-12 minutes, then stir in the ginger-garlic paste, coriander, garam masala, cumin, and chili powder.",
        "Add the tomatoes and cook down until thick, then stir in a little water and simmer until fragrant; blend smooth if desired.",
        "Stir in the cream, sugar, and kasoori methi (crumbled between your fingers), then fold in the charred chicken and simmer for 2-3 minutes. Garnish with cilantro before serving.",
      ],
      tags: ["dinner", "asian"],
    },
    bg: {
      title: "Пилешка тика масала",
      description:
        "Пилешко, мариновано в подправено кисело мляко, изпечено до овъгляне, после къкрещо в наситен, кремообразен доматено-лучен сос, довършен с касури мети.",
      steps: [
        "Смесете пилето с киселото мляко, лимоновия сок, паста от джинджифил и чесън, гарам масалата, дала на кориандър, кимиона, лютия пипер и куркумата; маринова в хладилника поне 3 часа, в идеалния случай през нощта.",
        "Изпечете маринованото пиле на грил или скара на силен огън по 3-4 минути от всяка страна, докато се овъгли по краищата и се сготви; оставете настрана.",
        "Запържете лука в масло гхи до дълбоко златисто, около 10-12 минути, после разбъркайте пастата от джинджифил и чесън, дала на кориандър, гарам масалата, кимиона и лютия пипер.",
        "Добавете доматите и гответе, докато се сгъстят, после разбъркайте малко вода и оставете да къкри до ароматизиране; пасирайте до гладкост, ако желаете.",
        "Разбъркайте сметаната, захарта и касури мети (натрошена между пръстите), после добавете овъгленото пиле и оставете да къкри 2-3 минути. Гарнирайте с кориандър преди сервиране.",
      ],
      ingredients: [
        "700 г пилешка гърда, нарязана на кубчета",
        "1/2 чаша натурално кисело мляко (за марината)",
        "1 с.л. лимонов сок (за марината)",
        "1 с.л. паста от джинджифил и чесън (за марината)",
        "1 ч.л. гарам масала (за марината)",
        "1 ч.л. дал на кориандър (за марината)",
        "1/2 ч.л. кимион на прах (за марината)",
        "1/2 ч.л. кашмирски лют пипер или червен пипер (за марината)",
        "1/4 ч.л. куркума",
        "3 с.л. масло гхи или олио",
        "1 1/2 чаши нарязан лук",
        "1 с.л. паста от джинджифил и чесън (за соса)",
        "1 с.л. дал на кориандър (за соса)",
        "2 ч.л. гарам масала (за соса)",
        "1 ч.л. кимион на прах (за соса)",
        "1/2 ч.л. кашмирски лют пипер или червен пипер (за соса)",
        "450 г домати, пасирани (или 1 консерва нарязани домати)",
        "1/2 чаша сметана за готвене",
        "1 с.л. касури мети (сушени листа сминдух)",
        "1 ч.л. захар",
        "Пресен кориандър, за гарниране",
      ],
    },
  },
  {
    en: {
      slug: "palak-paneer",
      title: "Palak Paneer",
      description:
        "Cubes of paneer simmered in a vibrant, spiced spinach purée - blanched and ice-shocked to keep its color, blended with tomato, garlic, and ginger, and finished with kasoori methi.",
      imageEmoji: "🍛",
      cookTimeMinutes: 45,
      servings: 4,
      ingredients: [
        { text: "1 lb spinach", ingredient: "spinach", quantity: 1 },
        { text: "1 tomato", ingredient: "tomato", quantity: 1 },
        { text: "5 cloves garlic (3 whole, 2 chopped)", ingredient: "garlic", quantity: 5 },
        { text: "1 inch ginger", ingredient: "ginger", quantity: 1 },
        { text: "1 green chili (optional)", ingredient: "green chili", quantity: null },
        { text: "1 1/2 tbsp oil", ingredient: "vegetable oil", quantity: 1.5 },
        { text: "1 onion, chopped", ingredient: "onion", quantity: 1 },
        { text: "3/4 tsp garam masala", ingredient: "garam masala", quantity: 0.75 },
        { text: "1/4 tsp turmeric", ingredient: "turmeric", quantity: 0.25 },
        { text: "1/4 tsp red chili powder", ingredient: "chili powder", quantity: 0.25 },
        { text: "8 oz paneer, cubed", ingredient: "paneer", quantity: 8 },
        { text: "2-3 tbsp heavy cream", ingredient: "heavy cream", quantity: 2.5 },
        { text: "1/2 tbsp kasoori methi (dried fenugreek leaves)", ingredient: "kasoori methi", quantity: 0.5 },
        { text: "Lemon juice, to taste", ingredient: "lemon juice", quantity: null },
        { text: "Salt to taste", ingredient: "salt", quantity: null },
      ],
      steps: [
        "Blanch the spinach in boiling salted water for 2-3 minutes until wilted, then immediately transfer to ice water to lock in its bright green color.",
        "Blend the blanched spinach with the tomato, 3 cloves of garlic, ginger, and green chili into a smooth purée.",
        "Sauté the remaining chopped garlic in oil until fragrant, then add the onion and cook until softened.",
        "Stir in the spinach purée with a splash of water, cover, and simmer for 10 minutes, then season with garam masala, turmeric, red chili powder, and salt.",
        "Stir in the cream and paneer, simmer for 3 minutes, then turn off the heat and stir in the kasoori methi and a squeeze of lemon juice before serving.",
      ],
      tags: ["dinner", "vegetarian"],
    },
    bg: {
      title: "Палак Панир",
      description:
        "Кубчета панир, къкрещи в ярко, подправено спанаково пюре - бланширано и шоково охладено в ледена вода, за да запази цвета си, пасирано с домат, чесън и джинджифил, довършено с касури мети.",
      steps: [
        "Бланширайте спанака във вряла подсолена вода 2-3 минути до омекване, после веднага го прехвърлете в ледена вода, за да запазите яркозеления му цвят.",
        "Пасирайте бланширания спанак с домата, 3-те скилидки чесън, джинджифила и лютата чушка до гладко пюре.",
        "Задушете останалия нарязан чесън в олио до ароматизиране, после добавете лука и гответе до омекване.",
        "Разбъркайте спанаковото пюре с малко вода, покрийте и оставете да къкри 10 минути, после подправете с гарам масала, куркума, лют пипер и сол.",
        "Разбъркайте сметаната и панира, къкрете 3 минути, после изгасете котлона и разбъркайте касури мети и малко лимонов сок преди сервиране.",
      ],
      ingredients: [
        "450 г спанак",
        "1 домат",
        "5 скилидки чесън (3 цели, 2 нарязани)",
        "2.5 см джинджифил",
        "1 люта чушка (по желание)",
        "1 1/2 с.л. олио",
        "1 лук, нарязан",
        "3/4 ч.л. гарам масала",
        "1/4 ч.л. куркума",
        "1/4 ч.л. лют червен пипер на прах",
        "225 г панир, нарязан на кубчета",
        "2-3 с.л. сметана за готвене",
        "1/2 с.л. касури мети (сушени листа сминдух)",
        "Лимонов сок на вкус",
        "Сол на вкус",
      ],
    },
  },
  {
    en: {
      slug: "chana-masala",
      title: "Chana Masala",
      description:
        "Chickpeas simmered in a deeply cooked-down tomato-onion masala, tangy with amchur (dried mango powder) - a hearty vegan classic built on the bhuna technique.",
      imageEmoji: "🍛",
      cookTimeMinutes: 40,
      servings: 4,
      ingredients: [
        { text: "2 cans chickpeas, drained (liquid reserved)", ingredient: "chickpeas", quantity: 2 },
        { text: "2 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 2 },
        { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
        { text: "3 cloves garlic, minced", ingredient: "garlic", quantity: 3 },
        { text: "1 tbsp grated ginger", ingredient: "ginger", quantity: 1 },
        { text: "1 can diced tomatoes", ingredient: "tomato", quantity: 1 },
        { text: "1 tsp cumin powder", ingredient: "cumin powder", quantity: 1 },
        { text: "1 tsp coriander powder", ingredient: "coriander powder", quantity: 1 },
        { text: "2 tsp garam masala", ingredient: "garam masala", quantity: 2 },
        { text: "1 tsp amchur (dried mango powder), or 1 tbsp lemon juice", ingredient: "amchur", quantity: 1 },
        { text: "1/2 tsp chili powder", ingredient: "chili powder", quantity: 0.5 },
        { text: "Salt to taste", ingredient: "salt", quantity: null },
        { text: "Fresh cilantro, for garnish", ingredient: "cilantro", quantity: null },
      ],
      steps: [
        "Sauté the onion in oil until golden, then add the garlic and ginger and cook for 1 minute.",
        "Stir in the cumin, coriander, garam masala, and chili powder, then add the diced tomatoes and cook down, stirring often, until the oil begins to separate from the masala - this bhuna technique is what builds real depth of flavor, about 10-12 minutes.",
        "Stir in the chickpeas with a splash of their liquid, then simmer for 10-15 minutes, lightly crushing some of the chickpeas against the pot to naturally thicken the sauce.",
        "Stir in the amchur and salt to taste, and garnish with cilantro before serving.",
      ],
      tags: ["dinner", "vegan", "vegetarian"],
    },
    bg: {
      title: "Чана Масала",
      description:
        "Нахут, къкрещ в дълбоко изпечена доматено-лучена масала, кисела от амчур (сушено манго на прах) - сита веган класика, изградена върху техниката бхуна.",
      steps: [
        "Запържете лука в олио до златисто, после добавете чесъна и джинджифила и гответе 1 минута.",
        "Разбъркайте кимиона, дала на кориандър, гарам масалата и лютия пипер, после добавете нарязаните домати и гответе, разбърквайки често, докато олиото започне да се отделя от масалата - тази техника бхуна изгражда истинската дълбочина на вкуса, около 10-12 минути.",
        "Разбъркайте нахута с малко от течността му, после оставете да къкри 10-15 минути, леко смачквайки част от нахута в тенджерата, за да сгъстите естествено соса.",
        "Разбъркайте амчура и солта на вкус, гарнирайте с кориандър преди сервиране.",
      ],
      ingredients: [
        "2 консерви нахут, отцеден (запазете течността)",
        "2 с.л. олио",
        "1 лук, нарязан на кубчета",
        "3 скилидки чесън, ситно нарязани",
        "1 с.л. настърган джинджифил",
        "1 консерва нарязани домати",
        "1 ч.л. кимион на прах",
        "1 ч.л. дал на кориандър",
        "2 ч.л. гарам масала",
        "1 ч.л. амчур (сушено манго на прах), или 1 с.л. лимонов сок",
        "1/2 ч.л. лют пипер на прах",
        "Сол на вкус",
        "Пресен кориандър, за гарниране",
      ],
    },
  },
];

applyRecipeUpdates(updates).catch((err) => {
  console.error(err);
  process.exit(1);
});
