import { applyRecipeUpdates } from "./update-lib.mjs";

const updates = [
  {
    en: {
      slug: "dal-tadka",
      title: "Dal Tadka",
      description:
        "Yellow lentils simmered until creamy, finished with a sizzling ghee tadka of cumin seeds, mustard seeds, garlic, and dried red chili.",
      imageEmoji: "🍲",
      cookTimeMinutes: 40,
      servings: 4,
      ingredients: [
        { text: "1 1/2 cups yellow split lentils (toor dal or moong dal)", ingredient: "lentils", quantity: 1.5 },
        { text: "1 tsp turmeric", ingredient: "turmeric", quantity: 1 },
        { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
        { text: "1 tomato, diced", ingredient: "tomato", quantity: 1 },
        { text: "Salt to taste", ingredient: "salt", quantity: null },
        { text: "3 tbsp ghee", ingredient: "ghee", quantity: 3 },
        { text: "1 tsp cumin seeds", ingredient: "cumin seeds", quantity: 1 },
        { text: "1/2 tsp mustard seeds", ingredient: "mustard seeds", quantity: 0.5 },
        { text: "3 cloves garlic, sliced", ingredient: "garlic", quantity: 3 },
        { text: "2 dried red chilies", ingredient: "dried red chili", quantity: 2 },
        { text: "Fresh cilantro, for garnish", ingredient: "cilantro", quantity: null },
      ],
      steps: [
        "Simmer the lentils with turmeric and 4 cups water until soft, about 20 minutes, skimming off any foam.",
        "Stir in the onion, tomato, and salt, simmering for another 5 minutes.",
        "Heat the ghee in a small pan, add the cumin and mustard seeds and let them sizzle and pop, then add the garlic and dried red chilies and fry until the garlic is golden.",
        "Pour the sizzling tadka over the hot dal immediately before serving, and garnish with cilantro.",
      ],
      tags: ["dinner", "vegetarian"],
    },
    bg: {
      title: "Дал Тадка",
      description:
        "Жълта леща, варена до кремообразност, довършена със съскащ тадка от кимион, черна горчица, чесън и сушено лютиво чили в гхи.",
      steps: [
        "Варете лещата с куркумата и 4 чаши вода до омекване, около 20 минути, обирайки пяната от време на време.",
        "Добавете лука, домата и солта, варете още 5 минути.",
        "Загрейте гхи в малък тиган, добавете кимиона и семената горчица и оставете да изпукат, после добавете чесъна и сушеното чили и запържете до златисто на чесъна.",
        "Излейте съскащата тадка върху горещия дал веднага преди сервиране и гарнирайте с кориандър.",
      ],
      ingredients: [
        "1 1/2 чаши жълта разцепена леща (тор дал или мунг дал)",
        "1 ч.л. куркума",
        "1 лук, нарязан на кубчета",
        "1 домат, нарязан на кубчета",
        "Сол на вкус",
        "3 с.л. гхи",
        "1 ч.л. семена кимион",
        "1/2 ч.л. семена черна горчица",
        "3 скилидки чесън, нарязани на резенчета",
        "2 сушени лютиви чушки",
        "Пресен кориандър, за гарниране",
      ],
    },
  },
  {
    en: {
      slug: "chicken-biryani",
      title: "Chicken Biryani",
      description:
        "Chicken marinated in spiced yogurt, layered with whole-spice basmati rice, saffron milk, and crispy fried onions, then sealed and steamed on low heat - the dum technique that makes it biryani rather than just spiced rice.",
      imageEmoji: "🍛",
      cookTimeMinutes: 80,
      servings: 6,
      ingredients: [
        { text: "2 lb chicken thighs, cut into pieces", ingredient: "chicken thighs", quantity: 2 },
        { text: "3/4 cup plain yogurt", ingredient: "yogurt", quantity: 0.75 },
        { text: "1 tbsp ginger paste", ingredient: "ginger paste", quantity: 1 },
        { text: "1 tbsp garlic paste", ingredient: "garlic paste", quantity: 1 },
        { text: "2 tsp biryani masala", ingredient: "biryani masala", quantity: 2 },
        { text: "1 tsp Kashmiri chili powder", ingredient: "chili powder", quantity: 1 },
        { text: "1/2 tsp turmeric", ingredient: "turmeric", quantity: 0.5 },
        { text: "2 tbsp lemon juice", ingredient: "lemon juice", quantity: 2 },
        { text: "1/4 cup fresh mint, chopped", ingredient: "mint", quantity: 0.25 },
        { text: "2 cups basmati rice, rinsed and soaked 20 minutes", ingredient: "basmati rice", quantity: 2 },
        { text: "4 tbsp ghee", ingredient: "ghee", quantity: 4 },
        { text: "2 onions, thinly sliced", ingredient: "onion", quantity: 2 },
        { text: "1 tsp cumin seeds", ingredient: "cumin seeds", quantity: 1 },
        { text: "2 bay leaves", ingredient: "bay leaf", quantity: 2 },
        { text: "4 green cardamom pods", ingredient: "cardamom", quantity: 4 },
        { text: "4 cloves", ingredient: "cloves", quantity: 4 },
        { text: "1/2 tsp saffron threads", ingredient: "saffron", quantity: 0.5 },
        { text: "2 tbsp warm milk", ingredient: "milk", quantity: 2 },
        { text: "1/4 cup chopped cilantro", ingredient: "cilantro", quantity: 0.25 },
        { text: "Salt to taste", ingredient: "salt", quantity: null },
      ],
      steps: [
        "Combine the chicken with yogurt, ginger paste, garlic paste, biryani masala, chili powder, turmeric, lemon juice, mint, and salt; marinate at least 30 minutes, ideally overnight.",
        "Soak the saffron in the warm milk and set aside. Fry the onions in ghee until deeply golden and crisp, about 15-20 minutes; set most aside for topping, stirring a few into the marinated chicken.",
        "Cook the marinated chicken in the remaining ghee for 8-10 minutes until nearly done.",
        "Boil plenty of water with the cumin seeds, bay leaves, cardamom, and cloves; add the soaked rice and boil for 5-6 minutes until about 90% cooked, then drain immediately.",
        "Layer the parboiled rice over the chicken, top with the fried onions, saffron milk, and cilantro, then seal the pot tightly (foil under the lid works) and cook on low heat for 20 minutes.",
        "Turn off the heat and let it rest sealed for 10 minutes, then fluff gently with a fork and serve with raita and lemon wedges.",
      ],
      tags: ["dinner"],
    },
    bg: {
      title: "Пилешко Бирияни",
      description:
        "Пиле, мариновано в подправено кисело мляко, наслоено с ориз басмати с цели подправки, шафраново мляко и хрупкав пържен лук, после запечатано и задушено на слаб огън - техниката дъм, която прави ястието истинско бирияни, а не просто подправен ориз.",
      steps: [
        "Смесете пилето с киселото мляко, пастата от джинджифил, пастата от чесън, подправката бирияни, лютия пипер, куркумата, лимоновия сок, ментата и солта; маринова поне 30 минути, в идеалния случай през нощта.",
        "Накиснете шафрана в топлото мляко и оставете настрана. Изпържете лука в гхи до дълбоко златисто и хрупкаво, около 15-20 минути; отделете по-голямата част за поръсване отгоре, а няколко лъжици разбъркайте в маринованото пиле.",
        "Изпечете маринованото пиле в останалото гхи 8-10 минути, докато е почти готово.",
        "Заврете обилно вода с кимионовите семена, дафиновите листа, кардамона и карамфила; добавете накиснатия ориз и варете 5-6 минути, докато стане около 90% готов, после веднага отцедете.",
        "Наредете полусварения ориз върху пилето, отгоре сложете пържения лук, шафрановото мляко и кориандъра, после запечатайте плътно тенджерата (фолио под капака помага) и гответе на слаб огън 20 минути.",
        "Изгасете котлона и оставете запечатано да почине 10 минути, после разбъркайте леко с вилица и сервирайте с раита и резенчета лимон.",
      ],
      ingredients: [
        "900 г пилешки бутчета, нарязани на парчета",
        "3/4 чаша натурално кисело мляко",
        "1 с.л. паста от джинджифил",
        "1 с.л. паста от чесън",
        "2 ч.л. подправка бирияни",
        "1 ч.л. кашмирски лют пипер",
        "1/2 ч.л. куркума",
        "2 с.л. лимонов сок",
        "1/4 чаша пресена мента, нарязана",
        "2 чаши ориз басмати, изплакнат и накиснат 20 минути",
        "4 с.л. гхи",
        "2 лука, нарязани на тънко",
        "1 ч.л. семена кимион",
        "2 дафинови листа",
        "4 шушулки зелен кардамон",
        "4 карамфила",
        "1/2 ч.л. нишки шафран",
        "2 с.л. топло мляко",
        "1/4 чаша нарязан кориандър",
        "Сол на вкус",
      ],
    },
  },
  {
    en: {
      slug: "vegetable-biryani",
      title: "Vegetable Biryani",
      description:
        "Fragrant basmati rice layered with spiced mixed vegetables, saffron milk, and crispy fried onions, sealed and steamed on low heat for a true dum biryani.",
      imageEmoji: "🍚",
      cookTimeMinutes: 70,
      servings: 6,
      ingredients: [
        { text: "2 cups basmati rice, rinsed and soaked 20 minutes", ingredient: "basmati rice", quantity: 2 },
        { text: "1 tsp cumin seeds", ingredient: "cumin seeds", quantity: 1 },
        { text: "2 bay leaves", ingredient: "bay leaf", quantity: 2 },
        { text: "4 green cardamom pods", ingredient: "cardamom", quantity: 4 },
        { text: "4 cloves", ingredient: "cloves", quantity: 4 },
        { text: "4 tbsp ghee", ingredient: "ghee", quantity: 4 },
        { text: "2 onions, thinly sliced", ingredient: "onion", quantity: 2 },
        { text: "1 tbsp ginger-garlic paste", ingredient: "ginger garlic paste", quantity: 1 },
        { text: "2 carrots, diced", ingredient: "carrot", quantity: 2 },
        { text: "1 potato, diced", ingredient: "potato", quantity: 1 },
        { text: "1 cup green peas", ingredient: "peas", quantity: 1 },
        { text: "1/2 cup plain yogurt", ingredient: "yogurt", quantity: 0.5 },
        { text: "2 tsp garam masala or biryani masala", ingredient: "garam masala", quantity: 2 },
        { text: "1/2 tsp turmeric", ingredient: "turmeric", quantity: 0.5 },
        { text: "1/2 tsp saffron threads", ingredient: "saffron", quantity: 0.5 },
        { text: "2 tbsp warm milk", ingredient: "milk", quantity: 2 },
        { text: "1/4 cup chopped mint and cilantro", ingredient: "mint", quantity: 0.25 },
        { text: "Salt to taste", ingredient: "salt", quantity: null },
      ],
      steps: [
        "Soak the saffron in the warm milk and set aside. Fry the onions in ghee until deeply golden and crisp, about 15-20 minutes; set most aside for topping.",
        "In the same pan, sauté the ginger-garlic paste, then add the carrots, potato, and peas with garam masala and turmeric and cook until nearly tender; stir in the yogurt and salt.",
        "Boil plenty of water with the cumin seeds, bay leaves, cardamom, and cloves; add the soaked rice and boil for 5-6 minutes until about 90% cooked, then drain immediately.",
        "Layer the parboiled rice over the vegetables, top with the fried onions, saffron milk, and mint and cilantro, then seal the pot tightly and cook on low heat for 15-20 minutes.",
        "Turn off the heat and let it rest sealed for 10 minutes, then fluff gently with a fork before serving.",
      ],
      tags: ["dinner", "vegan", "vegetarian"],
    },
    bg: {
      title: "Зеленчуково Бирияни",
      description:
        "Ароматен ориз басмати, наслоен с подправени смесени зеленчуци, шафраново мляко и хрупкав пържен лук, запечатан и задушен на слаб огън за истинско дъм бирияни.",
      steps: [
        "Накиснете шафрана в топлото мляко и оставете настрана. Изпържете лука в гхи до дълбоко златисто и хрупкаво, около 15-20 минути; отделете по-голямата част за поръсване отгоре.",
        "В същия тиган запържете пастата от джинджифил и чесън, после добавете морковите, картофа и граха с гарам масалата и куркумата и гответе почти до омекване; разбъркайте киселото мляко и солта.",
        "Заврете обилно вода с кимионовите семена, дафиновите листа, кардамона и карамфила; добавете накиснатия ориз и варете 5-6 минути, докато стане около 90% готов, после веднага отцедете.",
        "Наредете полусварения ориз върху зеленчуците, отгоре сложете пържения лук, шафрановото мляко и ментата с кориандъра, после запечатайте плътно тенджерата и гответе на слаб огън 15-20 минути.",
        "Изгасете котлона и оставете запечатано да почине 10 минути, после разбъркайте леко с вилица преди сервиране.",
      ],
      ingredients: [
        "2 чаши ориз басмати, изплакнат и накиснат 20 минути",
        "1 ч.л. семена кимион",
        "2 дафинови листа",
        "4 шушулки зелен кардамон",
        "4 карамфила",
        "4 с.л. гхи",
        "2 лука, нарязани на тънко",
        "1 с.л. паста от джинджифил и чесън",
        "2 моркова, нарязани на кубчета",
        "1 картоф, нарязан на кубчета",
        "1 чаша зелен грах",
        "1/2 чаша натурално кисело мляко",
        "2 ч.л. гарам масала или подправка бирияни",
        "1/2 ч.л. куркума",
        "1/2 ч.л. нишки шафран",
        "2 с.л. топло мляко",
        "1/4 чаша нарязана мента и кориандър",
        "Сол на вкус",
      ],
    },
  },
];

applyRecipeUpdates(updates).catch((err) => {
  console.error(err);
  process.exit(1);
});
