import { applyRecipeUpdates } from "./update-lib.mjs";

const updates = [
  {
    en: {
      slug: "butter-chicken",
      title: "Butter Chicken",
      description:
        "Chicken marinated in spiced yogurt and seared hard to mimic tandoor char, simmered into a reduced tomato-butter sauce finished with cream and crushed kasuri methi - the fenugreek leaves are what tie the tomato and cream together into that signature restaurant flavor.",
      imageEmoji: "🍛",
      cookTimeMinutes: 70,
      servings: 4,
      ingredients: [
        { text: "1 1/2 lb chicken thighs, cubed", ingredient: "chicken thighs", quantity: 1.5 },
        { text: "1/2 cup plain yogurt", ingredient: "yogurt", quantity: 0.5 },
        { text: "1 tbsp lemon juice", ingredient: "lemon juice", quantity: 1 },
        { text: "4 cloves garlic, minced (divided)", ingredient: "garlic", quantity: 4 },
        { text: "1 tbsp grated ginger (divided)", ingredient: "ginger", quantity: 1 },
        { text: "1 tsp turmeric", ingredient: "turmeric", quantity: 1 },
        { text: "1 tsp Kashmiri chili powder (or paprika)", ingredient: "chili powder", quantity: 1 },
        { text: "2 tsp garam masala (divided)", ingredient: "garam masala", quantity: 2 },
        { text: "4 tbsp butter", ingredient: "butter", quantity: 4 },
        { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
        { text: "1 can crushed tomatoes", ingredient: "tomato", quantity: 1 },
        { text: "1 cup heavy cream", ingredient: "heavy cream", quantity: 1 },
        { text: "1 tbsp kasuri methi (dried fenugreek leaves)", ingredient: "kasuri methi", quantity: 1 },
        { text: "1 tsp sugar", ingredient: "sugar", quantity: 1 },
        { text: "Salt to taste", ingredient: "salt", quantity: null },
      ],
      steps: [
        "Whisk together the yogurt, lemon juice, half the garlic, half the ginger, turmeric, chili powder, 1 teaspoon of the garam masala, and salt; marinate the chicken in the mixture, covered, for at least 30 minutes, ideally overnight.",
        "Sear the marinated chicken in a very hot pan or under the broiler until charred in spots - this mimics tandoor cooking and gives butter chicken its signature smoky edge; it doesn't need to be fully cooked through yet.",
        "Melt the butter and sauté the onion with the remaining garlic and ginger until softened, then stir in the remaining garam masala and crushed tomatoes.",
        "Simmer the tomato mixture uncovered for 15 minutes, stirring occasionally, until reduced and nearly dry - this concentrates the flavor before blending.",
        "Blend the sauce until smooth, then return it to the pot with the cream, sugar, and seared chicken; simmer for 10 minutes until the chicken is cooked through.",
        "Crush the kasuri methi between your palms and stir it in just before serving - it's what bridges the tomato and cream into the dish's signature flavor.",
      ],
      tags: ["dinner", "asian"],
    },
    bg: {
      title: "Пиле с масло по индийски",
      description:
        "Пиле, мариновано в подправено кисело мляко и запечено на силен огън, за да наподоби овъгляването от тандур, къкрено в сгъстен доматено-маслен сос, довършен със сметана и стрит касури методи - листата от сминдух са тези, които свързват доматите и сметаната в характерния ресторантски вкус.",
      steps: [
        "Разбийте киселото мляко, лимоновия сок, половината чесън, половината джинджифил, куркумата, лютия пипер на прах, 1 чаена лъжичка от гарам масалата и солта; маринова пилето в сместа, покрито, поне 30 минути, в идеалния случай през нощта.",
        "Запечете маринованото пиле в много горещ тиган или на грил до леко овъгляне на места - това наподобява печенето в тандур и придава на пилето с масло характерния му опушен вкус; не е нужно да е напълно готово на този етап.",
        "Разтопете маслото и запържете лука с останалия чесън и джинджифил до омекване, после добавете останалата гарам масала и пасираните домати.",
        "Варете доматената смес без капак 15 минути, разбърквайки от време на време, докато се сгъсти и почти изсъхне - това концентрира вкуса преди пасиране.",
        "Пасирайте соса до гладкост, после го върнете в тенджерата със сметаната, захарта и запеченото пиле; варете още 10 минути, докато пилето се сготви напълно.",
        "Стрийте касури методи между дланите си и ги разбъркайте точно преди сервиране - те са тези, които свързват доматите и сметаната в характерния вкус на ястието.",
      ],
      ingredients: [
        "700 г пилешки бутчета, нарязани на кубчета",
        "1/2 чаша натурално кисело мляко",
        "1 с.л. лимонов сок",
        "4 скилидки чесън, ситно нарязани (разделени)",
        "1 с.л. настърган джинджифил (разделен)",
        "1 ч.л. куркума",
        "1 ч.л. лют пипер кашмири на прах (или обикновена чушка на прах)",
        "2 ч.л. гарам масала (разделена)",
        "4 с.л. масло",
        "1 лук, нарязан на кубчета",
        "1 консерва пасирани домати",
        "1 чаша сметана за готвене",
        "1 с.л. касури методи (сушени листа сминдух)",
        "1 ч.л. захар",
        "Сол на вкус",
      ],
    },
  },
  {
    en: {
      slug: "malai-kofta",
      title: "Malai Kofta",
      description:
        "Fried paneer-potato dumplings studded with cashews and raisins, served in a rich onion-cashew-tomato sauce built on whole spices and finished with cream and kasuri methi.",
      imageEmoji: "🍛",
      cookTimeMinutes: 65,
      servings: 4,
      ingredients: [
        { text: "2 potatoes, boiled and mashed", ingredient: "potato", quantity: 2 },
        { text: "1 cup crumbled paneer", ingredient: "paneer", quantity: 1 },
        { text: "3 tbsp cornstarch", ingredient: "cornstarch", quantity: 3 },
        { text: "2 tbsp raisins", ingredient: "raisins", quantity: 2 },
        { text: "2 tbsp chopped cashews", ingredient: "cashews", quantity: 2 },
        { text: "2 cups vegetable oil for frying", ingredient: "vegetable oil", quantity: 2 },
        { text: "2 tbsp butter", ingredient: "butter", quantity: 2 },
        { text: "1 onion, chopped", ingredient: "onion", quantity: 1 },
        { text: "3 cloves garlic, minced", ingredient: "garlic", quantity: 3 },
        { text: "1 tbsp grated ginger", ingredient: "ginger", quantity: 1 },
        { text: "2 green cardamom pods", ingredient: "cardamom", quantity: 2 },
        { text: "1 small cinnamon stick", ingredient: "cinnamon stick", quantity: 1 },
        { text: "2 whole cloves", ingredient: "cloves", quantity: 2 },
        { text: "1 can crushed tomatoes", ingredient: "tomato", quantity: 1 },
        { text: "1/4 cup cashews, soaked", ingredient: "cashews", quantity: 0.25 },
        { text: "1 tsp garam masala", ingredient: "garam masala", quantity: 1 },
        { text: "1/2 tsp turmeric", ingredient: "turmeric", quantity: 0.5 },
        { text: "1/2 cup heavy cream", ingredient: "heavy cream", quantity: 0.5 },
        { text: "1 tbsp kasuri methi (dried fenugreek leaves)", ingredient: "kasuri methi", quantity: 1 },
        { text: "Salt to taste", ingredient: "salt", quantity: null },
      ],
      steps: [
        "Mix the mashed potato, paneer, and cornstarch into a dough, then work in the raisins and chopped cashews and form into small balls.",
        "Fry the balls in hot oil until golden, then drain; don't add them to the sauce yet - koftas added too early soak up the gravy and turn mushy.",
        "Melt the butter and sauté the onion with the garlic, ginger, cardamom, cinnamon, and cloves until the onion turns golden.",
        "Stir in the crushed tomatoes and soaked cashews, then simmer for 10-15 minutes until thickened; fish out the whole spices, then blend the sauce until smooth.",
        "Stir the garam masala, turmeric, and cream into the sauce and simmer for 5 minutes, then season with salt.",
        "Crush the kasuri methi between your palms and stir it in.",
        "Add the fried koftas to the sauce just before serving so they stay crisp.",
      ],
      tags: ["dinner", "vegetarian"],
    },
    bg: {
      title: "Малай Кофта",
      description:
        "Пържени кюфтенца от панир и картофи, обогатени с кашу и стафиди, поднесени в наситен сос от лук, кашу и домати, изграден върху цели подправки и довършен със сметана и касури методи.",
      steps: [
        "Смесете намаченото картофено пюре, панира и царевичното нишесте в тесто, после вмесете стафидите и нарязаното кашу и оформете малки топчета.",
        "Изпържете топчетата в горещо олио до златисто, после отцедете; не ги добавяйте в соса веднага - кофтите, добавени твърде рано, попиват соса и стават кашести.",
        "Разтопете маслото и запържете лука с чесъна, джинджифила, кардамона, канелата и карамфила, докато лукът стане златист.",
        "Добавете пасираните домати и накиснатото кашу, после варете 10-15 минути до сгъстяване; извадете целите подправки и пасирайте соса до гладкост.",
        "Разбъркайте гарам масалата, куркумата и сметаната в соса и варете 5 минути, после подправете със сол.",
        "Стрийте касури методи между дланите си и ги разбъркайте.",
        "Добавете пържените кофти в соса точно преди сервиране, за да останат хрупкави.",
      ],
      ingredients: [
        "2 картофа, сварени и намачкани",
        "1 чаша натрошен панир",
        "3 с.л. царевично нишесте",
        "2 с.л. стафиди",
        "2 с.л. нарязано кашу",
        "2 чаши олио за пържене",
        "2 с.л. масло",
        "1 лук, нарязан",
        "3 скилидки чесън, ситно нарязани",
        "1 с.л. настърган джинджифил",
        "2 шушулки зелен кардамон",
        "1 малка пръчка канела",
        "2 карамфилчета",
        "1 консерва пасирани домати",
        "1/4 чаша кашу, накиснато",
        "1 ч.л. гарам масала",
        "1/2 ч.л. куркума",
        "1/2 чаша сметана за готвене",
        "1 с.л. касури методи (сушени листа сминдух)",
        "Сол на вкус",
      ],
    },
  },
  {
    en: {
      slug: "egg-drop-soup",
      title: "Egg Drop Soup",
      description:
        "Chicken broth infused with ginger and white pepper, lightly thickened with cornstarch, then drizzled with beaten egg in a slow stream while stirring gently to form silky ribbons - finished with sesame oil off the heat so its aroma doesn't cook away.",
      imageEmoji: "🍲",
      cookTimeMinutes: 20,
      servings: 4,
      ingredients: [
        { text: "4 cups chicken broth", ingredient: "chicken broth", quantity: 4 },
        { text: "2 slices fresh ginger", ingredient: "ginger", quantity: 2 },
        { text: "2 eggs, beaten", ingredient: "eggs", quantity: 2 },
        { text: "1 tbsp cornstarch", ingredient: "cornstarch", quantity: 1 },
        { text: "2 green onions, sliced", ingredient: "green onion", quantity: 2 },
        { text: "1 tsp soy sauce", ingredient: "soy sauce", quantity: 1 },
        { text: "1/4 tsp white pepper", ingredient: "white pepper", quantity: 0.25 },
        { text: "1 tsp sesame oil", ingredient: "sesame oil", quantity: 1 },
      ],
      steps: [
        "Simmer the chicken broth with the ginger slices for 5 minutes to infuse, then remove the ginger.",
        "Stir in the soy sauce and white pepper.",
        "Mix the cornstarch with a little water, then stir it into the broth to lightly thicken it; bring to a gentle simmer with small bubbles, not a hard boil.",
        "Slowly drizzle in the beaten eggs in a thin stream while stirring the broth gently in one direction to create thin ribbons.",
        "Remove from the heat and stir in the sesame oil so its aroma doesn't cook off, then garnish with green onions before serving.",
      ],
      tags: ["lunch", "quick", "asian"],
    },
    bg: {
      title: "Супа с яйце",
      description:
        "Пилешки бульон, ароматизиран с джинджифил и бял пипер, леко сгъстен с царевично нишесте, после полят с разбито яйце в тънка струя, докато се разбърква леко, за да се образуват копринени нишки - довършен с сусамово масло извън котлона, за да не изгуби аромата си.",
      steps: [
        "Варете пилешкия бульон с резенчетата джинджифил 5 минути, за да се ароматизира, после извадете джинджифила.",
        "Разбъркайте соевия сос и белия пипер.",
        "Смесете царевичното нишесте с малко вода, после го разбъркайте в бульона за леко сгъстяване; доведете до леко къкрене с малки мехурчета, не до силно кипене.",
        "Бавно наливайте разбитите яйца в тънка струя, докато разбърквате бульона леко в една посока, за да се образуват тънки нишки.",
        "Свалете от котлона и разбъркайте сусамовото масло, за да не изгуби аромата си, после гарнирайте с пресен лук преди сервиране.",
      ],
      ingredients: [
        "4 чаши пилешки бульон",
        "2 резена пресен джинджифил",
        "2 разбити яйца",
        "1 с.л. царевично нишесте",
        "2 стръка пресен лук, нарязани",
        "1 ч.л. соев сос",
        "1/4 ч.л. бял пипер",
        "1 ч.л. сусамово масло",
      ],
    },
  },
];

applyRecipeUpdates(updates).catch((err) => {
  console.error(err);
  process.exit(1);
});
