import { applyRecipeUpdates } from "./update-lib.mjs";

const updates = [
  {
    en: {
      slug: "moussaka",
      title: "Moussaka",
      description:
        "Layers of salted, fried eggplant and cinnamon-spiced ground lamb, topped with a nutmeg-scented béchamel enriched with egg, baked until golden - the warm spices in the meat sauce are what set moussaka apart from a plain casserole.",
      imageEmoji: "🍆",
      cookTimeMinutes: 100,
      servings: 8,
      ingredients: [
        { text: "2 eggplants, sliced", ingredient: "eggplant", quantity: 2 },
        { text: "Salt, for salting the eggplant", ingredient: "salt", quantity: null },
        { text: "Olive oil, for frying", ingredient: "olive oil", quantity: null },
        { text: "1 lb ground lamb", ingredient: "ground lamb", quantity: 1 },
        { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
        { text: "2 cloves garlic, minced", ingredient: "garlic", quantity: 2 },
        { text: "1/2 cup red wine", ingredient: "red wine", quantity: 0.5 },
        { text: "1 can crushed tomatoes", ingredient: "tomato", quantity: 1 },
        { text: "1 tsp cinnamon", ingredient: "cinnamon", quantity: 1 },
        { text: "1/4 tsp ground allspice or cloves", ingredient: "allspice", quantity: 0.25 },
        { text: "3 tbsp butter", ingredient: "butter", quantity: 3 },
        { text: "3 tbsp flour", ingredient: "flour", quantity: 3 },
        { text: "2 cups milk, warmed", ingredient: "milk", quantity: 2 },
        { text: "2 eggs", ingredient: "eggs", quantity: 2 },
        { text: "1/4 tsp nutmeg", ingredient: "nutmeg", quantity: 0.25 },
        { text: "Salt and pepper to taste", ingredient: "salt", quantity: null },
      ],
      steps: [
        "Salt the eggplant slices and let them sit in a colander for 20-30 minutes to draw out bitterness, then rinse and pat dry.",
        "Fry the eggplant slices in olive oil until golden on both sides, then drain on paper towels (or roast at 400°F for a lighter version).",
        "Brown the ground lamb with the onion and garlic, then stir in the red wine and let it reduce; add the crushed tomatoes, cinnamon, and allspice and simmer for 15 minutes.",
        "Melt the butter, whisk in the flour, then gradually whisk in the warm milk to make a béchamel; season with nutmeg, salt, and pepper, then temper in the beaten eggs off the heat for a rich, custardy set.",
        "Layer the fried eggplant and meat sauce in a baking dish, top with the béchamel, and bake at 375°F for 30-35 minutes until golden on top.",
      ],
      tags: ["dinner", "mediterranean"],
    },
    bg: {
      title: "Мусака",
      description:
        "Пластове осолен, изпържен патладжан и агнешка кайма, подправена с канела, покрити с бешамел с аромат на индийско орехче и обогатен с яйце, запечени до златисто - топлите подправки в месния сос са това, което отличава мусаката от обикновен гювеч.",
      steps: [
        "Посолете резените патладжан и оставете в гевгир 20-30 минути, за да изтече горчивата течност, после изплакнете и подсушете.",
        "Изпържете резените патладжан в зехтин до златисто от двете страни, после отцедете върху хартиена кухненска кърпа (или изпечете на 200°C за по-лека версия).",
        "Запържете агнешката кайма с лука и чесъна, после разбъркайте червеното вино и оставете да се редуцира; добавете доматеното пюре, канелата и бахара и оставете да къкри 15 минути.",
        "Разтопете маслото, разбъркайте с брашното, после постепенно добавяйте топлото мляко, за да направите сос бешамел; подправете с индийско орехче, сол и черен пипер, после вмъкнете разбитите яйца извън котлона за богата, кремообразна консистенция.",
        "Наредете на пластове изпържения патладжан и месния сос в тава, покрийте с бешамела и печете на 190°C 30-35 минути до златисто отгоре.",
      ],
      ingredients: [
        "2 патладжана, нарязани на резени",
        "Сол, за осоляване на патладжана",
        "Зехтин, за пържене",
        "450 г агнешка кайма",
        "1 лук, нарязан на кубчета",
        "2 скилидки чесън, ситно нарязани",
        "1/2 чаша червено вино",
        "1 консерва доматено пюре",
        "1 ч.л. канела",
        "1/4 ч.л. смлян бахар или карамфил",
        "3 с.л. масло",
        "3 с.л. брашно",
        "2 чаши мляко, затоплено",
        "2 яйца",
        "1/4 ч.л. индийско орехче",
        "Сол и черен пипер на вкус",
      ],
    },
  },
  {
    en: {
      slug: "shakshuka",
      title: "Shakshuka",
      description: "Eggs poached in a spiced tomato and pepper sauce - a one-pan breakfast from North Africa and the Middle East.",
      imageEmoji: "🍅",
      cookTimeMinutes: 30,
      servings: 4,
      ingredients: [
        { text: "2 tbsp olive oil", ingredient: "olive oil", quantity: 2 },
        { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
        { text: "1 red bell pepper, diced", ingredient: "red pepper", quantity: 1 },
        { text: "3 cloves garlic, minced", ingredient: "garlic", quantity: 3 },
        { text: "1 tsp cumin", ingredient: "cumin", quantity: 1 },
        { text: "1 tsp paprika", ingredient: "paprika", quantity: 1 },
        { text: "1 can crushed tomatoes", ingredient: "tomato", quantity: 1 },
        { text: "1/4 tsp red pepper flakes (optional)", ingredient: "red pepper flakes", quantity: 0.25 },
        { text: "6 eggs", ingredient: "eggs", quantity: 6 },
        { text: "Salt to taste", ingredient: "salt", quantity: null },
        { text: "1/4 cup crumbled feta, for serving", ingredient: "feta cheese", quantity: 0.25 },
        { text: "Fresh parsley, chopped, for garnish", ingredient: "parsley", quantity: null },
      ],
      steps: [
        "Heat olive oil in a large skillet and sauté the onion and red pepper until softened.",
        "Add garlic, cumin, paprika, and red pepper flakes; cook for 1 minute until fragrant.",
        "Pour in the crushed tomatoes and simmer for 10 minutes, seasoning with salt.",
        "Make small wells in the sauce and crack an egg into each one.",
        "Cover and cook for 5-8 minutes until the egg whites are set but yolks are still runny.",
        "Garnish with crumbled feta and fresh parsley before serving.",
      ],
      tags: ["breakfast", "vegetarian", "dinner"],
    },
    bg: {
      title: "Шакшука",
      description:
        "Яйца, задушени в подправен доматено-чушков сос - закуска в един тиган от Северна Африка и Близкия изток.",
      steps: [
        "Загрейте зехтин в голям тиган и запържете лука и червената чушка до омекване.",
        "Добавете чесъна, кимиона, червения пипер и лютите чушки на люспи; гответе 1 минута до ароматизиране.",
        "Изсипете доматеното пюре и оставете да къкри 10 минути, подправяйки със сол.",
        "Направете малки вдлъбнатини в соса и счупете по едно яйце във всяка от тях.",
        "Покрийте и гответе 5-8 минути, докато белтъците се стегнат, а жълтъците останат течни.",
        "Гарнирайте с натрошено сирене фета и пресен магданоз преди сервиране.",
      ],
      ingredients: [
        "2 с.л. зехтин",
        "1 лук, нарязан на кубчета",
        "1 червена чушка, нарязана на кубчета",
        "3 скилидки чесън, ситно нарязани",
        "1 ч.л. кимион",
        "1 ч.л. червен пипер",
        "1 консерва доматено пюре",
        "1/4 ч.л. люти чушки на люспи (по желание)",
        "6 яйца",
        "Сол на вкус",
        "1/4 чаша натрошено сирене фета, за сервиране",
        "Пресен магданоз, нарязан, за гарниране",
      ],
    },
  },
  {
    en: {
      slug: "classic-hummus",
      title: "Classic Hummus",
      description:
        "A whipped, silky chickpea and tahini dip - the tahini and lemon are blended first to emulsify, then ice water is added for a fluffy, restaurant-style texture.",
      imageEmoji: "🧆",
      cookTimeMinutes: 15,
      servings: 6,
      ingredients: [
        { text: "2 cans chickpeas, drained (liquid reserved)", ingredient: "chickpeas", quantity: 2 },
        { text: "1/2 tsp baking soda", ingredient: "baking soda", quantity: 0.5 },
        { text: "2 cloves garlic, minced", ingredient: "garlic", quantity: 2 },
        { text: "1 lemon, juiced", ingredient: "lemon", quantity: 1 },
        { text: "1/2 cup tahini", ingredient: "tahini", quantity: 0.5 },
        { text: "3 tbsp ice water, plus more as needed", ingredient: "water", quantity: 3 },
        { text: "1/2 tsp cumin", ingredient: "cumin", quantity: 0.5 },
        { text: "3 tbsp olive oil", ingredient: "olive oil", quantity: 3 },
        { text: "Salt to taste", ingredient: "salt", quantity: null },
      ],
      steps: [
        "Simmer the chickpeas with the baking soda in a saucepan for 5 minutes to soften their skins, then drain and rinse.",
        "Let the minced garlic sit in the lemon juice for a few minutes to mellow its bite.",
        "Blend the tahini with the garlic-lemon juice for 1-2 minutes until pale and creamy, then add the ice water and blend again until light and whipped.",
        "Add the chickpeas, cumin, and salt, and blend for 3-4 minutes until completely smooth, streaming in the olive oil as it processes; adjust with more ice water for a silkier consistency. Serve with a drizzle of olive oil.",
      ],
      tags: ["snack", "vegan", "quick", "mediterranean"],
    },
    bg: {
      title: "Класически хумус",
      description:
        "Разбит, копринен сос от нахут и тахан - таханът и лимонът се пасират първо за емулгиране, после се добавя ледена вода за пухкава, ресторантска текстура.",
      steps: [
        "Варете нахута със содата бикарбонат в тенджера 5 минути, за да омекнат люспите, после отцедете и изплакнете.",
        "Оставете ситно нарязания чесън в лимоновия сок за няколко минути, за да омекне остротата му.",
        "Пасирайте тахана с чесново-лимоновата смес 1-2 минути, докато стане светъл и кремообразен, после добавете ледената вода и пасирайте отново, докато стане лек и разбит.",
        "Добавете нахута, кимиона и солта и пасирайте 3-4 минути до пълна гладкост, наливайки зехтина по време на пасиране; коригирайте с още ледена вода за по-копринена консистенция. Сервирайте с малко зехтин отгоре.",
      ],
      ingredients: [
        "2 консерви нахут, отцеден (запазете течността)",
        "1/2 ч.л. сода бикарбонат",
        "2 скилидки чесън, ситно нарязани",
        "сок от 1 лимон",
        "1/2 чаша тахан",
        "3 с.л. ледена вода, плюс още при нужда",
        "1/2 ч.л. кимион",
        "3 с.л. зехтин",
        "Сол на вкус",
      ],
    },
  },
];

applyRecipeUpdates(updates).catch((err) => {
  console.error(err);
  process.exit(1);
});
