import { applyRecipeUpdates } from "./update-lib.mjs";

const updates = [
  {
    en: {
      slug: "simple-vegetable-soup",
      title: "Simple Vegetable Soup",
      description:
        "A light, wholesome soup of mixed vegetables and garlic simmered in a savory broth, finished with salt and pepper - without them the vegetables taste like they're floating in plain water.",
      imageEmoji: "🥕",
      cookTimeMinutes: 35,
      servings: 6,
      ingredients: [
        { text: "2 carrots, sliced", ingredient: "carrot", quantity: 2 },
        { text: "2 celery stalks, sliced", ingredient: "celery", quantity: 2 },
        { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
        { text: "2 cloves garlic, minced", ingredient: "garlic", quantity: 2 },
        { text: "2 potatoes, cubed", ingredient: "potato", quantity: 2 },
        { text: "6 cups vegetable broth", ingredient: "vegetable broth", quantity: 6 },
        { text: "1 can diced tomatoes", ingredient: "tomato", quantity: 1 },
        { text: "Salt to taste", ingredient: "salt", quantity: null },
        { text: "Pepper to taste", ingredient: "pepper", quantity: null },
      ],
      steps: [
        "Combine all the vegetables, garlic, and vegetable broth in a large pot.",
        "Bring to a boil, then reduce heat and simmer for 25 minutes until the vegetables are tender.",
        "Stir in the diced tomatoes and simmer for another 5 minutes.",
        "Season with salt and pepper before serving - without them the vegetables taste like they're floating in plain water.",
      ],
      tags: ["lunch", "vegan", "vegetarian"],
    },
    bg: {
      title: "Проста зеленчукова супа",
      description:
        "Лека, питателна супа от смесени зеленчуци и чесън, къкрени в ароматен бульон, завършена със сол и черен пипер - без тях зеленчуците имат вкус, сякаш плуват в обикновена вода.",
      steps: [
        "Съберете всички зеленчуци, чесъна и зеленчуковия бульон в голяма тенджера.",
        "Оставете да заври, после намалете котлона и къкрете 25 минути, докато зеленчуците омекнат.",
        "Разбъркайте нарязаните домати и къкрете още 5 минути.",
        "Подправете със сол и черен пипер преди сервиране - без тях зеленчуците имат вкус, сякаш плуват в обикновена вода.",
      ],
      ingredients: [
        "2 моркова, нарязани на резени",
        "2 стръка целина, нарязани на резени",
        "1 лук, нарязан на кубчета",
        "2 скилидки чесън, ситно нарязани",
        "2 картофа, нарязани на кубчета",
        "6 чаши зеленчуков бульон",
        "1 консерва нарязани домати",
        "Сол на вкус",
        "Черен пипер на вкус",
      ],
    },
  },
  {
    en: {
      slug: "simple-vanilla-pudding",
      title: "Simple Vanilla Pudding",
      description:
        "A smooth, creamy homemade pudding made on the stovetop with just a handful of ingredients, plus a pinch of salt - salt is what keeps a vanilla custard from tasting flatly sweet.",
      imageEmoji: "🍮",
      cookTimeMinutes: 20,
      servings: 4,
      ingredients: [
        { text: "1/2 cup sugar", ingredient: "sugar", quantity: 0.5 },
        { text: "3 tbsp cornstarch", ingredient: "cornstarch", quantity: 3 },
        { text: "Pinch of salt", ingredient: "salt", quantity: null },
        { text: "2 cups milk", ingredient: "milk", quantity: 2 },
        { text: "2 egg yolks", ingredient: "egg yolks", quantity: 2 },
        { text: "1 tsp vanilla extract", ingredient: "vanilla extract", quantity: 1 },
      ],
      steps: [
        "Whisk together the sugar, cornstarch, and salt in a saucepan.",
        "Gradually whisk in the milk and egg yolks until smooth.",
        "Cook over medium heat, stirring constantly, until thickened, about 8-10 minutes.",
        "Remove from heat, stir in the vanilla, and chill before serving.",
      ],
      tags: ["dessert", "vegetarian"],
    },
    bg: {
      title: "Прост ванилов пудинг",
      description:
        "Гладък, кремообразен домашен пудинг, приготвен на котлона само от няколко съставки, плюс щипка сол - солта е това, което пази ваниловия крем от плосък сладък вкус.",
      steps: [
        "Разбъркайте захарта, царевичното нишесте и солта в тенджера.",
        "Постепенно разбийте млякото и жълтъците до гладкост.",
        "Гответе на среден огън, разбърквайки постоянно, докато се сгъсти, около 8-10 минути.",
        "Свалете от котлона, добавете ванилията и охладете преди сервиране.",
      ],
      ingredients: [
        "1/2 чаша захар",
        "3 с.л. царевично нишесте",
        "Щипка сол",
        "2 чаши мляко",
        "2 жълтъка",
        "1 ч.л. екстракт от ванилия",
      ],
    },
  },
  {
    en: {
      slug: "skillet-chicken-fajitas",
      title: "Skillet Chicken Fajitas",
      description:
        "Sizzling strips of chicken and peppers seasoned with a real blend of fajita spices - chili powder, cumin, garlic powder, and salt, not chili powder alone pretending to be a spice blend.",
      imageEmoji: "🌮",
      cookTimeMinutes: 25,
      servings: 4,
      ingredients: [
        { text: "2 chicken breasts, sliced", ingredient: "chicken breast", quantity: 2 },
        { text: "1 red bell pepper, sliced", ingredient: "red pepper", quantity: 1 },
        { text: "1 green bell pepper, sliced", ingredient: "green pepper", quantity: 1 },
        { text: "1 onion, sliced", ingredient: "onion", quantity: 1 },
        { text: "2 tsp chili powder", ingredient: "chili powder", quantity: 2 },
        { text: "1 tsp cumin", ingredient: "cumin", quantity: 1 },
        { text: "1 tsp garlic powder", ingredient: "garlic powder", quantity: 1 },
        { text: "Salt to taste", ingredient: "salt", quantity: null },
        { text: "2 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 2 },
        { text: "8 small flour tortillas", ingredient: "flour tortillas", quantity: 8 },
      ],
      steps: [
        "Heat oil in a large skillet and cook the chicken with chili powder, cumin, garlic powder, and salt until browned and cooked through; set aside.",
        "In the same skillet, cook the peppers and onion until softened and slightly charred.",
        "Return the chicken to the pan and toss together.",
        "Serve with warm tortillas.",
      ],
      tags: ["dinner", "mexican", "quick"],
    },
    bg: {
      title: "Пилешки фахитас в тиган",
      description:
        "Съскащи ивици пиле и чушки, подправени с истинска смес от фахитас подправки - чили на прах, кимион, чеснов прах и сол, а не само чили на прах, представящ се за подправъчна смес.",
      steps: [
        "Загрейте олио в голям тиган и гответе пилето с чили на прах, кимион, чеснов прах и сол до зачервяване и пълно сготвяне; отделете настрана.",
        "В същия тиган гответе чушките и лука до омекване и леко овъгляне.",
        "Върнете пилето в тигана и разбъркайте заедно.",
        "Сервирайте с топли тортили.",
      ],
      ingredients: [
        "2 пилешки гърди, нарязани",
        "1 червена чушка, нарязана",
        "1 зелена чушка, нарязана",
        "1 лук, нарязан",
        "2 ч.л. чили на прах",
        "1 ч.л. кимион",
        "1 ч.л. чеснов прах",
        "Сол на вкус",
        "2 с.л. олио",
        "8 малки пшенични тортили",
      ],
    },
  },
  {
    en: {
      slug: "slow-cooker-beef-stew",
      title: "Slow Cooker Beef Stew",
      description:
        "Tender beef and vegetables slow-cooked all day with garlic and thyme in a rich, savory broth, seasoned with salt and pepper - eight hours in the slow cooker won't season meat that never had salt to begin with.",
      imageEmoji: "🍲",
      cookTimeMinutes: 480,
      servings: 6,
      ingredients: [
        { text: "2 lb beef stew meat", ingredient: "beef", quantity: 2 },
        { text: "4 potatoes, cubed", ingredient: "potato", quantity: 4 },
        { text: "3 carrots, sliced", ingredient: "carrot", quantity: 3 },
        { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
        { text: "2 cloves garlic, minced", ingredient: "garlic", quantity: 2 },
        { text: "1 tsp dried thyme", ingredient: "thyme", quantity: 1 },
        { text: "4 cups beef broth", ingredient: "beef broth", quantity: 4 },
        { text: "2 tbsp flour", ingredient: "flour", quantity: 2 },
        { text: "Salt to taste", ingredient: "salt", quantity: null },
        { text: "Pepper to taste", ingredient: "pepper", quantity: null },
      ],
      steps: [
        "Toss the beef with flour, salt, and pepper, then place in a slow cooker with the vegetables, garlic, thyme, and beef broth - seasoning the beef before it goes in is what actually flavors it, not just the hours of cooking.",
        "Cook on low for 8 hours until the beef and vegetables are tender.",
        "Stir well before serving.",
      ],
      tags: ["dinner"],
    },
    bg: {
      title: "Телешко задушено в бавна готварска печка",
      description:
        "Крехко телешко и зеленчуци, задушени цял ден с чесън и мащерка в богат, ароматен бульон, подправени със сол и черен пипер - осем часа в бавната готварска печка не подправят месо, което никога не е имало сол в началото.",
      steps: [
        "Овалайте телешкото в брашно, сол и черен пипер, после го поставете в бавна готварска печка със зеленчуците, чесъна, мащерката и бульона - подправянето на месото преди да влезе е това, което наистина му дава вкус, а не само часовете готвене.",
        "Гответе на слаб режим 8 часа, докато телешкото и зеленчуците омекнат.",
        "Разбъркайте добре преди сервиране.",
      ],
      ingredients: [
        "900 г телешко за задушаване",
        "4 картофа, нарязани на кубчета",
        "3 моркова, нарязани на резени",
        "1 лук, нарязан на кубчета",
        "2 скилидки чесън, ситно нарязани",
        "1 ч.л. суха мащерка",
        "4 чаши телешки бульон",
        "2 с.л. брашно",
        "Сол на вкус",
        "Черен пипер на вкус",
      ],
    },
  },
  {
    en: {
      slug: "slow-cooker-chicken-curry",
      title: "Slow Cooker Chicken Curry",
      description:
        "Chicken thighs slow-cooked in a creamy coconut curry sauce with garlic and ginger - the aromatics a curry needs for real depth instead of tasting like plain curry-powder-flavored coconut milk.",
      imageEmoji: "🍛",
      cookTimeMinutes: 300,
      servings: 6,
      ingredients: [
        { text: "2 lb chicken thighs", ingredient: "chicken thighs", quantity: 2 },
        { text: "1 can coconut milk", ingredient: "coconut milk", quantity: 1 },
        { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
        { text: "3 cloves garlic, minced", ingredient: "garlic", quantity: 3 },
        { text: "1 tbsp fresh ginger, grated", ingredient: "ginger", quantity: 1 },
        { text: "3 tbsp curry powder", ingredient: "curry powder", quantity: 3 },
        { text: "1 can diced tomatoes", ingredient: "tomato", quantity: 1 },
        { text: "Salt to taste", ingredient: "salt", quantity: null },
      ],
      steps: [
        "Place the chicken, onion, garlic, ginger, curry powder, diced tomatoes, coconut milk, and salt in a slow cooker.",
        "Stir to combine.",
        "Cook on low for 5 hours until the chicken is tender.",
        "Serve over rice.",
      ],
      tags: ["dinner"],
    },
    bg: {
      title: "Пилешко къри в бавна готварска печка",
      description:
        "Пилешки бутчета, задушени в кремообразен сос от кокосово мляко с чесън и джинджифил - ароматите, от които всяко къри се нуждае за истинска дълбочина на вкуса, вместо да има вкус на обикновено кокосово мляко с къри на прах.",
      steps: [
        "Поставете пилето, лука, чесъна, джинджифила, къри подправката, нарязаните домати, кокосовото мляко и солта в бавна готварска печка.",
        "Разбъркайте за смесване.",
        "Гответе на слаб режим 5 часа, докато пилето омекне.",
        "Сервирайте върху ориз.",
      ],
      ingredients: [
        "900 г пилешки бутчета",
        "1 консерва кокосово мляко",
        "1 лук, нарязан на кубчета",
        "3 скилидки чесън, ситно нарязани",
        "1 с.л. настърган пресен джинджифил",
        "3 с.л. къри подправка",
        "1 консерва нарязани домати",
        "Сол на вкус",
      ],
    },
  },
  {
    en: {
      slug: "slow-cooker-chili",
      title: "Slow Cooker Chili",
      description:
        "A hands-off, all-day chili of ground beef, beans, and tomatoes, rounded out with cumin, garlic, and salt - chili powder alone leaves the classic chili flavor incomplete.",
      imageEmoji: "🌶️",
      cookTimeMinutes: 360,
      servings: 6,
      ingredients: [
        { text: "1 1/2 lb ground beef, browned", ingredient: "ground beef", quantity: 1.5 },
        { text: "2 cans kidney beans, drained", ingredient: "kidney beans", quantity: 2 },
        { text: "1 can diced tomatoes", ingredient: "tomato", quantity: 1 },
        { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
        { text: "2 cloves garlic, minced", ingredient: "garlic", quantity: 2 },
        { text: "3 tbsp chili powder", ingredient: "chili powder", quantity: 3 },
        { text: "1 tbsp cumin", ingredient: "cumin", quantity: 1 },
        { text: "Salt to taste", ingredient: "salt", quantity: null },
      ],
      steps: [
        "Combine the browned ground beef, kidney beans, diced tomatoes, onion, garlic, chili powder, and cumin in a slow cooker.",
        "Cook on low for 6 hours, stirring occasionally.",
        "Season with salt before serving.",
      ],
      tags: ["dinner"],
    },
    bg: {
      title: "Чили в бавна готварска печка",
      description:
        "Необременяващо целодневно чили от говежда кайма, боб и домати, обогатено с кимион, чесън и сол - самото чили на прах оставя класическия вкус на чили непълен.",
      steps: [
        "Съберете запържената говежда кайма, черния боб, нарязаните домати, лука, чесъна, чили на прах и кимиона в бавна готварска печка.",
        "Гответе на слаб режим 6 часа, разбърквайки от време на време.",
        "Подправете със сол преди сервиране.",
      ],
      ingredients: [
        "680 г говежда кайма, запържена",
        "2 консерви червен боб, отцеден",
        "1 консерва нарязани домати",
        "1 лук, нарязан на кубчета",
        "2 скилидки чесън, ситно нарязани",
        "3 с.л. чили на прах",
        "1 с.л. кимион",
        "Сол на вкус",
      ],
    },
  },
  {
    en: {
      slug: "slow-cooker-mac-and-cheese",
      title: "Slow Cooker Mac and Cheese",
      description:
        "Creamy, hands-off macaroni and cheese made entirely in the slow cooker, sharpened with dry mustard, salt, and pepper - dry mustard is the classic ingredient that keeps a cheese sauce from tasting one-dimensional.",
      imageEmoji: "🧀",
      cookTimeMinutes: 150,
      servings: 6,
      ingredients: [
        { text: "1 lb elbow macaroni, cooked", ingredient: "elbow macaroni", quantity: 1 },
        { text: "3 cups shredded cheddar cheese", ingredient: "cheddar cheese", quantity: 3 },
        { text: "2 cups milk", ingredient: "milk", quantity: 2 },
        { text: "1 can evaporated milk", ingredient: "evaporated milk", quantity: 1 },
        { text: "2 eggs, beaten", ingredient: "eggs", quantity: 2 },
        { text: "1/2 tsp dry mustard", ingredient: "dry mustard", quantity: 0.5 },
        { text: "Salt to taste", ingredient: "salt", quantity: null },
        { text: "Pepper to taste", ingredient: "pepper", quantity: null },
      ],
      steps: [
        "Combine the cooked macaroni, cheddar cheese, milk, evaporated milk, eggs, dry mustard, salt, and pepper in a slow cooker - dry mustard is what keeps the cheese sauce from tasting flat.",
        "Cook on low for 2-2.5 hours, stirring occasionally, until creamy.",
        "Serve warm.",
      ],
      tags: ["dinner", "vegetarian"],
    },
    bg: {
      title: "Макарони със сирене в бавна готварска печка",
      description:
        "Кремообразни, необременяващи макарони със сирене, приготвени изцяло в бавна готварска печка, подсилени със суха горчица, сол и черен пипер - сухата горчица е класическата съставка, която пази сиренения сос от еднообразен вкус.",
      steps: [
        "Съберете сварените макарони, чедъра, млякото, кондензираното мляко, яйцата, сухата горчица, солта и черния пипер в бавна готварска печка - сухата горчица е това, което пази сиренения сос от плосък вкус.",
        "Гответе на слаб режим 2-2.5 часа, разбърквайки от време на време, докато стане кремообразно.",
        "Сервирайте топло.",
      ],
      ingredients: [
        "450 г макарони, сварени",
        "3 чаши настърган чедър",
        "2 чаши мляко",
        "1 консерва кондензирано мляко",
        "2 яйца, разбити",
        "1/2 ч.л. суха горчица",
        "Сол на вкус",
        "Черен пипер на вкус",
      ],
    },
  },
  {
    en: {
      slug: "slow-cooker-pot-roast",
      title: "Slow Cooker Pot Roast",
      description:
        "Beef chuck roast rubbed with salt, pepper, garlic, and thyme, then slow-cooked with potatoes and carrots until fork-tender - eight hours in the slow cooker doesn't season a roast that goes in completely plain.",
      imageEmoji: "🍖",
      cookTimeMinutes: 480,
      servings: 6,
      ingredients: [
        { text: "3 lb beef chuck roast", ingredient: "beef chuck roast", quantity: 3 },
        { text: "4 potatoes, quartered", ingredient: "potato", quantity: 4 },
        { text: "4 carrots, cut into chunks", ingredient: "carrot", quantity: 4 },
        { text: "1 onion, quartered", ingredient: "onion", quantity: 1 },
        { text: "3 cloves garlic, minced", ingredient: "garlic", quantity: 3 },
        { text: "1 tsp dried thyme", ingredient: "thyme", quantity: 1 },
        { text: "2 cups beef broth", ingredient: "beef broth", quantity: 2 },
        { text: "Salt to taste", ingredient: "salt", quantity: null },
        { text: "Pepper to taste", ingredient: "pepper", quantity: null },
      ],
      steps: [
        "Rub the beef roast with salt, pepper, garlic, and thyme, then place in a slow cooker with the potatoes, carrots, and onion.",
        "Pour in the beef broth.",
        "Cook on low for 8 hours until the beef is fork-tender.",
        "Shred or slice the beef and serve with the vegetables.",
      ],
      tags: ["dinner"],
    },
    bg: {
      title: "Печено телешко в бавна готварска печка",
      description:
        "Телешко плешка, натрита със сол, черен пипер, чесън и мащерка, после задушена с картофи и моркови до пълна мекота - осем часа в бавната готварска печка не подправят печено, което влиза напълно голо.",
      steps: [
        "Натрийте телешкото със сол, черен пипер, чесън и мащерка, после го поставете в бавна готварска печка с картофите, морковите и лука.",
        "Долейте телешкия бульон.",
        "Гответе на слаб режим 8 часа, докато телешкото стане меко.",
        "Накъсайте или нарежете месото и сервирайте със зеленчуците.",
      ],
      ingredients: [
        "1.4 кг телешка плешка за печене",
        "4 картофа, разрязани на четвъртинки",
        "4 моркова, нарязани на едро",
        "1 лук, разрязан на четвъртинки",
        "3 скилидки чесън, ситно нарязани",
        "1 ч.л. суха мащерка",
        "2 чаши телешки бульон",
        "Сол на вкус",
        "Черен пипер на вкус",
      ],
    },
  },
  {
    en: {
      slug: "spinach-artichoke-dip",
      title: "Spinach Artichoke Dip",
      description:
        "A warm, creamy baked dip loaded with spinach, artichokes, garlic, Parmesan, and melted cheese - garlic and Parmesan are what give this dip its real depth instead of tasting like plain melted cream cheese.",
      imageEmoji: "🧀",
      cookTimeMinutes: 35,
      servings: 8,
      ingredients: [
        { text: "2 cups spinach, chopped", ingredient: "spinach", quantity: 2 },
        { text: "1 can artichoke hearts, chopped", ingredient: "artichoke hearts", quantity: 1 },
        { text: "8 oz cream cheese, softened", ingredient: "cream cheese", quantity: 8 },
        { text: "1 cup sour cream", ingredient: "sour cream", quantity: 1 },
        { text: "2 cloves garlic, minced", ingredient: "garlic", quantity: 2 },
        { text: "1/4 cup grated Parmesan", ingredient: "parmesan", quantity: 0.25 },
        { text: "Salt to taste", ingredient: "salt", quantity: null },
        { text: "Pepper to taste", ingredient: "pepper", quantity: null },
        { text: "1 1/2 cups shredded mozzarella", ingredient: "mozzarella", quantity: 1.5 },
      ],
      steps: [
        "Preheat oven to 375°F.",
        "Mix the spinach, artichoke hearts, cream cheese, sour cream, garlic, Parmesan, salt, pepper, and half the mozzarella.",
        "Spread into a baking dish and top with the remaining mozzarella.",
        "Bake for 20-25 minutes until bubbly and golden.",
      ],
      tags: ["snack", "vegetarian"],
    },
    bg: {
      title: "Дип със спанак и артишок",
      description:
        "Топъл, кремообразен печен дип, зареден със спанак, артишок, чесън, пармезан и разтопено сирене - чесънът и пармезанът са това, което дава на дипа истинска дълбочина, вместо вкус на обикновено разтопено крема сирене.",
      steps: [
        "Загрейте фурната на 190°C.",
        "Смесете спанака, артишока, крема сиренето, заквасената сметана, чесъна, пармезана, солта, черния пипер и половината моцарела.",
        "Разстелете в тава за печене и отгоре сложете останалата моцарела.",
        "Печете 20-25 минути до бълбукане и златист цвят.",
      ],
      ingredients: [
        "2 чаши спанак, нарязан",
        "1 консерва сърца от артишок, нарязани",
        "225 г крема сирене, омекнало",
        "1 чаша заквасена сметана",
        "2 скилидки чесън, ситно нарязани",
        "1/4 чаша настърган пармезан",
        "Сол на вкус",
        "Черен пипер на вкус",
        "1 1/2 чаши настъргана моцарела",
      ],
    },
  },
  {
    en: {
      slug: "split-pea-soup",
      title: "Split Pea Soup",
      description:
        "A thick, hearty soup of split peas simmered with ham, garlic, and a bay leaf - garlic and bay leaf round out the flavor instead of leaving it to rely on the ham alone.",
      imageEmoji: "🟢",
      cookTimeMinutes: 90,
      servings: 6,
      ingredients: [
        { text: "2 cups dried split peas", ingredient: "split peas", quantity: 2 },
        { text: "1 ham hock or diced ham", ingredient: "ham", quantity: 1 },
        { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
        { text: "2 carrots, diced", ingredient: "carrot", quantity: 2 },
        { text: "2 celery stalks, diced", ingredient: "celery", quantity: 2 },
        { text: "2 cloves garlic, minced", ingredient: "garlic", quantity: 2 },
        { text: "1 bay leaf", ingredient: "bay leaf", quantity: 1 },
        { text: "8 cups chicken broth", ingredient: "chicken broth", quantity: 8 },
        { text: "Pepper to taste", ingredient: "pepper", quantity: null },
      ],
      steps: [
        "Combine the split peas, ham, onion, carrots, celery, garlic, bay leaf, and chicken broth in a large pot.",
        "Bring to a boil, then reduce heat and simmer, partially covered, for about 1.5 hours, stirring occasionally.",
        "Remove the ham hock and bay leaf, shred the meat, and return it to the pot.",
        "Season with pepper and serve hot.",
      ],
      tags: ["dinner"],
    },
    bg: {
      title: "Супа от разцепен грах",
      description:
        "Гъста, засищаща супа от разцепен грах, къкрена с шунка, чесън и дафинов лист - чесънът и дафиновият лист обогатяват вкуса, вместо да разчита само на шунката.",
      steps: [
        "Съберете граха, шунката, лука, морковите, целината, чесъна, дафиновия лист и пилешкия бульон в голяма тенджера.",
        "Оставете да заври, после намалете котлона и къкрете, частично покрито, около 1.5 часа, разбърквайки от време на време.",
        "Извадете шунката и дафиновия лист, накъсайте месото и го върнете в тенджерата.",
        "Подправете с черен пипер и сервирайте горещо.",
      ],
      ingredients: [
        "2 чаши сух разцепен грах",
        "1 кокалче шунка или нарязана шунка",
        "1 лук, нарязан на кубчета",
        "2 моркова, нарязани на кубчета",
        "2 стръка целина, нарязани на кубчета",
        "2 скилидки чесън, ситно нарязани",
        "1 дафинов лист",
        "8 чаши пилешки бульон",
        "Черен пипер на вкус",
      ],
    },
  },
  {
    en: {
      slug: "stuffed-mushrooms",
      title: "Stuffed Mushrooms",
      description:
        "Mushroom caps filled with a savory, well-seasoned cream cheese and breadcrumb stuffing, baked until golden - salt and pepper are what keep the filling from tasting like plain cream cheese.",
      imageEmoji: "🍄",
      cookTimeMinutes: 35,
      servings: 6,
      ingredients: [
        { text: "20 button mushrooms, stems removed", ingredient: "mushroom", quantity: 20 },
        { text: "4 oz cream cheese, softened", ingredient: "cream cheese", quantity: 4 },
        { text: "1/2 cup breadcrumbs", ingredient: "breadcrumbs", quantity: 0.5 },
        { text: "1/4 cup grated Parmesan", ingredient: "parmesan", quantity: 0.25 },
        { text: "2 cloves garlic, minced", ingredient: "garlic", quantity: 2 },
        { text: "Salt to taste", ingredient: "salt", quantity: null },
        { text: "Pepper to taste", ingredient: "pepper", quantity: null },
      ],
      steps: [
        "Preheat oven to 375°F.",
        "Mix the cream cheese, breadcrumbs, Parmesan, garlic, salt, and pepper.",
        "Stuff the mixture into each mushroom cap.",
        "Bake for 20-25 minutes until golden and the mushrooms are tender.",
      ],
      tags: ["snack", "vegetarian"],
    },
    bg: {
      title: "Пълнени гъби",
      description:
        "Гъбени шапки, пълни с ароматен, добре подправен пълнеж от крема сирене и галета, изпечени до златисто - солта и черният пипер са това, което пази пълнежа от вкус на обикновено крема сирене.",
      steps: [
        "Загрейте фурната на 190°C.",
        "Смесете крема сиренето, галетата, пармезана, чесъна, солта и черния пипер.",
        "Напълнете сместа във всяка гъбена шапка.",
        "Печете 20-25 минути до златисто и докато гъбите омекнат.",
      ],
      ingredients: [
        "20 бели гъби, без дръжки",
        "115 г крема сирене, омекнало",
        "1/2 чаша галета",
        "1/4 чаша настърган пармезан",
        "2 скилидки чесън, ситно нарязани",
        "Сол на вкус",
        "Черен пипер на вкус",
      ],
    },
  },
  {
    en: {
      slug: "stuffed-portobello-mushrooms",
      title: "Stuffed Portobello Mushrooms",
      description:
        "Large portobello caps filled with a cheesy spinach, garlic, and breadcrumb stuffing - garlic and salt are what keep the filling from tasting bland against the meaty mushroom.",
      imageEmoji: "🍄",
      cookTimeMinutes: 35,
      servings: 4,
      ingredients: [
        { text: "4 portobello mushroom caps", ingredient: "portobello mushrooms", quantity: 4 },
        { text: "2 cups spinach, chopped", ingredient: "spinach", quantity: 2 },
        { text: "2 cloves garlic, minced", ingredient: "garlic", quantity: 2 },
        { text: "1/2 cup breadcrumbs", ingredient: "breadcrumbs", quantity: 0.5 },
        { text: "1/2 cup shredded mozzarella", ingredient: "mozzarella", quantity: 0.5 },
        { text: "3 tbsp olive oil", ingredient: "olive oil", quantity: 3 },
        { text: "Salt to taste", ingredient: "salt", quantity: null },
        { text: "Pepper to taste", ingredient: "pepper", quantity: null },
      ],
      steps: [
        "Preheat oven to 400°F.",
        "Brush the mushroom caps with olive oil and place on a baking sheet.",
        "Sauté the spinach and garlic until wilted and fragrant, then mix with breadcrumbs, salt, pepper, and half the mozzarella.",
        "Stuff the mixture into the caps, top with remaining mozzarella, and bake for 20 minutes.",
      ],
      tags: ["dinner", "vegetarian"],
    },
    bg: {
      title: "Пълнени гъби портобело",
      description:
        "Големи шапки от гъби портобело, пълни с пълнеж от спанак, чесън, сирене и галета - чесънът и солта са това, което пази пълнежа от безвкусие срещу месестата гъба.",
      steps: [
        "Загрейте фурната на 200°C.",
        "Намажете гъбените шапки със зехтин и ги наредете на тава.",
        "Запържете спанака и чесъна до омекване и ароматизиране, после смесете с галетата, солта, черния пипер и половината моцарела.",
        "Напълнете сместа в шапките, отгоре сложете останалата моцарела и печете 20 минути.",
      ],
      ingredients: [
        "4 шапки гъби портобело",
        "2 чаши спанак, нарязан",
        "2 скилидки чесън, ситно нарязани",
        "1/2 чаша галета",
        "1/2 чаша настъргана моцарела",
        "3 с.л. зехтин",
        "Сол на вкус",
        "Черен пипер на вкус",
      ],
    },
  },
];

applyRecipeUpdates(updates).catch((err) => {
  console.error(err);
  process.exit(1);
});
