import { applyRecipeUpdates } from "./update-lib.mjs";

const updates = [
  {
    en: {
      slug: "empanadas",
      title: "Empanadas",
      description:
        "Flaky pastry pockets filled with beef seasoned with paprika, cumin, and oregano, folded in hard-boiled egg and olives once cooled - the hard-boiled egg is a defining ingredient in real Argentine empanadas, added off the heat so it doesn't turn to mush.",
      imageEmoji: "🥟",
      cookTimeMinutes: 90,
      servings: 8,
      ingredients: [
        { text: "2 tbsp olive oil", ingredient: "olive oil", quantity: 2 },
        { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
        { text: "2 cloves garlic, minced", ingredient: "garlic", quantity: 2 },
        { text: "1/2 red bell pepper, diced", ingredient: "red pepper", quantity: 0.5 },
        { text: "1 lb ground beef", ingredient: "ground beef", quantity: 1 },
        { text: "1 tsp cumin", ingredient: "cumin", quantity: 1 },
        { text: "1 tsp sweet paprika", ingredient: "paprika", quantity: 1 },
        { text: "1/2 tsp dried oregano", ingredient: "oregano", quantity: 0.5 },
        { text: "1/2 cup green olives, chopped", ingredient: "olives", quantity: 0.5 },
        { text: "2 hard-boiled eggs, chopped", ingredient: "eggs", quantity: 2 },
        { text: "2 tbsp chopped parsley", ingredient: "parsley", quantity: 2 },
        { text: "16 empanada dough discs", ingredient: "empanada dough", quantity: 16 },
        { text: "1 egg, beaten (for brushing)", ingredient: "eggs", quantity: 1 },
      ],
      steps: [
        "Heat the olive oil and cook the onion with a pinch of salt for 10 minutes, then add the garlic and red pepper and cook another 10 minutes until softened.",
        "Stir in the cumin, paprika, and oregano and cook for 2 minutes, then add the ground beef and cook until browned, seasoning with salt and pepper.",
        "Let the filling cool, then stir in the olives, chopped hard-boiled eggs, and parsley off the heat - adding them while hot turns the eggs to mush and pushes the olive brine into the filling.",
        "Chill the filling for at least 1 hour so it firms up and is easier to fill.",
        "Preheat oven to 400°F.",
        "Spoon filling onto each dough disc, fold over into a half-moon, and crimp the edges to seal.",
        "Brush with beaten egg and bake for 20-25 minutes until golden.",
      ],
      tags: ["dinner", "snack"],
    },
    bg: {
      title: "Емпанади",
      description:
        "Хрупкави джобчета тесто, пълнени с телешко месо, подправено с червен пипер, кимион и риган, смесено с твърдо сварено яйце и маслини след изстиване - твърдо свареното яйце е характерна съставка в истинските аржентински емпанади, добавена извън котлона, за да не се превърне в каша.",
      steps: [
        "Загрейте зехтина и гответе лука с щипка сол 10 минути, после добавете чесъна и червената чушка и гответе още 10 минути до омекване.",
        "Разбъркайте кимиона, червения пипер и ригана и гответе 2 минути, после добавете каймата и гответе до запържване, подправяйки със сол и черен пипер.",
        "Оставете плънката да изстине, после разбъркайте маслините, нарязаните твърдо сварени яйца и магданоза извън котлона - добавянето им докато е горещо превръща яйцата в каша и изкарва саламурата от маслините в плънката.",
        "Охладете плънката поне 1 час, за да се стегне и да е по-лесна за пълнене.",
        "Загрейте фурната на 200°C.",
        "Сложете плънка върху всеки диск тесто, сгънете на полумесец и притиснете краищата за запечатване.",
        "Намажете с разбито яйце и печете 20-25 минути до златисто.",
      ],
      ingredients: [
        "2 с.л. зехтин",
        "1 лук, нарязан на кубчета",
        "2 скилидки чесън, ситно нарязани",
        "1/2 червена чушка, нарязана на кубчета",
        "450 г кайма от телешко месо",
        "1 ч.л. кимион",
        "1 ч.л. сладък червен пипер",
        "1/2 ч.л. сух риган",
        "1/2 чаша зелени маслини, нарязани",
        "2 твърдо сварени яйца, нарязани",
        "2 с.л. нарязан магданоз",
        "16 диска тесто за емпанади",
        "1 разбито яйце (за намазване)",
      ],
    },
  },
  {
    en: {
      slug: "arroz-con-pollo",
      title: "Arroz con Pollo",
      description:
        "Chicken and rice built on a blended sofrito of onion, garlic, bell pepper, and cilantro, colored with achiote instead of turmeric, with the rice toasted in the sofrito before the broth goes in - the sofrito and toasting step are what real arroz con pollo is built on, not just spiced rice and chicken.",
      imageEmoji: "🍚",
      cookTimeMinutes: 55,
      servings: 6,
      ingredients: [
        { text: "4 chicken thighs", ingredient: "chicken thighs", quantity: 4 },
        { text: "1 onion, quartered", ingredient: "onion", quantity: 1 },
        { text: "4 cloves garlic", ingredient: "garlic", quantity: 4 },
        { text: "1 red bell pepper, quartered", ingredient: "red pepper", quantity: 1 },
        { text: "1/4 cup cilantro, plus more for garnish", ingredient: "cilantro", quantity: 0.25 },
        { text: "2 tbsp olive oil", ingredient: "olive oil", quantity: 2 },
        { text: "1 tbsp achiote (annatto) paste or powder (or 1 tsp turmeric)", ingredient: "achiote paste", quantity: 1 },
        { text: "1 tsp cumin", ingredient: "cumin", quantity: 1 },
        { text: "2 cups rice, rinsed", ingredient: "rice", quantity: 2 },
        { text: "3 cups chicken broth", ingredient: "chicken broth", quantity: 3 },
        { text: "Lime wedges, for serving", ingredient: "lime", quantity: null },
      ],
      steps: [
        "Blend the onion, garlic, bell pepper, and cilantro into a coarse sofrito paste.",
        "Brown the chicken thighs in the olive oil in a large pot, then set aside.",
        "Sauté the sofrito in the same pot with the achiote and cumin until fragrant and slightly reduced, about 5 minutes.",
        "Add the rinsed rice and toast it in the sofrito for 2-3 minutes, coating every grain, so it holds its texture instead of turning mushy.",
        "Stir in the chicken broth and nestle the chicken back in.",
        "Cover and simmer for 25 minutes until the rice is tender and the chicken is cooked through.",
        "Garnish with cilantro and serve with lime wedges.",
      ],
      tags: ["dinner"],
    },
    bg: {
      title: "Арос кон Поло",
      description:
        "Пиле и ориз, изградени върху пасирано софрито от лук, чесън, чушка и кориандър, оцветено с ачоте вместо куркума, като оризът се препича в софритото преди да се добави бульонът - софритото и препичането на ориза са това, върху което е изградено истинското арос кон поло, не просто подправен ориз и пиле.",
      steps: [
        "Пасирайте лука, чесъна, чушката и кориандъра до груба паста софрито.",
        "Запържете пилешките бутчета в зехтина в голяма тенджера, после отделете настрани.",
        "Запържете софритото в същата тенджера с ачотето и кимиона до ароматизиране и леко редуциране, около 5 минути.",
        "Добавете изплакнатия ориз и го препечете в софритото 2-3 минути, покривайки всяко зърно, за да запази текстурата си, вместо да стане кашест.",
        "Разбъркайте пилешкия бульон и върнете пилето обратно.",
        "Покрийте и варете 25 минути, докато оризът омекне и пилето се сготви напълно.",
        "Гарнирайте с кориандър и сервирайте с резенчета лайм.",
      ],
      ingredients: [
        "4 пилешки бутчета",
        "1 лук, разрязан на четвъртинки",
        "4 скилидки чесън",
        "1 червена чушка, разрязана на четвъртинки",
        "1/4 чаша кориандър, плюс още за гарниране",
        "2 с.л. зехтин",
        "1 с.л. ачоте паста или на прах (или 1 ч.л. куркума)",
        "1 ч.л. кимион",
        "2 чаши ориз, изплакнат",
        "3 чаши пилешки бульон",
        "Резенчета лайм, за сервиране",
      ],
    },
  },
  {
    en: {
      slug: "peruvian-lomo-saltado",
      title: "Peruvian Lomo Saltado",
      description:
        "Beef seared hard and fast over high heat, stir-fried with garlic, aji amarillo paste, and tomatoes, then tossed with crispy fries right in the wok - aji amarillo is the ingredient that gives lomo saltado its authentic flavor, and real high heat is what keeps the beef from steaming gray.",
      imageEmoji: "🥩",
      cookTimeMinutes: 35,
      servings: 4,
      ingredients: [
        { text: "1 lb sirloin steak, sliced thin", ingredient: "sirloin steak", quantity: 1 },
        { text: "1 tsp cumin", ingredient: "cumin", quantity: 1 },
        { text: "Salt and pepper to taste", ingredient: "salt", quantity: null },
        { text: "2 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 2 },
        { text: "1 onion, sliced", ingredient: "onion", quantity: 1 },
        { text: "3 cloves garlic, minced", ingredient: "garlic", quantity: 3 },
        { text: "1 tbsp aji amarillo paste", ingredient: "aji amarillo paste", quantity: 1 },
        { text: "2 tomatoes, sliced into wedges", ingredient: "tomato", quantity: 2 },
        { text: "3 tbsp soy sauce", ingredient: "soy sauce", quantity: 3 },
        { text: "1 tbsp red wine vinegar", ingredient: "red wine vinegar", quantity: 1 },
        { text: "1 tsp sugar", ingredient: "sugar", quantity: 1 },
        { text: "3 cups frozen fries, cooked until crispy", ingredient: "fries", quantity: 3 },
        { text: "2 tbsp chopped cilantro, for garnish", ingredient: "cilantro", quantity: 2 },
      ],
      steps: [
        "Season the beef with cumin, salt, and pepper.",
        "Heat the oil in a wok or large skillet over high heat until nearly smoking, then sear the beef undisturbed for 1-2 minutes to develop a deep crust; toss briefly and set aside - real high heat is what keeps the beef from steaming gray instead of searing.",
        "Add the onion and stir-fry for 1-2 minutes, then add the garlic and aji amarillo paste and cook for 30 seconds until fragrant.",
        "Add the tomatoes and cook briefly, about 1 minute, until just starting to soften but still holding their shape.",
        "Return the beef to the pan with the soy sauce, vinegar, and sugar, tossing to combine.",
        "Add the hot, crispy fries directly to the pan and toss gently so some absorb the sauce while others stay crisp.",
        "Garnish with cilantro and serve immediately.",
      ],
      tags: ["dinner", "quick"],
    },
    bg: {
      title: "Перуанско Ломо Салтадо",
      description:
        "Телешко месо, запечено бързо и силно на висок огън, задушено с чесън, паста ахи амарильо и домати, после разбъркано с хрупкав пържен картоф направо в тигана - ахи амарильо е съставката, която придава на ломо салтадо автентичния му вкус, а истинският висок огън е това, което пази месото да не се задуши сиво.",
      steps: [
        "Подправете месото с кимион, сол и черен пипер.",
        "Загрейте олиото в уок или голям тиган на силен огън, почти до димене, после запечете месото неподвижно 1-2 минути за дълбока коричка; разбъркайте набързо и отделете настрани - истинският висок огън е това, което пази месото да не се задуши сиво, вместо да се запече.",
        "Добавете лука и задушавайте 1-2 минути, после добавете чесъна и пастата ахи амарильо и гответе 30 секунди до ароматизиране.",
        "Добавете доматите и гответе за кратко, около 1 минута, докато леко омекнат, но запазят формата си.",
        "Върнете месото в тигана със соевия сос, оцета и захарта, разбърквайки за съединяване.",
        "Добавете горещия, хрупкав пържен картоф директно в тигана и разбъркайте леко, така че част да попие соса, а част да остане хрупкава.",
        "Гарнирайте с кориандър и сервирайте веднага.",
      ],
      ingredients: [
        "450 г филе стек, нарязан на тънко",
        "1 ч.л. кимион",
        "Сол и черен пипер на вкус",
        "2 с.л. олио",
        "1 лук, нарязан на резени",
        "3 скилидки чесън, ситно нарязани",
        "1 с.л. паста ахи амарильо",
        "2 домата, нарязани на резени",
        "3 с.л. соев сос",
        "1 с.л. червен винен оцет",
        "1 ч.л. захар",
        "3 чаши замразени пържени картофи, изпечени до хрупкавост",
        "2 с.л. нарязан кориандър, за гарниране",
      ],
    },
  },
];

applyRecipeUpdates(updates).catch((err) => {
  console.error(err);
  process.exit(1);
});
