import { applyRecipeUpdates } from "./update-lib.mjs";

const updates = [
  {
    en: {
      slug: "beef-pho",
      title: "Beef Pho",
      description:
        "A fragrant Vietnamese noodle soup of thin-sliced beef in a broth built on charred onion and ginger and toasted whole spices, finished with the classic herb and lime garnish plate.",
      imageEmoji: "🍜",
      cookTimeMinutes: 55,
      servings: 4,
      ingredients: [
        { text: "8 cups beef broth", ingredient: "beef broth", quantity: 8 },
        { text: "1 onion, halved", ingredient: "onion", quantity: 1 },
        { text: "3 inch piece ginger, halved lengthwise", ingredient: "ginger", quantity: 1 },
        { text: "1 cinnamon stick", ingredient: "cinnamon stick", quantity: 1 },
        { text: "2 star anise", ingredient: "star anise", quantity: 2 },
        { text: "1 tsp coriander seeds", ingredient: "coriander seeds", quantity: 1 },
        { text: "3 whole cloves", ingredient: "cloves", quantity: 3 },
        { text: "1 tbsp fish sauce", ingredient: "fish sauce", quantity: 1 },
        { text: "1 tbsp sugar (or rock sugar)", ingredient: "sugar", quantity: 1 },
        { text: "1 lb beef sirloin, sliced thin", ingredient: "beef sirloin", quantity: 1 },
        { text: "8 oz rice noodles", ingredient: "rice noodles", quantity: 8 },
        { text: "2 cups bean sprouts", ingredient: "bean sprouts", quantity: 2 },
        { text: "1 cup Thai basil leaves", ingredient: "thai basil", quantity: 1 },
        { text: "1 lime, cut into wedges", ingredient: "lime", quantity: 1 },
        { text: "Sliced jalapeño and hoisin/sriracha, for serving", ingredient: "jalapeno", quantity: null },
      ],
      steps: [
        "Char the onion and ginger halves directly over a gas flame or under a broiler until blackened in spots, about 3-4 minutes per side, then rinse off any loose char.",
        "Toast the cinnamon stick, star anise, coriander seeds, and cloves in a dry pot for 2-3 minutes until fragrant.",
        "Add the beef broth, charred onion and ginger, fish sauce, and sugar; simmer for 20-30 minutes to infuse, then strain and keep hot.",
        "Cook the rice noodles according to package instructions and divide among bowls, then top with the raw sliced beef and ladle the hot broth over to cook it through.",
        "Serve with bean sprouts, Thai basil, lime wedges, jalapeño, hoisin, and sriracha on the side for each diner to add to taste.",
      ],
      tags: ["dinner", "asian"],
    },
    bg: {
      title: "Говежда Фо",
      description:
        "Ароматна виетнамска супа с юфка и тънко нарязано телешко месо в бульон, изграден върху овъглени лук и джинджифил и препечени цели подправки, довършена с класическата чиния билки и лайм.",
      steps: [
        "Овъглете половинките лук и джинджифил директно над газов пламък или под грил, докато почернеят на места, около 3-4 минути от всяка страна, после изплакнете хлабавите овъглени части.",
        "Препечете пръчката канела, звездовидния анасон, семената кориандър и карамфила в суха тенджера 2-3 минути до ароматизиране.",
        "Добавете телешкия бульон, овъглените лук и джинджифил, рибния сос и захарта; варете 20-30 минути, за да се ароматизира, после прецедете и дръжте горещо.",
        "Сварете оризовата юфка според инструкциите на опаковката и разпределете в купи, после отгоре сложете суровото нарязано телешко месо и залейте с горещия бульон, за да се сготви.",
        "Сервирайте с кълнове от боб, тайландски босилек, резенчета лайм, халапеньо, хоисин сос и шрирача отстрани, за да си доподправят гостите.",
      ],
      ingredients: [
        "8 чаши телешки бульон",
        "1 лук, разрязан наполовина",
        "8 см джинджифил, разрязан по дължина наполовина",
        "1 пръчка канела",
        "2 звездовиден анасон",
        "1 ч.л. семена кориандър",
        "3 цели карамфила",
        "1 с.л. рибен сос",
        "1 с.л. захар (или каменна захар)",
        "450 г телешко филе, нарязано на тънко",
        "225 г оризова юфка",
        "2 чаши кълнове от боб",
        "1 чаша листа тайландски босилек",
        "1 лайм, нарязан на резенчета",
        "Нарязано халапеньо и хоисин сос/шрирача, за сервиране",
      ],
    },
  },
  {
    en: {
      slug: "banh-mi",
      title: "Banh Mi",
      description:
        "A Vietnamese sandwich of crusty baguette spread with pâté and mayonnaise, filled with lemongrass pork, quick-pickled carrot and daikon, cucumber, jalapeño, and cilantro.",
      imageEmoji: "🥖",
      cookTimeMinutes: 45,
      servings: 4,
      ingredients: [
        { text: "1 lb pork tenderloin, sliced thin", ingredient: "pork tenderloin", quantity: 1 },
        { text: "2 tbsp fish sauce", ingredient: "fish sauce", quantity: 2 },
        { text: "1 tbsp lemongrass, minced (or 1 tsp lemongrass paste)", ingredient: "lemongrass", quantity: 1 },
        { text: "2 cloves garlic, minced", ingredient: "garlic", quantity: 2 },
        { text: "1 tbsp sugar", ingredient: "sugar", quantity: 1 },
        { text: "1 carrot, julienned", ingredient: "carrot", quantity: 1 },
        { text: "1 small daikon radish, julienned", ingredient: "daikon", quantity: 1 },
        { text: "1/2 cup rice vinegar", ingredient: "rice vinegar", quantity: 0.5 },
        { text: "1/2 cup water", ingredient: "water", quantity: 0.5 },
        { text: "2 tbsp sugar (for pickling)", ingredient: "sugar", quantity: 2 },
        { text: "1/2 tsp salt", ingredient: "salt", quantity: 0.5 },
        { text: "2 baguettes, halved", ingredient: "baguette", quantity: 2 },
        { text: "1/4 cup pâté", ingredient: "pate", quantity: 0.25 },
        { text: "1/4 cup mayonnaise", ingredient: "mayonnaise", quantity: 0.25 },
        { text: "1/2 cucumber, thinly sliced", ingredient: "cucumber", quantity: 0.5 },
        { text: "1 jalapeño, sliced", ingredient: "jalapeno", quantity: 1 },
        { text: "1/4 cup fresh cilantro", ingredient: "cilantro", quantity: 0.25 },
      ],
      steps: [
        "Combine the sliced carrot and daikon; bring the rice vinegar, water, 2 tbsp sugar, and salt to a boil, pour over the vegetables, and let cool - these can be used after 1 hour or left to mellow overnight.",
        "Marinate the pork in fish sauce, lemongrass, garlic, and 1 tbsp sugar for at least 30 minutes, then cook in a hot skillet until browned and cooked through.",
        "Spread pâté on one side of the baguettes and mayonnaise on the other.",
        "Layer in the pork, pickled carrot and daikon, cucumber, jalapeño, and cilantro, then slice and serve.",
      ],
      tags: ["lunch", "asian", "quick"],
    },
    bg: {
      title: "Бан Ми",
      description:
        "Виетнамски сандвич от хрупкава багета, намазана с пастет и майонеза, пълнена със свинско месо в лимонова трева, бързо кисели моркови и дайкон, краставица, халапеньо и кориандър.",
      steps: [
        "Смесете нарязания морков и дайкон; заврете оризовия оцет, водата, 2-те с.л. захар и солта, залейте зеленчуците и оставете да изстинат - могат да се използват след 1 час или да престоят през нощта за по-мек вкус.",
        "Маринова свинското месо в рибен сос, лимонова трева, чесън и 1 с.л. захар поне 30 минути, после изпечете в горещ тиган до запържване и готовност.",
        "Намажете пастет от едната страна на багетите и майонеза от другата.",
        "Наредете свинското месо, киселите моркови и дайкон, краставицата, халапеньото и кориандъра, после нарежете и сервирайте.",
      ],
      ingredients: [
        "450 г свинско филе, нарязано на тънко",
        "2 с.л. рибен сос",
        "1 с.л. лимонова трева, ситно нарязана (или 1 ч.л. паста от лимонова трева)",
        "2 скилидки чесън, ситно нарязани",
        "1 с.л. захар",
        "1 морков, нарязан на тънки ивици",
        "1 малък дайкон, нарязан на тънки ивици",
        "1/2 чаша оризов оцет",
        "1/2 чаша вода",
        "2 с.л. захар (за марината от зеленчуци)",
        "1/2 ч.л. сол",
        "2 багети, разрязани наполовина",
        "1/4 чаша пастет",
        "1/4 чаша майонеза",
        "1/2 краставица, нарязана на тънки резени",
        "1 халапеньо, нарязано на резенчета",
        "1/4 чаша пресен кориандър",
      ],
    },
  },
  {
    en: {
      slug: "chicken-katsu",
      title: "Chicken Katsu",
      description:
        "Crispy panko-breaded chicken cutlets, fried until golden, served with homemade tonkatsu sauce over finely shredded cabbage and rice - the classic Japanese way.",
      imageEmoji: "🍗",
      cookTimeMinutes: 35,
      servings: 4,
      ingredients: [
        { text: "4 chicken thighs, pounded to 1/2 inch thick", ingredient: "chicken thighs", quantity: 4 },
        { text: "Salt and pepper, for seasoning", ingredient: "salt", quantity: null },
        { text: "1/2 cup flour, plus 1 tbsp for the egg wash", ingredient: "flour", quantity: 0.5 },
        { text: "2 eggs, beaten", ingredient: "eggs", quantity: 2 },
        { text: "2 cups panko breadcrumbs", ingredient: "panko breadcrumbs", quantity: 2 },
        { text: "1 cup vegetable oil for frying", ingredient: "vegetable oil", quantity: 1 },
        { text: "1/4 cup ketchup", ingredient: "ketchup", quantity: 0.25 },
        { text: "2 tbsp Worcestershire sauce", ingredient: "worcestershire sauce", quantity: 2 },
        { text: "1 tbsp oyster sauce", ingredient: "oyster sauce", quantity: 1 },
        { text: "1 tbsp sugar", ingredient: "sugar", quantity: 1 },
        { text: "2 cups finely shredded cabbage", ingredient: "cabbage", quantity: 2 },
        { text: "Steamed rice, for serving", ingredient: "rice", quantity: null },
      ],
      steps: [
        "Season the chicken with salt and pepper, then dredge in flour, then the egg beaten with 1 tbsp flour, then panko, pressing to adhere.",
        "Heat oil to 350°F and fry the chicken for 1.5-3 minutes per side until golden brown and cooked through; drain on paper towels and slice into strips.",
        "Whisk together the ketchup, Worcestershire sauce, oyster sauce, and sugar to make the tonkatsu sauce.",
        "Serve the sliced katsu over finely shredded cabbage and rice, drizzled with the tonkatsu sauce.",
      ],
      tags: ["dinner", "asian"],
    },
    bg: {
      title: "Пиле Кацу",
      description:
        "Хрупкави пилешки котлети в панко панировка, изпържени до златисто, поднесени с домашен сос тонкацу върху фино настъргано зеле и ориз - класическият японски начин.",
      steps: [
        "Подправете пилето със сол и черен пипер, после овалайте в брашно, после в яйцето, разбито с 1 с.л. брашно, после в панкото, притискайки да залепне.",
        "Загрейте олиото на 175°C и изпържете пилето по 1.5-3 минути от всяка страна до златисто и готовност; отцедете върху кухненска хартия и нарежете на ивици.",
        "Разбийте кетчупа, соса Уорчестър, стридения сос и захарта, за да направите соса тонкацу.",
        "Сервирайте нарязаното кацу върху фино настъргано зеле и ориз, полети със соса тонкацу.",
      ],
      ingredients: [
        "4 пилешки бутчета, изтупани до 1.5 см дебелина",
        "Сол и черен пипер, за подправяне",
        "1/2 чаша брашно, плюс 1 с.л. за яйчената смес",
        "2 разбити яйца",
        "2 чаши панко галета",
        "1 чаша олио за пържене",
        "1/4 чаша кетчуп",
        "2 с.л. сос Уорчестър",
        "1 с.л. стриден сос",
        "1 с.л. захар",
        "2 чаши фино настъргано зеле",
        "Сготвен ориз, за сервиране",
      ],
    },
  },
];

applyRecipeUpdates(updates).catch((err) => {
  console.error(err);
  process.exit(1);
});
