import { applyRecipeUpdates } from "./update-lib.mjs";

const updates = [
  {
    en: {
      slug: "aloo-gobi",
      title: "Aloo Gobi",
      description:
        "Potatoes and cauliflower pan-fried until spotted brown, then simmered in a ginger-garlic-tomato masala with a full spice blend - the base masala and browning the vegetables first are what separate real aloo gobi from plain spiced vegetables.",
      imageEmoji: "🥔",
      cookTimeMinutes: 45,
      servings: 4,
      ingredients: [
        { text: "3 potatoes, cubed", ingredient: "potato", quantity: 3 },
        { text: "1 head cauliflower, cut into florets", ingredient: "cauliflower", quantity: 1 },
        { text: "3 tbsp vegetable oil (divided)", ingredient: "vegetable oil", quantity: 3 },
        { text: "1 tsp cumin seeds", ingredient: "cumin", quantity: 1 },
        { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
        { text: "1 tbsp grated ginger", ingredient: "ginger", quantity: 1 },
        { text: "3 cloves garlic, minced", ingredient: "garlic", quantity: 3 },
        { text: "1-2 green chilies, minced", ingredient: "green chili", quantity: 1 },
        { text: "2 tomatoes, diced", ingredient: "tomato", quantity: 2 },
        { text: "1 tsp turmeric", ingredient: "turmeric", quantity: 1 },
        { text: "1 tsp coriander powder", ingredient: "coriander", quantity: 1 },
        { text: "1/2 tsp red chili powder", ingredient: "chili powder", quantity: 0.5 },
        { text: "1/2 tsp amchur (dried mango powder, optional)", ingredient: "amchur", quantity: 0.5 },
        { text: "Salt to taste", ingredient: "salt", quantity: null },
        { text: "2 tbsp chopped cilantro, for garnish", ingredient: "cilantro", quantity: 2 },
      ],
      steps: [
        "Heat half the oil in a wide pan and pan-fry the potatoes and cauliflower separately until spotted brown on the edges, about 5-6 minutes each; set aside - browning them first, rather than steaming, keeps them from turning soggy.",
        "Heat the remaining oil and sizzle the cumin seeds until fragrant, then add the onion and cook until translucent.",
        "Add the ginger, garlic, and green chilies and cook for 1-2 minutes until the raw smell fades, then add the tomatoes and cook until soft and pulpy.",
        "Stir in the turmeric, coriander powder, chili powder, and amchur and cook until fragrant.",
        "Add the browned potatoes and cauliflower with a splash of water, cover, and cook over low heat for 12-15 minutes until tender.",
        "Season with salt, garnish with cilantro, and serve.",
      ],
      tags: ["dinner", "vegan", "vegetarian"],
    },
    bg: {
      title: "Алу Гоби",
      description:
        "Картофи и карфиол, запържени до леко покафеняване, после задушени в масала от джинджифил, чесън и домат с пълен набор подправки - основата масала и запържването на зеленчуците първо е това, което отличава истинското алу гоби от обикновено подправени зеленчуци.",
      steps: [
        "Запържете картофите и карфиола поотделно в половината от олиото до леко покафеняване по краищата, около 5-6 минути всеки; оставете настрана - запържването им първо, вместо задушаване на пара, ги пази да не станат кашести.",
        "Загрейте останалото олио и запържете семената кимион до ароматизиране, после добавете лука и гответе до прозрачност.",
        "Добавете джинджифила, чесъна и лютите чушки и гответе 1-2 минути, докато суровата им миризма изчезне, после добавете доматите и гответе до омекване и разпадане.",
        "Разбъркайте куркумата, млания кориандър, лютия пипер на прах и амчура и гответе до ароматизиране.",
        "Добавете запържените картофи и карфиол с малко вода, покрийте и гответе на слаб огън 12-15 минути до омекване.",
        "Подправете със сол, гарнирайте с кориандър и сервирайте.",
      ],
      ingredients: [
        "3 картофа, нарязани на кубчета",
        "1 глава карфиол, нарязана на съцветия",
        "3 с.л. олио (разделено)",
        "1 ч.л. семена кимион",
        "1 лук, нарязан на кубчета",
        "1 с.л. настърган джинджифил",
        "3 скилидки чесън, ситно нарязани",
        "1-2 люти чушки, ситно нарязани",
        "2 домата, нарязани на кубчета",
        "1 ч.л. куркума",
        "1 ч.л. млян кориандър",
        "1/2 ч.л. лют пипер на прах",
        "1/2 ч.л. амчур (прах от сушено манго, по желание)",
        "Сол на вкус",
        "2 с.л. нарязан кориандър, за гарниране",
      ],
    },
  },
  {
    en: {
      slug: "saag-aloo",
      title: "Saag Aloo",
      description:
        "Par-boiled potatoes and blanched spinach simmered into a ginger-garlic base seasoned with a full spice blend - the blanch-and-shock step is what keeps the spinach vivid green instead of dull.",
      imageEmoji: "🥔",
      cookTimeMinutes: 40,
      servings: 4,
      ingredients: [
        { text: "3 potatoes, cubed", ingredient: "potato", quantity: 3 },
        { text: "1 lb spinach", ingredient: "spinach", quantity: 1 },
        { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
        { text: "3 cloves garlic, minced", ingredient: "garlic", quantity: 3 },
        { text: "1 tbsp grated ginger", ingredient: "ginger", quantity: 1 },
        { text: "1-2 green chilies, minced", ingredient: "green chili", quantity: 1 },
        { text: "1 tsp cumin seeds", ingredient: "cumin", quantity: 1 },
        { text: "1/2 tsp turmeric", ingredient: "turmeric", quantity: 0.5 },
        { text: "1/2 tsp chili powder", ingredient: "chili powder", quantity: 0.5 },
        { text: "1 tsp coriander powder", ingredient: "coriander", quantity: 1 },
        { text: "1/2 tsp garam masala", ingredient: "garam masala", quantity: 0.5 },
        { text: "3 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 3 },
        { text: "Salt to taste", ingredient: "salt", quantity: null },
      ],
      steps: [
        "Boil the potatoes until just tender (about 70% done), then drain and let cool slightly.",
        "Blanch the spinach in boiling water for 1-2 minutes, then plunge into ice water to stop the cooking and lock in its color; drain, squeeze out the excess water, and roughly chop.",
        "Sizzle the cumin seeds in oil, then add the onion and cook until translucent.",
        "Add the ginger, garlic, and green chilies and cook until the raw smell fades, then stir in the turmeric, chili powder, and coriander powder.",
        "Add the potatoes and blanched spinach, tossing to coat in the spices, and cook for 5 minutes until well combined.",
        "Stir in the garam masala, season with salt, and serve.",
      ],
      tags: ["dinner", "vegan", "vegetarian"],
    },
    bg: {
      title: "Саг Алу",
      description:
        "Полу-сварени картофи и бланширан спанак, задушени в основа от джинджифил и чесън, подправена с пълен набор подправки - бланширането и шоковото охлаждане е това, което пази спанака ярко зелен, а не тъмен.",
      steps: [
        "Сварете картофите до почти омекване (около 70% готови), после отцедете и оставете да поизстинат.",
        "Бланширайте спанака във вряла вода за 1-2 минути, после го потопете в ледена вода, за да спре готвенето и да запази цвета си; отцедете, изстискайте излишната вода и нарежете едро.",
        "Запържете семената кимион в олио, после добавете лука и гответе до прозрачност.",
        "Добавете джинджифила, чесъна и лютите чушки и гответе, докато суровата им миризма изчезне, после разбъркайте куркумата, лютия пипер на прах и млания кориандър.",
        "Добавете картофите и бланширания спанак, разбърквайки, за да се покрият с подправките, и гответе 5 минути до добро съединяване.",
        "Разбъркайте гарам масалата, подправете със сол и сервирайте.",
      ],
      ingredients: [
        "3 картофа, нарязани на кубчета",
        "450 г спанак",
        "1 лук, нарязан на кубчета",
        "3 скилидки чесън, ситно нарязани",
        "1 с.л. настърган джинджифил",
        "1-2 люти чушки, ситно нарязани",
        "1 ч.л. семена кимион",
        "1/2 ч.л. куркума",
        "1/2 ч.л. лют пипер на прах",
        "1 ч.л. млян кориандър",
        "1/2 ч.л. гарам масала",
        "3 с.л. олио",
        "Сол на вкус",
      ],
    },
  },
  {
    en: {
      slug: "rajma",
      title: "Rajma",
      description:
        "Red kidney beans simmered in a ginger-garlic tomato masala built on a full spice blend - classic North Indian comfort food, traditionally served over rice as rajma chawal.",
      imageEmoji: "🫘",
      cookTimeMinutes: 45,
      servings: 4,
      ingredients: [
        { text: "2 cans kidney beans, drained", ingredient: "kidney beans", quantity: 2 },
        { text: "3 tbsp vegetable oil (or ghee for a richer, traditional finish)", ingredient: "vegetable oil", quantity: 3 },
        { text: "1 tsp cumin seeds", ingredient: "cumin", quantity: 1 },
        { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
        { text: "1 tbsp grated ginger", ingredient: "ginger", quantity: 1 },
        { text: "3 cloves garlic, minced", ingredient: "garlic", quantity: 3 },
        { text: "1-2 green chilies, minced", ingredient: "green chili", quantity: 1 },
        { text: "1 can crushed tomatoes", ingredient: "tomato", quantity: 1 },
        { text: "1 tsp coriander powder", ingredient: "coriander", quantity: 1 },
        { text: "1/2 tsp turmeric", ingredient: "turmeric", quantity: 0.5 },
        { text: "1/2 tsp Kashmiri chili powder", ingredient: "chili powder", quantity: 0.5 },
        { text: "1 tsp garam masala", ingredient: "garam masala", quantity: 1 },
        { text: "Salt to taste", ingredient: "salt", quantity: null },
        { text: "2 tbsp chopped cilantro, for garnish", ingredient: "cilantro", quantity: 2 },
      ],
      steps: [
        "Heat the oil (or ghee) in a pot and sizzle the cumin seeds until fragrant.",
        "Add the onion and cook until softened, then add the ginger, garlic, and green chilies and cook for 1-2 minutes until the raw smell fades.",
        "Stir in the crushed tomatoes, coriander powder, turmeric, and chili powder, and simmer for 10 minutes until the masala thickens and the oil starts to separate at the edges.",
        "Add the kidney beans and a splash of water, then simmer for 20 minutes, mashing a few beans against the side of the pot to help thicken the sauce.",
        "Stir in the garam masala, season with salt, and garnish with cilantro before serving over rice.",
      ],
      tags: ["dinner", "vegan", "vegetarian"],
    },
    bg: {
      title: "Раджма",
      description:
        "Червен боб, задушен в масала от джинджифил, чесън и домат с пълен набор подправки - класическа северноиндийска уютна храна, традиционно поднасяна върху ориз като раджма чавал.",
      steps: [
        "Загрейте олиото (или гхи) в тенджера и запържете семената кимион до ароматизиране.",
        "Добавете лука и гответе до омекване, после добавете джинджифила, чесъна и лютите чушки и гответе 1-2 минути, докато суровата им миризма изчезне.",
        "Разбъркайте пасираните домати, млания кориандър, куркумата и лютия пипер на прах, и оставете да къкри 10 минути, докато масалата се сгъсти и олиото започне да се отделя по краищата.",
        "Добавете боба и малко вода, после варете 20 минути, намачквайки няколко зърна о стената на тенджерата, за да помогнете за сгъстяването на соса.",
        "Разбъркайте гарам масалата, подправете със сол и гарнирайте с кориандър преди сервиране върху ориз.",
      ],
      ingredients: [
        "2 консерви червен боб, отцеден",
        "3 с.л. олио (или гхи за по-богат, традиционен вкус)",
        "1 ч.л. семена кимион",
        "1 лук, нарязан на кубчета",
        "1 с.л. настърган джинджифил",
        "3 скилидки чесън, ситно нарязани",
        "1-2 люти чушки, ситно нарязани",
        "1 консерва пасирани домати",
        "1 ч.л. млян кориандър",
        "1/2 ч.л. куркума",
        "1/2 ч.л. лют пипер кашмири на прах",
        "1 ч.л. гарам масала",
        "Сол на вкус",
        "2 с.л. нарязан кориандър, за гарниране",
      ],
    },
  },
];

applyRecipeUpdates(updates).catch((err) => {
  console.error(err);
  process.exit(1);
});
