import { PrismaClient } from "@prisma/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import { PrismaLibSql } from "@prisma/adapter-libsql";
import "dotenv/config";

const databaseUrl = process.env.DATABASE_URL ?? "file:./dev.db";
const adapter = databaseUrl.startsWith("libsql:")
  ? new PrismaLibSql({ url: databaseUrl, authToken: process.env.TURSO_AUTH_TOKEN })
  : new PrismaBetterSqlite3({ url: databaseUrl });
const prisma = new PrismaClient({ adapter });

// Each ingredient line pairs the exact display text (shown on the recipe
// page as-is), a canonical ingredient name (what "what can I cook with X"
// search matches against), and a parsed quantity (null when the line has no
// clean numeric amount, e.g. "Salt to taste") used to rank search matches by
// how much of that ingredient a recipe actually uses.
const recipes = [
  {
    slug: "classic-margherita-pizza",
    title: "Classic Margherita Pizza",
    description:
      "A simple, ingredient-driven pizza with fresh mozzarella, basil, and a bright tomato sauce.",
    imageEmoji: "🍕",
    cookTimeMinutes: 25,
    servings: 4,
    ingredients: [
      { text: "1 pizza dough ball", ingredient: "pizza dough", quantity: 1 },
      { text: "1/2 cup crushed San Marzano tomatoes", ingredient: "tomato", quantity: 0.5 },
      { text: "8 oz fresh mozzarella, torn", ingredient: "mozzarella", quantity: 8 },
      { text: "Fresh basil leaves", ingredient: "basil", quantity: null },
      { text: "2 tbsp olive oil", ingredient: "olive oil", quantity: 2 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
    ],
    steps: [
      "Preheat oven (with a pizza stone if you have one) to 500°F / 260°C.",
      "Stretch the dough into a 12-inch round on a floured surface.",
      "Spread the crushed tomatoes evenly, leaving a border for the crust.",
      "Scatter torn mozzarella over the sauce.",
      "Bake for 8-10 minutes until the crust is golden and cheese is bubbling.",
      "Top with fresh basil and a drizzle of olive oil before serving.",
    ],
    tags: ["dinner", "vegetarian", "italian"],
  },
  {
    slug: "spicy-chickpea-curry",
    title: "Spicy Chickpea Curry",
    description:
      "A warming, one-pot chickpea curry in a spiced tomato-coconut sauce, ready in half an hour.",
    imageEmoji: "🍛",
    cookTimeMinutes: 30,
    servings: 4,
    ingredients: [
      { text: "2 cans chickpeas, drained", ingredient: "chickpeas", quantity: 2 },
      { text: "1 can coconut milk", ingredient: "coconut milk", quantity: 1 },
      { text: "1 can diced tomatoes", ingredient: "tomato", quantity: 1 },
      { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
      { text: "3 cloves garlic, minced", ingredient: "garlic", quantity: 3 },
      { text: "1 tbsp curry powder", ingredient: "curry powder", quantity: 1 },
      { text: "1 tsp chili flakes", ingredient: "chili flakes", quantity: 1 },
      { text: "2 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 2 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
    ],
    steps: [
      "Heat the oil in a large pot and sauté the onion until soft, about 5 minutes.",
      "Add garlic, curry powder, and chili flakes; cook for 1 minute until fragrant.",
      "Stir in the diced tomatoes and coconut milk, then bring to a simmer.",
      "Add the chickpeas and simmer for 15 minutes, stirring occasionally.",
      "Season with salt and serve over rice.",
    ],
    tags: ["dinner", "vegan", "quick"],
  },
  {
    slug: "chocolate-chip-cookies",
    title: "Chocolate Chip Cookies",
    description:
      "Chewy in the middle, crisp at the edges - a reliable everyday chocolate chip cookie.",
    imageEmoji: "🍪",
    cookTimeMinutes: 20,
    servings: 24,
    ingredients: [
      { text: "2 1/4 cups all-purpose flour", ingredient: "flour", quantity: 2.25 },
      { text: "1 tsp baking soda", ingredient: "baking soda", quantity: 1 },
      { text: "1 tsp salt", ingredient: "salt", quantity: 1 },
      { text: "1 cup butter, softened", ingredient: "butter", quantity: 1 },
      { text: "3/4 cup granulated sugar", ingredient: "sugar", quantity: 0.75 },
      { text: "3/4 cup brown sugar", ingredient: "brown sugar", quantity: 0.75 },
      { text: "2 large eggs", ingredient: "eggs", quantity: 2 },
      { text: "2 tsp vanilla extract", ingredient: "vanilla extract", quantity: 2 },
      { text: "2 cups chocolate chips", ingredient: "chocolate chips", quantity: 2 },
    ],
    steps: [
      "Preheat oven to 375°F / 190°C.",
      "Whisk together flour, baking soda, and salt in a bowl.",
      "Cream the butter and both sugars until light and fluffy.",
      "Beat in the eggs and vanilla.",
      "Mix in the dry ingredients until just combined, then fold in chocolate chips.",
      "Drop rounded tablespoons of dough onto a baking sheet and bake for 9-11 minutes.",
    ],
    tags: ["dessert", "baking", "vegetarian"],
  },
  {
    slug: "avocado-toast",
    title: "Avocado Toast",
    description: "A fast, satisfying breakfast: mashed avocado on toasted sourdough with chili flakes.",
    imageEmoji: "🥑",
    cookTimeMinutes: 10,
    servings: 1,
    ingredients: [
      { text: "2 slices sourdough bread", ingredient: "sourdough bread", quantity: 2 },
      { text: "1 ripe avocado", ingredient: "avocado", quantity: 1 },
      { text: "1/2 lemon, juiced", ingredient: "lemon", quantity: 0.5 },
      { text: "Chili flakes", ingredient: "chili flakes", quantity: null },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "Pepper to taste", ingredient: "pepper", quantity: null },
      { text: "Olive oil for drizzling", ingredient: "olive oil", quantity: null },
    ],
    steps: [
      "Toast the sourdough slices until golden and crisp.",
      "Mash the avocado with lemon juice, salt, and pepper.",
      "Spread the mashed avocado over the toast.",
      "Top with chili flakes and a drizzle of olive oil.",
    ],
    tags: ["breakfast", "vegetarian", "quick"],
  },
  {
    slug: "beef-tacos",
    title: "Beef Tacos",
    description: "Weeknight ground beef tacos with a quick homemade spice blend.",
    imageEmoji: "🌮",
    cookTimeMinutes: 20,
    servings: 4,
    ingredients: [
      { text: "1 lb ground beef", ingredient: "ground beef", quantity: 1 },
      { text: "8 small corn tortillas", ingredient: "corn tortillas", quantity: 8 },
      { text: "1 tbsp chili powder", ingredient: "chili powder", quantity: 1 },
      { text: "1 tsp cumin", ingredient: "cumin", quantity: 1 },
      { text: "1/2 tsp paprika", ingredient: "paprika", quantity: 0.5 },
      { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
      { text: "Shredded lettuce for topping", ingredient: "lettuce", quantity: null },
      { text: "Diced tomato for topping", ingredient: "tomato", quantity: null },
      { text: "Shredded cheese for topping", ingredient: "cheese", quantity: null },
    ],
    steps: [
      "Cook the diced onion in a pan over medium heat until softened.",
      "Add the ground beef and cook until browned, breaking it up as it cooks.",
      "Stir in chili powder, cumin, and paprika; cook for another 2 minutes.",
      "Warm the tortillas and fill with the beef mixture.",
      "Top with lettuce, tomato, and cheese.",
    ],
    tags: ["dinner", "quick"],
  },
  {
    slug: "fluffy-pancakes",
    title: "Fluffy Pancakes",
    description: "Classic fluffy buttermilk-style pancakes, ready for a stack of butter and maple syrup.",
    imageEmoji: "🥞",
    cookTimeMinutes: 20,
    servings: 4,
    ingredients: [
      { text: "1 1/2 cups all-purpose flour", ingredient: "flour", quantity: 1.5 },
      { text: "3 1/2 tsp baking powder", ingredient: "baking powder", quantity: 3.5 },
      { text: "1 tsp salt", ingredient: "salt", quantity: 1 },
      { text: "1 tbsp sugar", ingredient: "sugar", quantity: 1 },
      { text: "1 1/4 cups milk", ingredient: "milk", quantity: 1.25 },
      { text: "1 egg", ingredient: "eggs", quantity: 1 },
      { text: "3 tbsp melted butter", ingredient: "butter", quantity: 3 },
    ],
    steps: [
      "Whisk together flour, baking powder, salt, and sugar in a large bowl.",
      "In a separate bowl, whisk the milk, egg, and melted butter together.",
      "Pour the wet ingredients into the dry ingredients and stir until just combined - a few lumps are fine.",
      "Heat a lightly greased griddle over medium heat and pour 1/4 cup batter per pancake.",
      "Cook until bubbles form on the surface, then flip and cook until golden on the other side.",
    ],
    tags: ["breakfast", "quick", "vegetarian"],
  },
  {
    slug: "classic-french-toast",
    title: "Classic French Toast",
    description: "Thick slices of bread soaked in a cinnamon-vanilla custard and pan-fried until golden.",
    imageEmoji: "🍞",
    cookTimeMinutes: 15,
    servings: 4,
    ingredients: [
      { text: "4 thick slices brioche or challah bread", ingredient: "bread", quantity: 4 },
      { text: "2 eggs", ingredient: "eggs", quantity: 2 },
      { text: "1/2 cup milk", ingredient: "milk", quantity: 0.5 },
      { text: "1 tsp vanilla extract", ingredient: "vanilla extract", quantity: 1 },
      { text: "1/2 tsp cinnamon", ingredient: "cinnamon", quantity: 0.5 },
      { text: "1 tbsp butter for frying", ingredient: "butter", quantity: 1 },
    ],
    steps: [
      "Whisk the eggs, milk, vanilla, and cinnamon together in a shallow dish.",
      "Dip each bread slice into the custard, coating both sides well.",
      "Melt butter in a skillet over medium heat.",
      "Cook each slice for 2-3 minutes per side until golden brown.",
      "Serve warm with maple syrup and fresh fruit.",
    ],
    tags: ["breakfast", "quick", "vegetarian"],
  },
  {
    slug: "classic-omelette",
    title: "Classic Omelette",
    description: "A simple three-egg omelette folded around melted cheese - a fast, protein-packed breakfast.",
    imageEmoji: "🍳",
    cookTimeMinutes: 10,
    servings: 1,
    ingredients: [
      { text: "3 eggs", ingredient: "eggs", quantity: 3 },
      { text: "1 tbsp milk", ingredient: "milk", quantity: 1 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "Pepper to taste", ingredient: "pepper", quantity: null },
      { text: "1 tbsp butter", ingredient: "butter", quantity: 1 },
      { text: "1/4 cup shredded cheese", ingredient: "cheese", quantity: 0.25 },
    ],
    steps: [
      "Whisk the eggs with milk, salt, and pepper until fully combined.",
      "Melt the butter in a nonstick pan over medium heat.",
      "Pour in the eggs and let them set for 30 seconds, then gently push the edges toward the center.",
      "When mostly set, sprinkle cheese over one half and fold the omelette over.",
      "Slide onto a plate and serve immediately.",
    ],
    tags: ["breakfast", "quick", "vegetarian"],
  },
  {
    slug: "overnight-oats",
    title: "Overnight Oats",
    description: "No-cook oats soaked overnight in milk and yogurt - a make-ahead breakfast ready when you wake up.",
    imageEmoji: "🥣",
    cookTimeMinutes: 5,
    servings: 1,
    ingredients: [
      { text: "1/2 cup rolled oats", ingredient: "oats", quantity: 0.5 },
      { text: "1/2 cup milk", ingredient: "milk", quantity: 0.5 },
      { text: "1/4 cup yogurt", ingredient: "yogurt", quantity: 0.25 },
      { text: "1 tbsp honey", ingredient: "honey", quantity: 1 },
      { text: "1/2 cup fresh berries", ingredient: "berries", quantity: 0.5 },
    ],
    steps: [
      "Combine the oats, milk, yogurt, and honey in a jar or container.",
      "Stir well, cover, and refrigerate overnight.",
      "In the morning, give it a stir and top with fresh berries.",
    ],
    tags: ["breakfast", "quick", "vegetarian"],
  },
  {
    slug: "shakshuka",
    title: "Shakshuka",
    description: "Eggs poached in a spiced tomato and pepper sauce - a one-pan breakfast from North Africa and the Middle East.",
    imageEmoji: "🍅",
    cookTimeMinutes: 30,
    servings: 4,
    ingredients: [
      { text: "2 tbsp olive oil", ingredient: "olive oil", quantity: 2 },
      { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
      { text: "1 red bell pepper, diced", ingredient: "red pepper", quantity: 1 },
      { text: "3 cloves garlic, minced", ingredient: "garlic", quantity: 3 },
      { text: "1 tsp cumin", ingredient: "cumin", quantity: 1 },
      { text: "1 tsp paprika", ingredient: "paprika", quantity: 1 },
      { text: "1 can crushed tomatoes", ingredient: "tomato", quantity: 1 },
      { text: "6 eggs", ingredient: "eggs", quantity: 6 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
    ],
    steps: [
      "Heat olive oil in a large skillet and sauté the onion and red pepper until softened.",
      "Add garlic, cumin, and paprika; cook for 1 minute until fragrant.",
      "Pour in the crushed tomatoes and simmer for 10 minutes, seasoning with salt.",
      "Make small wells in the sauce and crack an egg into each one.",
      "Cover and cook for 5-8 minutes until the egg whites are set but yolks are still runny.",
    ],
    tags: ["breakfast", "vegetarian", "dinner"],
  },
  {
    slug: "minestrone-soup",
    title: "Minestrone Soup",
    description: "A hearty Italian vegetable soup with beans and pasta - a full pot of comfort in one bowl.",
    imageEmoji: "🍲",
    cookTimeMinutes: 45,
    servings: 6,
    ingredients: [
      { text: "2 tbsp olive oil", ingredient: "olive oil", quantity: 2 },
      { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
      { text: "2 carrots, diced", ingredient: "carrot", quantity: 2 },
      { text: "2 celery stalks, diced", ingredient: "celery", quantity: 2 },
      { text: "3 cloves garlic, minced", ingredient: "garlic", quantity: 3 },
      { text: "1 can diced tomatoes", ingredient: "tomato", quantity: 1 },
      { text: "1 can kidney beans, drained", ingredient: "kidney beans", quantity: 1 },
      { text: "4 cups vegetable broth", ingredient: "vegetable broth", quantity: 4 },
      { text: "1 cup small pasta (ditalini or elbow)", ingredient: "pasta", quantity: 1 },
      { text: "2 cups chopped kale", ingredient: "kale", quantity: 2 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "Pepper to taste", ingredient: "pepper", quantity: null },
    ],
    steps: [
      "Heat olive oil in a large pot and sauté onion, carrots, and celery until softened, about 8 minutes.",
      "Add garlic and cook for 1 minute.",
      "Stir in the diced tomatoes, kidney beans, and vegetable broth; bring to a boil.",
      "Add the pasta and simmer until al dente, about 10 minutes.",
      "Stir in the kale, season with salt and pepper, and cook until wilted.",
    ],
    tags: ["dinner", "vegetarian"],
  },
  {
    slug: "french-onion-soup",
    title: "French Onion Soup",
    description: "Sweet caramelized onions in a rich beef broth, topped with toasted bread and melted Gruyère.",
    imageEmoji: "🧅",
    cookTimeMinutes: 60,
    servings: 4,
    ingredients: [
      { text: "4 tbsp butter", ingredient: "butter", quantity: 4 },
      { text: "4 large onions, thinly sliced", ingredient: "onion", quantity: 4 },
      { text: "1 tsp sugar", ingredient: "sugar", quantity: 1 },
      { text: "2 tbsp flour", ingredient: "flour", quantity: 2 },
      { text: "6 cups beef broth", ingredient: "beef broth", quantity: 6 },
      { text: "4 slices baguette", ingredient: "baguette", quantity: 4 },
      { text: "1 cup shredded Gruyère cheese", ingredient: "gruyere cheese", quantity: 1 },
    ],
    steps: [
      "Melt butter in a large pot and add the sliced onions with sugar.",
      "Cook over low heat, stirring occasionally, until deeply caramelized, about 35-40 minutes.",
      "Sprinkle in the flour and cook for 2 minutes, then whisk in the beef broth.",
      "Simmer for 15 minutes, seasoning to taste.",
      "Ladle into oven-safe bowls, top with toasted baguette and cheese, and broil until bubbly.",
    ],
    tags: ["dinner", "french"],
  },
  {
    slug: "chicken-noodle-soup",
    title: "Chicken Noodle Soup",
    description: "A soothing classic - tender chicken and egg noodles in a savory homemade broth.",
    imageEmoji: "🍜",
    cookTimeMinutes: 45,
    servings: 6,
    ingredients: [
      { text: "1 tbsp olive oil", ingredient: "olive oil", quantity: 1 },
      { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
      { text: "2 carrots, sliced", ingredient: "carrot", quantity: 2 },
      { text: "2 celery stalks, sliced", ingredient: "celery", quantity: 2 },
      { text: "8 cups chicken broth", ingredient: "chicken broth", quantity: 8 },
      { text: "2 chicken breasts", ingredient: "chicken breast", quantity: 2 },
      { text: "2 cups egg noodles", ingredient: "egg noodles", quantity: 2 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "Pepper to taste", ingredient: "pepper", quantity: null },
    ],
    steps: [
      "Heat olive oil in a large pot and sauté onion, carrots, and celery until softened.",
      "Add the chicken broth and chicken breasts; bring to a boil, then reduce to a simmer.",
      "Cook until the chicken is cooked through, about 15 minutes, then remove and shred it.",
      "Return the shredded chicken to the pot and add the egg noodles.",
      "Simmer until the noodles are tender, then season with salt and pepper.",
    ],
    tags: ["dinner", "quick"],
  },
  {
    slug: "tomato-basil-soup",
    title: "Tomato Basil Soup",
    description: "A creamy, bright tomato soup finished with fresh basil - perfect alongside a grilled cheese.",
    imageEmoji: "🍅",
    cookTimeMinutes: 30,
    servings: 4,
    ingredients: [
      { text: "2 tbsp butter", ingredient: "butter", quantity: 2 },
      { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
      { text: "3 cloves garlic, minced", ingredient: "garlic", quantity: 3 },
      { text: "2 cans crushed tomatoes", ingredient: "tomato", quantity: 2 },
      { text: "2 cups vegetable broth", ingredient: "vegetable broth", quantity: 2 },
      { text: "1/2 cup heavy cream", ingredient: "heavy cream", quantity: 0.5 },
      { text: "1/4 cup fresh basil leaves", ingredient: "basil", quantity: 0.25 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "Pepper to taste", ingredient: "pepper", quantity: null },
    ],
    steps: [
      "Melt butter in a pot and sauté the onion until soft, about 5 minutes.",
      "Add garlic and cook for 1 minute.",
      "Stir in the crushed tomatoes and vegetable broth; simmer for 15 minutes.",
      "Blend the soup until smooth, then stir in the cream and basil.",
      "Season with salt and pepper before serving.",
    ],
    tags: ["dinner", "vegetarian", "quick"],
  },
  {
    slug: "caesar-salad",
    title: "Caesar Salad",
    description: "Crisp romaine tossed in a garlicky, creamy Caesar dressing with croutons and Parmesan.",
    imageEmoji: "🥗",
    cookTimeMinutes: 20,
    servings: 4,
    ingredients: [
      { text: "1 head romaine lettuce, chopped", ingredient: "romaine lettuce", quantity: 1 },
      { text: "1/2 cup grated Parmesan", ingredient: "parmesan", quantity: 0.5 },
      { text: "1 cup croutons", ingredient: "croutons", quantity: 1 },
      { text: "1/2 cup mayonnaise", ingredient: "mayonnaise", quantity: 0.5 },
      { text: "2 cloves garlic, minced", ingredient: "garlic", quantity: 2 },
      { text: "1 tbsp lemon juice", ingredient: "lemon juice", quantity: 1 },
      { text: "1 tsp Dijon mustard", ingredient: "dijon mustard", quantity: 1 },
    ],
    steps: [
      "Whisk together mayonnaise, garlic, lemon juice, and Dijon mustard to make the dressing.",
      "Toss the chopped romaine with the dressing until evenly coated.",
      "Top with croutons and grated Parmesan before serving.",
    ],
    tags: ["lunch", "quick", "salad"],
  },
  {
    slug: "greek-salad",
    title: "Greek Salad",
    description: "Cucumber, tomato, olives, and feta tossed with a simple olive oil and oregano dressing.",
    imageEmoji: "🥙",
    cookTimeMinutes: 15,
    servings: 4,
    ingredients: [
      { text: "3 tomatoes, chopped", ingredient: "tomato", quantity: 3 },
      { text: "1 cucumber, chopped", ingredient: "cucumber", quantity: 1 },
      { text: "1/2 red onion, thinly sliced", ingredient: "red onion", quantity: 0.5 },
      { text: "1/2 cup Kalamata olives", ingredient: "olives", quantity: 0.5 },
      { text: "1 cup crumbled feta cheese", ingredient: "feta cheese", quantity: 1 },
      { text: "3 tbsp olive oil", ingredient: "olive oil", quantity: 3 },
      { text: "1 tbsp red wine vinegar", ingredient: "red wine vinegar", quantity: 1 },
      { text: "1 tsp dried oregano", ingredient: "oregano", quantity: 1 },
    ],
    steps: [
      "Combine the tomatoes, cucumber, red onion, and olives in a large bowl.",
      "Whisk together the olive oil, red wine vinegar, and oregano.",
      "Pour the dressing over the vegetables and toss gently.",
      "Top with crumbled feta cheese before serving.",
    ],
    tags: ["lunch", "vegetarian", "quick", "salad", "mediterranean"],
  },
  {
    slug: "caprese-salad",
    title: "Caprese Salad",
    description: "Fresh mozzarella, ripe tomatoes, and basil drizzled with olive oil and balsamic glaze.",
    imageEmoji: "🍅",
    cookTimeMinutes: 10,
    servings: 4,
    ingredients: [
      { text: "3 large tomatoes, sliced", ingredient: "tomato", quantity: 3 },
      { text: "8 oz fresh mozzarella, sliced", ingredient: "mozzarella", quantity: 8 },
      { text: "1/4 cup fresh basil leaves", ingredient: "basil", quantity: 0.25 },
      { text: "3 tbsp olive oil", ingredient: "olive oil", quantity: 3 },
      { text: "2 tbsp balsamic glaze", ingredient: "balsamic glaze", quantity: 2 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "Pepper to taste", ingredient: "pepper", quantity: null },
    ],
    steps: [
      "Arrange alternating slices of tomato and mozzarella on a platter.",
      "Tuck basil leaves between the slices.",
      "Drizzle with olive oil and balsamic glaze.",
      "Season with salt and pepper before serving.",
    ],
    tags: ["lunch", "vegetarian", "quick", "salad", "italian"],
  },
  {
    slug: "spaghetti-carbonara",
    title: "Spaghetti Carbonara",
    description: "A Roman classic - spaghetti in a silky egg and Pecorino sauce with crispy pancetta.",
    imageEmoji: "🍝",
    cookTimeMinutes: 25,
    servings: 4,
    ingredients: [
      { text: "1 lb spaghetti", ingredient: "spaghetti", quantity: 1 },
      { text: "6 oz pancetta, diced", ingredient: "pancetta", quantity: 6 },
      { text: "3 eggs", ingredient: "eggs", quantity: 3 },
      { text: "1 cup grated Pecorino Romano", ingredient: "pecorino", quantity: 1 },
      { text: "2 cloves garlic, minced", ingredient: "garlic", quantity: 2 },
      { text: "Black pepper to taste", ingredient: "pepper", quantity: null },
    ],
    steps: [
      "Cook the spaghetti in salted boiling water until al dente; reserve 1 cup pasta water.",
      "Meanwhile, cook the pancetta in a skillet until crispy, then add garlic for 1 minute.",
      "Whisk the eggs and Pecorino together in a bowl.",
      "Drain the pasta and toss it with the pancetta off the heat, then quickly stir in the egg mixture, adding pasta water to loosen the sauce.",
      "Season generously with black pepper and serve immediately.",
    ],
    tags: ["dinner", "italian", "quick"],
  },
  {
    slug: "spaghetti-bolognese",
    title: "Spaghetti Bolognese",
    description: "A slow-simmered beef and tomato ragù tossed with spaghetti - Sunday dinner comfort food.",
    imageEmoji: "🍝",
    cookTimeMinutes: 90,
    servings: 6,
    ingredients: [
      { text: "2 tbsp olive oil", ingredient: "olive oil", quantity: 2 },
      { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
      { text: "2 carrots, diced", ingredient: "carrot", quantity: 2 },
      { text: "2 celery stalks, diced", ingredient: "celery", quantity: 2 },
      { text: "1 lb ground beef", ingredient: "ground beef", quantity: 1 },
      { text: "1 cup red wine", ingredient: "red wine", quantity: 1 },
      { text: "2 cans crushed tomatoes", ingredient: "tomato", quantity: 2 },
      { text: "1 lb spaghetti", ingredient: "spaghetti", quantity: 1 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "Pepper to taste", ingredient: "pepper", quantity: null },
    ],
    steps: [
      "Heat olive oil in a large pot and sauté onion, carrots, and celery until softened.",
      "Add the ground beef and cook until browned.",
      "Pour in the red wine and simmer until mostly evaporated.",
      "Stir in the crushed tomatoes and simmer, partially covered, for at least 1 hour.",
      "Cook the spaghetti separately, then toss with the sauce and season to taste.",
    ],
    tags: ["dinner", "italian"],
  },
  {
    slug: "fettuccine-alfredo",
    title: "Fettuccine Alfredo",
    description: "Fettuccine tossed in a rich butter and Parmesan sauce - simple, indulgent, and fast.",
    imageEmoji: "🍝",
    cookTimeMinutes: 20,
    servings: 4,
    ingredients: [
      { text: "1 lb fettuccine", ingredient: "fettuccine", quantity: 1 },
      { text: "1/2 cup butter", ingredient: "butter", quantity: 0.5 },
      { text: "1 cup heavy cream", ingredient: "heavy cream", quantity: 1 },
      { text: "1 1/2 cups grated Parmesan", ingredient: "parmesan", quantity: 1.5 },
      { text: "2 cloves garlic, minced", ingredient: "garlic", quantity: 2 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "Pepper to taste", ingredient: "pepper", quantity: null },
    ],
    steps: [
      "Cook the fettuccine in salted boiling water until al dente.",
      "Melt the butter in a large skillet and sauté the garlic for 1 minute.",
      "Pour in the heavy cream and simmer gently for 3-4 minutes.",
      "Whisk in the Parmesan until melted and smooth.",
      "Toss the drained pasta in the sauce until well coated, seasoning with salt and pepper.",
    ],
    tags: ["dinner", "italian", "quick", "vegetarian"],
  },
  {
    slug: "pesto-pasta",
    title: "Pesto Pasta",
    description: "Fresh basil pesto tossed with pasta - a bright, fast weeknight dinner.",
    imageEmoji: "🍝",
    cookTimeMinutes: 20,
    servings: 4,
    ingredients: [
      { text: "1 lb pasta", ingredient: "pasta", quantity: 1 },
      { text: "2 cups fresh basil leaves", ingredient: "basil", quantity: 2 },
      { text: "1/2 cup grated Parmesan", ingredient: "parmesan", quantity: 0.5 },
      { text: "1/2 cup pine nuts", ingredient: "pine nuts", quantity: 0.5 },
      { text: "2 cloves garlic", ingredient: "garlic", quantity: 2 },
      { text: "1/2 cup olive oil", ingredient: "olive oil", quantity: 0.5 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
    ],
    steps: [
      "Cook the pasta in salted boiling water until al dente.",
      "Blend the basil, Parmesan, pine nuts, and garlic in a food processor.",
      "With the processor running, slowly stream in the olive oil until smooth.",
      "Toss the drained pasta with the pesto until evenly coated.",
      "Season with salt and serve.",
    ],
    tags: ["dinner", "italian", "quick", "vegetarian"],
  },
  {
    slug: "classic-lasagna",
    title: "Classic Lasagna",
    description: "Layers of pasta, meat sauce, and creamy cheese baked until bubbling - a classic crowd-pleaser.",
    imageEmoji: "🍝",
    cookTimeMinutes: 90,
    servings: 8,
    ingredients: [
      { text: "1 lb ground beef", ingredient: "ground beef", quantity: 1 },
      { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
      { text: "3 cloves garlic, minced", ingredient: "garlic", quantity: 3 },
      { text: "1 jar marinara sauce", ingredient: "marinara sauce", quantity: 1 },
      { text: "12 lasagna noodles", ingredient: "lasagna noodles", quantity: 12 },
      { text: "2 cups ricotta cheese", ingredient: "ricotta cheese", quantity: 2 },
      { text: "1 egg", ingredient: "eggs", quantity: 1 },
      { text: "3 cups shredded mozzarella", ingredient: "mozzarella", quantity: 3 },
      { text: "1/2 cup grated Parmesan", ingredient: "parmesan", quantity: 0.5 },
    ],
    steps: [
      "Brown the ground beef with onion and garlic, then stir in the marinara sauce.",
      "Cook the lasagna noodles according to package instructions.",
      "Mix the ricotta with the egg and half the Parmesan.",
      "Layer noodles, meat sauce, ricotta mixture, and mozzarella in a baking dish, repeating twice more.",
      "Top with remaining mozzarella and Parmesan, then bake at 375°F for 35-40 minutes until bubbly.",
    ],
    tags: ["dinner", "italian"],
  },
  {
    slug: "classic-guacamole",
    title: "Classic Guacamole",
    description: "Ripe avocados mashed with lime, cilantro, and onion - the essential chip dip.",
    imageEmoji: "🥑",
    cookTimeMinutes: 10,
    servings: 4,
    ingredients: [
      { text: "3 ripe avocados", ingredient: "avocado", quantity: 3 },
      { text: "1 lime, juiced", ingredient: "lime", quantity: 1 },
      { text: "1/2 red onion, finely diced", ingredient: "red onion", quantity: 0.5 },
      { text: "1 tomato, diced", ingredient: "tomato", quantity: 1 },
      { text: "1/4 cup chopped cilantro", ingredient: "cilantro", quantity: 0.25 },
      { text: "1 jalapeño, minced", ingredient: "jalapeno", quantity: 1 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
    ],
    steps: [
      "Mash the avocados in a bowl to your preferred consistency.",
      "Stir in the lime juice, red onion, tomato, cilantro, and jalapeño.",
      "Season with salt to taste.",
      "Serve immediately with tortilla chips.",
    ],
    tags: ["snack", "vegan", "quick", "mexican"],
  },
  {
    slug: "chicken-quesadillas",
    title: "Chicken Quesadillas",
    description: "Crispy tortillas filled with melted cheese and seasoned chicken - a fast weeknight favorite.",
    imageEmoji: "🧀",
    cookTimeMinutes: 20,
    servings: 4,
    ingredients: [
      { text: "2 cups shredded cooked chicken", ingredient: "chicken", quantity: 2 },
      { text: "2 cups shredded cheddar cheese", ingredient: "cheddar cheese", quantity: 2 },
      { text: "1/2 onion, diced", ingredient: "onion", quantity: 0.5 },
      { text: "1/2 red pepper, diced", ingredient: "red pepper", quantity: 0.5 },
      { text: "8 flour tortillas", ingredient: "flour tortillas", quantity: 8 },
      { text: "1 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 1 },
    ],
    steps: [
      "Sauté the onion and red pepper until softened, then mix with the shredded chicken.",
      "Lay a tortilla flat, sprinkle cheese and the chicken mixture over half, then fold over.",
      "Heat oil in a skillet over medium heat and cook each quesadilla until golden and crispy, about 3 minutes per side.",
      "Slice into wedges and serve with salsa or sour cream.",
    ],
    tags: ["lunch", "quick", "mexican"],
  },
  {
    slug: "chili-con-carne",
    title: "Chili Con Carne",
    description: "A hearty, spiced beef and bean chili - simmered low and slow for deep flavor.",
    imageEmoji: "🌶️",
    cookTimeMinutes: 75,
    servings: 6,
    ingredients: [
      { text: "2 tbsp olive oil", ingredient: "olive oil", quantity: 2 },
      { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
      { text: "1 lb ground beef", ingredient: "ground beef", quantity: 1 },
      { text: "2 tbsp chili powder", ingredient: "chili powder", quantity: 2 },
      { text: "1 tsp cumin", ingredient: "cumin", quantity: 1 },
      { text: "2 cans kidney beans, drained", ingredient: "kidney beans", quantity: 2 },
      { text: "1 can crushed tomatoes", ingredient: "tomato", quantity: 1 },
      { text: "1 cup beef broth", ingredient: "beef broth", quantity: 1 },
    ],
    steps: [
      "Heat olive oil and sauté the onion until softened.",
      "Add the ground beef and cook until browned.",
      "Stir in the chili powder and cumin, cooking for 1 minute until fragrant.",
      "Add the kidney beans, crushed tomatoes, and beef broth.",
      "Simmer, uncovered, for at least 45 minutes, stirring occasionally.",
    ],
    tags: ["dinner", "mexican"],
  },
  {
    slug: "beef-enchiladas",
    title: "Beef Enchiladas",
    description: "Corn tortillas rolled around seasoned beef, smothered in enchilada sauce and cheese.",
    imageEmoji: "🌯",
    cookTimeMinutes: 45,
    servings: 6,
    ingredients: [
      { text: "1 lb ground beef", ingredient: "ground beef", quantity: 1 },
      { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
      { text: "2 tsp cumin", ingredient: "cumin", quantity: 2 },
      { text: "12 corn tortillas", ingredient: "corn tortillas", quantity: 12 },
      { text: "2 cups enchilada sauce", ingredient: "enchilada sauce", quantity: 2 },
      { text: "2 cups shredded cheddar cheese", ingredient: "cheddar cheese", quantity: 2 },
    ],
    steps: [
      "Brown the ground beef with onion and cumin until cooked through.",
      "Warm the tortillas slightly so they roll without cracking.",
      "Fill each tortilla with the beef mixture and roll tightly, placing seam-side down in a baking dish.",
      "Pour the enchilada sauce over the top and sprinkle with cheese.",
      "Bake at 375°F for 20 minutes until bubbly.",
    ],
    tags: ["dinner", "mexican"],
  },
  {
    slug: "chicken-fried-rice",
    title: "Chicken Fried Rice",
    description: "Wok-fried rice with chicken, egg, and vegetables - a fast way to use up leftover rice.",
    imageEmoji: "🍚",
    cookTimeMinutes: 20,
    servings: 4,
    ingredients: [
      { text: "3 cups cooked, cold rice", ingredient: "rice", quantity: 3 },
      { text: "2 chicken breasts, diced", ingredient: "chicken breast", quantity: 2 },
      { text: "2 eggs, beaten", ingredient: "eggs", quantity: 2 },
      { text: "1 cup frozen peas and carrots", ingredient: "peas and carrots", quantity: 1 },
      { text: "3 green onions, sliced", ingredient: "green onion", quantity: 3 },
      { text: "3 tbsp soy sauce", ingredient: "soy sauce", quantity: 3 },
      { text: "2 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 2 },
    ],
    steps: [
      "Heat 1 tbsp oil in a large wok and scramble the eggs, then set aside.",
      "Add the remaining oil and stir-fry the chicken until cooked through.",
      "Add the peas and carrots and cook for 2 minutes.",
      "Add the cold rice, breaking up any clumps, and stir-fry for 3-4 minutes.",
      "Stir in the eggs, soy sauce, and green onions, tossing until well combined.",
    ],
    tags: ["dinner", "quick", "asian"],
  },
  {
    slug: "vegetable-stir-fry",
    title: "Vegetable Stir Fry",
    description: "A quick, colorful stir fry of crisp vegetables in a savory garlic-ginger sauce.",
    imageEmoji: "🥦",
    cookTimeMinutes: 20,
    servings: 4,
    ingredients: [
      { text: "1 broccoli head, cut into florets", ingredient: "broccoli", quantity: 1 },
      { text: "1 red bell pepper, sliced", ingredient: "red pepper", quantity: 1 },
      { text: "2 carrots, sliced", ingredient: "carrot", quantity: 2 },
      { text: "1 cup snap peas", ingredient: "snap peas", quantity: 1 },
      { text: "3 cloves garlic, minced", ingredient: "garlic", quantity: 3 },
      { text: "1 tbsp grated ginger", ingredient: "ginger", quantity: 1 },
      { text: "3 tbsp soy sauce", ingredient: "soy sauce", quantity: 3 },
      { text: "2 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 2 },
    ],
    steps: [
      "Heat the oil in a wok over high heat.",
      "Add garlic and ginger, stir-frying for 30 seconds until fragrant.",
      "Add the broccoli, carrots, and pepper; stir-fry for 4-5 minutes.",
      "Add the snap peas and soy sauce, cooking for another 2 minutes.",
      "Serve hot over rice or noodles.",
    ],
    tags: ["dinner", "vegan", "quick", "asian"],
  },
  {
    slug: "pad-thai",
    title: "Pad Thai",
    description: "Stir-fried rice noodles with shrimp or tofu, egg, and peanuts in a tangy tamarind sauce.",
    imageEmoji: "🍜",
    cookTimeMinutes: 30,
    servings: 4,
    ingredients: [
      { text: "8 oz rice noodles", ingredient: "rice noodles", quantity: 8 },
      { text: "2 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 2 },
      { text: "2 eggs", ingredient: "eggs", quantity: 2 },
      { text: "8 oz shrimp or tofu", ingredient: "shrimp", quantity: 8 },
      { text: "2 cups bean sprouts", ingredient: "bean sprouts", quantity: 2 },
      { text: "3 green onions, sliced", ingredient: "green onion", quantity: 3 },
      { text: "3 tbsp tamarind paste", ingredient: "tamarind paste", quantity: 3 },
      { text: "3 tbsp fish sauce", ingredient: "fish sauce", quantity: 3 },
      { text: "1/4 cup crushed peanuts", ingredient: "peanuts", quantity: 0.25 },
    ],
    steps: [
      "Soak the rice noodles in warm water until pliable, then drain.",
      "Heat oil in a wok and scramble the eggs, then push to one side.",
      "Add the shrimp or tofu and cook through.",
      "Add the noodles, tamarind paste, and fish sauce, tossing to combine.",
      "Stir in the bean sprouts and green onions, then top with crushed peanuts before serving.",
    ],
    tags: ["dinner", "asian"],
  },
  {
    slug: "chicken-tikka-masala",
    title: "Chicken Tikka Masala",
    description: "Marinated grilled chicken simmered in a creamy, spiced tomato sauce.",
    imageEmoji: "🍛",
    cookTimeMinutes: 50,
    servings: 4,
    ingredients: [
      { text: "2 chicken breasts, cubed", ingredient: "chicken breast", quantity: 2 },
      { text: "1 cup yogurt", ingredient: "yogurt", quantity: 1 },
      { text: "2 tbsp garam masala", ingredient: "garam masala", quantity: 2 },
      { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
      { text: "3 cloves garlic, minced", ingredient: "garlic", quantity: 3 },
      { text: "1 tbsp grated ginger", ingredient: "ginger", quantity: 1 },
      { text: "1 can crushed tomatoes", ingredient: "tomato", quantity: 1 },
      { text: "1 cup heavy cream", ingredient: "heavy cream", quantity: 1 },
    ],
    steps: [
      "Marinate the chicken cubes in yogurt and half the garam masala for at least 30 minutes.",
      "Grill or pan-sear the marinated chicken until cooked through, then set aside.",
      "Sauté the onion, garlic, and ginger until softened.",
      "Stir in the remaining garam masala and crushed tomatoes, simmering for 10 minutes.",
      "Stir in the cream and cooked chicken, simmering for another 5 minutes before serving.",
    ],
    tags: ["dinner", "asian"],
  },
  {
    slug: "butter-chicken",
    title: "Butter Chicken",
    description: "Tender chicken in a rich, buttery tomato-cream sauce - a beloved Indian classic.",
    imageEmoji: "🍛",
    cookTimeMinutes: 50,
    servings: 4,
    ingredients: [
      { text: "2 chicken breasts, cubed", ingredient: "chicken breast", quantity: 2 },
      { text: "4 tbsp butter", ingredient: "butter", quantity: 4 },
      { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
      { text: "3 cloves garlic, minced", ingredient: "garlic", quantity: 3 },
      { text: "1 tbsp grated ginger", ingredient: "ginger", quantity: 1 },
      { text: "2 tsp garam masala", ingredient: "garam masala", quantity: 2 },
      { text: "1 can crushed tomatoes", ingredient: "tomato", quantity: 1 },
      { text: "1 cup heavy cream", ingredient: "heavy cream", quantity: 1 },
    ],
    steps: [
      "Melt half the butter and cook the chicken cubes until browned; set aside.",
      "Melt the remaining butter and sauté onion, garlic, and ginger until softened.",
      "Stir in the garam masala and crushed tomatoes, simmering for 10 minutes.",
      "Blend the sauce until smooth, then return it to the pot with the cream and chicken.",
      "Simmer for 10 more minutes until the chicken is cooked through.",
    ],
    tags: ["dinner", "asian"],
  },
  {
    slug: "kung-pao-chicken",
    title: "Kung Pao Chicken",
    description: "Spicy stir-fried chicken with peanuts and dried chilies in a savory-sweet sauce.",
    imageEmoji: "🥜",
    cookTimeMinutes: 25,
    servings: 4,
    ingredients: [
      { text: "2 chicken breasts, diced", ingredient: "chicken breast", quantity: 2 },
      { text: "1/2 cup peanuts", ingredient: "peanuts", quantity: 0.5 },
      { text: "1 red bell pepper, diced", ingredient: "red pepper", quantity: 1 },
      { text: "4 dried red chilies", ingredient: "dried chilies", quantity: 4 },
      { text: "3 cloves garlic, minced", ingredient: "garlic", quantity: 3 },
      { text: "3 tbsp soy sauce", ingredient: "soy sauce", quantity: 3 },
      { text: "2 tbsp rice vinegar", ingredient: "rice vinegar", quantity: 2 },
      { text: "1 tbsp cornstarch", ingredient: "cornstarch", quantity: 1 },
    ],
    steps: [
      "Toss the chicken with cornstarch to lightly coat.",
      "Heat oil in a wok and stir-fry the chicken until cooked through; set aside.",
      "Add the dried chilies and garlic, stir-frying for 30 seconds.",
      "Add the red pepper and cook for 2-3 minutes.",
      "Return the chicken to the wok with soy sauce, rice vinegar, and peanuts, tossing to combine.",
    ],
    tags: ["dinner", "asian"],
  },
  {
    slug: "miso-soup",
    title: "Miso Soup",
    description: "A light, savory Japanese soup with tofu, seaweed, and a delicate miso broth.",
    imageEmoji: "🍲",
    cookTimeMinutes: 15,
    servings: 4,
    ingredients: [
      { text: "4 cups dashi or vegetable broth", ingredient: "dashi", quantity: 4 },
      { text: "3 tbsp miso paste", ingredient: "miso paste", quantity: 3 },
      { text: "1 cup cubed silken tofu", ingredient: "tofu", quantity: 1 },
      { text: "2 tbsp dried wakame seaweed", ingredient: "seaweed", quantity: 2 },
      { text: "2 green onions, sliced", ingredient: "green onion", quantity: 2 },
    ],
    steps: [
      "Bring the dashi or vegetable broth to a gentle simmer - do not boil.",
      "Whisk a ladleful of the hot broth into the miso paste until smooth, then stir it back into the pot.",
      "Add the tofu and wakame seaweed, warming through for 2-3 minutes.",
      "Garnish with sliced green onions before serving.",
    ],
    tags: ["lunch", "quick", "vegetarian", "asian"],
  },
  {
    slug: "classic-hummus",
    title: "Classic Hummus",
    description: "A creamy chickpea and tahini dip, brightened with lemon and garlic.",
    imageEmoji: "🧆",
    cookTimeMinutes: 10,
    servings: 6,
    ingredients: [
      { text: "2 cans chickpeas, drained", ingredient: "chickpeas", quantity: 2 },
      { text: "1/3 cup tahini", ingredient: "tahini", quantity: 0.33 },
      { text: "1 lemon, juiced", ingredient: "lemon", quantity: 1 },
      { text: "2 cloves garlic", ingredient: "garlic", quantity: 2 },
      { text: "3 tbsp olive oil", ingredient: "olive oil", quantity: 3 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
    ],
    steps: [
      "Combine the chickpeas, tahini, lemon juice, and garlic in a food processor.",
      "Blend until smooth, streaming in the olive oil as it processes.",
      "Add a splash of water if needed to reach a creamy consistency.",
      "Season with salt and serve with a drizzle of olive oil.",
    ],
    tags: ["snack", "vegan", "quick", "mediterranean"],
  },
  {
    slug: "falafel",
    title: "Falafel",
    description: "Crispy fried chickpea patties, seasoned with herbs and spices - a Middle Eastern staple.",
    imageEmoji: "🧆",
    cookTimeMinutes: 40,
    servings: 4,
    ingredients: [
      { text: "2 cups dried chickpeas, soaked overnight", ingredient: "chickpeas", quantity: 2 },
      { text: "1 onion, chopped", ingredient: "onion", quantity: 1 },
      { text: "3 cloves garlic", ingredient: "garlic", quantity: 3 },
      { text: "1/2 cup chopped parsley", ingredient: "parsley", quantity: 0.5 },
      { text: "1 tsp cumin", ingredient: "cumin", quantity: 1 },
      { text: "1 tsp coriander", ingredient: "coriander", quantity: 1 },
      { text: "2 tbsp flour", ingredient: "flour", quantity: 2 },
      { text: "Vegetable oil for frying", ingredient: "vegetable oil", quantity: null },
    ],
    steps: [
      "Drain the soaked chickpeas and pulse them in a food processor with onion, garlic, and parsley.",
      "Add the cumin, coriander, and flour, pulsing until a coarse, holdable mixture forms.",
      "Shape the mixture into small patties or balls.",
      "Heat oil in a deep pan and fry the falafel until golden brown and crisp, about 3-4 minutes.",
      "Drain on paper towels and serve in pita with tahini sauce.",
    ],
    tags: ["lunch", "vegan", "mediterranean"],
  },
  {
    slug: "tabbouleh",
    title: "Tabbouleh",
    description: "A refreshing parsley and bulgur salad with tomato, mint, and lemon.",
    imageEmoji: "🥗",
    cookTimeMinutes: 20,
    servings: 4,
    ingredients: [
      { text: "1/2 cup fine bulgur", ingredient: "bulgur", quantity: 0.5 },
      { text: "2 cups finely chopped parsley", ingredient: "parsley", quantity: 2 },
      { text: "2 tomatoes, diced", ingredient: "tomato", quantity: 2 },
      { text: "1/4 cup chopped mint", ingredient: "mint", quantity: 0.25 },
      { text: "1/4 cup lemon juice", ingredient: "lemon juice", quantity: 0.25 },
      { text: "1/4 cup olive oil", ingredient: "olive oil", quantity: 0.25 },
    ],
    steps: [
      "Soak the bulgur in warm water for 15 minutes, then drain well.",
      "Combine the bulgur with parsley, tomatoes, and mint in a large bowl.",
      "Whisk together the lemon juice and olive oil, then pour over the salad.",
      "Toss well and chill before serving.",
    ],
    tags: ["lunch", "vegan", "quick", "mediterranean", "salad"],
  },
  {
    slug: "baba-ganoush",
    title: "Baba Ganoush",
    description: "Smoky roasted eggplant blended with tahini and garlic into a creamy dip.",
    imageEmoji: "🍆",
    cookTimeMinutes: 45,
    servings: 6,
    ingredients: [
      { text: "2 large eggplants", ingredient: "eggplant", quantity: 2 },
      { text: "1/4 cup tahini", ingredient: "tahini", quantity: 0.25 },
      { text: "1 lemon, juiced", ingredient: "lemon", quantity: 1 },
      { text: "2 cloves garlic", ingredient: "garlic", quantity: 2 },
      { text: "2 tbsp olive oil", ingredient: "olive oil", quantity: 2 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
    ],
    steps: [
      "Roast the whole eggplants at 425°F until the skin is charred and the flesh is soft, about 30-35 minutes.",
      "Let cool slightly, then scoop out the flesh and discard the skins.",
      "Blend the eggplant flesh with tahini, lemon juice, and garlic until smooth.",
      "Season with salt and drizzle with olive oil before serving.",
    ],
    tags: ["snack", "vegan", "mediterranean"],
  },
  {
    slug: "baked-mac-and-cheese",
    title: "Baked Mac and Cheese",
    description: "Creamy stovetop cheese sauce baked with elbow macaroni until golden and bubbly.",
    imageEmoji: "🧀",
    cookTimeMinutes: 40,
    servings: 6,
    ingredients: [
      { text: "1 lb elbow macaroni", ingredient: "macaroni", quantity: 1 },
      { text: "4 tbsp butter", ingredient: "butter", quantity: 4 },
      { text: "1/4 cup flour", ingredient: "flour", quantity: 0.25 },
      { text: "3 cups milk", ingredient: "milk", quantity: 3 },
      { text: "3 cups shredded cheddar cheese", ingredient: "cheddar cheese", quantity: 3 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "Pepper to taste", ingredient: "pepper", quantity: null },
    ],
    steps: [
      "Cook the macaroni in salted boiling water until al dente.",
      "Melt the butter in a saucepan and whisk in the flour, cooking for 1 minute.",
      "Gradually whisk in the milk, cooking until thickened.",
      "Stir in the cheddar cheese until melted, then toss with the macaroni.",
      "Transfer to a baking dish and bake at 375°F for 20 minutes until golden.",
    ],
    tags: ["dinner", "vegetarian"],
  },
  {
    slug: "grilled-cheese-sandwich",
    title: "Grilled Cheese Sandwich",
    description: "Buttery toasted bread with melty cheese - the ultimate quick comfort sandwich.",
    imageEmoji: "🥪",
    cookTimeMinutes: 10,
    servings: 1,
    ingredients: [
      { text: "2 slices bread", ingredient: "bread", quantity: 2 },
      { text: "2 slices cheddar cheese", ingredient: "cheddar cheese", quantity: 2 },
      { text: "1 tbsp butter", ingredient: "butter", quantity: 1 },
    ],
    steps: [
      "Butter one side of each bread slice.",
      "Place cheese between the slices, buttered sides facing out.",
      "Cook in a skillet over medium heat until golden, about 3 minutes per side.",
      "Slice and serve warm.",
    ],
    tags: ["lunch", "quick", "vegetarian"],
  },
  {
    slug: "blt-sandwich",
    title: "BLT Sandwich",
    description: "Crispy bacon, lettuce, and tomato piled between toasted bread with mayonnaise.",
    imageEmoji: "🥪",
    cookTimeMinutes: 15,
    servings: 2,
    ingredients: [
      { text: "6 slices bacon", ingredient: "bacon", quantity: 6 },
      { text: "4 slices bread, toasted", ingredient: "bread", quantity: 4 },
      { text: "1 tomato, sliced", ingredient: "tomato", quantity: 1 },
      { text: "4 lettuce leaves", ingredient: "lettuce", quantity: 4 },
      { text: "2 tbsp mayonnaise", ingredient: "mayonnaise", quantity: 2 },
    ],
    steps: [
      "Cook the bacon in a skillet until crisp, then drain on paper towels.",
      "Spread mayonnaise on the toasted bread slices.",
      "Layer the bacon, lettuce, and tomato on two slices.",
      "Top with the remaining bread and slice in half to serve.",
    ],
    tags: ["lunch", "quick"],
  },
  {
    slug: "classic-meatloaf",
    title: "Classic Meatloaf",
    description: "A homestyle ground beef loaf glazed with a tangy ketchup topping.",
    imageEmoji: "🍖",
    cookTimeMinutes: 75,
    servings: 6,
    ingredients: [
      { text: "2 lb ground beef", ingredient: "ground beef", quantity: 2 },
      { text: "1 cup breadcrumbs", ingredient: "breadcrumbs", quantity: 1 },
      { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
      { text: "2 eggs", ingredient: "eggs", quantity: 2 },
      { text: "1/2 cup milk", ingredient: "milk", quantity: 0.5 },
      { text: "1/2 cup ketchup", ingredient: "ketchup", quantity: 0.5 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "Pepper to taste", ingredient: "pepper", quantity: null },
    ],
    steps: [
      "Combine the ground beef, breadcrumbs, onion, eggs, and milk in a large bowl.",
      "Season with salt and pepper, then mix gently until just combined.",
      "Shape into a loaf and place in a baking dish.",
      "Spread the ketchup over the top.",
      "Bake at 350°F for about 1 hour, until cooked through.",
    ],
    tags: ["dinner"],
  },
  {
    slug: "shepherds-pie",
    title: "Shepherd's Pie",
    description: "Savory ground lamb with vegetables, topped with creamy mashed potatoes and baked.",
    imageEmoji: "🥧",
    cookTimeMinutes: 60,
    servings: 6,
    ingredients: [
      { text: "1 lb ground lamb", ingredient: "ground lamb", quantity: 1 },
      { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
      { text: "2 carrots, diced", ingredient: "carrot", quantity: 2 },
      { text: "1 cup frozen peas", ingredient: "peas", quantity: 1 },
      { text: "2 tbsp flour", ingredient: "flour", quantity: 2 },
      { text: "1 cup beef broth", ingredient: "beef broth", quantity: 1 },
      { text: "4 cups mashed potatoes", ingredient: "mashed potatoes", quantity: 4 },
    ],
    steps: [
      "Brown the ground lamb with onion and carrots in a large skillet.",
      "Sprinkle in the flour and stir, then pour in the beef broth and simmer until thickened.",
      "Stir in the peas and transfer the mixture to a baking dish.",
      "Spread the mashed potatoes evenly over the top.",
      "Bake at 400°F for 25 minutes until golden on top.",
    ],
    tags: ["dinner"],
  },
  {
    slug: "chicken-pot-pie",
    title: "Chicken Pot Pie",
    description: "Tender chicken and vegetables in a creamy sauce, baked under a flaky pie crust.",
    imageEmoji: "🥧",
    cookTimeMinutes: 60,
    servings: 6,
    ingredients: [
      { text: "2 chicken breasts, cooked and diced", ingredient: "chicken breast", quantity: 2 },
      { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
      { text: "2 carrots, diced", ingredient: "carrot", quantity: 2 },
      { text: "1 cup frozen peas", ingredient: "peas", quantity: 1 },
      { text: "1/3 cup flour", ingredient: "flour", quantity: 0.33 },
      { text: "2 cups chicken broth", ingredient: "chicken broth", quantity: 2 },
      { text: "1 cup milk", ingredient: "milk", quantity: 1 },
      { text: "2 pie crusts", ingredient: "pie crust", quantity: 2 },
    ],
    steps: [
      "Sauté the onion and carrots until softened.",
      "Sprinkle in the flour and cook for 1 minute, then whisk in the chicken broth and milk until thickened.",
      "Stir in the cooked chicken and peas.",
      "Pour the filling into a pie crust-lined dish and top with the second crust, sealing the edges.",
      "Bake at 400°F for 30-35 minutes until the crust is golden.",
    ],
    tags: ["dinner"],
  },
  {
    slug: "banana-bread",
    title: "Banana Bread",
    description: "A moist, sweet quick bread made from ripe, spotty bananas - a classic way to use them up.",
    imageEmoji: "🍌",
    cookTimeMinutes: 65,
    servings: 8,
    ingredients: [
      { text: "3 ripe bananas, mashed", ingredient: "banana", quantity: 3 },
      { text: "1/3 cup melted butter", ingredient: "butter", quantity: 0.33 },
      { text: "3/4 cup sugar", ingredient: "sugar", quantity: 0.75 },
      { text: "1 egg", ingredient: "eggs", quantity: 1 },
      { text: "1 tsp vanilla extract", ingredient: "vanilla extract", quantity: 1 },
      { text: "1 tsp baking soda", ingredient: "baking soda", quantity: 1 },
      { text: "1 1/2 cups all-purpose flour", ingredient: "flour", quantity: 1.5 },
    ],
    steps: [
      "Preheat oven to 350°F and grease a loaf pan.",
      "Mix the mashed bananas with melted butter.",
      "Stir in the sugar, egg, and vanilla.",
      "Sprinkle the baking soda and flour over the mixture and stir until just combined.",
      "Pour into the loaf pan and bake for 55-60 minutes until a toothpick comes out clean.",
    ],
    tags: ["dessert", "baking", "vegetarian"],
  },
  {
    slug: "classic-apple-pie",
    title: "Classic Apple Pie",
    description: "Spiced apples baked in a flaky double crust - the quintessential American dessert.",
    imageEmoji: "🥧",
    cookTimeMinutes: 75,
    servings: 8,
    ingredients: [
      { text: "6 apples, peeled and sliced", ingredient: "apple", quantity: 6 },
      { text: "3/4 cup sugar", ingredient: "sugar", quantity: 0.75 },
      { text: "2 tbsp flour", ingredient: "flour", quantity: 2 },
      { text: "1 tsp cinnamon", ingredient: "cinnamon", quantity: 1 },
      { text: "2 pie crusts", ingredient: "pie crust", quantity: 2 },
      { text: "2 tbsp butter", ingredient: "butter", quantity: 2 },
    ],
    steps: [
      "Toss the sliced apples with sugar, flour, and cinnamon.",
      "Line a pie dish with one crust and fill with the apple mixture.",
      "Dot the filling with butter, then top with the second crust, sealing and venting the top.",
      "Bake at 375°F for 45-50 minutes until the crust is golden and filling is bubbling.",
      "Cool for at least an hour before slicing.",
    ],
    tags: ["dessert", "baking", "vegetarian"],
  },
  {
    slug: "fudgy-brownies",
    title: "Fudgy Brownies",
    description: "Rich, dense chocolate brownies with a shiny crackled top.",
    imageEmoji: "🍫",
    cookTimeMinutes: 40,
    servings: 9,
    ingredients: [
      { text: "1/2 cup butter", ingredient: "butter", quantity: 0.5 },
      { text: "1 cup sugar", ingredient: "sugar", quantity: 1 },
      { text: "2 eggs", ingredient: "eggs", quantity: 2 },
      { text: "1/3 cup cocoa powder", ingredient: "cocoa powder", quantity: 0.33 },
      { text: "1/2 cup flour", ingredient: "flour", quantity: 0.5 },
      { text: "1 tsp vanilla extract", ingredient: "vanilla extract", quantity: 1 },
    ],
    steps: [
      "Preheat oven to 350°F and grease a baking pan.",
      "Melt the butter, then whisk in the sugar, eggs, and vanilla.",
      "Stir in the cocoa powder and flour until just combined.",
      "Pour into the pan and bake for 25-30 minutes until the center is just set.",
      "Cool completely before cutting into squares.",
    ],
    tags: ["dessert", "baking", "vegetarian"],
  },
  {
    slug: "blueberry-muffins",
    title: "Blueberry Muffins",
    description: "Tender, bakery-style muffins studded with fresh blueberries.",
    imageEmoji: "🧁",
    cookTimeMinutes: 35,
    servings: 12,
    ingredients: [
      { text: "2 cups flour", ingredient: "flour", quantity: 2 },
      { text: "3/4 cup sugar", ingredient: "sugar", quantity: 0.75 },
      { text: "2 tsp baking powder", ingredient: "baking powder", quantity: 2 },
      { text: "1 egg", ingredient: "eggs", quantity: 1 },
      { text: "1 cup milk", ingredient: "milk", quantity: 1 },
      { text: "1/3 cup melted butter", ingredient: "butter", quantity: 0.33 },
      { text: "1 1/2 cups fresh blueberries", ingredient: "blueberries", quantity: 1.5 },
    ],
    steps: [
      "Preheat oven to 400°F and line a muffin tin with liners.",
      "Whisk together the flour, sugar, and baking powder.",
      "In another bowl, whisk the egg, milk, and melted butter.",
      "Combine the wet and dry ingredients, then fold in the blueberries.",
      "Divide the batter among the muffin cups and bake for 20-22 minutes until golden.",
    ],
    tags: ["breakfast", "dessert", "baking", "vegetarian"],
  },
  {
    slug: "carrot-cake",
    title: "Carrot Cake",
    description: "A moist spiced cake packed with shredded carrots, topped with cream cheese frosting.",
    imageEmoji: "🥕",
    cookTimeMinutes: 70,
    servings: 10,
    ingredients: [
      { text: "2 cups flour", ingredient: "flour", quantity: 2 },
      { text: "2 tsp cinnamon", ingredient: "cinnamon", quantity: 2 },
      { text: "1 tsp baking soda", ingredient: "baking soda", quantity: 1 },
      { text: "3 eggs", ingredient: "eggs", quantity: 3 },
      { text: "1 cup vegetable oil", ingredient: "vegetable oil", quantity: 1 },
      { text: "1 1/2 cups sugar", ingredient: "sugar", quantity: 1.5 },
      { text: "3 cups grated carrots", ingredient: "carrot", quantity: 3 },
      { text: "8 oz cream cheese, softened", ingredient: "cream cheese", quantity: 8 },
    ],
    steps: [
      "Preheat oven to 350°F and grease two cake pans.",
      "Whisk together the flour, cinnamon, and baking soda.",
      "In another bowl, beat the eggs, oil, and sugar together, then fold in the grated carrots.",
      "Combine the wet and dry ingredients and divide between the pans.",
      "Bake for 30-35 minutes, cool completely, then frost with cream cheese frosting.",
    ],
    tags: ["dessert", "baking", "vegetarian"],
  },
  {
    slug: "lemon-bars",
    title: "Lemon Bars",
    description: "A buttery shortbread crust topped with a tangy, sweet lemon custard filling.",
    imageEmoji: "🍋",
    cookTimeMinutes: 55,
    servings: 9,
    ingredients: [
      { text: "1 cup flour", ingredient: "flour", quantity: 1 },
      { text: "1/4 cup powdered sugar", ingredient: "powdered sugar", quantity: 0.25 },
      { text: "1/2 cup butter", ingredient: "butter", quantity: 0.5 },
      { text: "2 eggs", ingredient: "eggs", quantity: 2 },
      { text: "1 cup sugar", ingredient: "sugar", quantity: 1 },
      { text: "1/3 cup lemon juice", ingredient: "lemon juice", quantity: 0.33 },
      { text: "2 tbsp flour (for filling)", ingredient: "flour", quantity: 2 },
    ],
    steps: [
      "Preheat oven to 350°F and mix the flour, powdered sugar, and butter into a dough for the crust.",
      "Press the dough into a baking pan and bake for 15 minutes.",
      "Whisk the eggs, sugar, lemon juice, and remaining flour together for the filling.",
      "Pour the filling over the warm crust and bake for another 20 minutes until set.",
      "Cool completely, then dust with powdered sugar and cut into bars.",
    ],
    tags: ["dessert", "baking", "vegetarian"],
  },
  {
    slug: "tiramisu",
    title: "Tiramisu",
    description: "Espresso-soaked ladyfingers layered with a creamy mascarpone filling, dusted with cocoa.",
    imageEmoji: "☕",
    cookTimeMinutes: 30,
    servings: 8,
    ingredients: [
      { text: "24 ladyfinger cookies", ingredient: "ladyfingers", quantity: 24 },
      { text: "1 1/2 cups strong brewed coffee, cooled", ingredient: "coffee", quantity: 1.5 },
      { text: "4 egg yolks", ingredient: "egg yolks", quantity: 4 },
      { text: "1/2 cup sugar", ingredient: "sugar", quantity: 0.5 },
      { text: "16 oz mascarpone cheese", ingredient: "mascarpone", quantity: 16 },
      { text: "1 cup heavy cream, whipped", ingredient: "heavy cream", quantity: 1 },
      { text: "2 tbsp cocoa powder for dusting", ingredient: "cocoa powder", quantity: 2 },
    ],
    steps: [
      "Whisk the egg yolks and sugar together, then whisk in the mascarpone until smooth.",
      "Fold the whipped cream into the mascarpone mixture.",
      "Dip each ladyfinger briefly in the cooled coffee and layer half of them in a dish.",
      "Spread half the mascarpone mixture over the ladyfingers, then repeat with a second layer.",
      "Chill for at least 4 hours, then dust with cocoa powder before serving.",
    ],
    tags: ["dessert", "italian"],
  },
  {
    slug: "rice-pudding",
    title: "Rice Pudding",
    description: "Creamy, comforting rice simmered slowly in sweetened milk with a hint of vanilla.",
    imageEmoji: "🍮",
    cookTimeMinutes: 45,
    servings: 6,
    ingredients: [
      { text: "1 cup short-grain rice", ingredient: "rice", quantity: 1 },
      { text: "4 cups milk", ingredient: "milk", quantity: 4 },
      { text: "1/2 cup sugar", ingredient: "sugar", quantity: 0.5 },
      { text: "1 tsp vanilla extract", ingredient: "vanilla extract", quantity: 1 },
      { text: "1/2 tsp cinnamon", ingredient: "cinnamon", quantity: 0.5 },
    ],
    steps: [
      "Combine the rice and milk in a saucepan and bring to a gentle simmer.",
      "Cook, stirring often, for 30-35 minutes until the rice is tender and the mixture has thickened.",
      "Stir in the sugar and vanilla extract.",
      "Spoon into bowls and dust with cinnamon before serving, warm or chilled.",
    ],
    tags: ["dessert", "vegetarian"],
  },
  {
    slug: "simple-roast-chicken",
    title: "Simple Roast Chicken",
    description: "A whole chicken roasted until golden and juicy with garlic, lemon, and herbs.",
    imageEmoji: "🍗",
    cookTimeMinutes: 90,
    servings: 6,
    ingredients: [
      { text: "1 whole chicken (about 4 lb)", ingredient: "chicken", quantity: 1 },
      { text: "1 lemon, halved", ingredient: "lemon", quantity: 1 },
      { text: "4 cloves garlic", ingredient: "garlic", quantity: 4 },
      { text: "2 tbsp butter, softened", ingredient: "butter", quantity: 2 },
      { text: "1 tbsp fresh thyme", ingredient: "thyme", quantity: 1 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "Pepper to taste", ingredient: "pepper", quantity: null },
    ],
    steps: [
      "Preheat oven to 425°F and pat the chicken dry.",
      "Stuff the cavity with the lemon halves and garlic cloves.",
      "Rub the softened butter and thyme over the skin, then season generously with salt and pepper.",
      "Roast for about 1 hour 20 minutes, until the internal temperature reaches 165°F.",
      "Let rest for 10 minutes before carving.",
    ],
    tags: ["dinner"],
  },
  {
    slug: "hearty-beef-stew",
    title: "Hearty Beef Stew",
    description: "Tender chunks of beef slow-simmered with potatoes and carrots in a rich broth.",
    imageEmoji: "🍲",
    cookTimeMinutes: 120,
    servings: 6,
    ingredients: [
      { text: "2 lb beef chuck, cubed", ingredient: "beef chuck", quantity: 2 },
      { text: "3 potatoes, cubed", ingredient: "potato", quantity: 3 },
      { text: "3 carrots, sliced", ingredient: "carrot", quantity: 3 },
      { text: "1 onion, diced", ingredient: "onion", quantity: 1 },
      { text: "3 tbsp flour", ingredient: "flour", quantity: 3 },
      { text: "4 cups beef broth", ingredient: "beef broth", quantity: 4 },
      { text: "2 tbsp tomato paste", ingredient: "tomato paste", quantity: 2 },
    ],
    steps: [
      "Toss the beef cubes in flour, then brown them in a large pot.",
      "Add the onion and cook until softened.",
      "Stir in the tomato paste, then pour in the beef broth.",
      "Add the potatoes and carrots, then simmer, covered, for 1.5-2 hours until the beef is tender.",
      "Season to taste before serving.",
    ],
    tags: ["dinner"],
  },
  {
    slug: "grilled-salmon-lemon-butter",
    title: "Grilled Salmon with Lemon Butter",
    description: "Flaky grilled salmon fillets finished with a bright, buttery lemon sauce.",
    imageEmoji: "🐟",
    cookTimeMinutes: 20,
    servings: 4,
    ingredients: [
      { text: "4 salmon fillets", ingredient: "salmon", quantity: 4 },
      { text: "3 tbsp butter", ingredient: "butter", quantity: 3 },
      { text: "1 lemon, juiced", ingredient: "lemon", quantity: 1 },
      { text: "2 cloves garlic, minced", ingredient: "garlic", quantity: 2 },
      { text: "1 tbsp fresh dill", ingredient: "dill", quantity: 1 },
      { text: "Salt to taste", ingredient: "salt", quantity: null },
      { text: "Pepper to taste", ingredient: "pepper", quantity: null },
    ],
    steps: [
      "Season the salmon fillets with salt and pepper.",
      "Grill or pan-sear the salmon for 4-5 minutes per side until just cooked through.",
      "Melt the butter with garlic in a small saucepan, then stir in the lemon juice and dill.",
      "Spoon the lemon butter sauce over the salmon before serving.",
    ],
    tags: ["dinner", "quick"],
  },
  {
    slug: "vegetable-chow-mein",
    title: "Vegetable Chow Mein",
    description: "Stir-fried noodles with crisp vegetables in a savory soy-based sauce.",
    imageEmoji: "🍜",
    cookTimeMinutes: 25,
    servings: 4,
    ingredients: [
      { text: "8 oz chow mein noodles", ingredient: "chow mein noodles", quantity: 8 },
      { text: "1 red bell pepper, sliced", ingredient: "red pepper", quantity: 1 },
      { text: "2 carrots, julienned", ingredient: "carrot", quantity: 2 },
      { text: "2 cups shredded cabbage", ingredient: "cabbage", quantity: 2 },
      { text: "3 cloves garlic, minced", ingredient: "garlic", quantity: 3 },
      { text: "4 tbsp soy sauce", ingredient: "soy sauce", quantity: 4 },
      { text: "2 tbsp vegetable oil", ingredient: "vegetable oil", quantity: 2 },
    ],
    steps: [
      "Cook the chow mein noodles according to package instructions, then drain.",
      "Heat oil in a wok and stir-fry the garlic for 30 seconds.",
      "Add the pepper, carrots, and cabbage, stir-frying for 3-4 minutes until crisp-tender.",
      "Add the noodles and soy sauce, tossing everything together for 2 minutes.",
      "Serve hot.",
    ],
    tags: ["dinner", "vegan", "quick", "asian"],
  },
];

async function main() {
  for (const recipe of recipes) {
    const created = await prisma.recipe.upsert({
      where: { slug: recipe.slug },
      update: {
        title: recipe.title,
        description: recipe.description,
        imageEmoji: recipe.imageEmoji,
        cookTimeMinutes: recipe.cookTimeMinutes,
        servings: recipe.servings,
        steps: JSON.stringify(recipe.steps),
        tags: JSON.stringify(recipe.tags),
      },
      create: {
        slug: recipe.slug,
        title: recipe.title,
        description: recipe.description,
        imageEmoji: recipe.imageEmoji,
        cookTimeMinutes: recipe.cookTimeMinutes,
        servings: recipe.servings,
        steps: JSON.stringify(recipe.steps),
        tags: JSON.stringify(recipe.tags),
      },
    });

    // Re-link ingredients fresh each run rather than trying to diff them -
    // simplest way to keep a hand-authored seed script idempotent.
    await prisma.recipeIngredient.deleteMany({ where: { recipeId: created.id } });

    for (let i = 0; i < recipe.ingredients.length; i++) {
      const { text, ingredient, quantity } = recipe.ingredients[i];
      const ingredientRow = await prisma.ingredient.upsert({
        where: { name: ingredient },
        update: {},
        create: { name: ingredient },
      });
      await prisma.recipeIngredient.create({
        data: {
          recipeId: created.id,
          ingredientId: ingredientRow.id,
          displayText: text,
          quantity: quantity,
          position: i,
        },
      });
    }
  }
  console.log(`Seeded ${recipes.length} recipes.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
